### ISSUE TITLE
ValueError: Reference contigs span 3095677412 bases but only 0 bases (0.00%) were found in common among our input files

### ISSUE THREAD

**Issue by Reedwarbler** [google/deepvariant#106]
Hi,

I am trying to run the training step, and met the following error. Any possible reason for this? I have checked the bam file and reference are match well. Thank you!

```
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_OK9hEl/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1188, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_OK9hEl/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1178, in main
    make_examples_runner(options)
  File "/tmp/Bazel.runfiles_OK9hEl/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1076, in make_examples_runner
    regions = processing_regions_from_options(options)
  File "/tmp/Bazel.runfiles_OK9hEl/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 990, in processing_regions_from_options
    options.min_shared_contigs_basepairs)
  File "/tmp/Bazel.runfiles_OK9hEl/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 485, in _ensure_consistent_contigs
    min_coverage_fraction)
  File "/tmp/Bazel.runfiles_OK9hEl/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 557, in validate_reference_contig_coverage
    ref_bp, common_bp, coverage, format_contig_matches()))
ValueError: Reference contigs span 3095677412 bases but only 0 bases (0.00%) were found in common among our input files. Check that the sources were created on a common genome reference build. Contig matches were: "1" is 249250621 bp and IS MISSING, "2" is 243199373
 bp and IS MISSING, "3" is 198022430 bp and IS MISSING, "4" is 191154276 bp and IS MISSING, "5" is 180915260 bp and IS MISSING, "6" is 171115067 bp and IS MISSING, "7" is 159138663 bp and IS MISSING, "8" is 146364022 bp and IS MISSING, "9" is 141213431 bp and IS MIS
SING, "10" is 135534747 bp and IS MISSING, "11" is 135006516 bp and IS MISSING, "12" is 133851895 bp and IS MISSING, "13" is 115169878 bp and IS MISSING, "14" is 107349540 bp and IS MISSING, "15" is 102531392 bp and IS MISSING, "16" is 90354753 bp and IS MISSING, "1
7" is 81195210 bp and IS MISSING, "18" is 78077248 bp and IS MISSING, "19" is 59128983 bp and IS MISSING, "20" is 63025520 bp and IS MISSING, "21" is 48129895 bp and IS MISSING, "22" is 51304566 bp and IS MISSING, "X" is 155270560 bp and IS MISSING, "Y" is 59373566 
bp and IS MISSING
```

**Comment by Reedwarbler** [comment]
Problem solved. 
The vcf file doesn't match. Thanks!
