### ISSUE TITLE
No index file for the inputed vcf file: Training mode in Make_example

### ISSUE THREAD

**Issue by solokopi** [google/deepvariant#111]
`Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_OTW1G5/runfiles/genomics/deepvariant/make_examples.py", line 1015, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/tmp/Bazel.runfiles_OTW1G5/runfiles/genomics/deepvariant/make_examples.py", line 1005, in main
    make_examples_runner(options)
  File "/tmp/Bazel.runfiles_OTW1G5/runfiles/genomics/deepvariant/make_examples.py", line 912, in make_examples_runner
    regions = processing_regions_from_options(options)
  File "/tmp/Bazel.runfiles_OTW1G5/runfiles/genomics/deepvariant/make_examples.py", line 884, in processing_regions_from_options
    options.truth_variants_filename).contigs
  File "/tmp/Bazel.runfiles_OTW1G5/runfiles/genomics/deepvariant/core/genomics_io.py", line 161, in make_vcf_reader
    index_mode=index_mode, desired_format_entries=desired_vcf_fields))
ValueError: Not found: No index found for /training-case-study%2FBGISEQ-HG001%2FHG001_GRCh37_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_PGandRTGphasetransfer_chrs_FIXED.vcf` 

i had been getting this error trying to train a data. i have got the index file for this same vcf file but still gets this error. please what could be wrong? thank you

**Comment by pgrosu** [comment]
One of our forward-slash symbol is converted to a `%2F` - notice the one in the middle `...HG001%2FHG001...` so the search path is most likely not converted properly, and thus not reachable.

**Comment by solokopi** [comment]
thank you, it the same, but don't know what must have gone wrong. i used a different data it ran but gave a different error again, please can you help analyze this for me? 

WARNING: Logging before flag parsing goes to stderr.
I1024 02:24:26.300854 140364017985280 client.py:1004] Timeout attempting to reach GCE metadata service.
W1024 02:24:26.301438 140364017985280 htslib_gcp_oauth.py:88] GCP credentials not found; only local files and public gs:// URIs will be accessible from htslib
[W::hts_idx_load2] The index file is older than the data file: /TCGA-AF-6136-01A.add_rg.bam.bai
I1024 02:24:26.349014 140364017985280 make_examples.py:911] Preparing inputs
[W::hts_idx_load2] The index file is older than the data file: /TCGA-AF-6136-01A.add_rg.bam.bai
[W::hts_idx_load2] The index file is older than the data file: /performance-testdata%2FHG002_GIAB_highconf_IllFB-IllGATKHC-CG-Ion-Solid_CHROM1-22_v3.2.2_highconf.vcf.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: /performance-testdata%2FHG002_GIAB_highconf_IllFB-IllGATKHC-CG-Ion-Solid_CHROM1-22_v3.2.2_highconf.vcf.gz.tbi
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_CqnGJt/runfiles/genomics/deepvariant/make_examples.py", line 1015, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/tmp/Bazel.runfiles_CqnGJt/runfiles/genomics/deepvariant/make_examples.py", line 1005, in main
    make_examples_runner(options)
  File "/tmp/Bazel.runfiles_CqnGJt/runfiles/genomics/deepvariant/make_examples.py", line 912, in make_examples_runner
    regions = processing_regions_from_options(options)
  File "/tmp/Bazel.runfiles_CqnGJt/runfiles/genomics/deepvariant/make_examples.py", line 892, in processing_regions_from_options
    options.min_shared_contigs_basepairs)
  File "/tmp/Bazel.runfiles_CqnGJt/runfiles/genomics/deepvariant/make_examples.py", line 495, in validate_reference_contig_coverage
    ref_bp, common_bp, coverage, format_contig_matches()))
ValueError: Reference contigs span 3107576521 bases but only 0 bases (0.00%) were found in common among our input files. Check that the sources were created on a common genome reference build. Contig matches were: "chr1" is 248956422 bp and IS MISSING, "chr2" is 242193529 bp and IS MISSING, "chr3" is 198295559 bp and IS MISSING, "chr4" is 190214555 bp and IS MISSING, "chr5" is 181538259 bp and IS MISSING, "chr6" is 170805979 bp and IS MISSING, "chr7" is 159345973 bp and IS MISSING, "chr8" is 145138636 bp and IS MISSING, "chr9" is 138394717 bp and IS MISSING, "chr10" is 133797422 bp and IS MISSING, "chr11" is 135086622 bp and IS MISSING, "chr12" is 133275309 bp and IS MISSING, "chr13" is 114364328 bp and IS MISSING, "chr14" is 107043718 bp and IS MISSING, "chr15" is 101991189 bp and IS MISSING, "chr16" is 90338345 bp and IS MISSING, "chr17" is 83257441 bp and IS MISSING.................
it continues like this though but i don't want to paste all of it. i await your response thank you.
     On Tuesday, October 23, 2018, 10:09:51 PM GMT+8, Paul Grosu <notifications@github.com> wrote:  
 
 
Two of our forward-slash symbol is converted to a %2F - notice the one in the middle for ...HG001%2FHG001... and ...study%2FBGISEQ.... So the search path is most likely not converted properly, and thus not reachable.

**Comment by solokopi** [comment]
thank you, it the same, but don't know what must have gone wrong. i used a different data it ran but gave a different error again, please can you help analyze this for me?

WARNING: Logging before flag parsing goes to stderr.
I1024 02:24:26.300854 140364017985280 client.py:1004] Timeout attempting to reach GCE metadata service.
W1024 02:24:26.301438 140364017985280 htslib_gcp_oauth.py:88] GCP credentials not found; only local files and public gs:// URIs will be accessible from htslib
[W::hts_idx_load2] The index file is older than the data file: /TCGA-AF-6136-01A.add_rg.bam.bai
I1024 02:24:26.349014 140364017985280 make_examples.py:911] Preparing inputs
[W::hts_idx_load2] The index file is older than the data file: /TCGA-AF-6136-01A.add_rg.bam.bai
[W::hts_idx_load2] The index file is older than the data file: /performance-testdata%2FHG002_GIAB_highconf_IllFB-IllGATKHC-CG-Ion-Solid_CHROM1-22_v3.2.2_highconf.vcf.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: /performance-testdata%2FHG002_GIAB_highconf_IllFB-IllGATKHC-CG-Ion-Solid_CHROM1-22_v3.2.2_highconf.vcf.gz.tbi
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_CqnGJt/runfiles/genomics/deepvariant/make_examples.py", line 1015, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/tmp/Bazel.runfiles_CqnGJt/runfiles/genomics/deepvariant/make_examples.py", line 1005, in main
    make_examples_runner(options)
  File "/tmp/Bazel.runfiles_CqnGJt/runfiles/genomics/deepvariant/make_examples.py", line 912, in make_examples_runner
    regions = processing_regions_from_options(options)
  File "/tmp/Bazel.runfiles_CqnGJt/runfiles/genomics/deepvariant/make_examples.py", line 892, in processing_regions_from_options
    options.min_shared_contigs_basepairs)
  File "/tmp/Bazel.runfiles_CqnGJt/runfiles/genomics/deepvariant/make_examples.py", line 495, in validate_reference_contig_coverage
    ref_bp, common_bp, coverage, format_contig_matches()))
ValueError: Reference contigs span 3107576521 bases but only 0 bases (0.00%) were found in common among our input files. Check that the sources were created on a common genome reference build. Contig matches were: "chr1" is 248956422 bp and IS MISSING, "chr2" is 242193529 bp and IS MISSING, "chr3" is 198295559 bp and IS MISSING, "chr4" is 190214555 bp and IS MISSING, "chr5" is 181538259 bp and IS MISSING, "chr6" is 170805979 bp and IS MISSING, "chr7" is 159345973 bp and IS MISSING, "chr8" is 145138636 bp and IS MISSING, "chr9" is 138394717 bp and IS MISSING, "chr10" is 133797422 bp and IS MISSING, "chr11" is 135086622 bp and IS MISSING, "chr12" is 133275309 bp and IS MISSING, "chr13" is 114364328 bp and IS MISSING, "chr14" is 107043718 bp and IS MISSING, "chr15" is 101991189 bp and IS MISSING, "chr16" is 90338345 bp and IS MISSING, "chr17" is 83257441 bp and IS MISSING.................

it continues like this though but i don't want to paste all of it. i await your response thank you.

**Comment by pichuan** [comment]
Thanks @pgrosu !
Closing this issue.
