### ISSUE TITLE
Assign requires shapes of both tensors to match

### ISSUE THREAD

**Issue by snashraf** [google/deepvariant#117]
Hi Team,

 I was trying to run below command for call_variants 

docker run -it -v /gpfs/projects/bioinfo/najeeb/withKhalid/PMC/:/dv2/PMC01/ -v ${PWD}:/${PWD} -v /gpfs/data_jrnas1/ref_data/Homo_sapiens/GRCh37/Sequences/:/dv2/WholeGenomeSequence/ gcr.io/deepvariant-docker/deepvariant:0.7.0 /opt/deepvariant/bin/call_variants --outfile "$PWD/PMC01-01_AB082422_S5_L005_R1_001_output.tfrecord.gz" --examples "$PWD/PMC01-01_AB082422_S5_L005_R1_001.tfrecord.gz" --checkpoint ${PWD}/models/model.ckpt

But for some reason , I am getting below error.

I1108 10:29:03.150824 140295000123136 call_variants.py:283] Set KMP_BLOCKTIME to 0
2018-11-08 10:29:03.161879: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2 FMA
2018-11-08 10:29:03.168258: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
I1108 10:29:03.176211 140295000123136 modeling.py:318] Initializing model with random parameters
W1108 10:29:03.177896 140295000123136 tf_logging.py:125] Using temporary folder as model directory: /tmp/tmpkXijQm
I1108 10:29:03.178158 140295000123136 tf_logging.py:115] Using config: {'_save_checkpoints_secs': 1000, '_session_config': None, '_keep_checkpoint_max': 100000, '_task_type': 'worker', '_global_id_in_cluster': 0, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f9889d6e750>, '_evaluation_master': '', '_save_checkpoints_steps': None, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_num_ps_replicas': 0, '_tf_random_seed': None, '_master': '', '_device_fn': None, '_num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': 100, '_model_dir': '/tmp/tmpkXijQm', '_train_distribute': None, '_save_summary_steps': 100}
I1108 10:29:03.178364 140295000123136 call_variants.py:341] Writing calls to /gpfs/projects/bioinfo/najeeb/playGround/deepVariants/PMC01-01_AB082422_S5_L005_R1_001_output.tfrecord.gz
I1108 10:29:03.210211 140295000123136 tf_logging.py:115] Calling model_fn.
I1108 10:29:05.463484 140295000123136 tf_logging.py:115] Done calling model_fn.
I1108 10:29:06.500680 140295000123136 tf_logging.py:115] Graph was finalized.
I1108 10:29:06.501178 140295000123136 tf_logging.py:115] Restoring parameters from /gpfs/projects/bioinfo/najeeb/playGround/deepVariants/models/model.ckpt
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_qGBYAy/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 399, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_qGBYAy/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 389, in main
    use_tpu=FLAGS.use_tpu,
  File "/tmp/Bazel.runfiles_qGBYAy/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 348, in call_variants
    prediction = next(predictions)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 549, in predict
    hooks=all_hooks) as mon_sess:
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 826, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 549, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1012, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1017, in _create_session
    return self._sess_creator.create_session()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 706, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 477, in create_session
    init_fn=self._scaffold.init_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 281, in prepare_session
    config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 195, in _restore_checkpoint
    saver.restore(sess, checkpoint_filename_with_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1752, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [3,3,6,32] rhs shape= [3,3,7,32]
	 [[Node: save_1/Assign_3 = Assign[T=DT_FLOAT, _class=["loc:@InceptionV3/Conv2d_1a_3x3/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](InceptionV3/Conv2d_1a_3x3/weights, save_1/RestoreV2:3)]]

Caused by op u'save_1/Assign_3', defined at:
  File "/tmp/Bazel.runfiles_qGBYAy/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 399, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_qGBYAy/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 389, in main
    use_tpu=FLAGS.use_tpu,
  File "/tmp/Bazel.runfiles_qGBYAy/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 348, in call_variants
    prediction = next(predictions)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 549, in predict
    hooks=all_hooks) as mon_sess:
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 826, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 549, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1012, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1017, in _create_session
    return self._sess_creator.create_session()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 706, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 468, in create_session
    self._scaffold.finalize()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 212, in finalize
    self._saver = training_saver._get_saver_or_default()  # pylint: disable=protected-access
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 856, in _get_saver_or_default
    saver = Saver(sharded=True, allow_empty=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1284, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1296, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1333, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 775, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 453, in _AddShardedRestoreOps
    name="restore_shard"))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 422, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 113, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/state_ops.py", line 219, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 60, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [3,3,6,32] rhs shape= [3,3,7,32]
	 [[Node: save_1/Assign_3 = Assign[T=DT_FLOAT, _class=["loc:@InceptionV3/Conv2d_1a_3x3/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](InceptionV3/Conv2d_1a_3x3/weights, save_1/RestoreV2:3)]]

Could you please check and let us know about possible reason of this error ?

Thanks
Najeeb

**Comment by pichuan** [comment]
From looking at the shapes of the tensors, it seems like you might be using an older model checkpoint?
In an older release, we used to have 7 channels instead of 6.

Can you confirm whether you're using the 0.7.0 model checkpoint?

**Comment by pichuan** [comment]
Closing because inactivity. Feel free to open with more information.
