### ISSUE TITLE
Deep variant error: FAILED_PRECONDITION

### ISSUE THREAD

**Issue by ShrutiMarwaha** [google/deepvariant#118]
Hi Developers,

I am getting the following error when running a WES case through version 0.7.0 of deep variant:

Deep variant error: cause: 'Execution failed: action 1: unexpected exit status 1 was not ignored' code: FAILED_PRECONDITION

However, I am able to successfully run the same files though v0.6.1. I am unable to understand what the above error means. I looked at FAILED_PRECONDITION [here](https://cloud.google.com/genomics/reference/rest/Shared.Types/Code) but it was not helpful. I will appreciate if someone can point the mistake in the script for running v_0.7.0 of deepvariant. 
Operation id: ENLB84XvLBiClY23zqHw1vkBIK2c48-5AyoPcHJvZHVjdGlvblF1ZXVl
I am attaching the complete error file: UDN668131.err

script for v_0.7.0: deepvariant_v0.7.0_UDN668131.sh.txt

scripts for v0.6.1: deepvariant_v0.6.1_UDN668131.sh.txt
deepvariant_v0.6.1_UDN668131.yaml.txt
[UDN668131_error.txt](https://github.com/google/deepvariant/files/2563031/UDN668131_error.txt)
[deepvariant_v0.7.0_UDN668131.sh.txt](https://github.com/google/deepvariant/files/2563033/deepvariant_v0.7.0_UDN668131.sh.txt)
[deepvariant_v0.6.1_UDN668131.sh.txt](https://github.com/google/deepvariant/files/2563036/deepvariant_v0.6.1_UDN668131.sh.txt)
[deepvariant_v0.6.1_UDN668131.yaml.txt](https://github.com/google/deepvariant/files/2563037/deepvariant_v0.6.1_UDN668131.yaml.txt)

Thanks,
Shruti

**Comment by nmousavi** [comment]
No YAML file is needed for running DeepVariant as we migrated to using Genomics Pipeline API v2 since DeepVariant v0.7 . Please see DeepVariant's cloud page for sample scripts

https://cloud.google.com/genomics/docs/tutorials/deepvariant

Note that we keep the cloud page updated with every release, and it is the place to look into in case of major changes to DeepVariant runner.

For debugging, we found workers log more helpful in general. In your case, they are under `gs://gbsc-gcp-project-udn-dev-deep-variant/UDN668131_test/deepvariant_staging_folder/logs`

**Comment by ShrutiMarwaha** [comment]
Thanks nmousavi. I have the yaml file only for v0.6.1 and not for v_0.7.0.

However, thanks for pointing toward workers log folder. This gives a better idea in debugging.

Thanks,
Shruti

**Comment by ShrutiMarwaha** [comment]
Thanks Nima.

I ran it again. Looks like the error is because it is unable to open the bed file I have provided. However, the bed file exists on gcp and my v0.6.1 code was able to access it. I am not sure what I am doing wrong. I was able to run the same code successfully if I provide the bed file in the example documentation (gs://deepvariant/exome-case-study-testdata/refseq.coding_exons.b37.extended50.bed). 

Error file: gbsc-gcp-project-udn-dev-deep-variant/UDN668131_deepVariant_test4/deepvariant_staging_folder/logs/make_examples/0:

W::hts_idx_load2] The index file is older than the data file: /input-gcsfused-48/UDN668131/UDN668131-P_HGF2YBCX2_deduped.bai
2018-11-09 19:48:51.497793: W third_party/nucleus/io/sam_reader.cc:537] Unrecognized SAM header type, ignoring: 
I1109 19:48:51.498179 140612532332288 genomics_reader.py:213] Reading /input-gcsfused-48/UDN668131/UDN668131-P_HGF2YBCX2_deduped.bam with NativeSamReader
I1109 19:48:51.518172 140612532332288 make_examples.py:1075] Preparing inputs
[W::hts_idx_load2] The index file is older than the data file: /input-gcsfused-48/UDN668131/UDN668131-P_HGF2YBCX2_deduped.bai
2018-11-09 19:48:52.291229: W third_party/nucleus/io/sam_reader.cc:537] Unrecognized SAM header type, ignoring: 
I1109 19:48:52.291625 140612532332288 genomics_reader.py:213] Reading /input-gcsfused-48/UDN668131/UDN668131-P_HGF2YBCX2_deduped.bam with NativeSamReader
I1109 19:48:52.335163 140612532332288 make_examples.py:991] Common contigs are [u'1', u'2', u'3', u'4', u'5', u'6', u'7', u'8', u'9', u'10', u'11', u'12', u'13', u'14', u'15', u'16', u'17', u'18', u'19', u'20', u'21', u'22', u'X', u'Y']
[E::hts_open_format] **Failed to open file gs://gbsc-gcp-project-udn-dev-test/VCRome_2_1_hg19_capture_targets_chrStripped.bed**
Traceback (most recent call last):
  File "/mnt/google/.google/tmp/Bazel.runfiles_qQ5ryq/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1188, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/mnt/google/.google/tmp/Bazel.runfiles_qQ5ryq/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1178, in main
    make_examples_runner(options)
  File "/mnt/google/.google/tmp/Bazel.runfiles_qQ5ryq/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1076, in make_examples_runner
    regions = processing_regions_from_options(options)
  File "/mnt/google/.google/tmp/Bazel.runfiles_qQ5ryq/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 993, in processing_regions_from_options
    options.exclude_calling_regions)
  File "/mnt/google/.google/tmp/Bazel.runfiles_qQ5ryq/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 587, in build_calling_regions
    ranges.RangeSet.from_regions(regions_to_include, contig_dict))
  File "/mnt/google/.google/tmp/Bazel.runfiles_qQ5ryq/runfiles/com_google_deepvariant/third_party/nucleus/util/ranges.py", line 161, in from_regions
    return cls(ranges=from_regions(regions, contig_map=contig_map))
  File "/mnt/google/.google/tmp/Bazel.runfiles_qQ5ryq/runfiles/com_google_deepvariant/third_party/nucleus/util/ranges.py", line 113, in __init__
    for i, range_ in enumerate(ranges):
  File "/mnt/google/.google/tmp/Bazel.runfiles_qQ5ryq/runfiles/com_google_deepvariant/third_party/nucleus/util/ranges.py", line 464, in from_regions
    for elt in reader(region):
  File "/mnt/google/.google/tmp/Bazel.runfiles_qQ5ryq/runfiles/com_google_deepvariant/third_party/nucleus/util/ranges.py", line 429, in bed_parser
    with bed.BedReader(filename) as fin:
  File "/mnt/google/.google/tmp/Bazel.runfiles_qQ5ryq/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 211, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/mnt/google/.google/tmp/Bazel.runfiles_qQ5ryq/runfiles/com_google_deepvariant/third_party/nucleus/io/bed.py", line 127, in _native_reader
    return NativeBedReader(input_path, **kwargs)
  File "/mnt/google/.google/tmp/Bazel.runfiles_qQ5ryq/runfiles/com_google_deepvariant/third_party/nucleus/io/bed.py", line 104, in __init__
    self._reader = bed_reader.BedReader.from_file(bed_path, options)
ValueError: Not found: Could not open gs://gbsc-gcp-project-udn-dev-test/VCRome_2_1_hg19_capture_targets_chrStripped.bed
parallel: This job failed:
Using mount point: /input-gcsfused-48
Opening GCS connection...
Opening bucket...
Mounting file system...
File system has been successfully mounted.
mkdir -p ./input-gcsfused-48 && gcsfuse --implicit-dirs gbsc-gcp-project-udn-dev-deep-variant /input-gcsfused-48 && /opt/deepvariant/bin/make_examples --mode calling --examples /mnt/google/.google/output/gbsc-gcp-project-udn-dev-deep-variant/UDN668131_deepVariant_test4/deepvariant_staging_folder/examples/examples_output.tfrecord@64.gz --reads /input-gcsfused-48/UDN668131/UDN668131-P_HGF2YBCX2_deduped.bam --ref /mnt/google/.google/input/gbsc-gcp-project-udn-dev-test/hs37d5_ref/hs37d5.fa --task 48 --regions gs://gbsc-gcp-project-udn-dev-test/VCRome_2_1_hg19_capture_targets_chrStripped.bed

operation id: 3776708258517585322

$ gsutil ls gs://gbsc-gcp-project-udn-dev-test/VCRome_2_1_hg19_capture_targets_chrStripped.bed
gs://gbsc-gcp-project-udn-dev-test/VCRome_2_1_hg19_capture_targets_chrStripped.bed

[deepvariant_v0.7.0_UDN668131_test.sh.txt](https://github.com/google/deepvariant/files/2567583/deepvariant_v0.7.0_UDN668131_test.sh.txt)

Thanks,
Shruti

**Comment by nmousavi** [comment]
We are working on this, please check related bug #116 for the update.

**Comment by nmousavi** [comment]
Please see [my comment there](https://github.com/google/deepvariant/issues/116#issuecomment-438403390).

**Comment by ShrutiMarwaha** [comment]
Thanks Nima. Can you (or an automated message) let me know once this will be fixed.

**Comment by pichuan** [comment]
Hi @ShrutiMarwaha 
The fix for https://github.com/google/deepvariant/issues/119 is included in the v0.7.2 release.
If you still see any issues, let us know.
