### ISSUE TITLE
call_variant step 0.7.1 and 0.7.2rc - job failed with error

### ISSUE THREAD

**Issue by HagenC** [google/deepvariant#129]
Hi all,

I am currently running some tests using deepvariant and getting error codes that I do not understand.
I hope you can help me finding the error. (Sorry for the long post, but the devil is probably in the details!!)

Script:
#!/bin/bash
#set -euo pipefail
# Set common settings.
PROJECT_ID=ms-deepvariant
OUTPUT_BUCKET=gs://ms_bam/deep_output
STAGING_FOLDER_NAME=stage
OUTPUT_FILE_NAME=deeptest_FB4_chr20.vcf
# Model for calling whole exome sequencing data.
MODEL=gs://deepvariant/models/DeepVariant/0.7.1/DeepVariant-inception_v3-0.7.1+data-wgs_standard/
IMAGE_VERSION=0.7.1
DOCKER_IMAGE=gcr.io/deepvariant-docker/deepvariant:"${IMAGE_VERSION}"
COMMAND="/opt/deepvariant_runner/bin/gcp_deepvariant_runner \
  --project ${PROJECT_ID} \
  --zones europe-west1-* \
  --docker_image ${DOCKER_IMAGE} \
  --outfile ${OUTPUT_BUCKET}/${OUTPUT_FILE_NAME} \
  --staging ${OUTPUT_BUCKET}/${STAGING_FOLDER_NAME} \
  --model ${MODEL} \
  --regions gs://public_bed/CHR20.bed \
  --bam gs://ms_bam/NoDup_FB4.bam \
  --bai gs://ms_bam/NoDup_FB4.bam.bai \
  --ref gs://ms_bam/Homo_sapiens_assembly38.fasta \
  --ref_fai gs://ms_bam/Homo_sapiens_assembly38.fasta.fai \
  --gcsfuse"
# Run the pipeline.
gcloud alpha genomics pipelines run \
    --project "${PROJECT_ID}" \
    --service-account-scopes="https://www.googleapis.com/auth/cloud-platform" \
    --logging "${OUTPUT_BUCKET}/${STAGING_FOLDER_NAME}/runner_logs_$(date +%Y%m%d_%H%M%S).log" \
    --zones europe-west1-b \
    --docker-image gcr.io/deepvariant-docker/deepvariant_runner:"${IMAGE_VERSION}" \
    --command-line "${COMMAND}"

1. I have quoted #set -euo pipefail out as it returns an error.
2. The bed file is located in a public bucket #119 
3. I have tried with docker image 0.7.1 which returns following error:

[12/12/2018 14:14:08 INFO gcp_deepvariant_runner.py] Running make_examples...
[12/12/2018 14:34:47 INFO gcp_deepvariant_runner.py] make_examples is done!
[12/12/2018 14:34:47 INFO gcp_deepvariant_runner.py] Running call_variants...
[12/12/2018 14:37:23 ERROR gcp_deepvariant_runner.py] Job failed with error "run": operation "projects/ms-deepvariant/operations/5187520767668161022" failed: executing pipeline: Execution failed: action 4: unexpected exit status 1 was not ignored (reason: FAILED_PRECONDITION)
. Job args: ['pipelines', '--project', 'ms-deepvariant', 'run', '--attempts', '2', '--pvm-attempts', '0', '--boot-disk-size', '50', '--output-interval', '60s', '--zones', 'europe-west1-*', '--name', 'call_variants', '--vm-labels', 'dv-job-name=call_variants', '--output', 'gs://ms_bam/deep_output/stage/logs/call_variants/0', '--image', 'gcr.io/deepvariant-docker/deepvariant:0.7.1', '--inputs', 'EXAMPLES=gs://ms_bam/deep_output/stage/examples/0/*', '--outputs', 'CALLED_VARIANTS=gs://ms_bam/deep_output/stage/called_variants/*', '--machine-type', 'custom-8-30720', '--disk-size', '30', '--set', 'MODEL=gs://deepvariant/models/DeepVariant/0.7.1/DeepVariant-inception_v3-0.7.1+data-wgs_standard/', '--set', 'SHARDS=8', '--set', 'CALL_VARIANTS_SHARD_INDEX=0', '--set', 'CALL_VARIANTS_SHARDS=1', '--command', '\n/opt/deepvariant/bin/call_variants\n  --examples "${EXAMPLES}"/examples_output.tfrecord@"${SHARDS}".gz\n  --outfile "${CALLED_VARIANTS}"/call_variants_output.tfrecord-"$(printf "%05d" "${CALL_VARIANTS_SHARD_INDEX}")"-of-"$(printf "%05d" "${CALL_VARIANTS_SHARDS}")".gz\n  --checkpoint "${MODEL}"/model.ckpt\n  --batch_size 512\n']
Traceback (most recent call last):
  File "/opt/deepvariant_runner/src/gcp_deepvariant_runner.py", line 888, in <module>
    run()
  File "/opt/deepvariant_runner/src/gcp_deepvariant_runner.py", line 875, in run
    _run_call_variants(pipeline_args)
  File "/opt/deepvariant_runner/src/gcp_deepvariant_runner.py", line 472, in _run_call_variants
    _run_call_variants_with_pipelines_api(pipeline_args)
  File "/opt/deepvariant_runner/src/gcp_deepvariant_runner.py", line 464, in _run_call_variants_with_pipelines_api
    _wait_for_results(threads, results)
  File "/opt/deepvariant_runner/src/gcp_deepvariant_runner.py", line 350, in _wait_for_results
    result.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
RuntimeError: Job failed with error "run": operation "projects/ms-deepvariant/operations/23423423423423443" failed: executing pipeline: Execution failed: action 4: unexpected exit status 1 was not ignored (reason: FAILED_PRECONDITION)

4. Changing to 0.7.2rc gives following error: 
[12/12/2018 13:12:23 INFO gcp_deepvariant_runner.py] Running make_examples...
[12/12/2018 13:31:21 INFO gcp_deepvariant_runner.py] make_examples is done!
[12/12/2018 13:31:21 INFO gcp_deepvariant_runner.py] Running call_variants...
[12/12/2018 13:33:54 ERROR gcp_deepvariant_runner.py] Job failed with error {...........cutout...
13:33:48 Stopped running "-c /opt/deepvariant/bin/call_variants --examples \"${EXAMPLES}\"/examples_output.tfrecord@\"${SHARDS}\".gz --outfile \"${CALLED_VARIANTS}\"/call_variants_output.tfrecord-\"$(printf \"%05d\" \"${CALL_VARIANTS_SHARD_INDEX}\")\"-of-\"$(printf \"%05d\" \"${CALL_VARIANTS_SHARDS}\")\".gz --checkpoint \"${MODEL}\"/model.ckpt --batch_size 512": exit status 1: turn self._sess_creator.create_session()
  File "/root/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 800, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/root/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 566, in create_session
    init_fn=self._scaffold.init_fn)
  File "/root/.local/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 288, in prepare_session
    config=config)
  File "/root/.local/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 202, in _restore_checkpoint
    saver.restore(sess, checkpoint_filename_with_path)
  File "/root/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1538, in restore
    + compat.as_text(save_path))
ValueError: The passed save_path is not a valid checkpoint: gs://deepvariant/models/DeepVariant/0.7.1/DeepVariant-inception_v3-0.7.1+data-wgs_standard//model.ckpt
13:33:48 Unexpected exit status 1 while running "-c /opt/deepvariant/bin/call_variants --examples \"${EXAMPLES}\"/examples_output.tfrecord@\"${SHARDS}\".gz --outfile \"${CALLED_VARIANTS}\"/call_variants_output.tfrecord-\"$(printf \"%05d\" \"${CALL_VARIANTS_SHARD_INDEX}\")\"-of-\"$(printf \"%05d\" \"${CALL_VARIANTS_SHARDS}\")\".gz --checkpoint \"${MODEL}\"/model.ckpt --batch_size 512"
13:33:48 Started running "-c gsutil -q cp /google/logs/output gs://ms_bam/deep_output/stage/logs/call_variants/0"
13:33:50 Stopped running "-c gsutil -q cp /google/logs/output gs://ms_bam/deep_output/stage/logs/call_variants/0"
13:33:50 Execution failed: action 4: unexpected exit status 1 was not ignored
13:33:51 Worker released
 "run": operation "projects/ms-deepvariant/operations/234234234234" failed: executing pipeline: Execution failed: action 4: unexpected exit status 1 was not ignored (reason: FAILED_PRECONDITION)
. Job args: ['pipelines', '--project', 'ms-deepvariant', 'run', '--attempts', '2', '--pvm-attempts', '0', '--boot-disk-size', '50', '--output-interval', '60s', '--zones', 'europe-west1-*', '--name', 'call_variants', '--vm-labels', 'dv-job-name=call_variants', '--output', 'gs://ms_bam/deep_output/stage/logs/call_variants/0', '--image', 'gcr.io/deepvariant-docker/deepvariant:0.7.2rc', '--inputs', 'EXAMPLES=gs://ms_bam/deep_output/stage/examples/0/*', '--outputs', 'CALLED_VARIANTS=gs://ms_bam/deep_output/stage/called_variants/*', '--machine-type', 'custom-8-30720', '--disk-size', '30', '--set', 'MODEL=gs://deepvariant/models/DeepVariant/0.7.1/DeepVariant-inception_v3-0.7.1+data-wgs_standard/', '--set', 'SHARDS=8', '--set', 'CALL_VARIANTS_SHARD_INDEX=0', '--set', 'CALL_VARIANTS_SHARDS=1', '--command', '\n/opt/deepvariant/bin/call_variants\n  --examples "${EXAMPLES}"/examples_output.tfrecord@"${SHARDS}".gz\n  --outfile "${CALLED_VARIANTS}"/call_variants_output.tfrecord-"$(printf "%05d" "${CALL_VARIANTS_SHARD_INDEX}")"-of-"$(printf "%05d" "${CALL_VARIANTS_SHARDS}")".gz\n  --checkpoint "${MODEL}"/model.ckpt\n  --batch_size 512\n']
[12/12/2018 13:33:54 ERROR gcp_deepvariant_runner.py] For more information, consult the worker log at gs://ms_bam/deep_output/stage/logs/call_variants/0
Traceback (most recent call last):
  File "/opt/deepvariant_runner/src/gcp_deepvariant_runner.py", line 908, in <module>
    run()
  File "/opt/deepvariant_runner/src/gcp_deepvariant_runner.py", line 895, in run
    _run_call_variants(pipeline_args)
  File "/opt/deepvariant_runner/src/gcp_deepvariant_runner.py", line 491, in _run_call_variants
    _run_call_variants_with_pipelines_api(pipeline_args)
  File "/opt/deepvariant_runner/src/gcp_deepvariant_runner.py", line 483, in _run_call_variants_with_pipelines_api
    _wait_for_results(threads, results)
  File "/opt/deepvariant_runner/src/gcp_deepvariant_runner.py", line 369, in _wait_for_results
    result.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
RuntimeError: Job failed with error "run": operation "projects/ms-deepvariant/operations/23049213423" failed: executing pipeline: Execution failed: action 4: unexpected exit status 1 was not ignored (reason: FAILED_PRECONDITION)

5. The script is run from a GCP VM instance.
6. I have a standard setup with increased CPUs to 1025. 

It is not clear to me what the issues are and what to make of the errors? 
I am sorry If this is not the correct forum to post in - please let me know where to seek help if not! 
Cheers, C

**Comment by akolesnikov** [comment]
Hi Hagen,

Could you please attach worker logs located at gs://ms_bam/deep_output/stage/logs/call_variants/0?

**Comment by HagenC** [comment]
Hi @akolesnikov ,

Here it is:
[deep_output_stage_logs_call_variants_0.txt](https://github.com/google/deepvariant/files/2679100/deep_output_stage_logs_call_variants_0.txt)

Thanks.
