### ISSUE TITLE
Sharding issue for make_examples

### ISSUE THREAD

**Issue by ekofman** [google/deepvariant#143]
Hi,

I'm trying to run make_examples with 64 shards using 64 cores (1 worker per shard default I assume) and the following settings:
    docker: "gcr.io/deepvariant-docker/deepvariant_gpu:0.6.0"
    zones: ["us-central1-c"] 

I am trying to use essentially the same code as is listed in the documentation:

```
## Run `make_examples`
    echo "Start running make_examples...Log will be in the terminal and also to make_examples.log."
    ( time seq 0 $((${numShards}-1)) | \
      parallel -k --line-buffer \
          /opt/deepvariant/bin/make_examples \
          --mode calling \
          --ref ${Fasta} \
          --reads /reads.bam \
          --examples "${sample_id}.examples.tfrecord${numShards}" \
          --gvcf "${sample_id}.gvcf.tfrecord${numShards}" \
          --task {} \
    ) 2>&1 | tee "make_examples.log"
    echo "Done."
    echo

```
However, I am getting the following error for each of the shards: 

`ValueError: ('Output is not sharded but shard > 0', 4)`

What does this mean? I assume it means I am not actually sharding though it seems I am.

Any help appreciated, thanks.

Another example with full stack trace:

```
Traceback (most recent call last):
  File "/cromwell_root/tmp.97900f56/Bazel.runfiles_WhyWBe/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1120, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/cromwell_root/tmp.97900f56/Bazel.runfiles_WhyWBe/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1071, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/cromwell_root/tmp.97900f56/Bazel.runfiles_WhyWBe/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 335, in default_options
    flags_obj.gvcf or '')
  File "/cromwell_root/tmp.97900f56/Bazel.runfiles_WhyWBe/runfiles/com_google_deepvariant/third_party/nucleus/util/io_utils.py", line 212, in resolve_filespecs
    raise ValueError('Output is not sharded but shard > 0', shard)
ValueError: ('Output is not sharded but shard > 0', 44)

```

**Comment by akolesnikov** [comment]
Hi Eric,

Program determines if output is sharded by matching examples with the following pattern: ((.*)\@(\d*[1-9]\d*)(?:\.(.+))?)
In your code snippet there is no '@' in examples output spec. Try to make your example spec the same way (or similar) as in documentation:
--examples "${OUTPUT_DIR}/examples.tfrecord@${N_SHARDS}.gz"

**Comment by ekofman** [comment]
Ah I see, thank you @akolesnikov I'll try that out!

**Comment by akolesnikov** [comment]
I will close it for now. If needed you may reopen the issue.
