### ISSUE TITLE
Calling does not work

### ISSUE THREAD

**Issue by PlatonB** [google/deepvariant#219]
Distro: elementary OS 5.0

First attempt to run a calling:
`sudo docker run gcr.io/deepvariant-docker/deepvariant:0.8.0 /opt/deepvariant/bin/run_deepvariant --model_type=WGS --ref=/home/platon/_0_Диссертация/Exp/seq1/seq1.fa --reads=/home/platon/_0_Диссертация/Exp/seq1/seq1.bam --output_vcf=/home/platon/_0_Диссертация/Exp/seq1/seq1.vcf`

```
***** Running the command:*****
time seq 0 0 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/home/platon/_0_Диссертация/Exp/seq1/seq1.fa" --reads "/home/platon/_0_Диссертация/Exp/seq1/seq1.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@1.gz" --task {}

Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_vtX6qv/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1235, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_vtX6qv/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1186, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/tmp/Bazel.runfiles_vtX6qv/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 315, in default_options
    with sam.SamReader(flags_obj.reads) as sam_reader:
  File "/tmp/Bazel.runfiles_vtX6qv/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 216, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_vtX6qv/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 255, in _native_reader
    return NativeSamReader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_vtX6qv/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 224, in __init__
    input_path.encode('utf8'),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 16: ordinal not in range(128)

real	0m1.622s
user	0m1.578s
sys	0m0.693s
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 235, in <module>
    app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 215, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 0 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/home/platon/_0_Диссертация/Exp/seq1/seq1.fa" --reads "/home/platon/_0_Диссертация/Exp/seq1/seq1.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@1.gz" --task {}' returned non-zero exit status 1
```

Second attempt. This time with paths consisting only of latin characters.
`sudo docker run gcr.io/deepvariant-docker/deepvariant:0.8.0 /opt/deepvariant/bin/run_deepvariant --model_type=WGS --ref=/home/platon/test/seq1.fa --reads=/home/platon/test/seq1.bam --output_vcf=/home/platon/test/seq1.vcf`

```
***** Running the command:*****
time seq 0 0 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/home/platon/test/seq1.fa" --reads "/home/platon/test/seq1.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@1.gz" --task {}

[E::hts_open_format] Failed to open file /home/platon/test/seq1.bam
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_AruJXP/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1235, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_AruJXP/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1186, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/tmp/Bazel.runfiles_AruJXP/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 315, in default_options
    with sam.SamReader(flags_obj.reads) as sam_reader:
  File "/tmp/Bazel.runfiles_AruJXP/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 216, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_AruJXP/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 255, in _native_reader
    return NativeSamReader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_AruJXP/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 232, in __init__
    use_original_base_quality_scores=use_original_base_quality_scores)
ValueError: Not found: Could not open /home/platon/test/seq1.bam

real	0m1.571s
user	0m1.481s
sys	0m0.786s
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 235, in <module>
    app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 215, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 0 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/home/platon/test/seq1.fa" --reads "/home/platon/test/seq1.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@1.gz" --task {}' returned non-zero exit status 1
```

Source data:
[test_seq_data.tar.gz](https://github.com/google/deepvariant/files/3611565/test_seq_data.tar.gz)

**Comment by akolesnikov** [comment]
Hi PlatonB,

The error you get is "Could not open /home/platon/test/seq1.bam"
Did you forget to add "-v" flag to your docker run command to mount your input directory? Take a look at DeepVariant documentation [here](https://github.com/google/deepvariant/blob/r0.8/docs/deepvariant-quick-start.md#run-deepvariant-with-one-command) for the example on how to run DeepVariant from docker image.

**Comment by PlatonB** [comment]
I'm sorry for the inattention.
