### ISSUE TITLE
Error in running DeepVariant in Docker on CentOS 7

### ISSUE THREAD

**Issue by ccartermices** [google/deepvariant#226]
I ran deepvariant in docker on centos 7 but had some errors:
docker run -v  \
> /db_students/genetic_map/dv_workarea/test \
> dajunluo/deepvariant:latest \
> /opt/deepvariant/bin/run_deepvariant \
> --model_type=WGS \
> --ref=/opt/quickstart-testdata/ucsc.hg19.chr20.unittest.fasta \
> --reads=/opt/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam \
> --regions "chr20:10,000,000-10,010,000" \
> --output_vcf=test_output.vcf.gz \
> --output_gvcf=test_output.g.vcf.gz \
> --num_shards=2

***** Running the command:*****
time seq 0 1 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/opt/quickstart-testdata/ucsc.hg19.chr20.unittest.fasta" --reads "/opt/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@2.gz" --regions "chr20:10,000,000-10,010,000" --gvcf "/tmp/deepvariant_tmp_output/gvcf.tfrecord@2.gz" --task {}

2019-10-15 11:18:39.819615: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
2019-10-15 11:18:39.819621: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.

real	0m23.020s
user	0m1.610s
sys	0m3.206s
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 235, in <module>
    app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 215, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 1 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/opt/quickstart-testdata/ucsc.hg19.chr20.unittest.fasta" --reads "/opt/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@2.gz" --regions "chr20:10,000,000-10,010,000" --gvcf "/tmp/deepvariant_tmp_output/gvcf.tfrecord@2.gz" --task {}' returned non-zero exit status 2

Do anyone know how to handle it?

**Comment by gunjanbaid** [comment]
@ccartermices I'll close this issue for now, but feel free to reopen if you have any other questions. Thanks!
