### ISSUE TITLE
CondaError: Downloaded bytes did not match Content-Length

### ISSUE THREAD

**Issue by ydLiu-HIT** [google/deepvariant#228]
Hi, 
when I install deepvariant by anaconda with the command "conda install -c bioconda deepvariant", version 0.8.0 will be installed, but I got the following errors at the end of installation:

CondaError: Downloaded bytes did not match Content-Length
  url: https://conda.anaconda.org/bioconda/linux-64/deepvariant-0.8.0-py27h7333d49_0.tar.bz2
  target_path: /home/ydliu/anaconda3/pkgs/deepvariant-0.8.0-py27h7333d49_0.tar.bz2
  Content-Length: 229846992
  downloaded bytes: 217650750

Best.

**Comment by pichuan** [comment]
Hi @ydLiu-HIT 
I'll add @chapmanb (owner of the conda package) to this thread and see if he can provide some support here. Thanks!

**Comment by chapmanb** [comment]
Thanks for the question and sorry about these issues. It seems like there was some kind of download issue with the deepvariant conda package in your environment. The 0.8.0 package has been around ~6 months and not changed recently, so I'm guessing maybe you got a partial download or other issue. If you remove your local download (` /home/ydliu/anaconda3/pkgs/deepvariant-0.8.0-py27h7333d49_0.tar.bz2`) and re-run, does it work cleanly? Is there anything about your network or other messages that might indicate an issue that could help us debug more? Hope this helps.

**Comment by ydLiu-HIT** [comment]
Hi, 
I got another error when I remove my local download ( /home/ydliu/anaconda3/pkgs/deepvariant-0.8.0-py27h7333d49_0.tar.bz2) and re-run as follows.


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'bioconda::deepvariant-0.8.0-py27h7333d49_0'.
Rolling back transaction: done

LinkError: post-link script failed for package bioconda::deepvariant-0.8.0-py27h7333d49_0
location of failed script: /home/ydliu/anaconda3/envs/py2.7/bin/.deepvariant-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: INFO 1101 14:33:31.774699 util.py] Retrying request, attempt #1...
INFO 1101 14:34:33.764798 util.py] Retrying request, attempt #2...
INFO 1101 14:35:36.852041 util.py] Retrying request, attempt #3...
INFO 1101 14:36:43.774008 util.py] Retrying request, attempt #4...
INFO 1101 14:37:59.406010 util.py] Retrying request, attempt #5...
INFO 1101 14:39:31.468027 util.py] Retrying request, attempt #6...
INFO 1101 14:41:03.574773 util.py] Retrying request, attempt #7...
INFO 1101 14:42:35.649608 util.py] Retrying request, attempt #8...
INFO 1101 14:44:07.752737 util.py] Retrying request, attempt #9...
INFO 1101 14:45:39.836059 util.py] Retrying request, attempt #10...
INFO 1101 14:47:11.942440 util.py] Retrying request, attempt #11...
INFO 1101 14:48:43.990016 util.py] Retrying request, attempt #12...
INFO 1101 14:50:16.078940 util.py] Retrying request, attempt #13...
INFO 1101 14:51:48.200379 util.py] Retrying request, attempt #14...
INFO 1101 14:53:20.307419 util.py] Retrying request, attempt #15...
INFO 1101 14:54:52.388456 util.py] Retrying request, attempt #16...
INFO 1101 14:56:24.486618 util.py] Retrying request, attempt #17...
INFO 1101 14:57:56.579738 util.py] Retrying request, attempt #18...
INFO 1101 14:59:28.640781 util.py] Retrying request, attempt #19...
INFO 1101 15:01:00.705409 util.py] Retrying request, attempt #20...
INFO 1101 15:02:32.828025 util.py] Retrying request, attempt #21...
INFO 1101 15:04:04.934843 util.py] Retrying request, attempt #22...
Traceback (most recent call last):
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/gsutil", line 22, in <module>
    gsutil.RunMain()
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/gsutil.py", line 114, in RunMain
    sys.exit(gslib.__main__.main())
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/gslib/__main__.py", line 383, in main
    perf_trace_token=perf_trace_token)
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/gslib/__main__.py", line 577, in _RunNamedCommandAndHandleExceptions
    collect_analytics=True)
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/gslib/command_runner.py", line 317, in RunNamedCommand
    return_code = command_inst.RunCommand()
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/gslib/commands/cp.py", line 1139, in RunCommand
    seek_ahead_iterator=seek_ahead_iterator)
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/gslib/command.py", line 1368, in Apply
    arg_checker, should_return_results, fail_on_error)
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/gslib/command.py", line 1414, in _SequentialApply
    args = args_iterator.next()
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/gslib/name_expansion.py", line 622, in next
    name_expansion_result = self.current_expansion_iter.next()
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/gslib/plurality_checkable_iterator.py", line 60, in _PopulateHead
    e = self.base_iterator.next()
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/gslib/name_expansion.py", line 265, in __iter__
    for (names_container, blr) in post_step3_iter:
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/gslib/plurality_checkable_iterator.py", line 60, in _PopulateHead
    e = self.base_iterator.next()
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/gslib/name_expansion.py", line 468, in __iter__
    for (names_container, blr) in self.tuple_iter:
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/gslib/plurality_checkable_iterator.py", line 60, in _PopulateHead
    e = self.base_iterator.next()
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/gslib/name_expansion.py", line 432, in __iter__
    for blr in self.blr_iter:
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/gslib/plurality_checkable_iterator.py", line 60, in _PopulateHead
    e = self.base_iterator.next()
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/gslib/wildcard_iterator.py", line 476, in IterAll
    expand_top_level_buckets=expand_top_level_buckets):
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/gslib/wildcard_iterator.py", line 215, in __iter__
    provider=self.wildcard_url.scheme, fields=listing_fields):
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/gslib/gcs_json_api.py", line 595, in ListObjects
    global_params=global_params)
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/gslib/third_party/storage_apitools/storage_v1_client.py", line 1237, in List
    config, request, global_params=global_params)
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/third_party/apitools/apitools/base/py/base_api.py", line 701, in _RunMethod
    http, http_request, **opts)
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/third_party/apitools/apitools/base/py/http_wrapper.py", line 341, in MakeRequest
    check_response_func=check_response_func)
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/third_party/apitools/apitools/base/py/http_wrapper.py", line 391, in _MakeRequestNoRetry
    redirections=redirections, connection_type=connection_type)
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/third_party/httplib2/python2/httplib2/__init__.py", line 1570, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/third_party/httplib2/python2/httplib2/__init__.py", line 1317, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/third_party/httplib2/python2/httplib2/__init__.py", line 1252, in _conn_request
    conn.connect()
  File "/home/ydliu/anaconda3/envs/py2.7/share/google-cloud-sdk-166.0.0-0/platform/gsutil/third_party/httplib2/python2/httplib2/__init__.py", line 1018, in connect
    sock.connect((self.host, self.port))
  File "/home/ydliu/anaconda3/envs/py2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.timeout: timed out

return code: 1

()

**Comment by chapmanb** [comment]
Thanks for following up and for the detailed error log. This looks again like a connectivity issue. The deepvariant recipe needs to pull down the training files from a Google Bucket and is timing out trying to connect. Either there was a general internet issue or there is something blocking access to the bucket. If you re-try multiple times, does it fail in the same way? If so, you may need to investigate if the machine can access Google buckets for download. Hope this helps with tracking down the issue.

**Comment by ydLiu-HIT** [comment]
Thanks. 
I have solved this problem. The main reason is my machine can't access Google buckets for download as you say.

**Comment by nksas** [comment]
> Hi,
> when I install deepvariant by anaconda with the command "conda install -c bioconda deepvariant", version 0.8.0 will be installed, but I got the following errors at the end of installation:
> 
> CondaError: Downloaded bytes did not match Content-Length
> url: https://conda.anaconda.org/bioconda/linux-64/deepvariant-0.8.0-py27h7333d49_0.tar.bz2
> target_path: /home/ydliu/anaconda3/pkgs/deepvariant-0.8.0-py27h7333d49_0.tar.bz2
> Content-Length: 229846992
> downloaded bytes: 217650750
> 
> Best.

hey i have got the same error. can you pls help if it's solved by you ?
