### ISSUE TITLE
Reference contigs span 30884600 bases but only 0 bases (0.00%) were found in common among our input files

### ISSUE THREAD

**Issue by PlatonB** [google/deepvariant#250]
Elementary OS 5.1
Docker version 18.09.7, build 2d0083d
Bowtie 2
Samtools 1.9
DeepVariant 0.9.0

Original source files.
- _SRR062634.filt.fastq_ from ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/data/HG00096/sequence_read/
- _Homo_sapiens.GRCh38.dna.primary_assembly.fa_ from ftp://ftp.ensembl.org/pub/release-98/fasta/homo_sapiens/dna/

Actions.
1. Bowtie 2: indexing _Homo_sapiens.GRCh38.dna.primary_assembly.fa_
2. Bowtie 2: aligning _SRR062634.filt.fastq_ on _Homo_sapiens.GRCh38.dna.primary_assembly.fa_
3. Samtools: converting _SRR062634.sam_ to _SRR062634.bam_
4. Samtools: indexing _SRR062634.filt.fastq_
5. DeepVariant: trying to call SNPs.

DeepVariant command syntax.
`sudo docker run -v "/home/platon/_0_Диссертация/Exp/seq1/bowtie2/":"/input" -v "/home/platon/_0_Диссертация/Exp/seq1/bowtie2/":"/output" google/deepvariant:"0.9.0" /opt/deepvariant/bin/run_deepvariant --model_type=WGS --ref=/input/SRR062634.filt.fastq --reads=/input/SRR062634.bam --output_vcf=/output/SRR062634.vcf.gz --num_shards=4`

Part of error log.
```
***** Running the command:*****
time seq 0 3 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/SRR062634.filt.fastq" --reads "/input/SRR062634.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@4.gz" --task {}

I1208 19:49:03.680470 140573386819328 make_examples.py:377] ReadRequirements are: min_mapping_quality: 10
min_base_quality: 10
min_base_quality_mode: ENFORCED_BY_CLIENT

I1208 19:49:03.681448 140573386819328 genomics_reader.py:223] Reading /input/SRR062634.bam with NativeSamReader
W1208 19:49:03.681570 140573386819328 make_examples.py:558] No non-empty sample name found in the input reads. DeepVariant will use default as the sample name. You can also provide a sample name with the --sample_name argument.
I1208 19:49:03.742767 140573386819328 make_examples.py:1324] Preparing inputs
I1208 19:49:05.745795 140573386819328 genomics_reader.py:223] Reading /input/SRR062634.bam with NativeSamReader
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_pllyfZ/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1461, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_pllyfZ/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1451, in main
    make_examples_runner(options)
  File "/tmp/Bazel.runfiles_pllyfZ/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1325, in make_examples_runner
    regions = processing_regions_from_options(options)
  File "/tmp/Bazel.runfiles_pllyfZ/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1247, in processing_regions_from_options
    options.min_shared_contigs_basepairs)
  File "/tmp/Bazel.runfiles_pllyfZ/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 625, in _ensure_consistent_contigs
    min_coverage_fraction)
  File "/tmp/Bazel.runfiles_pllyfZ/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 703, in validate_reference_contig_coverage
    ref_bp, common_bp, coverage, format_contig_matches()))
ValueError: Reference contigs span 30884600 bases but only 0 bases (0.00%) were found in common among our input files. Check that the sources were created on a common genome reference build. Contig matches were: 
"SRR062634.321" is 100 bp and IS MISSING, 
"SRR062634.488" is 100 bp and IS MISSING, 
"SRR062634.849" is 100 bp and IS MISSING, 
"SRR062634.850" is 100 bp and IS MISSING, 
"SRR062634.1455" is 100 bp and IS MISSING, 
<...>
"SRR062634.24476105" is 100 bp and IS MISSING, 
"SRR062634.24476106" is 100 bp and IS MISSING, 
"SRR062634.24476107" is 100 bp and IS MISSING, 
"SRR062634.24476108" is 100 bp and IS MISSING, 
"SRR062634.24476109" is 100 bp and IS MISSING. Here is a useful article about different human genome reference builds:
https://gatkforums.broadinstitute.org/gatk/discussion/11010/human-genome-reference-builds-grch38-hg38-b37-hg19
Please make sure the --ref input matches the build used for the input in --reads.

real	4m17.584s
user	15m16.628s
sys	0m4.274s
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 317, in <module>
    app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 307, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 3 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/SRR062634.filt.fastq" --reads "/input/SRR062634.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@4.gz" --task {}' returned non-zero exit status 4
```

Please tell me what I did wrong.

**Comment by AndrewCarroll** [comment]
Hi @PlatonB 

The stderr output of DeepVariant for the make_examples line has: 

"--ref "/input/SRR062634.filt.fastq"

This is providing the input reads in position of the reference genome. Instead, you will need to provide the bgzipped, indexed file for Homo_sapiens.GRCh38.dna.primary_assembly.fa. You can do so with the commands:

bgzip -i Homo_sapiens.GRCh38.dna.primary_assembly.fa && samtools faidx Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

and then replace the ref location to match in the command.

**Comment by PlatonB** [comment]
Thank you! Now it works.
