### ISSUE TITLE
Install precompiled binaries

### ISSUE THREAD

**Issue by RenzoTale88** [google/deepvariant#252]
Hello,
I'm writing you because I'm trying to install deepvariant, but I'm encountering several difficulties in doing so.
I've tried at first to install through anaconda (```conda install -c bioconda deepvariant```), but I alway get the same problem:
```


    Traceback (most recent call last):
      File "/exports/applications/apps/SL7/anaconda/5.0.1/lib/python3.6/site-packages/conda/core/link.py", line 497, in run_script
        subprocess_call(command_args, env=env, path=dirname(path))
      File "/exports/applications/apps/SL7/anaconda/5.0.1/lib/python3.6/site-packages/conda/gateways/subprocess.py", line 56, in subprocess_call
        output=_format_output(command_str, path, rc, stdout, stderr))
    subprocess.CalledProcessError: Command '['/bin/bash', '-x', '/PATH/TO/MY/FOLDER/Andrea/myanaconda/deepvariant/bin/.deepvariant-post-link.sh']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/exports/applications/apps/SL7/anaconda/5.0.1/lib/python3.6/site-packages/conda/core/link.py", line 327, in _execute_actions
        run_script(target_prefix, Dist(pkg_data), 'post-unlink' if is_unlink else 'post-link')
      File "/exports/applications/apps/SL7/anaconda/5.0.1/lib/python3.6/site-packages/conda/core/link.py", line 513, in run_script
        raise LinkError(message)
    conda.exceptions.LinkError: post-link script failed for package bioconda::deepvariant-0.9.0-py27h7333d49_0
    running your command again with `-v` will provide additional information
    location of failed script: /PATH/TO/MY/FOLDER/Andrea/myanaconda/deepvariant/bin/.deepvariant-post-link.sh
    ==> script messages <==
    <None>
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/exports/applications/apps/SL7/anaconda/5.0.1/lib/python3.6/site-packages/conda/core/link.py", line 281, in execute
        pkg_data, actions)
      File "/exports/applications/apps/SL7/anaconda/5.0.1/lib/python3.6/site-packages/conda/core/link.py", line 344, in _execute_actions
        reverse_excs,
    conda.CondaMultiError: post-link script failed for package bioconda::deepvariant-0.9.0-py27h7333d49_0
    running your command again with `-v` will provide additional information
    location of failed script: /PATH/TO/MY/FOLDER/Andrea/myanaconda/deepvariant/bin/.deepvariant-post-link.sh
    ==> script messages <==
    <None>
    
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/exports/applications/apps/SL7/anaconda/5.0.1/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/exports/applications/apps/SL7/anaconda/5.0.1/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/exports/applications/apps/SL7/anaconda/5.0.1/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/exports/applications/apps/SL7/anaconda/5.0.1/lib/python3.6/site-packages/conda/cli/install.py", line 326, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/exports/applications/apps/SL7/anaconda/5.0.1/lib/python3.6/site-packages/conda/plan.py", line 828, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/exports/applications/apps/SL7/anaconda/5.0.1/lib/python3.6/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/exports/applications/apps/SL7/anaconda/5.0.1/lib/python3.6/site-packages/conda/instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "/exports/applications/apps/SL7/anaconda/5.0.1/lib/python3.6/site-packages/conda/core/link.py", line 297, in execute
        rollback_excs,
    conda.CondaMultiError: post-link script failed for package bioconda::deepvariant-0.9.0-py27h7333d49_0
    running your command again with `-v` will provide additional information
    location of failed script: /PATH/TO/MY/FOLDER/Andrea/myanaconda/deepvariant/bin/.deepvariant-post-link.sh
    ==> script messages <==
    <None>
```
Hovewer, since conda installed successfully all the dependencies, I've then tried to download the precompiled binaries and use them, but couldn't find a guide on how to install them.
Is there a page where to find guidelines on how to install the precompiled deepvariant?
If not, is there a way to fix the anaconda environment issue?

Thank you in advance,

Andrea

**Comment by pichuan** [comment]
Looking at this error message, I wonder if it's related to Python3 vs Python2.
Currently DeepVariant still only supports Python2.

Adding @chapmanb (who maintains DeepVariant on bioconda ) , do you think there might be other issues going on here? Thanks!

**Comment by chapmanb** [comment]
Thanks for the question. I'm agreed with Pi-Chuan, trying in a python 2.7 conda environment should hopefully resolve these issues. Hope that gets the install figured out.

**Comment by RenzoTale88** [comment]
Interestingly, mine is a python 2.7.15 machine. Below the list of the packages installed by anaconda in the environment:
```

Package plan for package removal in environment .../Andrea/myanaconda/deepvariant:

The following packages will be REMOVED:

    _libgcc_mutex:        0.1-main                      conda-forge
    _tflow_select:        2.1.0-gpu                                
    absl-py:              0.8.1-py27_0                  conda-forge
    astor:                0.7.1-py_0                    conda-forge
    backports:            1.0-py_2                      conda-forge
    backports.weakref:    1.0.post1-py27_1000           conda-forge
    boost:                1.70.0-py27h9de70de_1         conda-forge
    boost-cpp:            1.70.0-h8e57a91_2             conda-forge
    bzip2:                1.0.8-h516909a_2              conda-forge
    c-ares:               1.15.0-h516909a_1001          conda-forge
    ca-certificates:      2019.11.28-hecc5488_0         conda-forge
    certifi:              2019.11.28-py27_0             conda-forge
    cffi:                 1.13.2-py27h8022711_0         conda-forge
    chardet:              3.0.4-py27_1003               conda-forge
    cliff:                2.15.0-py27_0                 conda-forge
    cmd2:                 0.8.6-py27_0                  conda-forge
    contextlib2:          0.6.0-py_0                    conda-forge
    crcmod:               1.7-py27_1002                 conda-forge
    cryptography:         2.8-py27h72c5cf5_1            conda-forge
    cudatoolkit:          9.2-0                                    
    cudnn:                7.6.4-cuda9.2_0                          
    cupti:                9.2.148-0                                
    curl:                 7.65.3-hf8cf82a_0             conda-forge
    enum34:               1.1.6-py27_1002               conda-forge
    funcsigs:             1.0.2-py_3                    conda-forge
    futures:              3.3.0-py27_0                  conda-forge
    gast:                 0.3.2-py_0                    conda-forge
    google-cloud-sdk:     166.0.0-py27_0                bioconda   
    grpcio:               1.23.0-py27he9ae1f9_0         conda-forge
    h5py:                 2.10.0-nompi_py27h513d04c_101 conda-forge
    hdf5:                 1.10.5-nompi_h3c11f04_1104    conda-forge
    htslib:               1.9-h244ad75_9                bioconda   
    httplib2:             0.14.0-py27_0                 conda-forge
    icu:                  64.2-he1b5a44_1               conda-forge
    idna:                 2.8-py27_1000                 conda-forge
    intervaltree:         3.0.2-py_0                    conda-forge
    ipaddress:            1.0.23-py_0                   conda-forge
    keras-applications:   1.0.8-py_1                    conda-forge
    keras-preprocessing:  1.1.0-py_0                    conda-forge
    krb5:                 1.16.4-h2fd8d38_0             conda-forge
    libblas:              3.8.0-14_openblas             conda-forge
    libcblas:             3.8.0-14_openblas             conda-forge
    libcurl:              7.65.3-hda55be3_0             conda-forge
    libdeflate:           1.3-h516909a_0                conda-forge
    libedit:              3.1.20170329-hf8c457e_1001    conda-forge
    libffi:               3.2.1-he1b5a44_1006           conda-forge
    libgcc-ng:            9.2.0-hdf63c60_0              conda-forge
    libgfortran-ng:       7.3.0-hdf63c60_2              conda-forge
    liblapack:            3.8.0-14_openblas             conda-forge
    libopenblas:          0.3.7-h5ec1e0e_5              conda-forge
    libpng:               1.6.37-hed695b0_0             conda-forge
    libprotobuf:          3.11.1-h8b12597_0             conda-forge
    libssh2:              1.8.2-h22169c7_2              conda-forge
    libstdcxx-ng:         9.2.0-hdf63c60_0              conda-forge
    linecache2:           1.0.0-py_1                    conda-forge
    markdown:             3.1.1-py_0                    conda-forge
    mock:                 3.0.5-py27_0                  conda-forge
    ncurses:              6.1-hf484d3e_1002             conda-forge
    numpy:                1.14.6-py27h95a1406_1201      conda-forge
    oauth2client:         1.5.2-py27_0                  bioconda   
    openjdk:              8.0.192-h14c3975_1003         conda-forge
    openssl:              1.1.1d-h516909a_0             conda-forge
    parallel:             20160622-1                    bioconda   
    pbr:                  5.4.2-py_0                    conda-forge
    perl:                 5.26.2-h516909a_1006          conda-forge
    perl-threaded:        5.26.0-0                      bioconda   
    pip:                  19.3.1-py27_0                 conda-forge
    prettytable:          0.7.2-py_3                    conda-forge
    protobuf:             3.11.1-py27he1b5a44_0         conda-forge
    psutil:               5.6.7-py27h516909a_0          conda-forge
    pyasn1:               0.4.8-py_0                    conda-forge
    pyasn1-modules:       0.2.7-py_0                    conda-forge
    pycparser:            2.19-py27_1                   conda-forge
    pyopenssl:            19.1.0-py27_0                 conda-forge
    pyparsing:            2.4.5-py_0                    conda-forge
    pyperclip:            1.7.0-py_0                    conda-forge
    pysocks:              1.7.0-py27_0                  conda-forge
    python:               2.7.15-h5a48372_1009          conda-forge
    pyyaml:               5.2-py27h516909a_0            conda-forge
    readline:             8.0-hf8c457e_0                conda-forge
    requests:             2.22.0-py27_1                 conda-forge
    rsa:                  3.1.4-py27_0                  bioconda   
    scipy:                1.2.1-py27h921218d_2          conda-forge
    setuptools:           42.0.2-py27_0                 conda-forge
    six:                  1.13.0-py27_0                 conda-forge
    sortedcontainers:     2.1.0-py_0                    conda-forge
    sqlite:               3.30.1-hcee41ef_0             conda-forge
    stevedore:            1.30.1-py_0                   conda-forge
    subprocess32:         3.5.4-py27h516909a_0          conda-forge
    tensorboard:          1.12.0-py27_1000              conda-forge
    tensorflow:           1.12.0-gpu_py27h2a0f108_0                
    tensorflow-base:      1.12.0-gpu_py27had579c0_0                
    tensorflow-estimator: 1.13.0-py_0                              
    termcolor:            1.1.0-py_2                    conda-forge
    tk:                   8.6.10-hed695b0_0             conda-forge
    traceback2:           1.4.0-py27_0                  conda-forge
    unicodecsv:           0.14.1-py_1                   conda-forge
    unittest2:            1.1.0-py_0                    conda-forge
    urllib3:              1.25.7-py27_0                 conda-forge
    wcwidth:              0.1.7-py_1                    conda-forge
    werkzeug:             0.16.0-py_0                   conda-forge
    wheel:                0.33.6-py27_0                 conda-forge
    xz:                   5.2.4-h14c3975_1001           conda-forge
    yaml:                 0.2.2-h516909a_1              conda-forge
    zlib:                 1.2.11-h516909a_1006          conda-forge
```
I've also installed one package at a time, and then installed the deepvariant package with the comman ```conda install -c bioconda deepvariant```.

Andrea

**Comment by chapmanb** [comment]
Andrea;
Thanks for following up and for all the additional details. It's a bit strange, as all the file paths in your error messages look like it got installed under python 3.6 rather than 2.7. It's hard to tell if that's just coming from the conda machinery or indicative of a different problem. 

You could try installing in a separate environment as a first pass to avoid any conflicts:
```
conda create -y -n deepvariant python=2.7 -c bioconda -c conda-forge deepvariant 'google-cloud-sdk<243.0.0'
```
If that still has the same issue, then we'd need to dig more into the `post-link.sh` errors you're seeing. In this step deepvariant is downloading the trained model files from GCP, which can sometimes have internet issues or other problems. This previous post has some suggestions for debugging it:

https://github.com/google/deepvariant/issues/177#issuecomment-504940567

Hope this helps get it resolved and get deepvariant running for you.

**Comment by RenzoTale88** [comment]
Thank you for your quick answer. I had to make a couple of changes to the command (see below), but now it seems to be working:
```
conda create -y -n deepvariant -c bioconda -c conda-forge python=2.7 deepvariant google-cloud-sdk=239.0.0
```
Everything is installed correctly. Is there a guide to follow for locally installed variant caller?
I'm not sure I've been able to find it. 

Thank you again for your support,
Andrea

**Comment by RenzoTale88** [comment]
Thank you for your quick answer. I had to make a couple of changes to the command (see below), but now it seems to be working:
```
conda create -y -n deepvariant -c bioconda -c conda-forge python=2.7 deepvariant google-cloud-sdk=239.0.0
```
Everything is installed correctly. Is there a guide to follow for locally installed variant caller?
I'm not sure I've been able to find it. 

Thank you again for your support,
Andrea

**Comment by prabal97** [comment]
Hi Andrea, I am getting the same error while I am trying to run the deepvariant code through the conda installation. Did you find a solution for it?

> Thank you for your quick answer. I had to make a couple of changes to the command (see below), but now it seems to be working:
> 
> ```
> conda create -y -n deepvariant -c bioconda -c conda-forge python=2.7 deepvariant google-cloud-sdk=239.0.0
> ```
> 
> Everything is installed correctly. Is there a guide to follow for locally installed variant caller?
> I'm not sure I've been able to find it.
> 
> Thank you again for your support,
> Andrea

**Comment by gunjanbaid** [comment]
@RenzoTale88 after installing through bioconda, the binaries and models for DeepVariant will be located under the following path, where $ENV_NAME is the name of the conda environment.

```
$ ls miniconda2/envs/${ENV_NAME}/share/deepvariant-0.9.0-0
binaries  models 
```

The binaries can be run as shown in [this script](https://github.com/google/deepvariant/blob/r0.9/scripts/run_wgs_case_study_binaries.sh), which goes through the [WGS case study (Docker instructions)](https://github.com/google/deepvariant/blob/r0.9/docs/deepvariant-case-study.md). For example, you can run:

```
$ python miniconda2/envs/${ENV_NAME}/share/deepvariant-0.9.0-0/binaries/D
eepVariant/0.9.0/DeepVariant-0.9.0/make_examples.zip <flags>
```

Note, you may have to run `chmod +x miniconda2/envs/${ENV_NAME}/share/deepvariant-0.9.0-0/binaries/D
eepVariant/0.9.0/DeepVariant-0.9.0/make_examples.zip` prior to running the command above. This will apply to other binaries as well (`call_variants`, `postprocess_variants`, etc.). Let me know if you have any other questions!

@prabal97 could you share the error you are seeing?

**Comment by prabal97** [comment]
> @RenzoTale88 after installing through bioconda, the binaries and models for DeepVariant will be located under the following path, where $ENV_NAME is the name of the conda environment.
> 
> ```
> $ ls miniconda2/envs/${ENV_NAME}/share/deepvariant-0.9.0-0
> binaries  models 
> ```
> 
> The binaries can be run as shown in [this script](https://github.com/google/deepvariant/blob/r0.9/scripts/run_wgs_case_study_binaries.sh), which goes through the [WGS case study (Docker instructions)](https://github.com/google/deepvariant/blob/r0.9/docs/deepvariant-case-study.md). For example, you can run:
> 
> ```
> $ python miniconda2/envs/${ENV_NAME}/share/deepvariant-0.9.0-0/binaries/D
> eepVariant/0.9.0/DeepVariant-0.9.0/make_examples.zip <flags>
> ```
> 
> Note, you may have to run `chmod +x miniconda2/envs/${ENV_NAME}/share/deepvariant-0.9.0-0/binaries/D eepVariant/0.9.0/DeepVariant-0.9.0/make_examples.zip` prior to running the command above. This will apply to other binaries as well (`call_variants`, `postprocess_variants`, etc.). Let me know if you have any other questions!
> 
> @prabal97 could you share the error you are seeing?

I am getting the following error even after using the binaries in the mentioned directories 

ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found

**Comment by chapmanb** [comment]
The `GLIBC` error indicates that you're running on an older operating system that DeepVariant doesn't support. The DeepVariant binaries are pre-compiled (unlike most other conda libraries, which get compiled on Centos 6 systems with an older glibc). Unfortunately this means that on older systems (like Centos <=7) they won't work. What operating system are you running it on? If you have access, it would be worth switching to a more up to date system or running on a cloud instance. Sorry for the issues and hope this helps.

**Comment by RenzoTale88** [comment]
Thank you for your answer, unfortunately is a central cluster system, and I have not the options to make large system updates. If in the future I have the need to use deepvariant I will consider a cloud solution. Thank you again for your support, 

Andrea

**Comment by PlatonB** [comment]
> Currently DeepVariant still only supports Python2.

Is there a plan to migrate to Python 3?

**Comment by serge2016** [comment]
@PlatonB, https://github.com/google/deepvariant/issues/258#issuecomment-573807042

**Comment by pichuan** [comment]
@serge2016 @PlatonB Thank you for raising this issue again. We're now aiming for an earlier release, in March. I'll also update to the other issue.
