### ISSUE TITLE
newbie unable to run container ReadRequirements are: min_mapping_quality: 10 min_base_quality: 10 min_base_quality_mode: ENFORCED_BY_CLIENT

### ISSUE THREAD

**Issue by aedavids** [google/deepvariant#254]
Hi 

I am a student learning about bioinformatics. I am able to us the docker image to run the quick start data, however, I am not able to run on my data. 

I used samtools 1.9 to filter out low quality reads as follows

```
quality=11
samtools view -bSq ${quality} "${originalBAMFile}" > "${filteredBAMFile}"
samtools index "${filteredBAMFile}"
```

Note the output from the docker run script bellow is a little misleading. I copied all the data from an aws s3 buck to the local disk before the run.

Also, the data is RNA not DNA. I was asked to "see if it would just work". I think maybe we have to change Uracil to look like Thymine.  

Any suggestions would be greatly appreciated

Happy Holidays

Andy
```
ubuntu@ip-172-31-1-186:~$ cat nohup.out 
+ BIN_VERSION=0.9.0
+ s3Root=/data
+ INPUT_DIR=/data/aligned
+ OUTPUT_DIR=/data/output
+ quality=q11
+ ref=/data/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
+ reads=/data/aligned/84773251_trimmed.AH77TTBBXX_DS-229105_GCCAAT.sorted.rg.final.q11.bam
+ date +%Y-%m-%d-%H.%M.%S-%Z%n
+ dateStamp=2019-12-19-00.20.49-UTC
+ output_vcf=/data/output/2019-12-19-00.20.49-UTC.vcf.gz
+ output_gvcf=/data/output/2019-12-19-00.20.49-UTC.g.vcf.gz
+ nproc
+ num_shards=4
+ sudo docker run -v /data/aligned:/input -v /data/output:/output google/deepvariant:0.9.0 /opt/deepvariant/bin/run_deepvariant --model_type=WGS --ref=/data/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna --reads=/data/aligned/84773251_trimmed.AH77TTBBXX_DS-229105_GCCAAT.sorted.rg.final.q11.bam --output_vcf=/data/output/2019-12-19-00.20.49-UTC.vcf.gz --output_gvcf=/data/output/2019-12-19-00.20.49-UTC.g.vcf.gz --num_shards=4

***** Running the command:*****
time seq 0 3 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/data/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna" --reads "/data/aligned/84773251_trimmed.AH77TTBBXX_DS-229105_GCCAAT.sorted.rg.final.q11.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@4.gz" --gvcf "/tmp/deepvariant_tmp_output/gvcf.tfrecord@4.gz" --task {}

I1219 00:20:56.935748 140093586556672 make_examples.py:377] ReadRequirements are: min_mapping_quality: 10
min_base_quality: 10
min_base_quality_mode: ENFORCED_BY_CLIENT

[E::hts_open_format] Failed to open file /data/aligned/84773251_trimmed.AH77TTBBXX_DS-229105_GCCAAT.sorted.rg.final.q11.bam
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_YufZXM/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1461, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_YufZXM/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1399, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/tmp/Bazel.runfiles_YufZXM/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 388, in default_options
    with sam.SamReader(flags_obj.reads.split(',')[0]) as sam_reader:
  File "/tmp/Bazel.runfiles_YufZXM/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 221, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_YufZXM/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 255, in _native_reader
    return NativeSamReader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_YufZXM/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 232, in __init__
    use_original_base_quality_scores=use_original_base_quality_scores)
ValueError: Not found: Could not open /data/aligned/84773251_trimmed.AH77TTBBXX_DS-229105_GCCAAT.sorted.rg.final.q11.bam
I1219 00:20:56.936666 140612092569344 make_examples.py:377] ReadRequirements are: min_mapping_quality: 10
min_base_quality: 10
min_base_quality_mode: ENFORCED_BY_CLIENT

[E::hts_open_format] Failed to open file /data/aligned/84773251_trimmed.AH77TTBBXX_DS-229105_GCCAAT.sorted.rg.final.q11.bam
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_8pjzb6/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1461, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_8pjzb6/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1399, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/tmp/Bazel.runfiles_8pjzb6/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 388, in default_options
    with sam.SamReader(flags_obj.reads.split(',')[0]) as sam_reader:
  File "/tmp/Bazel.runfiles_8pjzb6/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 221, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_8pjzb6/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 255, in _native_reader
    return NativeSamReader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_8pjzb6/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 232, in __init__
    use_original_base_quality_scores=use_original_base_quality_scores)
ValueError: Not found: Could not open /data/aligned/84773251_trimmed.AH77TTBBXX_DS-229105_GCCAAT.sorted.rg.final.q11.bam
I1219 00:20:56.935748 139746404648704 make_examples.py:377] ReadRequirements are: min_mapping_quality: 10
min_base_quality: 10
min_base_quality_mode: ENFORCED_BY_CLIENT

[E::hts_open_format] Failed to open file /data/aligned/84773251_trimmed.AH77TTBBXX_DS-229105_GCCAAT.sorted.rg.final.q11.bam
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_4dYajH/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1461, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_4dYajH/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1399, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/tmp/Bazel.runfiles_4dYajH/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 388, in default_options
    with sam.SamReader(flags_obj.reads.split(',')[0]) as sam_reader:
  File "/tmp/Bazel.runfiles_4dYajH/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 221, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_4dYajH/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 255, in _native_reader
    return NativeSamReader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_4dYajH/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 232, in __init__
    use_original_base_quality_scores=use_original_base_quality_scores)
ValueError: Not found: Could not open /data/aligned/84773251_trimmed.AH77TTBBXX_DS-229105_GCCAAT.sorted.rg.final.q11.bam
I1219 00:20:56.936666 139723052500736 make_examples.py:377] ReadRequirements are: min_mapping_quality: 10
min_base_quality: 10
min_base_quality_mode: ENFORCED_BY_CLIENT

[E::hts_open_format] Failed to open file /data/aligned/84773251_trimmed.AH77TTBBXX_DS-229105_GCCAAT.sorted.rg.final.q11.bam
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_FlmiHS/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1461, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_FlmiHS/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1399, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/tmp/Bazel.runfiles_FlmiHS/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 388, in default_options
    with sam.SamReader(flags_obj.reads.split(',')[0]) as sam_reader:
  File "/tmp/Bazel.runfiles_FlmiHS/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 221, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_FlmiHS/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 255, in _native_reader
    return NativeSamReader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_FlmiHS/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 232, in __init__
    use_original_base_quality_scores=use_original_base_quality_scores)
ValueError: Not found: Could not open /data/aligned/84773251_trimmed.AH77TTBBXX_DS-229105_GCCAAT.sorted.rg.final.q11.bam

real	0m4.864s
user	0m7.056s
sys	0m2.308s
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 317, in <module>
    app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 307, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 3 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/data/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna" --reads "/data/aligned/84773251_trimmed.AH77TTBBXX_DS-229105_GCCAAT.sorted.rg.final.q11.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@4.gz" --gvcf "/tmp/deepvariant_tmp_output/gvcf.tfrecord@4.gz" --task {}' returned non-zero exit status 4
Command exited with non-zero status 1
0.04user 0.03system 0:07.68elapsed 0%CPU (0avgtext+0avgdata 62828maxresident)k
123448inputs+24outputs (242major+8435minor)pagefaults 0swaps
```

**Comment by gunjanbaid** [comment]
Hi @aedavids, the below messages are expected when running DeepVariant. You will see these and many other logging outputs when you run the software.

```
I1219 00:20:56.935748 140093586556672 make_examples.py:377] ReadRequirements are: min_mapping_quality: 10
min_base_quality: 10
min_base_quality_mode: ENFORCED_BY_CLIENT
```

I do notice a possible issue with your Docker command, pasted below.

```
sudo docker run -v /data/aligned:/input -v /data/output:/output google/deepvariant:0.9.0 /opt/deepvariant/bin/run_deepvariant --model_type=WGS --ref=/data/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna --reads=/data/aligned/84773251_trimmed.AH77TTBBXX_DS-229105_GCCAAT.sorted.rg.final.q11.bam --output_vcf=/data/output/2019-12-19-00.20.49-UTC.vcf.gz --output_gvcf=/data/output/2019-12-19-00.20.49-UTC.g.vcf.gz --num_shards=4
```

Since you are mounting your local `/data/input` and `/data/output` directories to `/input` and `/output` in the container,  you will want to change the file paths used in the command to reference the container directories. For example, in the below command, you can use: 
`--ref=/input/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna`

**Comment by aedavids** [comment]
Hi gunjanbaid

many thanks, I have never used docker before. You where correct the problem was with volume mounts.

to debug this issue I did the following

```
docker run -it -v /data/aligned:/input google/deepvariant:0.9.0
```
I was then able to use ls to see exactly what the file paths need to be

thanks

Happy Holidays

Andy

**Comment by gunjanbaid** [comment]
No problem, happy holidays @aedavids!
