### ISSUE TITLE
Runtime error:  merge_overlaps() got an unexpected keyword argument 'strict'

### ISSUE THREAD

**Issue by coneheadusa** [google/deepvariant#255]
I get the following error when running the example provided in the quick start document:

merge_overlaps() got an unexpected keyword argument 'strict'

Any advice as to how I can resolve the issue is greatly appreciated.

```
This is the context of the error.
***** Running the command:*****
time seq 0 0 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/data/hs37d5.fa.gz" --reads "/input/data/HG002_NIST_150bp_chr20_downsampled_30x.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@1.gz" `--gvcf` "/tmp/deepvariant_tmp_output/gvcf.tfrecord@1.gz" --regions "20" --task {}

perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
I1220 08:40:22.262234 46912496321664 make_examples.py:377] ReadRequirements are: min_mapping_quality: 10
min_base_quality: 10
min_base_quality_mode: ENFORCED_BY_CLIENT

I1220 08:40:22.268675 46912496321664 genomics_reader.py:223] Reading /input/data/HG002_NIST_150bp_chr20_downsampled_30x.bam with NativeSamReader
I1220 08:40:22.272100 46912496321664 make_examples.py:1324] Preparing inputs
I1220 08:40:22.280786 46912496321664 genomics_reader.py:223] Reading /input/data/HG002_NIST_150bp_chr20_downsampled_30x.bam with NativeSamReader
I1220 08:40:22.292714 46912496321664 make_examples.py:1248] Common contigs are [u'1', u'2', u'3', u'4', u'5', u'6', u'7', u'8', u'9', u'10', u'11', u'12', u'13', u'14', u'15', u'16', u'17', u'18', u'19', u'20', u'21', u'22', u'X', u'Y']
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_UJ59Z1/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1461, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_UJ59Z1/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1451, in main
    make_examples_runner(options)
  File "/tmp/Bazel.runfiles_UJ59Z1/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1325, in make_examples_runner
    regions = processing_regions_from_options(options)
  File "/tmp/Bazel.runfiles_UJ59Z1/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1250, in processing_regions_from_options
    options.exclude_calling_regions)
  File "/tmp/Bazel.runfiles_UJ59Z1/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 725, in build_calling_regions
    regions = ranges.RangeSet.from_contigs(contigs)
  File "/tmp/Bazel.runfiles_UJ59Z1/runfiles/com_google_deepvariant/third_party/nucleus/util/ranges.py", line 168, in from_contigs
    contigs)
  File "/tmp/Bazel.runfiles_UJ59Z1/runfiles/com_google_deepvariant/third_party/nucleus/util/ranges.py", line 125, in __init__
    tree.merge_overlaps(strict=False)
TypeError: merge_overlaps() got an unexpected keyword argument 'strict'

real    0m8.948s
user    0m1.033s
sys     0m2.422s
Traceback (most recent call last):
```

**Comment by pichuan** [comment]
Hi,
this seems like an issue with the version of intervaltree pip package. But this is surprising to me, because in our set up script, we pinned to the correct intervaltree version.

Can you clarify/confirm a few things:
(1) Given that you mentioned you're going through the Quick Start, I assume you're using our Docker version, and you're using v0.9.0?
(2) What operation system are you on?

We'd appreciate more information you can provide to help us reproduce the result.

**Comment by coneheadusa** [comment]
We are using singularity 3.5.2 and the image was obtained with this command:

singularity pull docker://gcr.io/deepvariant-docker/deepvariant:0.9.0

We have a wrapper script that we use with deepvariant-0.8.0 to submit to the CentOS 7 based compute cluster without issue and it is used with v0.9.0 with the only change being the version of deepvariant.  Also I opened a shell on the 0.9.0  image and ran 'pip freeze | grep intervaltree' and got this version:
                                  
intervaltree==2.1.0

This is the submit script without the SLURM commands:
```
export BIN_VERSION="0.9.0"
export BASE="${PWD}/deepvariant-run"
export INPUT_DIR="${BASE}/input"
export REF="hs37d5.fa.gz"
export BAM="HG002_NIST_150bp_chr20_downsampled_30x.bam"
export OUTPUT_DIR="${BASE}/output"
export DATA_DIR="${INPUT_DIR}/data"
export OUTPUT_VCF="HG002.output.vcf.gz"
export OUTPUT_GVCF="HG002.output.g.vcf.gz"

mkdir -p "${OUTPUT_DIR}"
mkdir -p "${INPUT_DIR}"
mkdir -p "${DATA_DIR}"

gsutil cp gs://deepvariant/performance-testdata/"${BAM}" "${DATA_DIR}"
gsutil cp gs://deepvariant/performance-testdata/"${BAM}".bai "${DATA_DIR}"

cd /scratch/rsmith/DeepvariantTests/case-study/
module load deepvariant/0.9.0-gpu-phoenix

run_deepvariant --model_type=WGS --ref="/input/data/${REF}" \
                --reads="${DATA}/input/data/${BAM}" \
	        --output_vcf=/output/${OUTPUT_VCF} \
                --output_gvcf=/output/${OUTPUT_GVCF} \
                --regions 20 --num_shards=$(nproc)

```

**Comment by pichuan** [comment]
Hi @coneheadusa 
Can you try installing intervaltree==3.0.2?
This is what we required in the run-prereq.sh script:
https://github.com/google/deepvariant/blob/97cd861800ccb43d750f392b518e99d514adddd8/run-prereq.sh#L89

**Comment by coneheadusa** [comment]
Thank you for providing the run-prereq.sh information.   I found a 2.1.0 version of intervaltree in ${HOME}/.local/lib/python2.7/site-packages that was overriding the site-packages directory within the container.  The test ran successfully once I eliminated the conflict.
