### ISSUE TITLE
How to input another model with v0.9

### ISSUE THREAD

**Issue by aderzelle** [google/deepvariant#268]
Hello guys,

following an email discussion ... I am unable to use a different model

The help seems to suggest one can set --model_type=WGS and then use --customized_model="PATH_to_model.cpk"

```
--model_type: <WGS|WES|PACBIO>: Required. Type of model to use for variant                                                                                                                               
    calling. Each model_type has an associated default model, which can be                                                                                                                                 
    overridden by the --customized_model flag.
```

But then the run produces

`"I0206 11:58:24.997612 140003716306688 saver.py:1270] Restoring parameters from /opt/models/wgs/model.ckpt"
`
which I interpret as deepvariant falling back on its default model. 
What I notice is that even with the customized-model flag, it doesn't run if I don't set up --model-type. It seems like when both flags are set (and there is no way to do otherwise) it gives priority to its default model, which is the opposite of the intended behaviour right? 

Or is there something I am missing? 

Thanks a lot for any help or suggestion (and sorry for the many messages, I just really want to try that model because it seems very promising and have it fit in my schedule)

**Comment by pichuan** [comment]
Hi @aderzelle ,
the current design is that you do need to specify both the `model_type` and `customized_model` flag.
The reason is that we're using the `model_type` flag to set a few assumptions in the run_deepvariant.py script. Specifically, if you specify `PACBIO`, you get these set for you:
https://github.com/google/deepvariant/blob/97cd861800ccb43d750f392b518e99d514adddd8/scripts/run_deepvariant.py#L183-L185

In the current version, if you set model_type to either `WGS` or `WES`, there's actually no additional assumption being made (that just means everything will be default value from the code). So, one strategy for you is to set:

```
  --model_type=WGS \
  --customized_model=/input/your.model.ckpt \
```

(or WES, they should be the same)
Then the behavior is that the call_variants step should be loading your customized model.

Let me know if this works for you. I'm pretty sure this answer will resolve your issue, so I'm closing this bug. But feel free to follow up.

And I'm very curious to know how your own trained model worked for your task!

**Comment by aderzelle** [comment]
Hello, I tried but this returns 
```

Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_QDZzEL/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 442, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_QDZzEL/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 432, in main
    use_tpu=FLAGS.use_tpu,
  File "/tmp/Bazel.runfiles_QDZzEL/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 388, in call_variants
    prediction = next(predictions)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 627, in predict
    hooks=all_hooks) as mon_sess:
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 934, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 648, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1122, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1127, in _create_session
    return self._sess_creator.create_session()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 805, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 571, in create_session
    init_fn=self._scaffold.init_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 281, in prepare_session
    config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 195, in _restore_checkpoint
    saver.restore(sess, checkpoint_filename_with_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1268, in restore
    + compat.as_text(save_path))
ValueError: The passed save_path is not a valid checkpoint: /input/mosquito_model/model.ckpt

real	0m7.387s
user	0m9.233s
sys	0m4.817s
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 317, in <module>
    app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 307, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time /opt/deepvariant/bin/call_variants --outfile "/tmp/deepvariant_tmp_output/call_variants_output.tfrecord.gz" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@20.gz" --checkpoint "/input/mosquito_model/model.ckpt"' returned non-zero exit status 1
```
However, the directory mosquito_model does exist and contains

`model.ckpt-97700.data-00000-of-00001  model.ckpt-97700.index  model.ckpt-97700.meta`

The model file was providen to me by your colleague Andrew Carroll. Is there a way to check the files are "correct"?

**Comment by pichuan** [comment]
@aderzelle 
Because your file name is `model.ckpt-97700*`, so you need to pass in:
```
--customized_model="/input/mosquito_model/model.ckpt-97700"
```

**Comment by aderzelle** [comment]
> @aderzelle
> Because your file name is `model.ckpt-97700*`, so you need to pass in:
> 
> ```
> --customized_model="/input/mosquito_model/model.ckpt-97700"
> ```

Indeed now it works. And the model seems to work much better, it no longer calls as HomRef Het sites that are in close proximity!
