### ISSUE TITLE
Follow up of inputing model files

### ISSUE THREAD

**Issue by aderzelle** [google/deepvariant#273]
Hello, a following-up thread of a previous issue.

I don't know if you get notified of a reply in a closed issue so I am opening a new one. 
I have tried your flag but it doesn't work. 

Thank you

```

Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_QDZzEL/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 442, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_QDZzEL/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 432, in main
    use_tpu=FLAGS.use_tpu,
  File "/tmp/Bazel.runfiles_QDZzEL/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 388, in call_variants
    prediction = next(predictions)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 627, in predict
    hooks=all_hooks) as mon_sess:
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 934, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 648, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1122, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1127, in _create_session
    return self._sess_creator.create_session()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 805, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 571, in create_session
    init_fn=self._scaffold.init_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 281, in prepare_session
    config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 195, in _restore_checkpoint
    saver.restore(sess, checkpoint_filename_with_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1268, in restore
    + compat.as_text(save_path))
ValueError: The passed save_path is not a valid checkpoint: /input/mosquito_model/model.ckpt

real	0m7.387s
user	0m9.233s
sys	0m4.817s
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 317, in <module>
    app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 307, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time /opt/deepvariant/bin/call_variants --outfile "/tmp/deepvariant_tmp_output/call_variants_output.tfrecord.gz" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@20.gz" --checkpoint "/input/mosquito_model/model.ckpt"' returned non-zero exit status 1
```
However, the directory mosquito_model does exist and contains

`model.ckpt-97700.data-00000-of-00001  model.ckpt-97700.index  model.ckpt-97700.meta`

The model file was providen to me by your colleague Andrew Carroll. Is there a way to check the files are "correct"? 

EDIT: here is the script 

```
#!/usr/bin/zsh
OUTPUT_DIR="${PWD}/ARCcestor_mosquito_model"
mkdir -p "${OUTPUT_DIR}"
INPUT_DIR="${PWD}"
BIN_VERSION="0.9.0"
N_SHARDS=20
LOG_DIR="${OUTPUT_DIR}/logs"                                                                                                                                                                                
mkdir -p "${LOG_DIR}"       
#declare -a decade=(ARCcestor D2A1 D2B3 D3A1 D4A3 D5B3 H2A3 H2C3 H4A4 H4C2 H5A3)
#for SAMPLE in "${decade[@]}"
#do
 # BAM=${SAMPLE}.sorted.bam


 #OUTPUT_VCF=${SAMPLE}.vcf.gz
 #OUTPUT_GVCF=${SAMPLE}.g.vcf.gz

 time (docker run -v "${INPUT_DIR}":"/input" -v "${OUTPUT_DIR}:/output" google/deepvariant:"${BIN_VERSION}" /opt/deepvariant/bin/run_deepvariant --model_type=WGS --ref=/input/shasta_final.fa --reads="/input/ARCcestor.sorted.bam" --regions="/input/ARCcestor.bed" --output_vcf="/output/${OUTPUT_VCF}" --output_gvcf="/output/${OUTPUT_GVCF}" --num_shards="${N_SHARDS}" --customized_model="/input/mosquito_model/model.ckpt" )  2>&1 | tee -a "${LOG_DIR}/make_examples.log"
#done
```

_Originally posted by @aderzelle in https://github.com/google/deepvariant/issues/268#issuecomment-586584341_

**Comment by pichuan** [comment]
Glad to hear this works now. Closing this issue.
