### ISSUE TITLE
error in make_examples extract_sample_name_from_reads

### ISSUE THREAD

**Issue by stevendavis** [google/deepvariant#28]
Running make_examples locally from the Docker container.  It runs without errors on the NA12878_S1.chr20.10_10p1mb.bam dataset, but fails with my BAM file.  See the stack trace below.  My BAM file is too large to attach here.  What do you recommend?  Also what are the allowed values for --logging_level?  Please advise.

```
# ./opt/deepvariant/bin/make_examples --logging_level DEBUG --mode calling --ref /dv2/reference/CFSAN000189.fasta --reads /dv2/samples/CFSAN000211/reads.sorted.bam --examples output.examples.tfrecord
WARNING: Logging before flag parsing goes to stderr.
I1228 21:10:23.407845 140668049200896 client.py:1004] Timeout attempting to reach GCE metadata service.
W1228 21:10:23.408325 140668049200896 htslib_gcp_oauth.py:88] GCP credentials not found; only local files and public gs:// URIs will be accessible from htslib
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_9tjOWl/runfiles/genomics/deepvariant/make_examples.py", line 1015, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/tmp/Bazel.runfiles_9tjOWl/runfiles/genomics/deepvariant/make_examples.py", line 969, in main
    options = default_options(add_flags=True, flags=FLAGS)
  File "/tmp/Bazel.runfiles_9tjOWl/runfiles/genomics/deepvariant/make_examples.py", line 207, in default_options
    sample_name = extract_sample_name_from_reads(flags.reads)
  File "/tmp/Bazel.runfiles_9tjOWl/runfiles/genomics/deepvariant/make_examples.py", line 406, in extract_sample_name_from_reads
    raise ValueError('Expected a single sample, found {}'.format(samples))
ValueError: Expected a single sample, found set([])

```

**Comment by depristo** [comment]
This is a known issue (tracked in our internal buganizer tracker). The problem is that your BAM file doesn't have a sample name associated with the reads. You can use the --sample_name argument to provide a value to make_examples.

**Comment by depristo** [comment]
A final update. We've just improved the error messages for these cases in the internal version. The next release of DeepVariant should have this fix.

**Comment by pgrosu** [comment]
That is wonderful news Mark!
Many thanks for all the great work,
Paul

**Comment by stevendavis** [comment]
@depristo Thank you mark, make_examples.py is working now with the --sample_name command line argument.
