### ISSUE TITLE
Could not open BAM file

### ISSUE THREAD

**Issue by NTNguyen13** [google/deepvariant#281]
Hi, I run this command to call variant on my bam file:
```
sudo docker run \
    google/deepvariant:"${BIN_VERSION}" \
    /opt/deepvariant/bin/run_deepvariant \
    --model_type=WGS \
    --ref=/home/thanh/ref37/hg19.fa \
    --reads=/home/thanh/Procedure_practice/17D2627041/qualification/17D2627041_hg19_arr.bam \
    --regions=$/home/thanh/RB1_Project/VBDI-VAR/RB1_padding_100.bed \
    --output_vcf=/home/thanh/Procedure_practice/17D2627041/VCF/17D2627041_De_hg19.vcf \
    --output_gvcf=/home/thanh/Procedure_practice/17D2627041/VCF/17D2627041_De_hg19.g.vcf \
    --num_shards=4 
```
it resulted in this error
```
ValueError: Not found: Could not open /home/thanh/Procedure_practice/17D2627041/qualification/17D2627041_hg19_arr.bam
I0305 09:55:16.252675 139778511243008 make_examples.py:377] ReadRequirements are: min_mapping_quality: 10
min_base_quality: 10
min_base_quality_mode: ENFORCED_BY_CLIENT

[E::hts_open_format] Failed to open file /home/thanh/Procedure_practice/17D2627041/qualification/17D2627041_hg19_arr.bam
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_3IsReI/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1461, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_3IsReI/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1399, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/tmp/Bazel.runfiles_3IsReI/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 388, in default_options
    with sam.SamReader(flags_obj.reads.split(',')[0]) as sam_reader:
  File "/tmp/Bazel.runfiles_3IsReI/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 221, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_3IsReI/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 255, in _native_reader
    return NativeSamReader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_3IsReI/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 232, in __init__
    use_original_base_quality_scores=use_original_base_quality_scores)
ValueError: Not found: Could not open /home/thanh/Procedure_practice/17D2627041/qualification/17D2627041_hg19_arr.bam
```

However I have checked my path and it's correct
```
file /home/thanh/Procedure_practice/17D2627041/qualification/17D2627041_hg19_arr.bam
/home/thanh/Procedure_practice/17D2627041/qualification/17D2627041_hg19_arr.bam: gzip compressed data, extra field
```

I can run the example command of DeepVariant without any issue.
What have gone wrong in my case, could you please help me on this?

**Comment by NTNguyen13** [comment]
silly me, it turned out that I need to mount the directory into docker by using flag `-v`
