### ISSUE TITLE
Add singularity usage to docs

### ISSUE THREAD

**Issue by moldach** [google/deepvariant#287]
Given that academic HPCs do not have root privileges it is not possible to run docker and one needs to use singularity. I think it would helpful to your user-base if you added a section on singularity to either the `deepvariant-quick-start.md` or `README.md`. 

I had never used containers before today so the following would have been very helpful for me getting your tool up-and-running quicker:

## Download an existing container from Docker Hub
```
singularity build deepvariant.simg docker://google/deepvariant
```

## Run Deep Variant with Singularity in one command
```
singularity -s exec -B /usr/lib/locale/:/usr/lib/locale/  \
  deepvariant.simg \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref=${INPUT_DIR}/ucsc.hg19.chr20.unittest.fasta \
  --reads=${INPUT_DIR}/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf=output.vcf.gz \
  --output_gvcf=output.g.vcf.gz 
```

Respectfully,
Matthew

**Comment by pichuan** [comment]
Hi @moldach 
Thank you for reporting this! For our upcoming release, I drafted a few new sections in the Quick Start already:
https://gist.github.com/pichuan/01f701573ba730e64354c534983f62c3#notes-on-singularity

I actually ended up just using `singularity pull`. (See the link above) Can you let me know if that works for you? If not, I can updated the doc to your version.

Thanks!

**Comment by moldach** [comment]
Pulling both the cpu/gpu versions works but I get an error when trying to run:

```
[moldach@cdr767 bin]$ singularity run -B /usr/lib/locale/:/usr/lib/locale/ \
>   docker://google/deepvariant:"${BIN_VERSION}" \
>   /opt/deepvariant/bin/run_deepvariant \
>   --model_type=WGS \ **Replace this string with exactly one of the following [WGS,WES,PACBIO]**
FATAL:   Unable to handle docker://google/deepvariant: uri: failed to get SHA of docker://google/deepvariant:: unable to parse image name docker://google/deepvariant:: invalid reference format
[moldach@cdr767 bin]$   --ref="${INPUT_DIR}"/ucsc.hg19.chr20.unittest.fasta \
>   --reads="${INPUT_DIR}"/NA12878_S1.chr20.10_10p1mb.bam \
>   --regions "chr20:10,000,000-10,010,000" \
>   --output_vcf="${OUTPUT_DIR}"/output.vcf.gz \
>   --output_gvcf="${OUTPUT_DIR}"/output.g.vcf.gz \
>   --num_shards=1
bash: --ref=/ucsc.hg19.chr20.unittest.fasta: No such file or directory
```

**Comment by pichuan** [comment]
Hi,
Thanks for trying the command. v0.10.0 is out today, and the Quick Start can be found here:
https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md

First of all, clean up the example script a bit: Don't include the part ` **Replace this string with exactly one of the following [WGS,WES,PACBIO]**` in your command.

And, the environment variables like "${BIN_VERSION}" and other variables will need to be set. Please refer to the documentation above to set it.

**Comment by moldach** [comment]
I had set the environment variables just didn't include them in the above message. That error was certainly caused by the `**Replace this string with exactly one of the following [WGS,WES,PACBIO]**` string.

However, I'm still getting an _unrelated_ error:
## Set the environment
```
[moldach@cdr767 bin]$ BIN_VERSION="0.10.0"
[moldach@cdr767 bin]$ INPUT_DIR="${PWD}/quickstart-testdata"
[moldach@cdr767 bin]$ OUTPUT_DIR="${PWD}/quickstart-output"
[moldach@cdr767 bin]$ salloc --time=0:30:0 --mem=8000
[moldach@cdr767 bin]$ singularity run -B /usr/lib/locale/:/usr/lib/locale/ \
>   docker://google/deepvariant:"${BIN_VERSION}" \
>   /opt/deepvariant/bin/run_deepvariant \
>   --model_type=WGS \
>   --ref="${INPUT_DIR}"/ucsc.hg19.chr20.unittest.fasta \
>   --reads="${INPUT_DIR}"/NA12878_S1.chr20.10_10p1mb.bam \
>   --regions "chr20:10,000,000-10,010,000" \
>   --output_vcf="${OUTPUT_DIR}"/output.vcf.gz \
>   --output_gvcf="${OUTPUT_DIR}"/output.g.vcf.gz \
>   --num_shards=1
WARN[0000] "/run/user/3019658" directory set by $XDG_RUNTIME_DIR does not exist. Eithe                                                                                                      r create the directory or unset $XDG_RUNTIME_DIR.: stat /run/user/3019658: no such fil                                                                                                      e or directory: Trying to pull image in the event that it is a public image.
I0327 13:31:58.252949 47794500922048 run_deepvariant.py:241] Re-using the directory fo                                                                                                      r intermediate results in /tmp/tmp63xxmwmi

***** Intermediate results will be written to /tmp/tmp63xxmwmi in docker. ****


***** Running the command:*****
time seq 0 0 | parallel --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mo                                                                                                      de calling --ref "/scratch/moldach/bin/quickstart-testdata/ucsc.hg19.chr20.unittest.fa                                                                                                      sta" --reads "/scratch/moldach/bin/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam"                                                                                                       --examples "/tmp/tmp63xxmwmi/make_examples.tfrecord@1.gz" --gvcf "/tmp/tmp63xxmwmi/gv                                                                                                      cf.tfrecord@1.gz" --regions "chr20:10,000,000-10,010,000" --task {}

Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence this citation notice: run 'parallel --citation'.

I0327 13:32:07.160181 47175299967680 make_examples.py:386] ReadRequirements are: min_m                                                                                                      apping_quality: 10
min_base_quality: 10
min_base_quality_mode: ENFORCED_BY_CLIENT

I0327 13:32:07.206463 47175299967680 genomics_reader.py:223] Reading /scratch/moldach/                                                                                                      bin/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam with NativeSamReader
I0327 13:32:07.218669 47175299967680 make_examples.py:535] Preparing inputs
I0327 13:32:07.293092 47175299967680 genomics_reader.py:223] Reading /scratch/moldach/                                                                                                      bin/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam with NativeSamReader
I0327 13:32:07.294783 47175299967680 make_examples.py:535] Common contigs are ['chr20'                                                                                                      ]
I0327 13:32:07.296233 47175299967680 make_examples.py:535] Writing examples to /tmp/tm                                                                                                      p63xxmwmi/make_examples.tfrecord-00000-of-00001.gz
I0327 13:32:07.296404 47175299967680 make_examples.py:535] Writing gvcf records to /tm                                                                                                      p/tmp63xxmwmi/gvcf.tfrecord-00000-of-00001.gz
I0327 13:32:07.298243 47175299967680 make_examples.py:535] Starting from v0.9.0, --use                                                                                                      _ref_for_cram is default to true. If you are using CRAM input, note that we will decod                                                                                                      e CRAM using the reference you passed in with --ref
2020-03-27 13:32:07.298857: I third_party/nucleus/io/sam_reader.cc:660] Setting HTS_OP                                                                                                      T_BLOCK_SIZE to 134217728
I0327 13:32:07.388042 47175299967680 genomics_reader.py:223] Reading /scratch/moldach/                                                                                                      bin/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam with NativeSamReader
I0327 13:32:07.389374 47175299967680 genomics_reader.py:223] Reading /scratch/moldach/                                                                                                      bin/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam with NativeSamReader
I0327 13:32:07.863366 47175299967680 make_examples.py:535] 6 candidates (6 examples) [                                                                                                      0.57s elapsed]
I0327 13:32:09.857359 47175299967680 make_examples.py:535] Found 78 candidate variants
I0327 13:32:09.857484 47175299967680 make_examples.py:535] Created 86 examples

real    0m11.980s
user    0m5.478s
sys     0m3.350s

***** Running the command:*****
time /opt/deepvariant/bin/call_variants --outfile "/tmp/tmp63xxmwmi/call_variants_outp                                                                                                      ut.tfrecord.gz" --examples "/tmp/tmp63xxmwmi/make_examples.tfrecord@1.gz" --checkpoint                                                                                                       "/opt/models/wgs/model.ckpt"

I0327 13:32:13.471893 47138345245376 call_variants.py:316] Set KMP_BLOCKTIME to 0
2020-03-27 13:32:13.524960: I tensorflow/core/platform/cpu_feature_guard.cc:145] This                                                                                                       TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instruct                                                                                                      ions in performance critical operations:  AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate comp                                                                                                      iler flags.
2020-03-27 13:32:13.625441: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94]                                                                                                       CPU Frequency: 2095014999 Hz
2020-03-27 13:32:13.625754: I tensorflow/compiler/xla/service/service.cc:168] XLA serv                                                                                                      ice 0x5289690 executing computations on platform Host. Devices:
2020-03-27 13:32:13.625958: I tensorflow/compiler/xla/service/service.cc:175]   Stream                                                                                                      Executor device (0): Host, Default Version
2020-03-27 13:32:13.629139: I tensorflow/core/common_runtime/process_util.cc:115] Crea                                                                                                      ting new thread pool with default inter op setting: 2. Tune using inter_op_parallelism                                                                                                      _threads for best performance.
I0327 13:32:13.749661 47138345245376 modeling.py:563] Initializing model with random p                                                                                                      arameters
W0327 13:32:13.750545 47138345245376 estimator.py:1821] Using temporary folder as mode                                                                                                      l directory: /tmp/tmpj5q00h0m
I0327 13:32:13.751226 47138345245376 estimator.py:212] Using config: {'_model_dir': '/                                                                                                      tmp/tmpj5q00h0m', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoi                                                                                                      nts_steps': None, '_save_checkpoints_secs': 600, '_session_config': , '_keep_checkpoin                                                                                                      t_max': 100000, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100,                                                                                                       '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute':                                                                                                       None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None,                                                                                                       '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow                                                                                                      .python.training.server_lib.ClusterSpec object at 0x2adfb39cd2b0>, '_task_type': 'work                                                                                                      er', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '                                                                                                      ', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
I0327 13:32:13.751701 47138345245376 call_variants.py:384] Writing calls to /tmp/tmp63                                                                                                      xxmwmi/call_variants_output.tfrecord.gz
W0327 13:32:13.760179 47138345245376 deprecation.py:506] From /usr/local/lib/python3.6                                                                                                      /dist-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseR                                                                                                      esourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with const                                                                                                      raint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
I0327 13:32:13.795566 47138345245376 data_providers.py:369] self.input_read_threads=8
W0327 13:32:13.795886 47138345245376 deprecation.py:323] From /tmp/Bazel.runfiles_ae3s                                                                                                      o6ns/runfiles/com_google_deepvariant/deepvariant/data_providers.py:374: parallel_inter                                                                                                      leave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and                                                                                                       will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_cal                                                                                                      ls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.da                                                                                                      ta.Options.experimental_determinstic`.
I0327 13:32:13.922482 47138345245376 data_providers.py:376] self.input_map_threads=48
W0327 13:32:13.922731 47138345245376 deprecation.py:323] From /tmp/Bazel.runfiles_ae3s                                                                                                      o6ns/runfiles/com_google_deepvariant/deepvariant/data_providers.py:381: map_and_batch                                                                                                       (from tensorflow.python.data.experimental.ops.batching) is deprecated and will be remo                                                                                                      ved in a future version.
Instructions for updating:
Use `tf.data.Dataset.map(map_func, num_parallel_calls)` followed by `tf.data.Dataset.b                                                                                                      atch(batch_size, drop_remainder)`. Static tf.data optimizations will take care of usin                                                                                                      g the fused implementation.
I0327 13:32:14.655726 47138345245376 estimator.py:1147] Calling model_fn.
W0327 13:32:14.658678 47138345245376 deprecation.py:323] From /tmp/Bazel.runfiles_ae3s                                                                                                      o6ns/runfiles/com_google_deepvariant/deepvariant/modeling.py:885: div (from tensorflow                                                                                                      .python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
W0327 13:32:14.662806 47138345245376 deprecation.py:323] From /usr/local/lib/python3.6                                                                                                      /dist-packages/tf_slim/layers/layers.py:1089: Layer.apply (from tensorflow.python.kera                                                                                                      s.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
I0327 13:32:21.277438 47138345245376 estimator.py:1149] Done calling model_fn.
I0327 13:32:23.167996 47138345245376 monitored_session.py:240] Graph was finalized.
I0327 13:32:23.169671 47138345245376 saver.py:1284] Restoring parameters from /opt/mod                                                                                                      els/wgs/model.ckpt
I0327 13:32:28.719004 47138345245376 session_manager.py:500] Running local_init_op.
I0327 13:32:28.854336 47138345245376 session_manager.py:502] Done running local_init_o                                                                                                      p.
I0327 13:32:29.648829 47138345245376 modeling.py:413] Reloading EMA...
I0327 13:32:29.650222 47138345245376 saver.py:1284] Restoring parameters from /opt/mod                                                                                                      els/wgs/model.ckpt
I0327 13:32:39.446630 47138345245376 call_variants.py:402] Processed 1 examples in 1 b                                                                                                      atches [2569.441 sec per 100]
I0327 13:32:39.551621 47138345245376 call_variants.py:404] Done evaluating variants

real    0m29.939s
user    0m20.774s
sys     0m5.396s

***** Running the command:*****
time /opt/deepvariant/bin/postprocess_variants --ref "/scratch/moldach/bin/quickstart-                                                                                                      testdata/ucsc.hg19.chr20.unittest.fasta" --infile "/tmp/tmp63xxmwmi/call_variants_outp                                                                                                      ut.tfrecord.gz" --outfile "/scratch/moldach/bin/quickstart-output/output.vcf.gz" --non                                                                                                      variant_site_tfrecord_path "/tmp/tmp63xxmwmi/gvcf.tfrecord@1.gz" --gvcf_outfile "/scra                                                                                                      tch/moldach/bin/quickstart-output/output.g.vcf.gz"

2020-03-27 13:32:43.691530: I deepvariant/postprocess_variants.cc:88] Read from: /tmp/                                                                                                      tmp63xxmwmi/call_variants_output.tfrecord.gz
2020-03-27 13:32:43.692692: I deepvariant/postprocess_variants.cc:97] Done reading: /t                                                                                                      mp/tmp63xxmwmi/call_variants_output.tfrecord.gz. #entries in single_site_calls = 86
2020-03-27 13:32:43.692820: I deepvariant/postprocess_variants.cc:101] Total #entries                                                                                                       in single_site_calls = 86
2020-03-27 13:32:43.692941: I deepvariant/postprocess_variants.cc:103] Start SortSingl                                                                                                      eSiteCalls
2020-03-27 13:32:43.693087: I deepvariant/postprocess_variants.cc:105] Done SortSingle                                                                                                      SiteCalls
I0327 13:32:43.693562 47816170105536 postprocess_variants.py:976] CVO sorting took 3.3                                                                                                      83557001749674e-05 minutes
I0327 13:32:43.694538 47816170105536 postprocess_variants.py:978] Transforming call_va                                                                                                      riants_output to variants.
I0327 13:32:43.694916 47816170105536 postprocess_variants.py:1004] Merging and writing                                                                                                       variants to VCF and gVCF.
[E::hts_open_format] Failed to open file /scratch/moldach/bin/quickstart-output/output                                                                                                      .vcf.gz
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_gmddntqf/runfiles/com_google_deepvariant/deepvariant/postp                                                                                                      rocess_variants.py", line 1039, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py"                                                                                                      , line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/tmp/Bazel.runfiles_gmddntqf/runfiles/absl_py/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_gmddntqf/runfiles/absl_py/absl/app.py", line 251, in _run_                                                                                                      main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_gmddntqf/runfiles/com_google_deepvariant/deepvariant/postp                                                                                                      rocess_variants.py", line 1007, in main
    FLAGS.outfile, header=header, round_qualities=True) as vcf_writer, \
  File "/tmp/Bazel.runfiles_gmddntqf/runfiles/com_google_deepvariant/third_party/nucle                                                                                                      us/io/genomics_writer.py", line 170, in __init__
    self._writer = self._native_writer(output_path, **kwargs)
  File "/tmp/Bazel.runfiles_gmddntqf/runfiles/com_google_deepvariant/third_party/nucle                                                                                                      us/io/vcf.py", line 316, in _native_writer
    exclude_header=exclude_header)
  File "/tmp/Bazel.runfiles_gmddntqf/runfiles/com_google_deepvariant/third_party/nucle                                                                                                      us/io/vcf.py", line 288, in __init__
    writer_options)
ValueError: Unknown: Could not open variants_path: /scratch/moldach/bin/quickstart-out                                                                                                      put/output.vcf.gz

real    0m3.763s
user    0m2.899s
sys     0m0.651s
I0327 13:32:43.946818 47794500922048 run_deepvariant.py:321] None
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 332, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 319, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time /opt/deepvariant/bin/postprocess_variants                                                                                                       --ref "/scratch/moldach/bin/quickstart-testdata/ucsc.hg19.chr20.unittest.fasta" --inf                                                                                                      ile "/tmp/tmp63xxmwmi/call_variants_output.tfrecord.gz" --outfile "/scratch/moldach/bi                                                                                                      n/quickstart-output/output.vcf.gz" --nonvariant_site_tfrecord_path "/tmp/tmp63xxmwmi/g                                                                                                      vcf.tfrecord@1.gz" --gvcf_outfile "/scratch/moldach/bin/quickstart-output/output.g.vcf                                                                                                      .gz"' returned non-zero exit status 1.
[moldach@cdr767 bin]$ ^C
[moldach@cdr767 bin]$ exit
exit
srun: error: cdr767: task 0: Exited with exit code 130
```

Any idea what could be causing this?

**Comment by pichuan** [comment]
Hi @moldach 
somehow your logs above have a lot of spaces in the middle, making it hard to read.

It seems like the last step was looking for `/scratch/moldach/bin/quickstart-output/output.vcf.gz` but couldn't find it. 

I'll walk through the steps again to see if I can reproduce your error, but meanwhile, can you try:

```
singularity run -B $PWD,/usr/lib/locale/ \
```

instead of 

```
singularity run -B /usr/lib/locale/:/usr/lib/locale/  \
```

And see if it works for you? Thanks.

**Comment by pichuan** [comment]
@moldach Actually, I think I might know the problem. Does your OUTPUT_DIR exist?

I suggest you add a line below:
```
OUTPUT_DIR="${PWD}/quickstart-output"
mkdir -p ${OUTPUT_DIR}
```
to first ensure the directory is created.
