### ISSUE TITLE
command line pipeline support?

### ISSUE THREAD

**Issue by yvanst** [google/deepvariant#288]
Hi, I want to know is there any way to make deepvariant  support command line pipeline, I'm expecting it could accept read from stdin and pipe result to stdout.

I tried explicitly using /dev/stdout to pipe result to stdout, 
```bash
  docker run \
  --gpus all \
  --rm \
  -v ${INPUT_DIR}:/input \
  -v ${OUTPUT_DIR}:/output \
  google/deepvariant:latest-gpu \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref=/input/ucsc.hg19.chr20.unittest.fasta \
  --reads=/input/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,000,100" \
  --output_vcf=/dev/stdout \
  --num_shards=4 \
  2> stderr.txt
```
it could work, but print some debug information to stdout and pollute the result
```
***** Running the command:*****
time seq 0 3 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/ucsc.hg19.chr20.unittest.fasta" --reads "/input/NA12878_S1.chr20.10_10p1mb.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@4.gz" --regions "chr20:10,000,000-10,000,100" --task {}


***** Running the command:*****
time /opt/deepvariant/bin/call_variants --outfile "/tmp/deepvariant_tmp_output/call_variants_output.tfrecord.gz" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@4.gz" --checkpoint "/opt/models/wgs/model.ckpt"


WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.


***** Running the command:*****
time /opt/deepvariant/bin/postprocess_variants --ref "/input/ucsc.hg19.chr20.unittest.fasta" --infile "/tmp/deepvariant_tmp_output/call_variants_output.tfrecord.gz" --outfile "/dev/stdout"

##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##FILTER=<ID=RefCall,Description="Genotyping model thinks this site is reference.">
##FILTER=<ID=LowQual,Description="Confidence in this variant being real is below calling threshold.">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position (for use with symbolic alleles)">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Conditional genotype quality">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read depth">
##FORMAT=<ID=MIN_DP,Number=1,Type=Integer,Description="Minimum DP observed within the GVCF block.">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Read depth for each allele">
##FORMAT=<ID=VAF,Number=A,Type=Float,Description="Variant allele fractions.">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Phred-scaled genotype likelihoods rounded to the closest integer">
##contig=<ID=chr20,length=63025520>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	default
```

I then tried explicitly using /dev/stdin, this time I got errors
```bash
cat ${INPUT_DIR}/NA12878_S1.chr20.10_10p1mb.bam  | \
docker run \
  --gpus all \
  --rm \
  -i \
  -v ${INPUT_DIR}:/input \
  -v ${OUTPUT_DIR}:/output \
  google/deepvariant:latest-gpu \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref=/input/ucsc.hg19.chr20.unittest.fasta \
  --reads=/dev/stdin \
  --regions "chr20:10,000,000-10,000,100" \
  --output_vcf=/output/output.vcf \
  --num_shards=4 
```

```
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_O8GZSR/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1461, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_O8GZSR/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1451, in main
    make_examples_runner(options)
  File "/tmp/Bazel.runfiles_O8GZSR/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1325, in make_examples_runner
    regions = processing_regions_from_options(options)
  File "/tmp/Bazel.runfiles_O8GZSR/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1243, in processing_regions_from_options
    sam_contigs = common_contigs(only_true(*all_sam_contigs))
  File "/tmp/Bazel.runfiles_O8GZSR/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 656, in common_contigs
    common = contigs_list[0]
IndexError: list index out of range
```

so is there any way to make it work?
Thanks

**Comment by pichuan** [comment]
There is an answer from @akolesnikov 

---

I'm afraid that passing input reads through stdin would not be possible. BAM reader expects an index file to be the same name is an input BAM file with ".bai" added.
Console output can be removed by modifying run_deepvariant.py script, except the TensorFlow warning, which originates from TensorFlow.
Bottom line is I'm afraid it wouldn't be possible to read input from stdin and write output to stdout.

---
