### ISSUE TITLE
exit status 55

### ISSUE THREAD

**Issue by sjin09** [google/deepvariant#315]
To whom it may concern,

I have created an openstack instance to run deepvariant 0.9.0 as detailed below. I had no problem running deepvariant in another openstack instance, but I cannot figure out why it will not work in the instance that I newly created.

I was wondering if deepvariant developers could provide some guidance towards running deepvariant again.

Regards,
Sangjin

```
***** Running the command:*****
time seq 0 54 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/ilAriAges1.fasta.bgz" --reads "/input/ilAriAges1.m64097_191226_203354.minimap2_asm20.primary_alignments.sorted.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@55.gz" --norealign_reads --vsc_min_fraction_indels "0.12" --task {}


real    0m1.608s
user    0m25.676s
sys     0m23.860s
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 317, in <module>
    app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 307, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 54 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/ilAriAges1.fasta.bgz" --reads "/input/ilAriAges1.m64097_191226_203354.minimap2_asm20.primary_alignments.sorted.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@55.gz" --norealign_reads --vsc_min_fraction_indels "0.12" --task {}' returned non-zero exit status 55
```

**Comment by akolesnikov** [comment]
Looks like the problem is in make_examples. In order to debug the problem we need make_examples logs. You can run the command below. Flag "logtostderr" redirect logs to the console. You need to run it inside docker the same way as you ran your original command.
``` 
/opt/deepvariant/bin/make_examples --mode calling --ref "/input/ilAriAges1.fasta.bgz" --reads "/input/ilAriAges1.m64097_191226_203354.minimap2_asm20.primary_alignments.sorted.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@55.gz" --norealign_reads --vsc_min_fraction_indels "0.12" --task 54 --logtostderr
```

**Comment by sjin09** [comment]
I ran the above command as such, but the terminal didn't return any errors except `sudo: unable to resolve host smd` where `smd` is the OpenStack instance name.

```
sudo docker run \
    -v "${INPUT_DIR}":"/input" \
    -v "${OUTPUT_DIR}:/output" \
    gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}" \
    /opt/deepvariant/bin/make_examples \
    --mode calling \
    --ref "/input/ilAriAges1.fasta.bgz" \
    --reads "/input/ilAriAges1.m64097_191226_203354.minimap2_asm20.primary_alignments.sorted.bam" \
    --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@55.gz" \
    --norealign_reads \
    --vsc_min_fraction_indels "0.12" \
    --task 54 --logtostderr
```

**Comment by sjin09** [comment]
hello @akolesnikov,

I was wondering if you might have some additional guidance towards running deepvariant. I have started running deepvariant successfully in another server, but I would like to be run the process in parallel in multiple servers.

**Comment by akolesnikov** [comment]
Hello sjin09,

Unfortunately we don't have a tutorial for how to run DeepVariant in distributed environment. Although, there are multiple external solutions that provide good solutions. Please see https://github.com/google/deepvariant#external-solutions for more information.
