### ISSUE TITLE
parallel: This job failed reproducing the test example

### ISSUE THREAD

**Issue by abrozzi** [google/deepvariant#325]
Dears,

I get an error trying to reproduce the test example on my Bio-Linux Ubuntu 14.04.6 LTS where I run a 1.6.2 docker.

The docker installation was successful:

```
REPOSITORY           TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
google/deepvariant   0.10.0              4745891a5ab0        3 months ago        3.866 GB
google/deepvariant   latest              4745891a5ab0        3 months ago        3.866 GB
```

But I get this error:

```
I0715 10:39:51.140211 139624775427840 run_deepvariant.py:241] Re-using the directory for intermediate results in /tmp/tmpsowmvllp

***** Intermediate results will be written to /tmp/tmpsowmvllp in docker. ****


***** Running the command:*****
time seq 0 31 | parallel --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/ucsc.hg19.chr20.unittest.fasta" --reads "/input/NA12878_S1.chr20.10_10p1mb.bam" --examples "/tmp/tmpsowmvllp/make_examples.tfrecord@32.gz" --gvcf "/tmp/tmpsowmvllp/gvcf.tfrecord@32.gz" --regions "chr20:10,000,000-10,010,000" --task {}

parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /input/ucsc.hg19.chr20.unittest.fasta --reads /input/NA12878_S1.chr20.10_10p1mb.bam --examples /tmp/tmpsowmvllp/make_examples.tfrecord@32.gz --gvcf /tmp/tmpsowmvllp/gvcf.tfrecord@32.gz --regions chr20:10,000,000-10,010,000 --task 2
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /input/ucsc.hg19.chr20.unittest.fasta --reads /input/NA12878_S1.chr20.10_10p1mb.bam --examples /tmp/tmpsowmvllp/make_examples.tfrecord@32.gz --gvcf /tmp/tmpsowmvllp/gvcf.tfrecord@32.gz --regions chr20:10,000,000-10,010,000 --task 0
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /input/ucsc.hg19.chr20.unittest.fasta --reads /input/NA12878_S1.chr20.10_10p1mb.bam --examples /tmp/tmpsowmvllp/make_examples.tfrecord@32.gz --gvcf /tmp/tmpsowmvllp/gvcf.tfrecord@32.gz --regions chr20:10,000,000-10,010,000 --task 3

real    0m20.988s
user    0m7.822s
sys     3m7.414s
I0715 10:40:12.133007 139624775427840 run_deepvariant.py:321] None
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 332, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 319, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 31 | parallel --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/ucsc.hg19.chr20.unittest.fasta" --reads "/input/NA12878_S1.chr20.10_10p1mb.bam" --examples "/tmp/tmpsowmvllp/make_examples.tfrecord@32.gz" --gvcf "/tmp/tmpsowmvllp/gvcf.tfrecord@32.gz" --regions "chr20:10,000,000-10,010,000" --task {}' returned non-zero exit status 252.
```
The command I run is the following:

```
:~# cat command.sh
docker run -v "/root/quickstart-testdata":"/input" -v "/root/quickstart-output":"/output" google/deepvariant:latest /opt/deepvariant/bin/run_deepvariant --model_type=WGS --ref=/input/ucsc.hg19.chr20.unittest.fasta --reads=/input/NA12878_S1.chr20.10_10p1mb.bam --regions "chr20:10,000,000-10,010,000" --output_vcf=/output/output.vcf.gz --output_gvcf=/output/output.g.vcf.gz --num_shards=32
```
And the content of ```testdata``` dir is:

```
:~# ls quickstart-testdata/
NA12878_S1.chr20.10_10p1mb.bam                 ucsc.hg19.chr20.unittest.fasta
NA12878_S1.chr20.10_10p1mb.bam.bai             ucsc.hg19.chr20.unittest.fasta.fai
test_nist.b37_chr20_100kbp_at_10mb.bed         ucsc.hg19.chr20.unittest.fasta.gz
test_nist.b37_chr20_100kbp_at_10mb.vcf.gz      ucsc.hg19.chr20.unittest.fasta.gz.fai
test_nist.b37_chr20_100kbp_at_10mb.vcf.gz.tbi  ucsc.hg19.chr20.unittest.fasta.gz.gzi
```

Thanks a lot for any help!
-A

**Comment by gunjanbaid** [comment]
Hi @abrozzi, a quick check: where is the `quickstart-testdata` directory located? The Docker command you are using expects it to be under `/root`.

**Comment by gunjanbaid** [comment]
Some other things to look in to:

* Is what you have pasted above the full stack trace? If there's any other output, it would be helpful to see that as well.
* Could you try running `make_examples` directly using the below command? This is only using one shard. If this command fails, we may see a more informative error message.

```
sudo docker run \
  -v "/root/quickstart-testdata":"/input" \
  -v "/root/quickstart-output":"/output" \
  google/deepvariant:latest \
  /opt/deepvariant/bin/make_examples \
  --mode calling \
  --ref "/input/ucsc.hg19.chr20.unittest.fasta" \
  --reads "/input/NA12878_S1.chr20.10_10p1mb.bam" \
  --examples "/output/make_examples.tfrecord@1.gz" \
  --gvcf "/output/gvcf.tfrecord@1.gz" \
  --regions "chr20:10,000,000-10,010,000"
```

**Comment by abrozzi** [comment]
Hi Gunjan,
and thanks a lot for your reply.

Yes, the directories where all accessible and under ```root``` (I know it can be done better....).
Indeed when I added to the docker command the option ``` --user root``` the error changed and was very clear: ``` disk full```.
It remains to me to free disk or change docker location, add a docker group to allow users run it without ```sudo``` and rerun it. I am pretty confident it should work.

With Regards,
-A

**Comment by gunjanbaid** [comment]
Glad to hear you found the problem! I'll close this issue, but feel free to reopen it if you have any other questions.
