### ISSUE TITLE
Malformed AD field in GVCF when variant calling with proposed variants VCF

### ISSUE THREAD

**Issue by GuillaumeHolley** [google/deepvariant#341]
**Describe the issue:**
When doing the variant calling with a VCF file of proposed variants (`variant_caller=vcf_candidate_importer,proposed_variants=${VCF_JOIN}`) and specifying GVCF output, ref call sites end up with only 2 entries in the FORMAT field AD while the ALT field contain also 2 entries which should result in 3 AD entries. 
Example: `chr1 11391 . T A,<*> 0 RefCall . GT:GQ:DP:AD:VAF:PL 0/0:24:0:0,0:0:0,26,27,990,990,990`. Here the AD field has 2 entries but should have 3. Thereafter, the merging with GLNexus fails with the following error `Failed to genotype: Invalid: genotyper: VCF allele depth FORMAT field is malformed (sample <0>:11391-11391 (AD))`.  

**Setup**
  - Operating system: Linux
  - DeepVariant version: 0.10.0
  - Installation method (Docker, built from source, etc.): Singularity

**Steps to reproduce:**
  - Command: ` singularity exec -B /usr/lib/locale/:/usr/lib/locale/ ${SINGULARITY_IMG} bash /opt/deepvariant/bin/run_deepvariant --model_type WGS --customized_model ${MODEL} --ref ${REF} --reads ${IN_BAM} --output_vcf ${OUT_VCF}.2.vcf.gz --output_gvcf ${OUT_VCF}.2.g.vcf.gz --num_shards 24 --make_examples_extra_args=\"realign_reads=false,min_mapping_quality=${MIN_MAPQ},min_base_quality=${MIN_QS},variant_caller=vcf_candidate_importer,proposed_variants=${VCF_JOIN}\" --sample_name ${IN_PN} ${BED_ARG};"
`

**Comment by sgoe1** [comment]
Hi @GuillaumeHolley, thanks for raising the issue. Could you try to run this with 1.0.0 image and let me know whether the issue persists? We haven't officially released 1.0.0 just yet, but we can use it to test this.

**Comment by GuillaumeHolley** [comment]
Hi @sgoe1,

Thanks for getting back to me on this so quickly. I will give a shot at the 1.0.0 image first thing tomorrow morning and will let you know how it went.

Guillaume

**Comment by GuillaumeHolley** [comment]
Hi @sgoe1,

Using the 1.0.0 image, the variant calling fails on nearly all of my input samples with the following error:
```
2020-09-03 10:01:02.237494: I deepvariant/postprocess_variants.cc:88] Read from: /tmp/tmpqosj7aak/call_variants_output.tfrecord.gz
2020-09-03 10:01:02.575525: I deepvariant/postprocess_variants.cc:103] Total #entries in single_site_calls = 63099
I0903 10:01:02.988874 140046207305472 postprocess_variants.py:1079] CVO sorting took 0.012529869874318441 minutes
I0903 10:01:02.989492 140046207305472 postprocess_variants.py:1081] Transforming call_variants_output to variants.
I0903 10:01:02.989910 140046207305472 postprocess_variants.py:1108] Merging and writing variants to VCF and gVCF.
I0903 10:01:02.996278 140046207305472 genomics_writer.py:172] Writing /<REDACTED>/ID.2.vcf.gz with NativeVcfWriter
I0903 10:01:02.998338 140046207305472 genomics_writer.py:172] Writing /<REDACTED>/ID.2.g.vcf.gz with NativeVcfWriter
W0903 10:01:17.865604 140046207305472 postprocess_variants.py:394] Alt allele indices found from call_variants_outputs for variant reference_bases: "CTT"
alternate_bases: "CT"
alternate_bases: "CTTT"
alternate_bases: "CTTTTTTTCT"
calls {
  info {
    key: "AD"
    value {
      values {
        int_value: 7
      }
      values {
        int_value: 7
      }
      values {
        int_value: 0
      }
      values {
        int_value: 0
      }
    }
  }
  info {
    key: "DP"
    value {
      values {
        int_value: 19
      }
    }
  }
  info {
    key: "VAF"
    value {
      values {
        number_value: 0.3684210526315789
      }
      values {
        number_value: 0.0
      }
      values {
        number_value: 0.0
      }
    }
  }
  genotype: -1
  genotype: -1
  call_set_name: "ID"
}
end: 21441513
reference_name: "chr16"
start: 21441510
 is [[0], [0], [0, 1], [0, 2], [1], [1, 2], [2]], which is invalid.
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_fbg2uft9/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1143, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/tmp/Bazel.runfiles_fbg2uft9/runfiles/absl_py/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_fbg2uft9/runfiles/absl_py/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_fbg2uft9/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1122, in main
    vcf_writer, gvcf_writer)
  File "/tmp/Bazel.runfiles_fbg2uft9/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 962, in merge_and_write_variants_and_nonvariants
    variant = next_or_none(variant_iterable)
  File "/tmp/Bazel.runfiles_fbg2uft9/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 948, in next_or_none
    return next(iterable)
  File "/tmp/Bazel.runfiles_fbg2uft9/runfiles/com_google_deepvariant/deepvariant/haplotypes.py", line 91, in maybe_resolve_conflicting_variants
    for overlapping_candidates in _group_overlapping_variants(sorted_variants):
  File "/tmp/Bazel.runfiles_fbg2uft9/runfiles/com_google_deepvariant/deepvariant/haplotypes.py", line 110, in _group_overlapping_variants
    for variant in sorted_variants:
  File "/tmp/Bazel.runfiles_fbg2uft9/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 807, in _transform_call_variants_output_to_variants
    multiallelic_model=multiallelic_model)
  File "/tmp/Bazel.runfiles_fbg2uft9/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 680, in merge_predictions
    raise ValueError('`call_variants_outputs` did not pass sanity check.')
ValueError: `call_variants_outputs` did not pass sanity check.
```

**Comment by sgoe1** [comment]
When you run postprocess_variants can you try setting the `group_variants` flag to False?

**Comment by GuillaumeHolley** [comment]
Success :)

Note that to make it work, I used `bcftools norm -m-any` on the VCF file of proposed variants (generated by GLnexus) to split multiallelic sites into multiple lines. Otherwise, it failed as previously reported.

Thank you for the help!
