### ISSUE TITLE
Crash due to incorrect sample name ("default") in empty VCF file

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [google/deepvariant#354]
**Describe the issue:**
`/opt/deepvariant/bin/run_deepvariant` crashes when there are no variants, because a VCF file gets written with 'default' as the sample name'. This happens because I use targetted sequencing, and when the capture fails, I get hardly any reads. This can be simulated by downsampling the quickstart data to 0.1%, see below.

**Setup**
  - HPC
  - google/deepvariant:0.10.0
  - Docker
  - Targetted PacBio sequencing, aligned against HG38

**Does the quick start test work on your system?**
Yes

**Workaround, for version 1.0.0 only**
This error does not occur when using version 1.0.0, and explicitly passing the `--sample_name` flag to `run_deepvariant`. 

**Steps to reproduce, using the quickstart data:**
```bash
MODEL_TYPE=PACBIO
NUM_SHARDS=4
READS=NA12878_0.1_percent.bam

# Downsample the reads to 0.1%
samtools view -s 0.001 -b NA12878_S1.chr20.10_10p1mb.bam -o ${READS} --write-index

docker run \
  -v "${INPUT_DIR}":"/input" \
  -v "${OUTPUT_DIR}":"/output" \
  google/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=${MODEL_TYPE} \
  --ref=/input/ucsc.hg19.chr20.unittest.fasta \
  --reads=/input/${READS} \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf=/output/output.vcf.gz \
  --output_gvcf=/output/output.g.vcf.gz \
  --intermediate_results_dir /output/intermediate_results_dir \
  --num_shards=${NUM_SHARDS}
```

**Error trace**
```bash
$ docker run   -v "${INPUT_DIR}":"/input"   -v "${OUTPUT_DIR}":"/output"   google/deepvariant:"${BIN_VERSION}"   /opt/deepvariant/bin/run_deepvariant   --model_type=${MODEL_TYPE}   --ref=/input/ucsc.hg19.chr20.unittest.fasta   --reads=/input/${READS}   --regions "chr20:10,000,000-10,010,000"   --output_vcf=/output/output.vcf.gz   --output_gvcf=/output/output.g.vcf.gz   --intermediate_results_dir /output/intermediate_results_dir   --num_shards=${NUM_SHARDS}
I0921 06:50:39.795207 140086398105344 run_deepvariant.py:241] Re-using the directory for intermediate results in /output/intermediate_results_dir

***** Intermediate results will be written to /output/intermediate_results_dir in docker. ****


***** Running the command:*****
time seq 0 3 | parallel --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/ucsc.hg19.chr20.unittest.fasta" --reads "/input/NA12878_0.1_percent.bam" --examples "/output/intermediate_results_dir/make_examples.tfrecord@4.gz" --gvcf "/output/intermediate_results_dir/gvcf.tfrecord@4.gz" --norealign_reads --regions "chr20:10,000,000-10,010,000" --vsc_min_fraction_indels "0.12" --task {}

I0921 06:50:42.018504 140507660818176 make_examples.py:386] ReadRequirements are: min_mapping_quality: 10
min_base_quality: 10
min_base_quality_mode: ENFORCED_BY_CLIENT

I0921 06:50:42.019153 140507660818176 genomics_reader.py:223] Reading /input/NA12878_0.1_percent.bam with NativeSamReader
I0921 06:50:42.020942 140507660818176 make_examples.py:535] Task 2/4: Preparing inputs
I0921 06:50:42.021255 140507660818176 genomics_reader.py:223] Reading /input/NA12878_0.1_percent.bam with NativeSamReader
I0921 06:50:42.021699 140507660818176 make_examples.py:535] Task 2/4: Common contigs are ['chr20']
I0921 06:50:42.022325 140507660818176 make_examples.py:535] Task 2/4: Writing examples to /output/intermediate_results_dir/make_examples.tfrecord-00002-of-00004.gz
I0921 06:50:42.022399 140507660818176 make_examples.py:535] Task 2/4: Writing gvcf records to /output/intermediate_results_dir/gvcf.tfrecord-00002-of-00004.gz
I0921 06:50:42.022782 140507660818176 make_examples.py:535] Task 2/4: Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2020-09-21 06:50:42.022911: I third_party/nucleus/io/sam_reader.cc:660] Setting HTS_OPT_BLOCK_SIZE to 134217728
I0921 06:50:42.023052 140507660818176 genomics_reader.py:223] Reading /input/NA12878_0.1_percent.bam with NativeSamReader
I0921 06:50:41.996238 139913398449920 make_examples.py:386] ReadRequirements are: min_mapping_quality: 10
min_base_quality: 10
min_base_quality_mode: ENFORCED_BY_CLIENT

I0921 06:50:41.996968 139913398449920 genomics_reader.py:223] Reading /input/NA12878_0.1_percent.bam with NativeSamReader
I0921 06:50:42.017571 139913398449920 make_examples.py:535] Task 1/4: Preparing inputs
I0921 06:50:42.017939 139913398449920 genomics_reader.py:223] Reading /input/NA12878_0.1_percent.bam with NativeSamReader
I0921 06:50:42.018360 139913398449920 make_examples.py:535] Task 1/4: Common contigs are ['chr20']
I0921 06:50:42.018917 139913398449920 make_examples.py:535] Task 1/4: Writing examples to /output/intermediate_results_dir/make_examples.tfrecord-00001-of-00004.gz
I0921 06:50:42.018983 139913398449920 make_examples.py:535] Task 1/4: Writing gvcf records to /output/intermediate_results_dir/gvcf.tfrecord-00001-of-00004.gz
I0921 06:50:42.019343 139913398449920 make_examples.py:535] Task 1/4: Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2020-09-21 06:50:42.019467: I third_party/nucleus/io/sam_reader.cc:660] Setting HTS_OPT_BLOCK_SIZE to 134217728
I0921 06:50:42.019596 139913398449920 genomics_reader.py:223] Reading /input/NA12878_0.1_percent.bam with NativeSamReader
I0921 06:50:42.000666 140575591024384 make_examples.py:386] ReadRequirements are: min_mapping_quality: 10
min_base_quality: 10
min_base_quality_mode: ENFORCED_BY_CLIENT

I0921 06:50:42.001444 140575591024384 genomics_reader.py:223] Reading /input/NA12878_0.1_percent.bam with NativeSamReader
I0921 06:50:42.021518 140575591024384 make_examples.py:535] Task 3/4: Preparing inputs
I0921 06:50:42.021949 140575591024384 genomics_reader.py:223] Reading /input/NA12878_0.1_percent.bam with NativeSamReader
I0921 06:50:42.022429 140575591024384 make_examples.py:535] Task 3/4: Common contigs are ['chr20']
I0921 06:50:42.023006 140575591024384 make_examples.py:535] Task 3/4: Writing examples to /output/intermediate_results_dir/make_examples.tfrecord-00003-of-00004.gz
I0921 06:50:42.023092 140575591024384 make_examples.py:535] Task 3/4: Writing gvcf records to /output/intermediate_results_dir/gvcf.tfrecord-00003-of-00004.gz
I0921 06:50:42.023483 140575591024384 make_examples.py:535] Task 3/4: Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2020-09-21 06:50:42.023610: I third_party/nucleus/io/sam_reader.cc:660] Setting HTS_OPT_BLOCK_SIZE to 134217728
I0921 06:50:42.023738 140575591024384 genomics_reader.py:223] Reading /input/NA12878_0.1_percent.bam with NativeSamReader
I0921 06:50:41.993439 140201192457984 make_examples.py:386] ReadRequirements are: min_mapping_quality: 10
min_base_quality: 10
min_base_quality_mode: ENFORCED_BY_CLIENT

I0921 06:50:41.994182 140201192457984 genomics_reader.py:223] Reading /input/NA12878_0.1_percent.bam with NativeSamReader
I0921 06:50:42.033505 140201192457984 make_examples.py:535] Task 0/4: Preparing inputs
I0921 06:50:42.033882 140201192457984 genomics_reader.py:223] Reading /input/NA12878_0.1_percent.bam with NativeSamReader
I0921 06:50:42.034327 140201192457984 make_examples.py:535] Task 0/4: Common contigs are ['chr20']
I0921 06:50:42.034979 140201192457984 make_examples.py:535] Task 0/4: Writing examples to /output/intermediate_results_dir/make_examples.tfrecord-00000-of-00004.gz
I0921 06:50:42.035050 140201192457984 make_examples.py:535] Task 0/4: Writing gvcf records to /output/intermediate_results_dir/gvcf.tfrecord-00000-of-00004.gz
I0921 06:50:42.035436 140201192457984 make_examples.py:535] Task 0/4: Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2020-09-21 06:50:42.035560: I third_party/nucleus/io/sam_reader.cc:660] Setting HTS_OPT_BLOCK_SIZE to 134217728
I0921 06:50:42.035694 140201192457984 genomics_reader.py:223] Reading /input/NA12878_0.1_percent.bam with NativeSamReader
I0921 06:50:42.136245 140507660818176 make_examples.py:535] Task 2/4: 0 candidates (0 examples) [0.11s elapsed]
I0921 06:50:42.146824 140507660818176 make_examples.py:535] Task 2/4: Found 0 candidate variants
I0921 06:50:42.146936 140507660818176 make_examples.py:535] Task 2/4: Created 0 examples
I0921 06:50:42.133788 139913398449920 make_examples.py:535] Task 1/4: 0 candidates (0 examples) [0.11s elapsed]
I0921 06:50:42.154796 139913398449920 make_examples.py:535] Task 1/4: Found 0 candidate variants
I0921 06:50:42.154923 139913398449920 make_examples.py:535] Task 1/4: Created 0 examples
I0921 06:50:42.137424 140575591024384 make_examples.py:535] Task 3/4: 0 candidates (0 examples) [0.11s elapsed]
I0921 06:50:42.147503 140575591024384 make_examples.py:535] Task 3/4: Found 0 candidate variants
I0921 06:50:42.147607 140575591024384 make_examples.py:535] Task 3/4: Created 0 examples
I0921 06:50:42.173398 140201192457984 make_examples.py:535] Task 0/4: 0 candidates (0 examples) [0.14s elapsed]
I0921 06:50:42.195395 140201192457984 make_examples.py:535] Task 0/4: Found 0 candidate variants
I0921 06:50:42.195529 140201192457984 make_examples.py:535] Task 0/4: Created 0 examples

real	0m2.637s
user	0m8.272s
sys	0m1.419s

***** Running the command:*****
time /opt/deepvariant/bin/call_variants --outfile "/output/intermediate_results_dir/call_variants_output.tfrecord.gz" --examples "/output/intermediate_results_dir/make_examples.tfrecord@4.gz" --checkpoint "/opt/models/pacbio/model.ckpt"

I0921 06:50:44.216155 140117089298176 call_variants.py:316] Set KMP_BLOCKTIME to 0
W0921 06:50:44.234806 140117089298176 call_variants.py:323] Unable to read any records from /output/intermediate_results_dir/make_examples.tfrecord@4.gz. Output will contain zero records.

real	0m1.979s
user	0m1.868s
sys	0m0.327s

***** Running the command:*****
time /opt/deepvariant/bin/postprocess_variants --ref "/input/ucsc.hg19.chr20.unittest.fasta" --infile "/output/intermediate_results_dir/call_variants_output.tfrecord.gz" --outfile "/output/output.vcf.gz" --nonvariant_site_tfrecord_path "/output/intermediate_results_dir/gvcf.tfrecord@4.gz" --gvcf_outfile "/output/output.g.vcf.gz"

I0921 06:50:46.249888 139970848761600 postprocess_variants.py:966] call_variants_output is empty. Writing out empty VCF.
I0921 06:50:46.250269 139970848761600 postprocess_variants.py:1004] Merging and writing variants to VCF and gVCF.
I0921 06:50:46.250618 139970848761600 genomics_writer.py:172] Writing /output/output.vcf.gz with NativeVcfWriter
I0921 06:50:46.250890 139970848761600 genomics_writer.py:172] Writing /output/output.g.vcf.gz with NativeVcfWriter
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_vzky1fw7/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1039, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/tmp/Bazel.runfiles_vzky1fw7/runfiles/absl_py/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_vzky1fw7/runfiles/absl_py/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_vzky1fw7/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1018, in main
    vcf_writer, gvcf_writer)
  File "/tmp/Bazel.runfiles_vzky1fw7/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 867, in merge_and_write_variants_and_nonvariants
    gvcf_writer.write(nonvariant)
  File "/tmp/Bazel.runfiles_vzky1fw7/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_writer.py", line 188, in write
    self._writer.write(proto)
  File "/tmp/Bazel.runfiles_vzky1fw7/runfiles/com_google_deepvariant/third_party/nucleus/io/vcf.py", line 292, in write
    self._writer.write(proto)
ValueError: Failed precondition: Out-of-order call set names, or unrecognized call set name, with respect to samples declared in VCF header. Variant has NA12878 at position 0 while the VCF header expected a sample named default at this position

real	0m2.173s
user	0m1.878s
sys	0m0.379s
I0921 06:50:46.590006 140086398105344 run_deepvariant.py:321] None
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 332, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 319, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time /opt/deepvariant/bin/postprocess_variants --ref "/input/ucsc.hg19.chr20.unittest.fasta" --infile "/output/intermediate_results_dir/call_variants_output.tfrecord.gz" --outfile "/output/output.vcf.gz" --nonvariant_site_tfrecord_path "/output/intermediate_results_dir/gvcf.tfrecord@4.gz" --gvcf_outfile "/output/output.g.vcf.gz"' returned non-zero exit status 1.
```

**Comment by Redmar-van-den-Berg** [comment]
The same error happens with `google/deepvariant:1.0.0`

**Comment by gunjanbaid** [comment]
Hi @Redmar-van-den-Berg, thanks for reporting this! We will look into the issue and plan to release a fix in the next version of DeepVariant.

**Comment by gunjanbaid** [comment]
@Redmar-van-den-Berg this issue has been fixed internally, and the fix will be out with the next release. When gVCF records are present, we will try to extract the sample name from those, instead of using 'default'. I'll close this issue for now, but feel free to reopen if you have any other questions. Thanks!
