### ISSUE TITLE
Singularity version error: ModuleNotFoundError

### ISSUE THREAD

**Issue by gevro** [google/deepvariant#385]
Hi,
I'm using the docker Deepvariant 1.0.0 via singularity, and getting this error:

Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_nug2d3l9/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 47, in <module>
    import tensorflow as tf
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/tensorflow_core/__init__.py", line 33, in <module>
    import distutils as _distutils
  File "/usr/local/lib/python3.6/dist-packages/_distutils_hack/__init__.py", line 82, in create_module
    return importlib.import_module('._distutils', 'setuptools')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 6, in <module>
    import distutils.core
  File "/usr/local/lib/python3.6/dist-packages/_distutils_hack/__init__.py", line 82, in create_module
    return importlib.import_module('._distutils', 'setuptools')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'setuptools._distutils'

**Comment by gevro** [comment]
I believe the issue is that singularity is using my local python, instead of python inside the image.... How do I fix this?

**Comment by pichuan** [comment]
@gevro Given the error information, can you try installing setuptools?
For example, https://stackoverflow.com/questions/14426491/python-3-importerror-no-module-named-setuptools

**Comment by gevro** [comment]
I tried, but then I get this error:
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_39ce4fku/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 47, in <module>
    import tensorflow as tf
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/tensorflow_core/__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 947, in _find_and_load_unlocked
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/tensorflow_core/python/__init__.py", line 68, in <module>
    from tensorflow.core.protobuf.meta_graph_pb2 import TensorInfo
  File "/gpfs/home/evrong01/.local/lib/python3.6/site-packages/tensorflow_core/core/protobuf/meta_graph_pb2.py", line 526, in <module>
    serialized_options=None, file=DESCRIPTOR),
  File "/tmp/Bazel.runfiles_39ce4fku/runfiles/com_google_protobuf/python/google/protobuf/descriptor.py", line 534, in __new__
    return _message.default_pool.FindFieldByName(full_name)
KeyError: "Couldn't find field tensorflow.TensorInfo.CompositeTensor.type_spec"

**Comment by gevro** [comment]
For some reason singularity is accessing my local python libs, instead of the singularity image's libraries.

**Comment by danielecook** [comment]
@gevro can you send the command you are using to run singularity?

**Comment by gevro** [comment]
singularity run -B /usr/lib/locale/:/usr/lib/locale/ ~/bin/deepvariant/deepvariant_1.0.0.sif /opt/deepvariant/bin/run_deepvariant --model_type=WGS --ref=reference.fasta --reads=input.bam --regions=regions.bed --output_vcf=output.vcf.gz --output_gvcf=output.g.vcf.gz --num_shards=16

I also tried with the -e flag, and removing -B. Same error.

**Comment by danielecook** [comment]
@gevro this may be related:

[Stackoverflow #62693948](https://stackoverflow.com/questions/62693948/why-does-mounting-the-home-directory-in-singularity-container-break-a-python-imp)

What directory are you running singularity from? I have run into issues in the past running singularity from my home directory.

Try the following:

(1) Move all data files to a dedicated folder if they are not already
(2) Move to that directory, and run singularity using `--cleanevn`, `--no-home`, and binding only the directory you are located in (`-B $(pwd):$(pwd)`):

```bash
singularity run --cleanenv \
                --no-home \
                -B $(pwd):$(pwd) \
                ~/bin/deepvariant/deepvariant_1.0.0.sif \
                /opt/deepvariant/bin/run_deepvariant \
                --model_type=WGS \
                --ref=reference.fasta \
                --reads=input.bam \
                --regions=regions.bed \
                --output_vcf=output.vcf.gz \
                --output_gvcf=output.g.vcf.gz \
                --num_shards=16
```

**Comment by gevro** [comment]
Yup that fixed it! Singularity is a fairly problematic system given the complexity of how it treats the native environment and folders/permissions outside the container. I wish it was made more seamless like docker, because it's a real hassle to use.
