### ISSUE TITLE
"no such file or directory: --ref=/input/Hg19ChrY.fa"

### ISSUE THREAD

**Issue by marcovth** [google/deepvariant#390]
Hello ...

On Mac, OSX ... When I run deepvariant with ls -l /input ... the input directory is recognized ...

```
docker run \
  -v "${INPUT_DIR}:/input" \
  -v "${OUTPUT_DIR}:/output" \
  google/deepvariant:"1.0.0" \
  ls -l /input

total 86276
-rw-r--r-- 1 root root     1816 Dec  2 12:55 GRCh37ToHg19.over.chain.gz
-rw-r--r-- 1 root root      162 Dec  2 14:04 Hg19ChrY.dict
-rw-r----- 1 root root 60561044 Dec  2 14:04 Hg19ChrY.fa
-rw-r--r-- 1 root root       22 Dec  2 14:04 Hg19ChrY.fa.fai
-rw-r--r-- 1 root root 13086641 Dec  2 12:57 VK446chrYx19.bam
-rw-r--r-- 1 root root    38296 Dec  2 12:57 VK446chrYx19.bam.bai
drwxr-xr-x 2 root root       64 Dec  2 14:19 VK446chrYx19_dv
-rw-r----- 1 root root 13023881 Dec  2 12:45 VK446chrYx37.bam
-rw-r--r-- 1 root root    37880 Dec  2 12:44 VK446chrYx37.bam.bai
```

However, when I attempt deepvariant run,  I am getting "no such file or directory: --ref=/input/Hg19ChrY.fa"

```
BAMName="VK446chrYx19"
INPUT_DIR="${PWD}/"
OUTPUT_DIR="${PWD}/${BAMName}_dv"

docker run \
  -v "${INPUT_DIR}:/input" \
  -v "${OUTPUT_DIR}:/output" \
  google/deepvariant:"1.0.0" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \ 
  --ref=/input/Hg19ChrY.fa \
  --reads=/input/${BAMName}.bam \
  --output_vcf=/output/${BAMName}.vcf.gz \
  --output_gvcf=/output/${BAMName}.g.vcf.gz \
  --num_shards=24
```
```
  --ref is required.
Pass --helpshort or --helpfull to see help on flags.
zsh: no such file or directory: --ref=/input/Hg19ChrY.fa

```
Thanks for any suggestions.

**Comment by gunjanbaid** [comment]
When I copy pasted your command, it was split up into two commands, with the `--ref` onwards showing up as a separate command. Could you try the following? This should show up as one command and you should no longer see the error.

```
BAMName="VK446chrYx19"
INPUT_DIR="${PWD}/"
OUTPUT_DIR="${PWD}/${BAMName}_dv"

docker run \
  -v "${INPUT_DIR}:/input" \
  -v "${OUTPUT_DIR}:/output" \
  google/deepvariant:"1.0.0" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref=/input/Hg19ChrY.fa \
  --reads=/input/${BAMName}.bam \
  --output_vcf=/output/${BAMName}.vcf.gz \
  --output_gvcf=/output/${BAMName}.g.vcf.gz \
  --num_shards=24
```

**Comment by marcovth** [comment]
Thanks ... that brought me one step further, just for another problem to show up.
 Is this a MacPro / OSX specific problem?

Thanks again.
```
I1202 22:38:15.063603 140422166050560 run_deepvariant.py:364] None
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 369, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 362, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 23 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/Hg19ChrYy.fa" --reads "/input/.bam" --examples "/output/temp/make_examples.tfrecord@24.gz" --gvcf "/output/temp/gvcf.tfrecord@24.gz" --task {}' returned non-zero exit status 252.
```

**Comment by gunjanbaid** [comment]
@marcovth I'm assuming this is resolved, so I'll close this issue. Feel free to reopen if you have any other questions.
