### ISSUE TITLE
Incorrect model in GS bucket

### ISSUE THREAD

**Issue by wharvey31** [google/deepvariant#392]
Hello, when running Deepvariant with the following command: 

```bash
BIN_VERSION="1.0.0"`
INPUT_DIR="${PWD}/data"
OUTPUT_DIR="${PWD}/output"
LOGDIR="${PWD}/log"
N_SHARDS=$( /bin/ls output/ | wc -l )
 
sudo docker run --gpus 1 \
  -v ${HOME}:${HOME} \
  -v "${INPUT_DIR}":"/input" \
  -v "${OUTPUT_DIR}:/output" \
  google/deepvariant:"${BIN_VERSION}-gpu" \
  /opt/deepvariant/bin/call_variants \
  --outfile "${OUTPUT_DIR}/call_variants_output.tfrecord.gz" \
  --examples "${OUTPUT_DIR}/examples.tfrecord@${N_SHARDS}.gz" \
  --checkpoint "gs://deepvariant/models/DeepVariant/1.0.0/DeepVariant-inception_v3-1.0.0+data-pacbio_standard/model.ckpt"
```

the following error occurs:

```
I1203 17:49:21.931325 140389904897792 call_variants.py:335] Shape of input examples: [100, 221, 6]
2020-12-03 17:49:32.284722: W tensorflow/core/platform/cloud/google_auth_provider.cc:178] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Not found: Could not locate the credentials file.". Retrieving token from GCE failed with "Aborted: All 10 retry attempts failed. The last failure: Unavailable: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Couldn't resolve host 'metadata'".
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_a7fwubx_/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 491, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/tmp/Bazel.runfiles_a7fwubx_/runfiles/absl_py/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_a7fwubx_/runfiles/absl_py/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_a7fwubx_/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 481, in main
    use_tpu=FLAGS.use_tpu,
  File "/tmp/Bazel.runfiles_a7fwubx_/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 348, in call_variants
    num_channels_in_checkpoint_model, example_shape[2]))
ValueError: The number of channels in examples and checkpoint should match, but the checkpoint has 8 channels while the examples have 6.
```

Running with the checkpoint for 0.9.0 works with this command. Is the model on the GS bucket correct?

**Comment by gunjanbaid** [comment]
@wharvey31 when running `make_examples`, you'll need to add `--alt_aligned_pileup=diff_channels` for the PacBio model provided in v1.0.0. This will result in tf.Examples with two additional channels, so the shapes should match after that. If you did add this flag but are still seeing errors, please let me know, and I can help troubleshoot further.

I would recommend using the `run_deepvariant` script when possible, as this will set various flags correctly for each model type (Illumina WGS, Illumina WES, PacBio, Hybrid). See [this quickstart doc](https://github.com/google/deepvariant/blob/r1.0/docs/deepvariant-quick-start.md#run-deepvariant-with-one-command) for an example of how to use this script through Docker.

**Comment by wharvey31** [comment]
Got it! Thank you!
