### ISSUE TITLE
make_examples exit status 252

### ISSUE THREAD

**Issue by williamrowell** [google/deepvariant#419]
**Describe the issue:**
Running DeepVariant v1.1.0 on viral amplicon PacBio HiFi data, aligned with pbmm2, using the run_deepvariant script.  Core dump during the make_examples step with exit status 252.

**Setup**
  - Operating system: CentOS Linux release 7.4.1708 (Core), singularity version 3.5.3-1.el7
  - DeepVariant version: 1.1.0
  - Installation method (Docker, built from source, etc.): singularity image pulled from docker://google/deepvariant:1.1.0
  - Type of data: PacBio HiFi amplicons

**Steps to reproduce:**
  - Command:
```bash
singularity exec --bind /scratch:/tmp,/usr/lib/locale/ \
  docker://google/deepvariant:1.1.0 \
    /opt/deepvariant/bin/run_deepvariant \
    --model_type PACBIO \
    --ref ref.fa \
    --reads reads.bam \
    --output_vcf "deepvariant/output.vcf.gz" \
    --num_shards 24 -v 2
```
  - Error trace: (if applicable)
```bash
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref ref.fa --reads reads.bam --examples /tmp/tmp7rsj5zvh/make_examples.tfrecord@24.gz --add_hp_channel --alt_aligned_pileup diff_channels --noparse_sam_aux_fields --norealign_reads --nosort_by_haplotypes --vsc_min_fraction_indels 0.12 --task 2

real    0m35.091s
user    0m1.452s
sys     0m1.237s
I0205 10:26:31.374659 47922265431040 run_deepvariant.py:416] None
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 421, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 414, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '( time seq 0 23 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref ref.fa --reads reads.bam --examples "/tmp/tmp7rsj5zvh/make_examples.tfrecord@24.gz" --add_hp_channel --alt_aligned_pileup "diff_channels" --noparse_sam_aux_fields --norealign_reads --nosort_by_haplotypes --vsc_min_fraction_indels "0.12" --task {} )' returned non-zero exit status 252.
```

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?
- I have limited access to docker in general, and no access to docker on this machine. I've been running v1.0.0 on singularity on different input types (human WGS) regularly without errors.

**Any additional context:**

**Comment by williamrowell** [comment]
With DeepVariant 1.0.0, similar result:

```bash
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref ref.fa --reads reads.bam --examples /tmp/tmpfpe8sndc/make_examples.tfrecord@24.gz --alt_aligned_pileup diff_channels --norealign_reads --vsc_min_fraction_indels 0.12 --task 16

real    0m35.240s
user    0m1.356s
sys     0m1.216s
I0205 11:52:59.059437 47804134787776 run_deepvariant.py:364] None
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 369, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 362, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 23 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref ref.fa --reads reads.bam --examples "/tmp/tmpfpe8sndc/make_examples.tfrecord@24.gz" --alt_aligned_pileup "diff_channels" --norealign_reads --vsc_min_fraction_indels "0.12" --task {}' returned non-zero exit status 252.```

**Comment by MariaNattestad** [comment]
Do you see any other error messages higher up in the logs? The CalledProcessError is just the wrapper, so it doesn't tell us what went wrong inside make_examples.

**Comment by williamrowell** [comment]
That's everything from the first indication of an error in the output.

When I run make_examples directly, it core dumps with no stdout or stderr:
```bash
singularity exec --bind /scratch:/tmp,/usr/lib/locale docker://google/deepvariant:1.1.0 /opt/deepvariant/bin/make_examples --mode calling --ref ref.fa --reads reads.bam --examples make_examples.tfrecord@24.gz --alt_aligned_pileup diff_channels --norealign_reads --vsc_min_fraction_indels 0.12 --task 0
```

**Comment by danielecook** [comment]
@williamrowell try removing the `--task` flag does that change anything?

**Comment by williamrowell** [comment]
Still yields a core dump with no error message.  Going to test this on docker.

**Comment by williamrowell** [comment]
This works with docker:

```bash
docker run -v $PWD:/data google/deepvariant:1.1.0 /opt/deepvariant/bin/make_examples --mode calling --ref /data/ref.fa --reads /data/reads.bam --examples /data/make_examples.tfrecord@24.gz --alt_aligned_pileup diff_channels --norealign_reads --vsc_min_fraction_indels 0.12 --task 0
```

Output:
```bash
2021-02-05 21:03:25.094808: W third_party/nucleus/io/sam_reader.cc:130] Unknown tag pb: in header line, ignoring: @HD   VN:1.9  SO:coordinate   pb:3.0.7
I0205 21:03:25.095168 140318393947904 genomics_reader.py:223] Reading /data/reads.bam with NativeSamReader
I0205 21:03:25.100202 140318393947904 make_examples.py:648] Task 0/24: Preparing inputs
2021-02-05 21:03:25.143855: W third_party/nucleus/io/sam_reader.cc:130] Unknown tag pb: in header line, ignoring: @HD   VN:1.9  SO:coordinate   pb:3.0.7
I0205 21:03:25.144100 140318393947904 genomics_reader.py:223] Reading /data/reads.bam with NativeSamReader
I0205 21:03:25.145697 140318393947904 make_examples.py:648] Task 0/24: Common contigs are ['contig']
I0205 21:03:25.149076 140318393947904 make_examples.py:648] Task 0/24: Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2021-02-05 21:03:25.149922: I third_party/nucleus/io/sam_reader.cc:662] Setting HTS_OPT_BLOCK_SIZE to 134217728
2021-02-05 21:03:25.162121: W third_party/nucleus/io/sam_reader.cc:130] Unknown tag pb: in header line, ignoring: @HD   VN:1.9  SO:coordinate   pb:3.0.7
I0205 21:03:25.162382 140318393947904 genomics_reader.py:223] Reading /data/reads.bam with NativeSamReader
2021-02-05 21:03:25.163749: W third_party/nucleus/io/sam_reader.cc:130] Unknown tag pb: in header line, ignoring: @HD   VN:1.9  SO:coordinate   pb:3.0.7
I0205 21:03:25.163837 140318393947904 genomics_reader.py:223] Reading /data/reads.bam with NativeSamReader
I0205 21:03:25.349464 140318393947904 make_examples.py:648] Task 0/24: Writing examples to /data/make_examples.tfrecord-00000-of-00024.gz
I0205 21:03:25.352185 140318393947904 make_examples.py:648] Task 0/24: Overhead for preparing inputs: 0 seconds
I0205 21:03:25.385783 140318393947904 make_examples.py:648] Task 0/24: 2 candidates (2 examples) [0.03s elapsed]
I0205 21:03:25.394754 140318393947904 make_examples.py:648] Task 0/24: Found 2 candidate variants
I0205 21:03:25.394980 140318393947904 make_examples.py:648] Task 0/24: Created 2 examples```

Looks like something is going on with the singularity invocation then?

**Comment by pichuan** [comment]
Here I'll try to run Singularity on CentOS7 to see if I can reproduce the issue.
 
# Get a CentOS 7 machine
```
gcloud compute instances create "${USER}-centos" \
--scopes "compute-rw,storage-full,cloud-platform" \
--image-family "centos-7" \
--image-project "centos-cloud" \
--machine-type "e2-standard-16" \
--zone "us-west1-b" \
--boot-disk-size "200"  
```

# Install Singularity 3.5
Following steps here https://sylabs.io/guides/3.5/admin-guide/installation.html#installation-on-linux. Then I have:
```
[pichuan@pichuan-centos singularity]$ singularity --version
singularity version 3.5.2
```

# Run Quick Start with Singularity

I downloaded the data from [Quick Start](https://github.com/google/deepvariant/blob/r1.1/docs/deepvariant-quick-start.md)

and then I tried:
```
singularity pull docker://google/deepvariant:1.1.0"

singularity exec --bind /usr/lib/locale/ \
  docker://google/deepvariant:1.1.0 \
    /opt/deepvariant/bin/run_deepvariant \
    --model_type WGS \
   --regions "chr20:10,000,000-10,010,000" \
   --ref="${INPUT_DIR}"/ucsc.hg19.chr20.unittest.fasta \
   --reads="${INPUT_DIR}"/NA12878_S1.chr20.10_10p1mb.bam \
   --output_vcf="${OUTPUT_DIR}"/output.vcf.gz \
   --num_shards 24 -v 2
```

This finished running and output the output.vcf.gz file without an issue.

---

Then, I was searching for "status 252" and found this earlier issue: https://github.com/google/deepvariant/issues/345 . At the end the issue seems to be that the CPU didn't have AVX instructions. Specifically, see @tedyun 's comment: https://github.com/google/deepvariant/issues/345#issuecomment-690820723

@williamrowell Can you check whether your CPU supports AVX instruction?

**Comment by pichuan** [comment]
Hmm, after reading the whole thread again, the AVX explanation didn't quite make sense either because @williamrowell mentioned that running with docker worked..

I don't have a next suggestion yet :-/

**Comment by pgrosu** [comment]
I think the error is simpler than that.  If you grep for these specific flags (i.e. `noparse_sam_aux_fields`, `norealign_reads`, and `nosort_by_haplotypes`) they do not exist in `make_examples` -- though it uses them in the command-line -- and thus it does not know how to process them, which is probably why you are seeing the 252 exit status:

```Bash
$ grep -E 'noparse_sam_aux_fields|norealign_reads|nosort_by_haplotypes' deepvariant/make_examples.py
$
```
Hope it helps,
~p

**Comment by williamrowell** [comment]
> Hmm, after reading the whole thread again, the AVX explanation didn't quite make sense either because @williamrowell mentioned that running with docker worked..
> 
> 
> 
> I don't have a next suggestion yet :-/ 

I had to run docker on a different node, so this is very possible. Will look into this on Monday, as I didn't save which mode I was using and might need helping looking up that information.

**Comment by danielecook** [comment]
@pgrosu the `no` prefix is used to set a flag to FALSE with the flag library we are using. These types of flags are allowed.

---

@williamrowell can you launch a singularity shell and try executing these commands manually?

```shell
singularity shell --bind /scratch:/tmp,/usr/lib/locale/ \
  docker://google/deepvariant:1.1.0
```

Then once you are in the shell, try running one of the commands that failed directly:

```
/opt/deepvariant/bin/make_examples --mode calling --ref ref.fa --reads reads.bam --examples /tmp/tmpfpe8sndc/make_examples.tfrecord@24.gz --alt_aligned_pileup diff_channels --norealign_reads --vsc_min_fraction_indels 0.12 --task 16
```

And let us know what the output looks like.

**Comment by williamrowell** [comment]
> @williamrowell Can you check whether your CPU supports AVX instruction?

This is the likely cause.  No AVX support on this node.  Seems odd that there's a core dump with no error message.

```bash
wrowell@mp0608-sge:~$ lscpu | grep Flags
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 popcnt aes lahf_lm tpr_shadow vnmi flexpriority ept vpid dtherm ida arat
```

**Comment by gunjanbaid** [comment]
@williamrowell I'll close out this issue, but feel free to reopen if you have any other questions. Thanks!
