### ISSUE TITLE
Can`t open .bam file

### ISSUE THREAD

**Issue by belarus1941** [google/deepvariant#420]
I am running Docker image of your software. Pls help to solve the problem.  Here are the codes for running it:

BIN_VERSION="1.1.0"
export OUTPUT_DIR=/home/manager/deepvariant-run/input
sudo docker run -v "${OUTPUT_DIR}":/opt/deepvariant/output dajunluo/deepvariant python run_deepvariant.py \
--model_type=WGS \
--ref=Reference.fasta \
--reads=newtest.bam \
--output_vcf=../output/test_output.vcf.gz \
--output_gvcf=../test_output/output.g.vcf.gz
ls $OUTPUT_DIR

Result:

[sudo] password for manager: 
[E::hts_open_format] Failed to open file newtest.bam
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_a5JjgU/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1235, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_a5JjgU/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1186, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/tmp/Bazel.runfiles_a5JjgU/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 315, in default_options
    with sam.SamReader(flags_obj.reads) as sam_reader:
  File "/tmp/Bazel.runfiles_a5JjgU/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 216, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_a5JjgU/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 255, in _native_reader
    return NativeSamReader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_a5JjgU/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 232, in __init__
    use_original_base_quality_scores=use_original_base_quality_scores)
ValueError: Not found: Could not open newtest.bam

real	0m6.581s
user	0m4.128s
sys	0m1.476s
Traceback (most recent call last):
  File "run_deepvariant.py", line 235, in <module>
    app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "run_deepvariant.py", line 215, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 0 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "Reference.fasta" --reads "newtest.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@1.gz" --gvcf "/tmp/deepvariant_tmp_output/gvcf.tfrecord@1.gz" --task {}' returned non-zero exit status 1

***** Running the command:*****
time seq 0 0 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "Reference.fasta" --reads "newtest.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@1.gz" --gvcf "/tmp/deepvariant_tmp_output/gvcf.tfrecord@1.gz" --task {}

data  newtest.bam  Reference  Reference.fasta  Test  Test.bam

------------------
(program exited with code: 0)
Press return to continue

Thx for helping me

**Comment by danielecook** [comment]
Hello - you can run docker interactively to verify that your files are being mounted correctly.

Try running the following command:

```
BIN_VERSION="1.1.0"
export OUTPUT_DIR=/home/manager/deepvariant-run/input
sudo docker run -it -v "${OUTPUT_DIR}":/opt/deepvariant/output dajunluo/deepvariant /bin/bash
```

From the looks of it you can probably rectify the issue by specifying the full path to `newtest.bam`:

`output/newtest.bam`

**Comment by gunjanbaid** [comment]
@belarus1941 I'm going to close this thread due to inactivity, but feel free to reopen of you have any other questions. Thanks!
