### ISSUE TITLE
Unable to run on local machine

### ISSUE THREAD

**Issue by nilesh-iiita** [google/deepvariant#435]
```(bash
BIN_VERSION="1.1.0"
INPUT_DIR="${PWD}/lecture8_data"

ls -1 ${INPUT_DIR}

OUTPUT_DIR="${PWD}/AO6-output"
mkdir -p "${OUTPUT_DIR}"

docker run \
	-v "${INPUT_DIR}":"/input" \
	-v "${OUTPUT_DIR}":"/output" \
	google/deepvariant:"${BIN_VERSION}" \
	/opt/deepvariant/bin/run_deepvariant \
	--model_type=WGS \
	--ref=/input/ref.fa \
	--reads=/input/sample.bam \
	--output_vcf=/output/OUTPUT_VCF.vfc \
	--output_gvcf=/output/OUTPUT_GVCF.vfc \
	--call_variants_extra_args="use_openvino=true" \
	--num_shards=$(nproc) \
	--logging_dir=/output/logs

```

```{bash}
***** Running the command:*****
( time /opt/deepvariant/bin/call_variants --outfile "/tmp/tmpgv2oy1s_/call_variants_output.tfrecord.gz" --examples "/tmp/tmpgv2oy1s_/make_examples.tfrecord@8.gz" --checkpoint "/opt/models/wgs/model.ckpt" --use_openvino ) 2>&1 | tee /output/logs/call_variants.log

Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_7of_f3z_/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 502, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/tmp/Bazel.runfiles_7of_f3z_/runfiles/absl_py/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_7of_f3z_/runfiles/absl_py/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_7of_f3z_/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 492, in main
    use_tpu=FLAGS.use_tpu,
  File "/tmp/Bazel.runfiles_7of_f3z_/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 323, in call_variants
    first_example = tf_utils.get_one_example_from_examples_path(examples_filename)
  File "/tmp/Bazel.runfiles_7of_f3z_/runfiles/com_google_deepvariant/deepvariant/tf_utils.py", line 205, in get_one_example_from_examples_path
    'Cannot find matching files with the pattern "{}"'.format(source))
ValueError: Cannot find matching files with the pattern "/tmp/tmpgv2oy1s_/make_examples.tfrecord@8.gz"

real	0m2.022s
user	0m2.036s
sys	0m0.413s

***** Running the command:*****
( time /opt/deepvariant/bin/postprocess_variants --ref "/input/ref.fa" --infile "/tmp/tmpgv2oy1s_/call_variants_output.tfrecord.gz" --outfile "/output/OUTPUT_VCF.vfc" --nonvariant_site_tfrecord_path "/tmp/tmpgv2oy1s_/gvcf.tfrecord@8.gz" --gvcf_outfile "/output/OUTPUT_GVCF.vfc" ) 2>&1 | tee /output/logs/postprocess_variants.log

Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_vdgo7zab/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1184, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/tmp/Bazel.runfiles_vdgo7zab/runfiles/absl_py/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_vdgo7zab/runfiles/absl_py/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_vdgo7zab/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1107, in main
    sample_name = get_sample_name()
  File "/tmp/Bazel.runfiles_vdgo7zab/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1053, in get_sample_name
    _, record = get_cvo_paths_and_first_record()
  File "/tmp/Bazel.runfiles_vdgo7zab/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1035, in get_cvo_paths_and_first_record
    ','.join(paths), proto=deepvariant_pb2.CallVariantsOutput)
  File "/tmp/Bazel.runfiles_vdgo7zab/runfiles/com_google_deepvariant/deepvariant/tf_utils.py", line 205, in get_one_example_from_examples_path
    'Cannot find matching files with the pattern "{}"'.format(source))
ValueError: Cannot find matching files with the pattern "/tmp/tmpgv2oy1s_/call_variants_output.tfrecord.gz"
```
Please explain what I am doing wrong.

Thanks

**Comment by gunjanbaid** [comment]
@nilesh-iiita I can't immediately spot anything wrong with your command. I'd recommend looking at the `make_examples.log` file in the output directory to make sure that step completed successfully. You can also set `--intermediate_results_dir=/output` to see if the `make_examples.tfrecord@8.gz` are being generated.

**Comment by gunjanbaid** [comment]
@nilesh-iiita to address this issue, you should not need to realign the reads. Instead, you can pass the `--sample_name=<NAME>` to the `run_deepvariant` command. `<NAME>` can be set to any desired value. It seems like your BAM file is missing a sample name, and when this happens, `make_examples` fails. Adding this flag will ensure that there is a sample name available for `make_examples` to use.
