### ISSUE TITLE
GPU mode error

### ISSUE THREAD

**Issue by aardes** [google/deepvariant#452]
Hi,

I got the following error: 

I'm using Docker version 1.1.0
gpu NVIDIA GeForce RTX 3090

Any suggestion or advice?

Thanks in advance.
Amin

`2021-05-06 16:56:50.765879: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
I0506 16:56:52.008759 140393620989696 call_variants.py:338] Shape of input examples: [100, 221, 6]
2021-05-06 16:56:52.013998: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-06 16:56:52.046181: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2100000000 Hz
2021-05-06 16:56:52.053674: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x47507d0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-05-06 16:56:52.053727: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-05-06 16:56:52.058754: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2021-05-06 16:56:52.188018: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x47b9240 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-05-06 16:56:52.188089: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce RTX 3090, Compute Capability 8.6
2021-05-06 16:56:52.191811: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:20:00.0 name: NVIDIA GeForce RTX 3090 computeCapability: 8.6
coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 23.70GiB deviceMemoryBandwidth: 871.81GiB/s
2021-05-06 16:56:52.191885: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-05-06 16:56:52.195656: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-05-06 16:56:52.199014: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-05-06 16:56:52.199715: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-05-06 16:56:52.203305: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-05-06 16:56:52.205473: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-05-06 16:56:52.211828: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-05-06 16:56:52.216068: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2021-05-06 16:56:52.216108: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-05-06 16:58:21.551842: E tensorflow/core/common_runtime/session.cc:91] Failed to create session: Internal: CUDA runtime implicit initialization on GPU:0 failed. Status: device kernel image is invalid
2021-05-06 16:58:21.551943: E tensorflow/c/c_api.cc:2184] Internal: CUDA runtime implicit initialization on GPU:0 failed. Status: device kernel image is invalid
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_1q2x77gk/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 502, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/tmp/Bazel.runfiles_1q2x77gk/runfiles/absl_py/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_1q2x77gk/runfiles/absl_py/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_1q2x77gk/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 492, in main
    use_tpu=FLAGS.use_tpu,
  File "/tmp/Bazel.runfiles_1q2x77gk/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 393, in call_variants
    with tf.compat.v1.Session(config=config) as sess:
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1586, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 701, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: device kernel image is invalid

real	1m31.942s
user	1m31.967s
sys	0m8.062s
`

**Comment by gunjanbaid** [comment]
Hi @aardes, thanks for reaching out! Are you having problems running TensorFlow on your machine separately from DeepVariant? This seems like an issue with the TensorFlow setup, so I would recommend taking a look at the issues in the TF repo. Here are some that may be relevant: https://github.com/tensorflow/tensorflow/issues/41990, https://github.com/tensorflow/tensorflow/issues/43588

**Comment by gunjanbaid** [comment]
The TF/Cuda/cuDNN versions being used may be incompatible with your GPU. A few questions for you:

* Does the quickstart without GPU run without errors? Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
* What OS are you running on?
* Command to reproduce your issue?
* Are you able to run TF + GPU separately from DeepVariant?
* Do older versions of DeepVariant run without errors? I recommend trying 1.0.0 or 0.10.0. We recommend using the latest version for best results, but this is just for debugging.

**Comment by aardes** [comment]
Dear @gunjanbaid 

thanks for your reply,

I am using the docker version, and the quick start with gpu does not work. 
I have Ubuntu 20.04.
I used the exact same command as quickstart


the issue is the TF and CUDA version which is not matched with the deep variant current ubuntu version. I am using RTX 3090 and this card needs a higher version of TF.

I tried to make a Docker-based on the versions that I need but unfortunately, this failed too,

Would it be possible to have an additional docker for these gpu cards?

I followed the exact libraries mentioned in this link to make the docker
https://www.fatalerrors.org/a/rtx3090-ubuntu-20.04-tensorflow-2.4.0-installation-guide.html

Thanks in advance.

**Comment by aardes** [comment]
any update?

**Comment by gunjanbaid** [comment]
Hi @aardes, my understanding is that cuDNN v8, CUDA 11, TF 2.5, and Python 3.8 will be needed for RTX 3090. Our code is currently not ready to be upgraded to Python 3.8, but this is something we are looking into for future releases.

**Comment by splaisan** [comment]
may 2023, how can we use the docker on a ubuntu machine reporting the warning:
"To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags."
thanks for your help

**Comment by danielecook** [comment]
@splaisan if the quickstart runs and the timing is acceptable to you then you can use the Docker image as is.

Otherwise you can [build from source](https://github.com/google/deepvariant/blob/r1.5/docs/deepvariant-build-test.md)

**Comment by splaisan** [comment]
thanks for your answer,

depends what acceptable is, is analysing 30depth chicken bam for 5h a good time? (I have 50 such genomes to process)

I started building from source but quickly it stopped complaining about my python version.
When I build from source, can I put myself in a virtenv or conda env with no risk of overwriting some system file or will it also put things in the OS path (/usr/...)?
I fear for my OS and do not dare to proceed in that direction.

Finally, conda install does not install, which leaves me with only the docker which is not a perfect match for my cpus.

This is all not really optimal! weird for one of the current leaders in variant calling, I was expecting a more carefully built set of docker(s) to match different cpu configurations.

**Comment by splaisan** [comment]
It is ubuntu 20

**Comment by aardes** [comment]
strange, we had some issues with the CentoOS but nothing with Ubuntu, I assume you have my contact information from the time that I worked at KUL, let m know if you think I could help.
