### ISSUE TITLE
Run demo inside Best practices for multi-sample variant calling with DeepVariant and it report bam file crash.

### ISSUE THREAD

**Issue by zjminglead** [google/deepvariant#455]
**Describe the issue:**
run demo inside Best practices for multi-sample variant calling with DeepVariant failed

**Setup**
  - Operating system: centos 7,
  - DeepVariant version:1.1.0
  - Installation method (Docker, built from source, etc.): Docker
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)

**Steps to reproduce:**
  - Command: docker run     -v "${DIR}":"/data"     google/deepvariant:1.1.0     /opt/deepvariant/bin/run_deepvariant     --model_type=WES     --ref="/data/hs37d5.fa"     --reads="/data/HG002.bam"     --regions="/data/agilent_sureselect_human_all_exon_v5_b37_targets.bed"     --output_vcf="/data/HG002.vcf.gz"     --output_gvcf="/data/HG002.gvcf.gz"     --num_shards=25
  - Error trace: (if applicable): 
 [E::bgzf_read] Read block operation failed with error 2 after 0 of 4 bytes
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_n9h1txbv/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1529, in region_reads
    reads.extend(sam_reader.query(region))
  File "/tmp/Bazel.runfiles_n9h1txbv/runfiles/com_google_deepvariant/third_party/nucleus/io/clif_postproc.py", line 82, in __next__
    record, not_done = self._raw_next()
  File "/tmp/Bazel.runfiles_n9h1txbv/runfiles/com_google_deepvariant/third_party/nucleus/io/clif_postproc.py", line 141, in _raw_next
    not_done = self._cc_iterable.PythonNext(record)
ValueError: Data loss: Failed to parse SAM record

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_n9h1txbv/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 2136, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_n9h1txbv/runfiles/absl_py/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_n9h1txbv/runfiles/absl_py/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_n9h1txbv/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 2126, in main
    make_examples_runner(options)
  File "/tmp/Bazel.runfiles_n9h1txbv/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 2003, in make_examples_runner
    candidates, examples, gvcfs = region_processor.process(region)
  File "/tmp/Bazel.runfiles_n9h1txbv/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1472, in process
    self.in_memory_sam_reader.replace_reads(self.region_reads(region))
  File "/tmp/Bazel.runfiles_n9h1txbv/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1534, in region_reads
    error_message + '\nFailed to parse BAM/CRAM file. '
ValueError: Data loss: Failed to parse SAM record
Failed to parse BAM/CRAM file. This is often caused by:
(1) When using a CRAM file, and setting --use_ref_for_cram to false (which means you want to use the embedded ref instead of a ref file), this error could be because of inability to find the embedded ref file.
(2) Your BAM/CRAM file could be corrupted. Please check its md5.

**Does the quick start test work on your system?**
it work

**Any additional context:**
I also run the mistaken command directly inside docker container, 

[gosadmin@node3 trio]$ docker run -it -v "${DIR}":"/data" google/deepvariant:${VERSION} /bin/bash

root@d2911291b750:/data# ls -alh
total 42G
drwxrwxr-x 2 1000 1000 4.0K May  8 03:39 .
drwxr-xr-x 1 root root   29 May  8 08:21 ..
-rw-rw-r-- 1 1000 1000 6.9M Apr 30 08:19 HG002.bai
-rw-rw-r-- 1 1000 1000 9.7G Apr 30 08:19 HG002.bam
-rw-rw-r-- 1 1000 1000 9.6M Apr 30 09:01 HG002_truth.bed
-rw-rw-r-- 1 1000 1000 147M Apr 30 09:00 HG002_truth.vcf.gz
-rw-rw-r-- 1 1000 1000 1.5M Apr 30 09:00 HG002_truth.vcf.gz.tbi
-rw-rw-r-- 1 1000 1000 6.8M Apr 30 08:33 HG003.bai
-rw-rw-r-- 1 1000 1000 8.4G Apr 30 08:33 HG003.bam
-rw-rw-r-- 1 1000 1000 9.2M Apr 30 09:03 HG003_truth.bed
-rw-rw-r-- 1 1000 1000 129M Apr 30 09:02 HG003_truth.vcf.gz
-rw-rw-r-- 1 1000 1000 1.5M Apr 30 09:02 HG003_truth.vcf.gz.tbi
-rw-rw-r-- 1 1000 1000 7.0M May  7 07:42 HG004.bai
-rw-rw-r-- 1 1000 1000 7.0M Apr 30 08:50 HG004.bai.bak
-rw-rw-r-- 1 1000 1000 9.5G May  7 07:42 HG004.bam
-rw-rw-r-- 1 1000 1000 9.5G Apr 30 08:49 HG004.bam.bak
-rw-rw-r-- 1 1000 1000 9.3M Apr 30 09:05 HG004_truth.bed
-rw-rw-r-- 1 1000 1000 132M Apr 30 09:05 HG004_truth.vcf.gz
-rw-rw-r-- 1 1000 1000 1.5M Apr 30 09:05 HG004_truth.vcf.gz.tbi
-rw-rw-r-- 1 1000 1000 4.6M Apr 30 08:59 agilent_sureselect_human_all_exon_v5_b37_targets.bed
-rw-r--r-- 1 root root  25K May  7 09:40 gvcf.tfrecord-00000-of-00030.gz
-rw-rw-r-- 1 1000 1000 3.0G Apr 30 08:54 hs37d5.fa
-rw-rw-r-- 1 1000 1000 2.8K Apr 30 08:58 hs37d5.fa.fai
-rw-rw-r-- 1 1000 1000 852M May  7 08:11 hs37d5.fa.gz
-rw-r--r-- 1 root root 1.2M May  7 09:40 make_examples.tfrecord-00000-of-00030.gz

root@a8d04f73bc21:/opt/deepvariant/bin# mkdir /tmp/tmpd7h_gv7l

root@a8d04f73bc21:/opt/deepvariant/bin# ./make_examples --mode calling --ref /data/hs37d5.fa --reads /data/HG002.bam --examples /tmp/tmpd7h_gv7l/make_examples.tfrecord@25.gz --gvcf /tmp/tmpd7h_gv7l/gvcf.tfrecord@25.gz -regions /data/agilent_sureselect_human_all_exon_v5_b37_targets.bed --task 8
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
I0508 07:35:12.928799 140432686110464 genomics_reader.py:223] Reading /data/HG002.bam with NativeSamReader
I0508 07:35:12.947474 140432686110464 make_examples.py:648] Task 8/25: Preparing inputs
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
I0508 07:35:12.988700 140432686110464 genomics_reader.py:223] Reading /data/HG002.bam with NativeSamReader
I0508 07:35:13.011471 140432686110464 make_examples.py:648] Task 8/25: Common contigs are ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y', 'MT']
I0508 07:35:13.020151 140432686110464 genomics_reader.py:223] Reading /data/agilent_sureselect_human_all_exon_v5_b37_targets.bed with NativeBedReader
I0508 07:36:27.125286 140432686110464 make_examples.py:648] Task 8/25: Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2021-05-08 07:36:27.125969: I third_party/nucleus/io/sam_reader.cc:662] Setting HTS_OPT_BLOCK_SIZE to 134217728
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
I0508 07:36:27.267024 140432686110464 genomics_reader.py:223] Reading /data/HG002.bam with NativeSamReader
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
I0508 07:36:27.306630 140432686110464 genomics_reader.py:223] Reading /data/HG002.bam with NativeSamReader
I0508 07:36:27.465119 140432686110464 make_examples.py:648] Task 8/25: Writing examples to /tmp/tmpd7h_gv7l/make_examples.tfrecord-00008-of-00025.gz
I0508 07:36:27.465305 140432686110464 make_examples.py:648] Task 8/25: Writing gvcf records to /tmp/tmpd7h_gv7l/gvcf.tfrecord-00008-of-00025.gz
I0508 07:36:27.465700 140432686110464 make_examples.py:648] Task 8/25: Overhead for preparing inputs: 74 seconds
I0508 07:36:27.529915 140432686110464 make_examples.py:648] Task 8/25: 0 candidates (0 examples) [0.06s elapsed]
[E::bgzf_read] Read block operation failed with error 2 after 0 of 4 bytes
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_y3fqbfu4/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1611, in region_reads
    reads.extend(sam_reader.query(region))
  File "/tmp/Bazel.runfiles_y3fqbfu4/runfiles/com_google_deepvariant/third_party/nucleus/io/clif_postproc.py", line 82, in __next__
    record, not_done = self._raw_next()
  File "/tmp/Bazel.runfiles_y3fqbfu4/runfiles/com_google_deepvariant/third_party/nucleus/io/clif_postproc.py", line 141, in _raw_next
    not_done = self._cc_iterable.PythonNext(record)
ValueError: Data loss: Failed to parse SAM record

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_y3fqbfu4/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 2246, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_y3fqbfu4/runfiles/absl_py/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_y3fqbfu4/runfiles/absl_py/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_y3fqbfu4/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 2236, in main
    make_examples_runner(options)
  File "/tmp/Bazel.runfiles_y3fqbfu4/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 2106, in make_examples_runner
    candidates, examples, gvcfs, runtimes = region_processor.process(region)
  File "/tmp/Bazel.runfiles_y3fqbfu4/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1540, in process
    reads = self.region_reads(region)
  File "/tmp/Bazel.runfiles_y3fqbfu4/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1616, in region_reads
    error_message + '\nFailed to parse BAM/CRAM file. '
ValueError: Data loss: Failed to parse SAM record
Failed to parse BAM/CRAM file. This is often caused by:
(1) When using a CRAM file, and setting --use_ref_for_cram to false (which means you want to use the embedded ref instead of a ref file), this error could be because of inability to find the embedded ref file.
(2) Your BAM/CRAM file could be corrupted. Please check its md5.
If you cannot find out the reason why this error is occurring, please report to https://github.com/google/deepvariant/issues
root@a8d04f73bc21:/opt/deepvariant/bin# exit

i also test version 1.0.0, it also return same exception

**Comment by zjminglead** [comment]
Hello @MariaNattestad 
Thanks for reply, it turns out BAM file is truncated, here is my train of thought and step to fix the problem.
1. Because 3 bam(HG002 HG003 HG004) file report same error, and I also tried to redownload bam file, it didn't work  either,  it reports [W::bam_hdr_read] EOF marker is absent. The input is probably truncated and [E::bgzf_read] Read block operation failed with error 2 after 0 of 4 bytes
2. I google [E::bgzf_read] Read block operation failed with error 2 after 0 of 4 bytes, this error mostly occur at samtools usage, I think it maybe bam format error.
3. I convert bam to sam  using samtools , and it reports bam is truncated, Then convert sam back to bam. The size between two bam is different, the  original one about 8GB, but the one I generated is just about 800M
4. I run make_example.py using new bam file,  it also report my bam is error, it may be bai and bam don't match.
5. I try another bam file, https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/ChineseTrio/HG005_NA24631_son/OsloUniversityHospital_Exome/151002_7001448_0359_AC7F6GANXX_Sample_HG005-EEogPU_v02-KIT-Av5_CGCATACA_L008.posiSrt.markDup.bam,
because i familiar with wget, so I use wget to download bam file. And it runs successful.
6. So it maybe aria2c error, I redownload all file using wget and demo is successfully executed.
