### ISSUE TITLE
Retrain model on GCP

### ISSUE THREAD

**Issue by MainTankJerry** [google/deepvariant#46]
Hi,

I have some thoughts on the **creating-pileup-image** part and really want to try it out. Since I don't have the GPU resources, I followed the **Getting Started with GCP** guide.

Q1: How could I retrain my modified forked version of deep variant using gcloud? 

Should I change the last parameter in this command?
`gcloud beta compute instances create "${USER}-deepvariant-quickstart"`

Q2: How could I prepare the trianing data? 

You mentioned running make_examples in training mode to get the data in the **Training DeepVariant models** Guide. How do I "providing the --confident_regions and --truth_variants arguments"? These two terms are too biological for me to understand completely. 

Really appreciated if you can provide some help. 

Thank you

**Comment by rpoplin** [comment]
Hey there,

I was able to get a training started up on GCP today. Here is what I did, hopefully it is helpful:

First I created an instance using the command-line from the doc you pointed to

`gcloud beta compute instances create "${USER}-deepvariant-quickstart"   --scopes "compute-rw,storage-full,cloud-platform"    --image-family ubuntu-1604-lts --image-project ubuntu-os-cloud   --machine-type n1-standard-8    --boot-disk-size=200GB   --zone us-west1-b   --accelerator type=nvidia-tesla-k80,count=1 --maintenance-policy TERMINATE --restart-on-failure`

then I downloaded and built DeepVariant (here you could tweak different build optimization settings, but for now I left it alone):

```
git clone https://github.com/google/deepvariant.git
./build-prereq.sh
./build_release_binaries.sh
```

Then I downloaded and set up some of the variables from the case study doc (https://github.com/google/deepvariant/blob/r0.5/docs/deepvariant-case-study.md)
I had to change N_SHARDS to be 8 since we have 8 cpus on this instance.

Then I ran make_examples in training mode on a small portion of the genome to create some labeled training data. I adapted the command line from the one used in the case study. You would also want to randomly shuffle the data but I didn't do that here.

```
( time seq 0 $((N_SHARDS-1)) | \
  parallel --halt 2 --joblog "${LOG_DIR}/log" --res "${LOG_DIR}" \
    python "${BIN_DIR}"/make_examples.zip \
      --mode training \
      --ref "${REF}" \
      --reads "${BAM}" \
      --confident_regions "${TRUTH_BED}" \
      --truth_variants "${TRUTH_VCF}" \
      --examples "${EXAMPLES}" \
      --regions "20:10,000,000-12,000,000" \
      --task {}
) >"${LOG_DIR}/make_examples.log" 2>&1
```

The  --confident_regions, and --truth_variants are how you supply the truth data to the program in order to create the labels.

Then I created a data.pbtxt config file that is described in the training doc (https://github.com/google/deepvariant/blob/r0.5/docs/deepvariant-model-training.md)

It looks like:
```
> cat output/data.pbtxt 
name: "my-training-dataset"
tfrecord_path: "/home/rpoplin/case-study/output/HG002.examples.tfrecord-?????-of-00008.gz"
num_examples: 150
```

Then I launched a training job with model_train.zip:

```
python "${BIN_DIR}"/model_train.zip \
--dataset_config_pbtxt output/data.pbtxt \
--start_from_checkpoint "" \
--batch_size 16 \
--alsologtostderr
```


This is quick overview, but definitely let me know if you have any questions!

**Comment by MainTankJerry** [comment]
Thank you! After the training is running on Google Cloud, will it stop on its own? Do you remember how long it took you to run it based on this setting? Where would the result model be stored?

**Comment by MainTankJerry** [comment]
we found the default model saving path is "/tmp/deepvariant" https://github.com/google/deepvariant/blob/r0.5/deepvariant/model_train.py#L67 and default numbers of trainig batches is unlimited https://github.com/google/deepvariant/blob/r0.5/deepvariant/call_variants.py#L85 . However, we would like to try to train the model with a different pretrained model, and we found that for Inception V3, it uses TensorFlow Slim's model, with a parameter of pretrained_model_path https://github.com/google/deepvariant/blob/r0.5/deepvariant/modeling.py#L353 . We don't quite get where this path comes from. It doesn't seem to exist in the Slim repo. Can you please point us to where to find this set of pretrained weights?

```
WARNING: Logging before flag parsing goes to stderr.
I0209 02:46:47.705486 139970286499584 htslib_gcp_oauth.py:82] GCP credentials found; will be able to access non-public gs:// URIs from htslib
2018-02-09 02:46:50.318843: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
I0209 02:46:51.237144 139970286499584 call_variants.py:325] Initializing model from /root/case-study/output/model.ckpt
2018-02-09 02:46:51.248949: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /root/case-study/output/model.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_lnD8hJ/runfiles/genomics/deepvariant/call_variants.py", line 387, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/tmp/Bazel.runfiles_lnD8hJ/runfiles/genomics/deepvariant/call_variants.py", line 378, in main
    batch_size=FLAGS.batch_size)
  File "/tmp/Bazel.runfiles_lnD8hJ/runfiles/genomics/deepvariant/call_variants.py", line 326, in call_variants
    model.initialize_from_checkpoint(checkpoint_path, 3, False)(sess)
  File "/tmp/Bazel.runfiles_lnD8hJ/runfiles/genomics/deepvariant/modeling.py", line 298, in initialize_from_checkpoint
    [self.n_classes_model_variable])
  File "/tmp/Bazel.runfiles_lnD8hJ/runfiles/genomics/deepvariant/tf_utils.py", line 264, in model_shapes
    reader = tf.train.NewCheckpointReader(checkpoint_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 150, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepatterFurthermore, it seems that automatically saved checkpoints can't be read with `call_variants.zip` (We just used the default command in the case study)
```

```
root@qiuz-deepvariant-quickstart:~/case-study/output/logs# cat call_variants.log
WARNING: Logging before flag parsing goes to stderr.
I0209 02:46:47.705486 139970286499584 htslib_gcp_oauth.py:82] GCP credentials found; will be able to access non-public gs:// URIs from htslib
2018-02-09 02:46:50.318843: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
I0209 02:46:51.237144 139970286499584 call_variants.py:325] Initializing model from /root/case-study/output/model.ckpt
2018-02-09 02:46:51.248949: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /root/case-study/output/model.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_lnD8hJ/runfiles/genomics/deepvariant/call_variants.py", line 387, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/tmp/Bazel.runfiles_lnD8hJ/runfiles/genomics/deepvariant/call_variants.py", line 378, in main
    batch_size=FLAGS.batch_size)
  File "/tmp/Bazel.runfiles_lnD8hJ/runfiles/genomics/deepvariant/call_variants.py", line 326, in call_variants
    model.initialize_from_checkpoint(checkpoint_path, 3, False)(sess)
File "/tmp/Bazel.runfiles_lnD8hJ/runfiles/genomics/deepvariant/modeling.py", line 298, in initialize_from_checkpoint
    [self.n_classes_model_variable])
  File "/tmp/Bazel.runfiles_lnD8hJ/runfiles/genomics/deepvariant/tf_utils.py", line 264, in model_shapes
    reader = tf.train.NewCheckpointReader(checkpoint_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 150, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file /root/case-study/output/model.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
 
real        0m5.561s
user       0m6.116s
sys          0m0.810s
```

**Comment by MainTankJerry** [comment]
Also, when we tried to run `call_varaints.zip` with a training checkpoint we just found earlier, it failed with this exception below. We are not entirely sure what we did wrong. We just used your command to train and the command in the case study to run the model to produce variants
```
root@qiuz-deepvariant-quickstart:~/case-study/output/logs# cat call_variants.log
WARNING: Logging before flag parsing goes to stderr.
I0209 02:46:47.705486 139970286499584 htslib_gcp_oauth.py:82] GCP credentials found; will be able to access non-public gs:// URIs from htslib
2018-02-09 02:46:50.318843: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
I0209 02:46:51.237144 139970286499584 call_variants.py:325] Initializing model from /root/case-study/output/model.ckpt
2018-02-09 02:46:51.248949: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /root/case-study/output/model.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_lnD8hJ/runfiles/genomics/deepvariant/call_variants.py", line 387, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/tmp/Bazel.runfiles_lnD8hJ/runfiles/genomics/deepvariant/call_variants.py", line 378, in main
    batch_size=FLAGS.batch_size)
  File "/tmp/Bazel.runfiles_lnD8hJ/runfiles/genomics/deepvariant/call_variants.py", line 326, in call_variants
    model.initialize_from_checkpoint(checkpoint_path, 3, False)(sess)
File "/tmp/Bazel.runfiles_lnD8hJ/runfiles/genomics/deepvariant/modeling.py", line 298, in initialize_from_checkpoint
    [self.n_classes_model_variable])
  File "/tmp/Bazel.runfiles_lnD8hJ/runfiles/genomics/deepvariant/tf_utils.py", line 264, in model_shapes
    reader = tf.train.NewCheckpointReader(checkpoint_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 150, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file /root/case-study/output/model.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
 
real        0m5.561s
user       0m6.116s
sys          0m0.810s
```

**Comment by rpoplin** [comment]
Regarding the pretrained inception model: I was able to find an example that was pretrained on ImageNet classes (it is likely the same or at least very similar to the file that is mentioned in the code): https://github.com/tensorflow/models/tree/master/research/slim [about halfway down that page at Pre-Trained Models]

On the Cloud instance I download and unpack the checkpoint:
wget http://download.tensorflow.org/models/inception_v3_2016_08_28.tar.gz
tar -xzvf inception_v3_2016_08_28.tar.gz

then in the training command you can add
" --start_from_checkpoint inception_v3.ckpt"

After the tf_logging messages you'll see

model_train.py:160] Initializing model from checkpoint at inception_v3.ckpt
modeling.py:314] Checkpoint was trained against 1001 classes while our dataset is using 3, enabling fine-tuning

to let you know that it loaded the pre-trained network.

I'll look into your checkpoint loading issue next.

**Comment by depristo** [comment]
It's also possible to start training from our released checkpoints, if you want, so you can either start from scratch, start from imagenet, or start from a DeepVariant released model.

**Comment by rpoplin** [comment]
Regarding loading the checkpoint, it worked for me. I wonder if it is because of the gotcha of the filenames. The --checkpoint argument to call_variants is actually supposed to be the model prefix name, not an actual file name.

For example I just tried 

`( time python bin/call_variants.zip     --outfile "${CALL_VARIANTS_OUTPUT}"     --examples ~/case-study/output/HG002.examples.tfrecord-00004-of-00008.gz     --checkpoint /tmp/deepvariant/model.ckpt-726     --batch_size 32; ) >"${LOG_DIR}/call_variants.log" 2>&1`

and it ran as expected. Let me know if that works for you.

Another thing to keep in mind is that if you run again without specifying the 'train_dir' arg then it will attempt to pick up where it left off.

**Comment by MainTankJerry** [comment]
Thank you.
