### ISSUE TITLE
Fresh AWS install failing on quick start data

### ISSUE THREAD

**Issue by mvelinder** [google/deepvariant#462]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.1/docs/FAQ.md**:
Yes

**Describe the issue:**
Launching an Ubuntu 20.04 server t2 micro EC2 on AWS, installed docker using snap, downloaded data from quickstart guide verbatim https://github.com/google/deepvariant/blob/r1.0/docs/deepvariant-quick-start.md

**Setup**
  - Operating system: Ubuntu 20.04 server t2 micro EC2 on AWS
  - DeepVariant version: BIN_VERSION="1.1.0"
  - Installation method (Docker, built from source, etc.): Docker
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?) Quick start data

**Steps to reproduce:**
  - Command:
```
mkdir -p output
mkdir -p output/intermediate_results_dir

BIN_VERSION="1.1.0"

sudo docker run \
  -v "${PWD}/input":"/input" \
  -v "${PWD}/output":"/output" \
  -v "${PWD}/reference":"/reference" \
  google/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type WES \
  --ref /reference/GRCh38_no_alt_analysis_set.fasta \
  --reads /input/HG003.novaseq.wes_idt.100x.dedup.bam \
  --regions /input/idt_capture_novogene.grch38.bed \
  --output_vcf /output/HG003.output.vcf.gz \
  --output_gvcf /output/HG003.output.g.vcf.gz \
  --num_shards $(nproc) \
  --intermediate_results_dir /output/intermediate_results_dir
```

  - Error trace: (if applicable)
```
Unable to find image 'google/deepvariant:1.1.0' locally
1.1.0: Pulling from google/deepvariant
be8ec4e48d7f: Pull complete 
33b8b485aff0: Pull complete 
d887158cc58c: Pull complete 
05895bb28c18: Pull complete 
35be0878dcf6: Pull complete 
03fb656082b2: Pull complete 
1d3e393af6d8: Pull complete 
9663085972fa: Pull complete 
10ac03989960: Pull complete 
401f11974a9b: Pull complete 
67f12673f7e4: Pull complete 
99116330e4f4: Pull complete 
6fbbce8e3587: Pull complete 
c223e83ce2e3: Pull complete 
c02ebb3220a1: Pull complete 
0c7a427ce17a: Pull complete 
ec9cd66333fe: Pull complete 
9d57046ae5b9: Pull complete 
0f5478ac499a: Pull complete 
b07098b67a6d: Pull complete 
0accf0f55269: Pull complete 
ccc95462eb8f: Pull complete 
f1416983139e: Pull complete 
2242c582e0cc: Pull complete 
8f749be1be0b: Pull complete 
03fdf02906f9: Pull complete 
ea2763a10d98: Pull complete 
fff529645086: Pull complete 
42ad15be12fa: Pull complete 
82830610edc8: Pull complete 
d1a85d710a45: Pull complete 
a7463a89d05f: Pull complete 
966acfe9e7ff: Pull complete 
987808dd3c93: Pull complete 
079d9da9d9ee: Pull complete 
875aa906c231: Pull complete 
9463688d586c: Pull complete 
2943d0ab0b4f: Pull complete 
7a91c30c18a7: Pull complete 
66996f762384: Pull complete 
90237953ba0a: Pull complete 
Digest: sha256:b269b5b547bd8aa46f104f7bbdffaf6cdcf1df0143cfe85aa7f5a68767fa49bc
Status: Downloaded newer image for google/deepvariant:1.1.0
I0611 15:20:51.532788 140688071014144 run_deepvariant.py:317] Re-using the directory for intermediate results in /output/intermediate_results_dir

***** Intermediate results will be written to /output/intermediate_results_dir in docker. ****


***** Running the command:*****
( time seq 0 0 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/reference/GRCh38_no_alt_analysis_set.fasta" --reads "/input/HG003.novaseq.wes_idt.100x.dedup.bam" --examples "/output/intermediate_results_dir/make_examples.tfrecord@1.gz" --gvcf "/output/intermediate_results_dir/gvcf.tfrecord@1.gz" --regions "/input/idt_capture_novogene.grch38.bed" --task {} )

I0611 15:20:58.470178 139788927993600 genomics_reader.py:223] Reading /input/HG003.novaseq.wes_idt.100x.dedup.bam with NativeSamReader
I0611 15:20:58.487128 139788927993600 make_examples.py:648] Preparing inputs
I0611 15:20:58.513385 139788927993600 genomics_reader.py:223] Reading /input/HG003.novaseq.wes_idt.100x.dedup.bam with NativeSamReader
I0611 15:20:58.537174 139788927993600 make_examples.py:648] Common contigs are ['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20', 'chr21', 'chr22', 'chrX', 'chrY', 'chrM']
I0611 15:20:58.552222 139788927993600 genomics_reader.py:223] Reading /input/idt_capture_novogene.grch38.bed with NativeBedReader
I0611 15:22:06.001182 139788927993600 make_examples.py:648] Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2021-06-11 15:22:06.016750: I third_party/nucleus/io/sam_reader.cc:662] Setting HTS_OPT_BLOCK_SIZE to 134217728
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /reference/GRCh38_no_alt_analysis_set.fasta --reads /input/HG003.novaseq.wes_idt.100x.dedup.bam --examples /output/intermediate_results_dir/make_examples.tfrecord@1.gz --gvcf /output/intermediate_results_dir/gvcf.tfrecord@1.gz --regions /input/idt_capture_novogene.grch38.bed --task 0

real	1m16.629s
user	1m9.338s
sys	0m1.008s
I0611 15:22:08.176606 140688071014144 run_deepvariant.py:416] None
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 421, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 414, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '( time seq 0 0 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/reference/GRCh38_no_alt_analysis_set.fasta" --reads "/input/HG003.novaseq.wes_idt.100x.dedup.bam" --examples "/output/intermediate_results_dir/make_examples.tfrecord@1.gz" --gvcf "/output/intermediate_results_dir/gvcf.tfrecord@1.gz" --regions "/input/idt_capture_novogene.grch38.bed" --task {} )' returned non-zero exit status 247.
```

**Does the quick start test work on your system?** No
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start? Yes

**Any additional context:**

**Comment by pichuan** [comment]
Hello @mvelinder 
Were you able to resolve the issue? Can you share a bit more context on what went wrong?
Thanks!

**Comment by mvelinder** [comment]
I was not able to get this working @pichuan , if you could provide any guidance that'd still be helpful for me. Thanks!

**Comment by pichuan** [comment]
@mvelinder I noticed that you're running on t2 micro. And it seems like you're not running the Quick Start, but actually running on our WES BAM file.

Given that t2 micro only has 1G RAM, make_examples likely ran out of memory. 
DeepVariant's error message when running OOM can be a bit confusing. This is something we still hope to improve.

Can you try a machine with more RAM? If you're just running a small example like the Quick Start:
https://github.com/google/deepvariant/blob/r1.1/docs/deepvariant-quick-start.md

I've confirmed that **t2.medium** worked for just the [Quick Start](https://github.com/google/deepvariant/blob/r1.1/docs/deepvariant-quick-start.md).

After copying all the data, I ran:
```
time sudo docker run \
  -v "${INPUT_DIR}":"/input" \
  -v "${OUTPUT_DIR}":"/output" \
  google/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref=/input/ucsc.hg19.chr20.unittest.fasta \
  --reads=/input/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf=/output/output.vcf.gz \
  --output_gvcf=/output/output.g.vcf.gz \
  --intermediate_results_dir /output/intermediate_results_dir \
  --num_shards=1
```
In my test run on a **t2.medium** instance, this took: 
```
real0m23.790s
user0m0.032s
sys0m0.028s
```
to complete.

**Comment by mvelinder** [comment]
With a brand new t2.medium instance per the quickstart guide and your command I get:

```
docker: invalid reference format.
See 'docker run --help'.

real	0m0.046s
user	0m0.023s
sys	0m0.028s
```

**Comment by pichuan** [comment]
@mvelinder I think sometimes this could happen when the environment variables were not manually set right.

For example, can you do:
```
echo $BIN_VERSION
```
(and all the others that you might have in your command) to make sure they're all set as expected?

**Comment by mvelinder** [comment]
Including my `$BIN_VERSION` `INPUT_DIR` and `OUTPUT_DIR` in a run script fixed this and I was able to run the test data on a t2.medium. Thanks! 

```
BIN_VERSION="1.1.0"
INPUT_DIR="${PWD}/quickstart-testdata"
OUTPUT_DIR="${PWD}/quickstart-output"

time sudo docker run \
	-v "${INPUT_DIR}":"/input" \
	-v "${OUTPUT_DIR}":"/output" \
	google/deepvariant:"${BIN_VERSION}" \
	/opt/deepvariant/bin/run_deepvariant \
	--model_type=WGS \
	--ref=/input/ucsc.hg19.chr20.unittest.fasta \
	--reads=/input/NA12878_S1.chr20.10_10p1mb.bam \
	--regions "chr20:10,000,000-10,010,000" \
	--output_vcf=/output/output.vcf.gz \
	--output_gvcf=/output/output.g.vcf.gz \
	--intermediate_results_dir /output/intermediate_results_dir \
	--num_shards=1
```

**Comment by pichuan** [comment]
Glad that it's working @mvelinder .
For larger data, you'll likely want to use more resources. You can see this doc for more examples for different machine types and costs (estimated on GCP).
