### ISSUE TITLE
parallel: job failed:

### ISSUE THREAD

**Issue by Asppagh** [google/deepvariant#465]
Does anyone know what caused the below error?
I use deepvariant image on singularity and running it on a cluster but this error happens on many machines.
I don't know what causes this error.

I0624 02:14:00.095050 47429297437696 run_deepvariant.py:313] Creating a directory for intermediate results in /output/intermediate_results_dir
I0624 02:14:01.826225 47429297437696 run_deepvariant.py:405] Creating a directory for logs in /output/logs
I0624 02:14:01.954994 47429297437696 run_deepvariant.py:227] Creating a make_examples runtime by region directory in /output/logs/make_examples_runtime_by_region

***** Intermediate results will be written to /output/intermediate_results_dir in docker. ****

***** Running the command:*****
( time seq 0 0 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa" --reads "/input/S-001737188.markdup.bam" --examples "/output/intermediate_results_dir/make_examples.tfrecord@1.gz" --runtime_by_region "/output/logs/make_examples_runtime_by_region/make_examples_runtime@1.tsv" --gvcf "/output/intermediate_results_dir/gvcf.tfrecord@1.gz" --task {} ) 2>&1 | tee /output/logs/make_examples.log

parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /ref/GRCh38_full_analysis_set_plus_decoy_hla.fa --reads /input/S-001737188.markdup.bam --examples /output/intermediate_results_dir/make_examples.tfrecord@1.gz --runtime_by_region /output/logs/make_examples_runtime_by_region/make_examples_runtime@1.tsv --gvcf /output/intermediate_results_dir/gvcf.tfrecord@1.gz --task 0

real	14m5.230s
user	0m1.869s
sys	0m3.689s

***** Running the command:*****
( time /opt/deepvariant/bin/call_variants --outfile "/output/intermediate_results_dir/call_variants_output.tfrecord.gz" --examples "/output/intermediate_results_dir/make_examples.tfrecord@1.gz" --checkpoint "/opt/models/wgs/model.ckpt" --use_openvino ) 2>&1 | tee /output/logs/call_variants.log

real	6m35.370s
user	0m1.385s
sys	0m1.152s

***** Running the command:*****
( time /opt/deepvariant/bin/postprocess_variants --ref "/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa" --infile "/output/intermediate_results_dir/call_variants_output.tfrecord.gz" --outfile "/output/S-001737188.vcf.gz" --nonvariant_site_tfrecord_path "/output/intermediate_results_dir/gvcf.tfrecord@1.gz" --gvcf_outfile "/output/S-001737188.g.vcf.gz" ) 2>&1 | tee /output/logs/postprocess_variants.log

real	10m14.442s
user	0m1.472s
sys	0m1.164s

**Comment by pichuan** [comment]
Hi @Asppagh 
From the error above it wasn't very informative.

This seems like it failed on the make_examples step already. We should have just stopped there, instead of proceeding into call_variants and next steps. --> This is now fixed in internal code, and will be fixed in the next release.

Another question is -- why did the failed make_examples not produce any useful logs?

This one is a bit less clear to me. 

With the same setting, instead of using /opt/deepvariant/bin/run_deepvariant (which is a convenient script that combines 3 steps), can you try directly running with 

`/opt/deepvariant/bin/make_examples --mode calling --ref "/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa" --reads "/input/S-001737188.markdup.bam" --examples "/output/intermediate_results_dir/make_examples.tfrecord.gz" --runtime_by_region "/output/logs/make_examples_runtime_by_region/make_examples_runtime.tsv" --gvcf "/output/intermediate_results_dir/gvcf.tfrecord.gz"`

This should allow you to just run 1 make_examples, without using GNU parallel as well. Hopefully whatever error messages will be more clear here.
Thanks!

**Comment by Asppagh** [comment]
Hi @pichuan 
I just used the command you suggested but I am not getting  any log.
could you please let me know how to set /opt/deepvariant/bin/make_examples parameter to get the errors?
Thanks,

**Comment by pichuan** [comment]
@Asppagh Usually when make_examples has an error and crashes, it should have the stack trace at the end. (I've seen them in the errors I've seen before)
In this case it seems like we're trying to find out why it didn't. 
I think it's possible to change the verbose level. I'll need to look into that later. I'm traveling so it'll take a while for me to get back to this. Adding @danielecook in case you have a chance to take a look.

**Comment by pichuan** [comment]
Here is an attempt to deliberately mess up the BAM file in the case study, so I can get the make_examples step to fail, and observe the logs.
However, in my test runs below, I'm seeing useful error messages. @Asppagh if you have suggestions on how I can reproduce an error type like yours. It'll be really useful! Otherwise I'm currently stuck on how to help you debug this.

I'll share my test runs below so you can take a look:

---

I followed steps in:
https://github.com/google/deepvariant/blob/r1.1/docs/deepvariant-quick-start.md
to get data.

## I deliberately messed up the BAM, and ran `run_deepvariant`
```
ls -l quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam
-rw-rw-r-- 1 pichuan pichuan 3925783 Nov 27  2017 quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam
```
```
head -c 3000000 quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam > quickstart-testdata/NA12878_S1.chr20.10_10p1mb.truncated.bam
cp quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam.bai quickstart-testdata/NA12878_S1.chr20.10_10p1mb.truncated.bam.bai
```

I ran:
```
sudo docker run \
  -v "${INPUT_DIR}":"/input" \
  -v "${OUTPUT_DIR}":"/output" \
  google/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref=/input/ucsc.hg19.chr20.unittest.fasta \
  --reads=/input/NA12878_S1.chr20.10_10p1mb.truncated.bam \
  --output_vcf=/output/output.vcf.gz \
  --output_gvcf=/output/output.g.vcf.gz \
  --num_shards=1
```

for the sake of completeness, I'll paste the log below up to the stack trace in make_examples:

```
I0629 23:08:46.468520 139667868600064 run_deepvariant.py:317] Re-using the directory for intermediate results in /tmp/tmpj5fx0phm

***** Intermediate results will be written to /tmp/tmpj5fx0phm in docker. ****


***** Running the command:*****
( time seq 0 0 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/ucsc.hg19.chr20.unittest.fasta" --reads "/input/NA12878_S1.chr20.10_10p1mb.truncated.bam" --examples "/tmp/tmpj5fx0phm/make_examples.tfrecord@1.gz" --gvcf "/tmp/tmpj5fx0phm/gvcf.tfrecord@1.gz" --task {} )

[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
[W::hts_idx_load3] The index file is older than the data file: /input/NA12878_S1.chr20.10_10p1mb.truncated.bam.bai
I0629 23:08:49.655763 139654431344384 genomics_reader.py:223] Reading /input/NA12878_S1.chr20.10_10p1mb.truncated.bam with NativeSamReader
I0629 23:08:49.663154 139654431344384 make_examples.py:648] Preparing inputs
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
[W::hts_idx_load3] The index file is older than the data file: /input/NA12878_S1.chr20.10_10p1mb.truncated.bam.bai
I0629 23:08:49.663682 139654431344384 genomics_reader.py:223] Reading /input/NA12878_S1.chr20.10_10p1mb.truncated.bam with NativeSamReader
I0629 23:08:49.664449 139654431344384 make_examples.py:648] Common contigs are ['chr20']
I0629 23:08:49.855972 139654431344384 make_examples.py:648] Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2021-06-29 23:08:49.856404: I third_party/nucleus/io/sam_reader.cc:662] Setting HTS_OPT_BLOCK_SIZE to 134217728
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
[W::hts_idx_load3] The index file is older than the data file: /input/NA12878_S1.chr20.10_10p1mb.truncated.bam.bai
I0629 23:08:49.858718 139654431344384 genomics_reader.py:223] Reading /input/NA12878_S1.chr20.10_10p1mb.truncated.bam with NativeSamReader
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
[W::hts_idx_load3] The index file is older than the data file: /input/NA12878_S1.chr20.10_10p1mb.truncated.bam.bai
I0629 23:08:49.859084 139654431344384 genomics_reader.py:223] Reading /input/NA12878_S1.chr20.10_10p1mb.truncated.bam with NativeSamReader
I0629 23:08:50.047413 139654431344384 make_examples.py:648] Writing examples to /tmp/tmpj5fx0phm/make_examples.tfrecord-00000-of-00001.gz
I0629 23:08:50.047621 139654431344384 make_examples.py:648] Writing gvcf records to /tmp/tmpj5fx0phm/gvcf.tfrecord-00000-of-00001.gz
I0629 23:08:50.048107 139654431344384 make_examples.py:648] Overhead for preparing inputs: 0 seconds
I0629 23:08:50.064639 139654431344384 make_examples.py:648] 0 candidates (0 examples) [0.02s elapsed]
I0629 23:10:07.477154 139654431344384 make_examples.py:648] 102 candidates (110 examples) [77.41s elapsed]
I0629 23:10:11.740366 139654431344384 make_examples.py:648] 202 candidates (223 examples) [4.26s elapsed]
[E::bgzf_read] Read block operation failed with error 4 after 0 of 4 bytes
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_jqt5759c/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1611, in region_reads
    reads.extend(sam_reader.query(region))
  File "/tmp/Bazel.runfiles_jqt5759c/runfiles/com_google_deepvariant/third_party/nucleus/io/clif_postproc.py", line 82, in __next__
    record, not_done = self._raw_next()
  File "/tmp/Bazel.runfiles_jqt5759c/runfiles/com_google_deepvariant/third_party/nucleus/io/clif_postproc.py", line 141, in _raw_next
    not_done = self._cc_iterable.PythonNext(record)
ValueError: Data loss: Failed to parse SAM record

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_jqt5759c/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 2246, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_jqt5759c/runfiles/absl_py/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_jqt5759c/runfiles/absl_py/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_jqt5759c/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 2236, in main
    make_examples_runner(options)
  File "/tmp/Bazel.runfiles_jqt5759c/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 2106, in make_examples_runner
    candidates, examples, gvcfs, runtimes = region_processor.process(region)
  File "/tmp/Bazel.runfiles_jqt5759c/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1540, in process
    reads = self.region_reads(region)
  File "/tmp/Bazel.runfiles_jqt5759c/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1616, in region_reads
    error_message + '\nFailed to parse BAM/CRAM file. '
ValueError: Data loss: Failed to parse SAM record
Failed to parse BAM/CRAM file. This is often caused by:
(1) When using a CRAM file, and setting --use_ref_for_cram to false (which means you want to use the embedded ref instead of a ref file), this error could be because of inability to find the embedded ref file.
(2) Your BAM/CRAM file could be corrupted. Please check its md5.
If you cannot find out the reason why this error is occurring, please report to https://github.com/google/deepvariant/issues
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /input/ucsc.hg19.chr20.unittest.fasta --reads /input/NA12878_S1.chr20.10_10p1mb.truncated.bam --examples /tmp/tmpj5fx0phm/make_examples.tfrecord@1.gz --gvcf /tmp/tmpj5fx0phm/gvcf.tfrecord@1.gz --task 0

real    1m25.608s
user    1m28.020s
sys     0m5.611s
I0629 23:10:12.080424 139667868600064 run_deepvariant.py:416] None
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 421, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 414, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '( time seq 0 0 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/ucsc.hg19.chr20.unittest.fasta" --reads "/input/NA12878_S1.chr20.10_10p1mb.truncated.bam" --examples "/tmp/tmpj5fx0phm/make_examples.tfrecord@1.gz" --gvcf "/tmp/tmpj5fx0phm/gvcf.tfrecord@1.gz" --task {} )' returned non-zero exit status 1.
```

## With the same input, I tried running just the make_examples step:

```
sudo docker run \
  -v "${INPUT_DIR}":"/input" \
  -v "${OUTPUT_DIR}":"/output" \
  google/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/make_examples \
  --mode calling \
  --ref "/input/ucsc.hg19.chr20.unittest.fasta" \
  --reads "/input/NA12878_S1.chr20.10_10p1mb.truncated.bam" \
  --examples "/output/make_examples.tfrecord.gz" \
  --gvcf "/output/gvcf.tfrecord.gz"
```

For the sake of completeness, here is my output:
```
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
[W::hts_idx_load3] The index file is older than the data file: /input/NA12878_S1.chr20.10_10p1mb.truncated.bam.bai
I0629 23:22:14.429270 140118199654144 genomics_reader.py:223] Reading /input/NA12878_S1.chr20.10_10p1mb.truncated.bam with NativeSamReader
I0629 23:22:14.436468 140118199654144 make_examples.py:648] Preparing inputs
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
[W::hts_idx_load3] The index file is older than the data file: /input/NA12878_S1.chr20.10_10p1mb.truncated.bam.bai
I0629 23:22:14.437053 140118199654144 genomics_reader.py:223] Reading /input/NA12878_S1.chr20.10_10p1mb.truncated.bam with NativeSamReader
I0629 23:22:14.437869 140118199654144 make_examples.py:648] Common contigs are ['chr20']
I0629 23:22:14.600047 140118199654144 make_examples.py:648] Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2021-06-29 23:22:14.600408: I third_party/nucleus/io/sam_reader.cc:662] Setting HTS_OPT_BLOCK_SIZE to 134217728
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
[W::hts_idx_load3] The index file is older than the data file: /input/NA12878_S1.chr20.10_10p1mb.truncated.bam.bai
I0629 23:22:14.602724 140118199654144 genomics_reader.py:223] Reading /input/NA12878_S1.chr20.10_10p1mb.truncated.bam with NativeSamReader
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
[W::hts_idx_load3] The index file is older than the data file: /input/NA12878_S1.chr20.10_10p1mb.truncated.bam.bai
I0629 23:22:14.603199 140118199654144 genomics_reader.py:223] Reading /input/NA12878_S1.chr20.10_10p1mb.truncated.bam with NativeSamReader
I0629 23:22:14.780351 140118199654144 make_examples.py:648] Writing examples to /output/make_examples.tfrecord.gz
I0629 23:22:14.780567 140118199654144 make_examples.py:648] Writing gvcf records to /output/gvcf.tfrecord.gz
I0629 23:22:14.781277 140118199654144 make_examples.py:648] Overhead for preparing inputs: 0 seconds
I0629 23:22:14.797983 140118199654144 make_examples.py:648] 0 candidates (0 examples) [0.02s elapsed]
I0629 23:23:33.302437 140118199654144 make_examples.py:648] 102 candidates (110 examples) [78.50s elapsed]
I0629 23:23:37.605793 140118199654144 make_examples.py:648] 202 candidates (223 examples) [4.30s elapsed]
[E::bgzf_read] Read block operation failed with error 4 after 0 of 4 bytes
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_im0i33s_/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1611, in region_reads
    reads.extend(sam_reader.query(region))
  File "/tmp/Bazel.runfiles_im0i33s_/runfiles/com_google_deepvariant/third_party/nucleus/io/clif_postproc.py", line 82, in __next__
    record, not_done = self._raw_next()
  File "/tmp/Bazel.runfiles_im0i33s_/runfiles/com_google_deepvariant/third_party/nucleus/io/clif_postproc.py", line 141, in _raw_next
    not_done = self._cc_iterable.PythonNext(record)
ValueError: Data loss: Failed to parse SAM record

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_im0i33s_/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 2246, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_im0i33s_/runfiles/absl_py/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_im0i33s_/runfiles/absl_py/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_im0i33s_/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 2236, in main
    make_examples_runner(options)
  File "/tmp/Bazel.runfiles_im0i33s_/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 2106, in make_examples_runner
    candidates, examples, gvcfs, runtimes = region_processor.process(region)
  File "/tmp/Bazel.runfiles_im0i33s_/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1540, in process
    reads = self.region_reads(region)
  File "/tmp/Bazel.runfiles_im0i33s_/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1616, in region_reads
    error_message + '\nFailed to parse BAM/CRAM file. '
ValueError: Data loss: Failed to parse SAM record
Failed to parse BAM/CRAM file. This is often caused by:
(1) When using a CRAM file, and setting --use_ref_for_cram to false (which means you want to use the embedded ref instead of a ref file), this error could be because of inability to find the embedded ref file.
(2) Your BAM/CRAM file could be corrupted. Please check its md5.
If you cannot find out the reason why this error is occurring, please report to https://github.com/google/deepvariant/issues
```

It seems like for this particular failure mode (BAM file is truncated), the default stackt race was already clear.
But given that I mentioned different level of verbosity. I tried that next.

## Use `-v` to increase verbosity level.

if you run `/opt/deepvariant/bin/make_examples --helpfull` you'll see this flag:

```
  -v,--verbosity: Logging verbosity level. Messages logged at this level or
    lower will be included. Set to 1 for debug logging. If the flag was not set
    or supplied, the value will be changed from the default of -1 (warning) to 0
    (info) after flags are parsed.
    (default: '-1')
    (an integer)
```
You can try to add `-v 1`. But in this case above, my run already had useful logging and didn't seem to produce more useful logs.

## What if we run with Singularity?

I think you were running with Singularity, so I tried that too. I repeated the steps in https://github.com/google/deepvariant/issues/463#issuecomment-866352316 to install Singularity.

And then with the same data, I ran:

```
# Pull the image.
BIN_VERSION=1.1.0
singularity pull docker://google/deepvariant:"${BIN_VERSION}"

# Run DeepVariant.
singularity run -B /usr/lib/locale/:/usr/lib/locale/ \
  docker://google/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/make_examples \
  --mode calling \
  --ref "quickstart-testdata/ucsc.hg19.chr20.unittest.fasta" \
  --reads "quickstart-testdata/NA12878_S1.chr20.10_10p1mb.truncated.bam" \
  --examples "quickstart-output/sing.make_examples.tfrecord.gz" \
  --gvcf "quickstart-output/sing.gvcf.tfrecord.gz"
```

Here is the log I got from my Singularity run:
```
INFO:    Using cached SIF image
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
[W::hts_idx_load3] The index file is older than the data file: quickstart-testdata/NA12878_S1.chr20.10_10p1mb.truncated.bam.bai
I0629 23:43:41.562350 139796154570496 genomics_reader.py:223] Reading quickstart-testdata/NA12878_S1.chr20.10_10p1mb.truncated.bam with NativeSamReader
I0629 23:43:41.568112 139796154570496 make_examples.py:648] Preparing inputs
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
[W::hts_idx_load3] The index file is older than the data file: quickstart-testdata/NA12878_S1.chr20.10_10p1mb.truncated.bam.bai
I0629 23:43:41.568638 139796154570496 genomics_reader.py:223] Reading quickstart-testdata/NA12878_S1.chr20.10_10p1mb.truncated.bam with NativeSamReader
I0629 23:43:41.569230 139796154570496 make_examples.py:648] Common contigs are ['chr20']
I0629 23:43:41.686007 139796154570496 make_examples.py:648] Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2021-06-29 23:43:41.686352: I third_party/nucleus/io/sam_reader.cc:662] Setting HTS_OPT_BLOCK_SIZE to 134217728
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
[W::hts_idx_load3] The index file is older than the data file: quickstart-testdata/NA12878_S1.chr20.10_10p1mb.truncated.bam.bai
I0629 23:43:41.688519 139796154570496 genomics_reader.py:223] Reading quickstart-testdata/NA12878_S1.chr20.10_10p1mb.truncated.bam with NativeSamReader
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
[W::hts_idx_load3] The index file is older than the data file: quickstart-testdata/NA12878_S1.chr20.10_10p1mb.truncated.bam.bai
I0629 23:43:41.688877 139796154570496 genomics_reader.py:223] Reading quickstart-testdata/NA12878_S1.chr20.10_10p1mb.truncated.bam with NativeSamReader
I0629 23:43:41.804690 139796154570496 make_examples.py:648] Writing examples to quickstart-output/sing.make_examples.tfrecord.gz
I0629 23:43:41.804903 139796154570496 make_examples.py:648] Writing gvcf records to quickstart-output/sing.gvcf.tfrecord.gz
I0629 23:43:41.805349 139796154570496 make_examples.py:648] Overhead for preparing inputs: 0 seconds
I0629 23:43:41.821153 139796154570496 make_examples.py:648] 0 candidates (0 examples) [0.02s elapsed]
I0629 23:44:41.827408 139796154570496 make_examples.py:648] 102 candidates (110 examples) [60.01s elapsed]
I0629 23:44:45.517579 139796154570496 make_examples.py:648] 202 candidates (223 examples) [3.69s elapsed]
[E::bgzf_read] Read block operation failed with error 4 after 0 of 4 bytes
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_7g_iun5k/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1611, in region_reads
    reads.extend(sam_reader.query(region))
  File "/tmp/Bazel.runfiles_7g_iun5k/runfiles/com_google_deepvariant/third_party/nucleus/io/clif_postproc.py", line 82, in __next__
    record, not_done = self._raw_next()
  File "/tmp/Bazel.runfiles_7g_iun5k/runfiles/com_google_deepvariant/third_party/nucleus/io/clif_postproc.py", line 141, in _raw_next
    not_done = self._cc_iterable.PythonNext(record)
ValueError: Data loss: Failed to parse SAM record

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_7g_iun5k/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 2246, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_7g_iun5k/runfiles/absl_py/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_7g_iun5k/runfiles/absl_py/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_7g_iun5k/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 2236, in main
    make_examples_runner(options)
  File "/tmp/Bazel.runfiles_7g_iun5k/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 2106, in make_examples_runner
    candidates, examples, gvcfs, runtimes = region_processor.process(region)
  File "/tmp/Bazel.runfiles_7g_iun5k/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1540, in process
    reads = self.region_reads(region)
  File "/tmp/Bazel.runfiles_7g_iun5k/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1616, in region_reads
    error_message + '\nFailed to parse BAM/CRAM file. '
ValueError: Data loss: Failed to parse SAM record
Failed to parse BAM/CRAM file. This is often caused by:
(1) When using a CRAM file, and setting --use_ref_for_cram to false (which means you want to use the embedded ref instead of a ref file), this error could be because of inability to find the embedded ref file.
(2) Your BAM/CRAM file could be corrupted. Please check its md5.
If you cannot find out the reason why this error is occurring, please report to https://github.com/google/deepvariant/issues
```

**Comment by pichuan** [comment]
Hi @Asppagh , 
I'm closing this issue given that I haven't had more information from you.
If you have more information to help us reproduce this issue, please feel free to reopen!
