### ISSUE TITLE
Docker image google/deepvariant:1.1.0-gpu fails to run with "model_train --use_tpu"

### ISSUE THREAD

**Issue by mattwood-codifiedgenomics** [google/deepvariant#469]
When using the provided docker image, google/deepvariant:1.1.0-gpu, an error is produced if --use_tpu is used with model_train.

The command:

```
docker run \
  -v /home/${USER}:/home/${USER} \
  google/deepvariant:1.1.0-gpu \
  /opt/deepvariant/bin/model_train \
  --gcp_project="" \
  --tpu_name="" \
  --tpu_zone="us-central1-a" \
  --use_tpu \
  --dataset_config_pbtxt="${OUTPUT_BUCKET}/training_set.dataset_config.pbtxt" \
  --train_dir="${OUTPUT_BUCKET}/training-tpu/" \
  --model_name="inception_v3" \
  --number_of_steps=50000 \
  --save_interval_secs=300 \
  --batch_size=32 \
  --learning_rate=0.0005 \
  --start_from_checkpoint="${INPUT_BUCKET}/wgs_model/model.ckpt" 
```

The error that prints is:

```
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_461ld2s6/runfiles/com_google_deepvariant/deepvariant/model_train.py", line 303, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/tmp/Bazel.runfiles_461ld2s6/runfiles/absl_py/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_461ld2s6/runfiles/absl_py/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_461ld2s6/runfiles/com_google_deepvariant/deepvariant/model_train.py", line 291, in main
    parse_and_run()
  File "/tmp/Bazel.runfiles_461ld2s6/runfiles/com_google_deepvariant/deepvariant/model_train.py", line 236, in parse_and_run
    FLAGS.gcp_project) if FLAGS.use_tpu else ''
  File "/tmp/Bazel.runfiles_461ld2s6/runfiles/com_google_deepvariant/deepvariant/tf_utils.py", line 391, in resolve_master
    tpu=[tpu_name], zone=tpu_zone, project=gcp_project).get_master()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/cluster_resolver/tpu/tpu_cluster_resolver.py", line 257, in get_master
    return self.master()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/cluster_resolver/tpu/tpu_cluster_resolver.py", line 241, in master
    cluster_spec = self.cluster_spec()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/cluster_resolver/tpu/tpu_cluster_resolver.py", line 311, in cluster_spec
    network_endpoints = self._cloud_tpu_client.network_endpoints()
  File "/usr/local/lib/python3.6/dist-packages/cloud_tpu_client/client.py", line 320, in network_endpoints
    response = self._fetch_cloud_tpu_metadata()
  File "/usr/local/lib/python3.6/dist-packages/cloud_tpu_client/client.py", line 234, in _fetch_cloud_tpu_metadata
    service = self._tpu_service()
  File "/usr/local/lib/python3.6/dist-packages/cloud_tpu_client/client.py", line 209, in _tpu_service
    raise RuntimeError('Missing runtime dependency on the Google API client. '
RuntimeError: Missing runtime dependency on the Google API client. Run `pip install cloud-tpu-client` to fix.

```
However, cloud-tpu-client is not actually the problem. The issue is that  `google.api_core.client_options` is not found when being imported from `googleapiclient.discovery`.

The issue appears to be the [python3.3 _ _ init _ _.py trap](http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-init-py-trap) where one python module is blocking another from being found. In the python path there is a `google` module with an `__init__.py` found here, `/tmp/Bazel.runfiles_461ld2s6/runfiles/com_google_protobuf/python/google/__init__.py`, while running. That may be blocking the discovery of `/usr/local/lib/python3.6/dist-packages/google/api_core/client_options.py`.

**Work Around**

I think configuring Bazel to avoid the issue is probably the right way to fix this, but I worked around the issue by patching `googleapiclient.discovery` with the following patch:

```
49c49,59
< import google.api_core.client_options
---
> 
> # Mega hack to avoid init.py trap of google/init.py which is somewhere on the path
> # Make a namespace to hold our module
> import types
> google = types.SimpleNamespace()
> google.api_core = types.SimpleNamespace()
> # Directly import our module into the namespace
> import importlib.util
> spec = importlib.util.spec_from_file_location("google.api_core.client_options", "/usr/local/lib/python3.6/dist-packages/google/api_core/client_options.py")
> google.api_core.client_options = importlib.util.module_from_spec(spec)
> spec.loader.exec_module(google.api_core.client_options)
```
This manually imports the required module, which only works because we know the path won't change in our docker image and we know `googleapiclient.discovery` only uses `client_options.py`.

Finally, make a new docker image with this patch by calling it discovery.patch and using this Dockerfile:

```
ARG VERSION=1.1.0

FROM google/deepvariant:"${VERSION}"-gpu

RUN python3.6 -m pip install --upgrade pip
RUN python3.6 -m pip install --upgrade --force-reinstall cloud-tpu-client

WORKDIR /opt/deepvariant

COPY discovery.patch /opt/deepvariant/
RUN patch /usr/local/lib/python3.6/dist-packages/googleapiclient/discovery.py discovery.patch

CMD ["/opt/deepvariant/bin/run_deepvariant", "--help"]
```

**Comment by pichuan** [comment]
Thanks @mattwood-codifiedgenomics . I'll take a look at this before the next release.

**Comment by pichuan** [comment]
First thing I'm trying to do is to see if I can follow similar steps in:
https://github.com/google/deepvariant/blob/r0.9/docs/deepvariant-tpu-training-case-study.md

Context: We switched our training tutorial to GPU since then, because GPU is a more common use case. The one in v0.9.0 is the latest that I can refer to, so I'll start from there. The following steps is a combination of
https://github.com/google/deepvariant/blob/r0.9/docs/deepvariant-tpu-training-case-study.md
and
https://github.com/google/deepvariant/blob/r1.1/docs/deepvariant-training-case-study.md.

---

I got a CPU machine:
```
gcloud compute instances create "${USER}-cpu" \
  --scopes "compute-rw,storage-full,cloud-platform" \
  --image-family "ubuntu-1804-lts" \
  --image-project "ubuntu-os-cloud" \
  --machine-type "custom-64-131072" \
  --boot-disk-size "300" \
  --zone "us-west2-b" \
  --min-cpu-platform "Intel Skylake"
```

Set variables
```
YOUR_PROJECT=REPLACE_WITH_YOUR_PROJECT
OUTPUT_GCS_BUCKET=REPLACE_WITH_YOUR_GCS_BUCKET

BUCKET="gs://deepvariant"
BIN_VERSION="1.1.0"

MODEL_BUCKET="${BUCKET}/models/DeepVariant/${BIN_VERSION}/DeepVariant-inception_v3-${BIN_VERSION}+data-wgs_standard"
GCS_PRETRAINED_WGS_MODEL="${MODEL_BUCKET}/model.ckpt"

OUTPUT_BUCKET="${OUTPUT_GCS_BUCKET}/customized_training"
TRAINING_DIR="${OUTPUT_BUCKET}/training_dir"

BASE="${HOME}/training-case-study"
DATA_BUCKET=gs://deepvariant/training-case-study/BGISEQ-HG001

INPUT_DIR="${BASE}/input"
BIN_DIR="${INPUT_DIR}/bin"
DATA_DIR="${INPUT_DIR}/data"
OUTPUT_DIR="${BASE}/output"
LOG_DIR="${OUTPUT_DIR}/logs"
SHUFFLE_SCRIPT_DIR="${HOME}/deepvariant/tools"

REF="${DATA_DIR}/ucsc_hg19.fa"
BAM_CHR1="${DATA_DIR}/BGISEQ_PE100_NA12878.sorted.chr1.bam"
BAM_CHR20="${DATA_DIR}/BGISEQ_PE100_NA12878.sorted.chr20.bam"
BAM_CHR21="${DATA_DIR}/BGISEQ_PE100_NA12878.sorted.chr21.bam"
TRUTH_VCF="${DATA_DIR}/HG001_GRCh37_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_PGandRTGphasetransfer_chrs_FIXED.vcf.gz"
TRUTH_BED="${DATA_DIR}/HG001_GRCh37_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_nosomaticdel_chr.bed"

N_SHARDS=64
```

```
mkdir -p "${OUTPUT_DIR}"
mkdir -p "${BIN_DIR}"
mkdir -p "${DATA_DIR}"
mkdir -p "${LOG_DIR}"
```

```
gsutil -m cp ${DATA_BUCKET}/BGISEQ_PE100_NA12878.sorted.chr*.bam* "${DATA_DIR}"
gsutil -m cp -r "${DATA_BUCKET}/ucsc_hg19.fa*" "${DATA_DIR}"
gsutil -m cp -r "${DATA_BUCKET}/HG001_GRCh37_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_*" "${DATA_DIR}"

gunzip "${DATA_DIR}/ucsc_hg19.fa.gz"
```

```
sudo apt -y update
sudo apt -y install parallel
sudo apt -y install docker.io
```

```
sudo docker pull google/deepvariant:"${BIN_VERSION}"
```

```
( time seq 0 $((N_SHARDS-1)) | \
  parallel --halt 2 --line-buffer \
    sudo docker run \
      -v ${HOME}:${HOME} \
      google/deepvariant:"${BIN_VERSION}" \
      /opt/deepvariant/bin/make_examples \
      --mode training \
      --ref "${REF}" \
      --reads "${BAM_CHR1}" \
      --examples "${OUTPUT_DIR}/training_set.with_label.tfrecord@${N_SHARDS}.gz" \
      --truth_variants "${TRUTH_VCF}" \
      --confident_regions "${TRUTH_BED}" \
      --task {} \
      --regions "'chr1'" \
) 2>&1 | tee "${LOG_DIR}/training_set.with_label.make_examples.log"
```

```
gsutil -m cp ${OUTPUT_DIR}/training_set.with_label.tfrecord-?????-of-000??.gz \
  ${OUTPUT_BUCKET}
```

```
( time seq 0 $((N_SHARDS-1)) | \
  parallel --halt 2 --line-buffer \
    sudo docker run \
      -v /home/${USER}:/home/${USER} \
      google/deepvariant:"${BIN_VERSION}" \
      /opt/deepvariant/bin/make_examples \
      --mode training \
      --ref "${REF}" \
      --reads "${BAM_CHR21}" \
      --examples "${OUTPUT_DIR}/validation_set.with_label.tfrecord@${N_SHARDS}.gz" \
      --truth_variants "${TRUTH_VCF}" \
      --confident_regions "${TRUTH_BED}" \
      --task {} \
      --regions "'chr21'" \
) 2>&1 | tee "${LOG_DIR}/validation_set.with_label.make_examples.log"
```

```
gsutil -m cp ${OUTPUT_DIR}/validation_set.with_label.tfrecord-?????-of-000??.gz \
  ${OUTPUT_BUCKET}
```

```
mkdir -p ${SHUFFLE_SCRIPT_DIR}
wget https://gist.githubusercontent.com/pichuan/75aa5aebc961dd2c2472bcbcdd9ecaa9/raw/3c313815050f1b517a660604b222ecc7528b37e0/shuffle_tfrecords_beam.py -O ${SHUFFLE_SCRIPT_DIR}/shuffle_tfrecords_beam.py
```

```
sudo apt -y update
sudo apt -y install python3-dev python3-pip
pip3 install setuptools --upgrade
# I had to fix the version, otherwise I hit this issue: https://github.com/apache/arrow/issues/2163
pip3 install apache_beam[gcp]==2.26.0
pip3 install tensorflow  # For parsing tf.Example in shuffle_tfrecords_beam.py.
```

```
time python3 ${SHUFFLE_SCRIPT_DIR}/shuffle_tfrecords_beam.py \
  --project="${YOUR_PROJECT}" \
  --input_pattern_list="${OUTPUT_BUCKET}"/training_set.with_label.tfrecord-?????-of-00064.gz \
  --output_pattern_prefix="${OUTPUT_BUCKET}/training_set.with_label.shuffled" \
  --output_dataset_name="HG001" \
  --output_dataset_config_pbtxt="${OUTPUT_BUCKET}/training_set.dataset_config.pbtxt" \
  --job_name=shuffle-tfrecords \
  --runner=DataflowRunner \
  --staging_location="${OUTPUT_BUCKET}/staging" \
  --temp_location="${OUTPUT_BUCKET}/tempdir" \
  --save_main_session \
  --region us-east1
```

```
time python3 ${SHUFFLE_SCRIPT_DIR}/shuffle_tfrecords_beam.py \
  --project="${YOUR_PROJECT}" \
  --input_pattern_list="${OUTPUT_BUCKET}"/validation_set.with_label.tfrecord-?????-of-00064.gz \
  --output_pattern_prefix="${OUTPUT_BUCKET}/validation_set.with_label.shuffled" \
  --output_dataset_name="HG001" \
  --output_dataset_config_pbtxt="${OUTPUT_BUCKET}/validation_set.dataset_config.pbtxt" \
  --job_name=shuffle-tfrecords \
  --runner=DataflowRunner \
  --staging_location="${OUTPUT_BUCKET}/staging" \
  --temp_location="${OUTPUT_BUCKET}/tempdir" \
  --save_main_session \
  --region us-east1
```

```
time gcloud compute tpus create ${USER}-demo-tpu \
  --network=default \
  --version=2.3 \
  --zone=us-central1-c
```

# Below is the main difference from the instruction in r0.9: How to look up the TPU_IP:

Given that it seems like we didn't have the right library to properly look up `tpu_name` (`pip install cloud-tpu-client` is needed, it seems). I will try to fix this in our future Dockerfile and test it. But for now, I'll show up to manually resolve the tpu_name.

First, install this:
```
pip3 install cloud-tpu-client
``` 

And then:

```
TPU_NAME="${USER}-demo-tpu"
TPU_IP=$(python3 -c "import tensorflow as tf; print(tf.distribute.cluster_resolver.TPUClusterResolver(tpu=['${TPU_NAME}'], zone='us-central1-c').get_master())")
```
Check the IP:
```
$ echo ${TPU_IP}
grpc://10.33.164.2:8470
```

```
( time sudo docker run \
  -v /home/${USER}:/home/${USER} \
  google/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/model_train \
  --use_tpu \
  --master="${TPU_IP}" \
  --dataset_config_pbtxt="${OUTPUT_BUCKET}/training_set.dataset_config.pbtxt" \
  --train_dir="${TRAINING_DIR}" \
  --model_name="inception_v3" \
  --number_of_steps=50000 \
  --save_interval_secs=300 \
  --batch_size=512 \
  --learning_rate=0.008 \
  --start_from_checkpoint="" \
) 2>&1 | tee "${LOG_DIR}/train.log"
```

This now seems to be able to see the TPU. But right now I seem to be having some issue of using ${GCS_PRETRAINED_WGS_MODEL} as `--start_from_checkpoint`, so I might need to continue looking into why.

And, at this point, I'm done for now. So I manually deleted the TPU:
```
gcloud compute tpus delete ${TPU_NAME} --zone us-central1-c
```

---

@mattwood-codifiedgenomics Thanks for reporting this. I don't think the `--tpu_name` code path is commonly used. I'll see if I can get the right dependencies installed, and see if I can get proper unit tests to cover this. At the very least, I'll try to get a manual run to succeed.

**Comment by pichuan** [comment]
Hi @mattwood-codifiedgenomics , I have an internal tracker to track this, so I'll close this for now.
If I encounter any issues when adding the dependency, I'll let you know.

**Comment by pichuan** [comment]
@mattwood-codifiedgenomics To give you an update, I just tested with our latest code (still internal) and was able to run this successfully.

We're hoping to make the next release not too long from now (~1month). 

In my recent test that worked, I had to create a TPU version 2.5.0 (because that's the new TF version we're using).

So, something like:

```
time gcloud compute tpus create ${USER}-demo-tpu \
  --network=default \
  --version=2.5.0 \
  --zone=us-central1-c
```

And then with that TPU, this worked:

```
OUTPUT_GCS_BUCKET=<OURBUCKET>
OUTPUT_BUCKET="${OUTPUT_GCS_BUCKET}/customized_training"
TRAINING_DIR="${OUTPUT_BUCKET}/training_dir"

time sudo docker run \
  -v /home/${USER}:/home/${USER} \
  deepvariant:latest \
  /opt/deepvariant/bin/model_train \
  --use_tpu \
  --tpu_name="pichuan-demo-tpu" \
  --tpu_zone="us-central1-c" \
  --dataset_config_pbtxt="${OUTPUT_BUCKET}/training_set.dataset_config.pbtxt" \
  --train_dir="${TRAINING_DIR}" \
  --model_name="inception_v3" \
  --number_of_steps=50000 \
  --save_interval_secs=300 \
  --batch_size=512 \
  --learning_rate=0.008 \
  --start_from_checkpoint=""
```

When the next release is out, it'll be great if you can try it and let us know if it works.

Specifically, you'll need to specify flags like:
```
  --tpu_name="pichuan-demo-tpu" \
  --tpu_zone="us-central1-c" \
```
