### ISSUE TITLE
[E::idx_find_and_load] Could not retrieve index file

### ISSUE THREAD

**Issue by madhubioinfo** [google/deepvariant#492]
I have used the following commandline for running deepvariant

sudo docker run \
        -v "/media/eniac/WD1/Hifi_Assemblies/mapping/":"/input" \
        -v "/media/eniac/WD1/Hifi_Assemblies/mapping/docker_out:/output" \
google/deepvariant:1.2.0 \
/opt/deepvariant/bin/run_deepvariant \
--model_type=WGS \
--ref=/input/G1.asm.hic.hap2.p_ctg.fa \
--reads=/input/G1_hap2.bam \
--output_vcf=/output/output.vcf \
--num_shards=4

Deepvariant docker version is unable to find the indexed file. But there is an index file located in the specified directory

*****Error Message *******
I1104 14:33:59.843885 140094834329408 run_deepvariant.py:344] Re-using the directory for intermediate results in /tmp/tmp6zw47x4_
[E::idx_find_and_load] Could not retrieve index file for '/input/G1_hap2.bam'
I1104 14:34:02.363862 139708777084736 genomics_reader.py:222] Reading /input/G1_hap2.bam with NativeSamReader
W1104 14:34:02.364024 139708777084736 make_examples_core.py:273] No non-empty sample name found in the input reads. DeepVariant will use default as the sample name. You can also provide a sample name with the --sample_name argument.
[E::idx_find_and_load] Could not retrieve index file for '/input/G1_hap2.bam'
I1104 14:34:02.363985 139750224725824 genomics_reader.py:222] Reading /input/G1_hap2.bam with NativeSamReader
W1104 14:34:02.364139 139750224725824 make_examples_core.py:273] No non-empty sample name found in the input reads. DeepVariant will use default as the sample name. You can also provide a sample name with the --sample_name argument.
[E::idx_find_and_load] Could not retrieve index file for '/input/G1_hap2.bam'
I1104 14:34:02.364016 140243238704960 genomics_reader.py:222] Reading /input/G1_hap2.bam with NativeSamReader
W1104 14:34:02.364171 140243238704960 make_examples_core.py:273] No non-empty sample name found in the input reads. DeepVariant will use default as the sample name. You can also provide a sample name with the --sample_name argument.
[E::idx_find_and_load] Could not retrieve index file for '/input/G1_hap2.bam'
I1104 14:34:02.363935 139685650237248 genomics_reader.py:222] Reading /input/G1_hap2.bam with NativeSamReader
W1104 14:34:02.364088 139685650237248 make_examples_core.py:273] No non-empty sample name found in the input reads. DeepVariant will use default as the sample name. You can also provide a sample name with the --sample_name argument.
I1104 14:34:02.587771 139708777084736 make_examples_core.py:236] Task 1/4: Preparing inputs
[E::idx_find_and_load] Could not retrieve index file for '/input/G1_hap2.bam'
I1104 14:34:02.590152 139708777084736 genomics_reader.py:222] Reading /input/G1_hap2.bam with NativeSamReader
I1104 14:34:02.630764 139708777084736 make_examples_core.py:236] Task 1/4: Common contigs are ['h2tg000001l', 'h2tg000002l', 'h2tg000003l', 'h2tg000004l', 'h2tg000005l', 'h2tg000006l', 'h2tg000007l', 'h2tg000008l', 'h2tg000009l', 'h2tg000010l', 'h2tg000011l', 'h2tg000012l', 'h2tg000013l', 'h2tg000014l', 'h2tg000015l', 'h2tg000016l', 'h2tg000017l', 'h2tg000018l', 'h2tg000019l', 'h2tg000020l', 'h2tg000021l', 'h2tg000022l', 'h2tg000023l', 'h2tg000024l', 'h2tg000025l', 'h2tg000026l', 'h2tg000027l', 'h2tg000028l', 'h2tg000029l', 'h2tg000030l', 'h2tg000031l', 'h2tg000032c', 'h2tg000033l', 'h2tg000034l', 'h2tg000035l', 'h2tg000036l', 'h2tg000037l', 'h2tg000038l', 'h2tg000039l', 'h2tg000040l', 'h2tg000041l', 'h2tg000042l', 'h2tg000043l', 'h2tg000044l', 'h2tg000045l', 'h2tg000046l', 'h2tg000047l', 'h2tg000048l', 'h2tg000049l', 'h2tg000050l', 'h2tg000051l', 'h2tg000052c', 'h2tg000053l', 'h2tg000054l', 'h2tg000055l', 'h2tg000056l', 'h2tg000057l', 'h2tg000058l', 'h2tg000059l', 'h2tg000060l', 'h2tg000061l', 'h2tg000062l', 'h2tg000063l', 'h2tg000064l', 'h2tg000065l', 'h2tg000066l', 'h2tg000067l', 'h2tg000068l', 'h2tg000069l', 'h2tg000070l', 'h2tg000071l', 'h2tg000072l', 'h2tg000073l', 'h2tg000074l', 'h2tg000075l', 'h2tg000076l', 'h2tg000077l']
I1104 14:34:02.568957 139750224725824 make_examples_core.py:236] Task 3/4: Preparing inputs
[E::idx_find_and_load] Could not retrieve index file for '/input/G1_hap2.bam'
I1104 14:34:02.571760 139750224725824 genomics_reader.py:222] Reading /input/G1_hap2.bam with NativeSamReader
I1104 14:34:02.611608 139750224725824 make_examples_core.py:236] Task 3/4: Common contigs are ['h2tg000001l', 'h2tg000002l', 'h2tg000003l', 'h2tg000004l', 'h2tg000005l', 'h2tg000006l', 'h2tg000007l', 'h2tg000008l', 'h2tg000009l', 'h2tg000010l', 'h2tg000011l', 'h2tg000012l', 'h2tg000013l', 'h2tg000014l', 'h2tg000015l', 'h2tg000016l', 'h2tg000017l', 'h2tg000018l', 'h2tg000019l', 'h2tg000020l', 'h2tg000021l', 'h2tg000022l', 'h2tg000023l', 'h2tg000024l', 'h2tg000025l', 'h2tg000026l', 'h2tg000027l', 'h2tg000028l', 'h2tg000029l', 'h2tg000030l', 'h2tg000031l', 'h2tg000032c', 'h2tg000033l', 'h2tg000034l', 'h2tg000035l', 'h2tg000036l', 'h2tg000037l', 'h2tg000038l', 'h2tg000039l', 'h2tg000040l', 'h2tg000041l', 'h2tg000042l', 'h2tg000043l', 'h2tg000044l', 'h2tg000045l', 'h2tg000046l', 'h2tg000047l', 'h2tg000048l', 'h2tg000049l', 'h2tg000050l', 'h2tg000051l', 'h2tg000052c', 'h2tg000053l', 'h2tg000054l', 'h2tg000055l', 'h2tg000056l', 'h2tg000057l', 'h2tg000058l', 'h2tg000059l', 'h2tg000060l', 'h2tg000061l', 'h2tg000062l', 'h2tg000063l', 'h2tg000064l', 'h2tg000065l', 'h2tg000066l', 'h2tg000067l', 'h2tg000068l', 'h2tg000069l', 'h2tg000070l', 'h2tg000071l', 'h2tg000072l', 'h2tg000073l', 'h2tg000074l', 'h2tg000075l', 'h2tg000076l', 'h2tg000077l']
I1104 14:34:02.569077 140243238704960 make_examples_core.py:236] Task 2/4: Preparing inputs
[E::idx_find_and_load] Could not retrieve index file for '/input/G1_hap2.bam'
I1104 14:34:02.571856 140243238704960 genomics_reader.py:222] Reading /input/G1_hap2.bam with NativeSamReader
I1104 14:34:02.613078 140243238704960 make_examples_core.py:236] Task 2/4: Common contigs are ['h2tg000001l', 'h2tg000002l', 'h2tg000003l', 'h2tg000004l', 'h2tg000005l', 'h2tg000006l', 'h2tg000007l', 'h2tg000008l', 'h2tg000009l', 'h2tg000010l', 'h2tg000011l', 'h2tg000012l', 'h2tg000013l', 'h2tg000014l', 'h2tg000015l', 'h2tg000016l', 'h2tg000017l', 'h2tg000018l', 'h2tg000019l', 'h2tg000020l', 'h2tg000021l', 'h2tg000022l', 'h2tg000023l', 'h2tg000024l', 'h2tg000025l', 'h2tg000026l', 'h2tg000027l', 'h2tg000028l', 'h2tg000029l', 'h2tg000030l', 'h2tg000031l', 'h2tg000032c', 'h2tg000033l', 'h2tg000034l', 'h2tg000035l', 'h2tg000036l', 'h2tg000037l', 'h2tg000038l', 'h2tg000039l', 'h2tg000040l', 'h2tg000041l', 'h2tg000042l', 'h2tg000043l', 'h2tg000044l', 'h2tg000045l', 'h2tg000046l', 'h2tg000047l', 'h2tg000048l', 'h2tg000049l', 'h2tg000050l', 'h2tg000051l', 'h2tg000052c', 'h2tg000053l', 'h2tg000054l', 'h2tg000055l', 'h2tg000056l', 'h2tg000057l', 'h2tg000058l', 'h2tg000059l', 'h2tg000060l', 'h2tg000061l', 'h2tg000062l', 'h2tg000063l', 'h2tg000064l', 'h2tg000065l', 'h2tg000066l', 'h2tg000067l', 'h2tg000068l', 'h2tg000069l', 'h2tg000070l', 'h2tg000071l', 'h2tg000072l', 'h2tg000073l', 'h2tg000074l', 'h2tg000075l', 'h2tg000076l', 'h2tg000077l']
I1104 14:34:02.568975 139685650237248 make_examples_core.py:236] Task 0/4: Preparing inputs
[E::idx_find_and_load] Could not retrieve index file for '/input/G1_hap2.bam'
I1104 14:34:02.571821 139685650237248 genomics_reader.py:222] Reading /input/G1_hap2.bam with NativeSamReader
I1104 14:34:02.613319 139685650237248 make_examples_core.py:236] Task 0/4: Common contigs are ['h2tg000001l', 'h2tg000002l', 'h2tg000003l', 'h2tg000004l', 'h2tg000005l', 'h2tg000006l', 'h2tg000007l', 'h2tg000008l', 'h2tg000009l', 'h2tg000010l', 'h2tg000011l', 'h2tg000012l', 'h2tg000013l', 'h2tg000014l', 'h2tg000015l', 'h2tg000016l', 'h2tg000017l', 'h2tg000018l', 'h2tg000019l', 'h2tg000020l', 'h2tg000021l', 'h2tg000022l', 'h2tg000023l', 'h2tg000024l', 'h2tg000025l', 'h2tg000026l', 'h2tg000027l', 'h2tg000028l', 'h2tg000029l', 'h2tg000030l', 'h2tg000031l', 'h2tg000032c', 'h2tg000033l', 'h2tg000034l', 'h2tg000035l', 'h2tg000036l', 'h2tg000037l', 'h2tg000038l', 'h2tg000039l', 'h2tg000040l', 'h2tg000041l', 'h2tg000042l', 'h2tg000043l', 'h2tg000044l', 'h2tg000045l', 'h2tg000046l', 'h2tg000047l', 'h2tg000048l', 'h2tg000049l', 'h2tg000050l', 'h2tg000051l', 'h2tg000052c', 'h2tg000053l', 'h2tg000054l', 'h2tg000055l', 'h2tg000056l', 'h2tg000057l', 'h2tg000058l', 'h2tg000059l', 'h2tg000060l', 'h2tg000061l', 'h2tg000062l', 'h2tg000063l', 'h2tg000064l', 'h2tg000065l', 'h2tg000066l', 'h2tg000067l', 'h2tg000068l', 'h2tg000069l', 'h2tg000070l', 'h2tg000071l', 'h2tg000072l', 'h2tg000073l', 'h2tg000074l', 'h2tg000075l', 'h2tg000076l', 'h2tg000077l']
I1104 14:34:02.965431 139750224725824 make_examples_core.py:236] Task 3/4: Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2021-11-04 14:34:02.965795: I third_party/nucleus/io/sam_reader.cc:705] Setting HTS_OPT_BLOCK_SIZE to 134217728
I1104 14:34:02.979464 140243238704960 make_examples_core.py:236] Task 2/4: Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2021-11-04 14:34:02.979810: I third_party/nucleus/io/sam_reader.cc:705] Setting HTS_OPT_BLOCK_SIZE to 134217728
I1104 14:34:02.976352 139685650237248 make_examples_core.py:236] Task 0/4: Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2021-11-04 14:34:02.976696: I third_party/nucleus/io/sam_reader.cc:705] Setting HTS_OPT_BLOCK_SIZE to 134217728
I1104 14:34:02.996676 139708777084736 make_examples_core.py:236] Task 1/4: Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2021-11-04 14:34:02.997065: I third_party/nucleus/io/sam_reader.cc:705] Setting HTS_OPT_BLOCK_SIZE to 134217728
[E::idx_find_and_load] Could not retrieve index file for '/input/G1_hap2.bam'
I1104 14:34:03.100254 139708777084736 genomics_reader.py:222] Reading /input/G1_hap2.bam with NativeSamReader
[E::idx_find_and_load] Could not retrieve index file for '/input/G1_hap2.bam'
I1104 14:34:03.225395 139708777084736 genomics_reader.py:222] Reading /input/G1_hap2.bam with NativeSamReader
I1104 14:34:03.225888 139708777084736 make_examples_core.py:236] Task 1/4: Writing examples to /tmp/tmp6zw47x4_/make_examples.tfrecord-00001-of-00004.gz
I1104 14:34:03.225993 139708777084736 make_examples_core.py:236] Task 1/4: Overhead for preparing inputs: 0 seconds
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_o60bhxse/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 173, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_o60bhxse/runfiles/absl_py/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_o60bhxse/runfiles/absl_py/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_o60bhxse/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 163, in main
    make_examples_core.make_examples_runner(options)
  File "/tmp/Bazel.runfiles_o60bhxse/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1569, in make_examples_runner
    runtimes) = region_processor.process(region)
  File "/tmp/Bazel.runfiles_o60bhxse/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 918, in process
    reads = self.region_reads(
  File "/tmp/Bazel.runfiles_o60bhxse/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1024, in region_reads
    raise err
  File "/tmp/Bazel.runfiles_o60bhxse/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1002, in region_reads
    reads.extend(sam_reader.query(region))
  File "/tmp/Bazel.runfiles_o60bhxse/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 247, in query
    return self._reader.query(region)
  File "/tmp/Bazel.runfiles_o60bhxse/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 245, in query
    return self._reader.query(region)
ValueError: Failed precondition: Cannot query without an index
[E::idx_find_and_load] Could not retrieve index file for '/input/G1_hap2.bam'
I1104 14:34:03.068893 139750224725824 genomics_reader.py:222] Reading /input/G1_hap2.bam with NativeSamReader
[E::idx_find_and_load] Could not retrieve index file for '/input/G1_hap2.bam'
I1104 14:34:03.193795 139750224725824 genomics_reader.py:222] Reading /input/G1_hap2.bam with NativeSamReader
I1104 14:34:03.194288 139750224725824 make_examples_core.py:236] Task 3/4: Writing examples to /tmp/tmp6zw47x4_/make_examples.tfrecord-00003-of-00004.gz
I1104 14:34:03.194392 139750224725824 make_examples_core.py:236] Task 3/4: Overhead for preparing inputs: 0 seconds
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_j563zta4/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 173, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_j563zta4/runfiles/absl_py/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_j563zta4/runfiles/absl_py/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_j563zta4/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 163, in main
    make_examples_core.make_examples_runner(options)
  File "/tmp/Bazel.runfiles_j563zta4/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1569, in make_examples_runner
    runtimes) = region_processor.process(region)
  File "/tmp/Bazel.runfiles_j563zta4/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 918, in process
    reads = self.region_reads(
  File "/tmp/Bazel.runfiles_j563zta4/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1024, in region_reads
    raise err
  File "/tmp/Bazel.runfiles_j563zta4/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1002, in region_reads
    reads.extend(sam_reader.query(region))
  File "/tmp/Bazel.runfiles_j563zta4/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 247, in query
    return self._reader.query(region)
  File "/tmp/Bazel.runfiles_j563zta4/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 245, in query
    return self._reader.query(region)
ValueError: Failed precondition: Cannot query without an index
[E::idx_find_and_load] Could not retrieve index file for '/input/G1_hap2.bam'
I1104 14:34:03.079088 140243238704960 genomics_reader.py:222] Reading /input/G1_hap2.bam with NativeSamReader
[E::idx_find_and_load] Could not retrieve index file for '/input/G1_hap2.bam'
I1104 14:34:03.208736 140243238704960 genomics_reader.py:222] Reading /input/G1_hap2.bam with NativeSamReader
I1104 14:34:03.209183 140243238704960 make_examples_core.py:236] Task 2/4: Writing examples to /tmp/tmp6zw47x4_/make_examples.tfrecord-00002-of-00004.gz
I1104 14:34:03.209277 140243238704960 make_examples_core.py:236] Task 2/4: Overhead for preparing inputs: 0 seconds
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_fkyy0r3x/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 173, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_fkyy0r3x/runfiles/absl_py/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_fkyy0r3x/runfiles/absl_py/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_fkyy0r3x/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 163, in main
    make_examples_core.make_examples_runner(options)
  File "/tmp/Bazel.runfiles_fkyy0r3x/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1569, in make_examples_runner
    runtimes) = region_processor.process(region)
  File "/tmp/Bazel.runfiles_fkyy0r3x/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 918, in process
    reads = self.region_reads(
  File "/tmp/Bazel.runfiles_fkyy0r3x/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1024, in region_reads
    raise err
  File "/tmp/Bazel.runfiles_fkyy0r3x/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1002, in region_reads
    reads.extend(sam_reader.query(region))
  File "/tmp/Bazel.runfiles_fkyy0r3x/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 247, in query
    return self._reader.query(region)
  File "/tmp/Bazel.runfiles_fkyy0r3x/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 245, in query
    return self._reader.query(region)
ValueError: Failed precondition: Cannot query without an index
[E::idx_find_and_load] Could not retrieve index file for '/input/G1_hap2.bam'
I1104 14:34:03.079069 139685650237248 genomics_reader.py:222] Reading /input/G1_hap2.bam with NativeSamReader
[E::idx_find_and_load] Could not retrieve index file for '/input/G1_hap2.bam'
I1104 14:34:03.205049 139685650237248 genomics_reader.py:222] Reading /input/G1_hap2.bam with NativeSamReader
I1104 14:34:03.205483 139685650237248 make_examples_core.py:236] Task 0/4: Writing examples to /tmp/tmp6zw47x4_/make_examples.tfrecord-00000-of-00004.gz
I1104 14:34:03.205575 139685650237248 make_examples_core.py:236] Task 0/4: Overhead for preparing inputs: 0 seconds
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_z12b2b_u/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 173, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_z12b2b_u/runfiles/absl_py/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_z12b2b_u/runfiles/absl_py/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_z12b2b_u/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 163, in main
    make_examples_core.make_examples_runner(options)
  File "/tmp/Bazel.runfiles_z12b2b_u/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1569, in make_examples_runner
    runtimes) = region_processor.process(region)
  File "/tmp/Bazel.runfiles_z12b2b_u/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 918, in process
    reads = self.region_reads(
  File "/tmp/Bazel.runfiles_z12b2b_u/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1024, in region_reads
    raise err
  File "/tmp/Bazel.runfiles_z12b2b_u/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1002, in region_reads
    reads.extend(sam_reader.query(region))
  File "/tmp/Bazel.runfiles_z12b2b_u/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 247, in query
    return self._reader.query(region)
  File "/tmp/Bazel.runfiles_z12b2b_u/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 245, in query
    return self._reader.query(region)
ValueError: Failed precondition: Cannot query without an index
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /input/G1.asm.hic.hap2.p_ctg.fa --reads /input/G1_hap2.bam --examples /tmp/tmp6zw47x4_/make_examples.tfrecord@4.gz --task 3

**Comment by akolesnikov** [comment]
What is the index filename? By convention it is expected to be /input/G1_hap2.bam.bai

**Comment by madhubioinfo** [comment]
Yes it is there , it is G1_hap2.bam.bai

**Comment by madhubioinfo** [comment]
I ran it with a different dataset with the same command just changed the files, I am getting a different error
This is the command I have
        -v "/media/eniac/WD1/HiFi_Dikaryon_data/Hifi_Assemblies":"/input" \
        -v "/media/eniac/WD1/HiFi_Dikaryon_data/Hifi_Assemblies/docker_out:/output" \
google/deepvariant:1.2.0 \
/opt/deepvariant/bin/run_deepvariant \
--model_type=WGS \
--ref=/input/G1-hifi.contigs.fasta \
--reads=/input/G1_sorted.bam \
--output_vcf=/output/output.vcf \
--num_shards=4


[E::hts_open_format] Failed to open file "/input/G1_sorted.bam" : No such file or directory
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_ai032aw7/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 173, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_ai032aw7/runfiles/absl_py/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_ai032aw7/runfiles/absl_py/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_ai032aw7/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 159, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/tmp/Bazel.runfiles_ai032aw7/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 121, in default_options
    samples_in_order, sample_role_to_train = one_sample_from_flags(
  File "/tmp/Bazel.runfiles_ai032aw7/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 80, in one_sample_from_flags
    sample_name = make_examples_core.assign_sample_name(
  File "/tmp/Bazel.runfiles_ai032aw7/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 128, in assign_sample_name
    with sam.SamReader(reads_filenames.split(',')[0]) as sam_reader:
  File "/tmp/Bazel.runfiles_ai032aw7/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 221, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_ai032aw7/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 255, in _native_reader
    return NativeSamReader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_ai032aw7/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 223, in __init__
    self._reader = sam_reader.SamReader.from_file(
ValueError: Not found: Could not open /input/G1_sorted.bam
[E::hts_open_format] Failed to open file "/input/G1_sorted.bam" : No such file or directory
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_7p9q24x8/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 173, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_7p9q24x8/runfiles/absl_py/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_7p9q24x8/runfiles/absl_py/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_7p9q24x8/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 159, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/tmp/Bazel.runfiles_7p9q24x8/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 121, in default_options
    samples_in_order, sample_role_to_train = one_sample_from_flags(
  File "/tmp/Bazel.runfiles_7p9q24x8/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 80, in one_sample_from_flags
    sample_name = make_examples_core.assign_sample_name(
  File "/tmp/Bazel.runfiles_7p9q24x8/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 128, in assign_sample_name
    with sam.SamReader(reads_filenames.split(',')[0]) as sam_reader:
  File "/tmp/Bazel.runfiles_7p9q24x8/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 221, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_7p9q24x8/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 255, in _native_reader
    return NativeSamReader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_7p9q24x8/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 223, in __init__
    self._reader = sam_reader.SamReader.from_file(
ValueError: Not found: Could not open /input/G1_sorted.bam
[E::hts_open_format] Failed to open file "/input/G1_sorted.bam" : No such file or directory
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_fmpe4uwf/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 173, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_fmpe4uwf/runfiles/absl_py/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_fmpe4uwf/runfiles/absl_py/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_fmpe4uwf/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 159, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/tmp/Bazel.runfiles_fmpe4uwf/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 121, in default_options
    samples_in_order, sample_role_to_train = one_sample_from_flags(
  File "/tmp/Bazel.runfiles_fmpe4uwf/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 80, in one_sample_from_flags
    sample_name = make_examples_core.assign_sample_name(
  File "/tmp/Bazel.runfiles_fmpe4uwf/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 128, in assign_sample_name
    with sam.SamReader(reads_filenames.split(',')[0]) as sam_reader:
  File "/tmp/Bazel.runfiles_fmpe4uwf/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 221, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_fmpe4uwf/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 255, in _native_reader
    return NativeSamReader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_fmpe4uwf/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 223, in __init__
    self._reader = sam_reader.SamReader.from_file(
ValueError: Not found: Could not open /input/G1_sorted.bam
[E::hts_open_format] Failed to open file "/input/G1_sorted.bam" : No such file or directory
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_u7og4tn6/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 173, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_u7og4tn6/runfiles/absl_py/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_u7og4tn6/runfiles/absl_py/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_u7og4tn6/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 159, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/tmp/Bazel.runfiles_u7og4tn6/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 121, in default_options
    samples_in_order, sample_role_to_train = one_sample_from_flags(
  File "/tmp/Bazel.runfiles_u7og4tn6/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 80, in one_sample_from_flags
    sample_name = make_examples_core.assign_sample_name(
  File "/tmp/Bazel.runfiles_u7og4tn6/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 128, in assign_sample_name
    with sam.SamReader(reads_filenames.split(',')[0]) as sam_reader:
  File "/tmp/Bazel.runfiles_u7og4tn6/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 221, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_u7og4tn6/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 255, in _native_reader
    return NativeSamReader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_u7og4tn6/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 223, in __init__
    self._reader = sam_reader.SamReader.from_file(
ValueError: Not found: Could not open /input/G1_sorted.bam
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /input/G1-hifi.contigs.fasta --reads /input/G1_sorted.bam --examples /tmp/tmpe6hg2fef/make_examples.tfrecord@4.gz --task 1

**Comment by luciamayorf** [comment]
Did you finally solve this issue? I've encountered the same problem when running the WGS model. It says that it cannot query without and index and that it cannot find the index file for the BAM file, when it is in the same directory as the bam file and it has the same name with the extension .bai.

**Comment by pichuan** [comment]
Hi @luciamayorf , can you share your command?

And, can you quickly test with https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-quick-start.md and see if that worked for you?
