### ISSUE TITLE
Training works with DeepVariant-inception_v3-1.3.0+data-wgs_standard but not DeepVariant-inception_v3-1.3.0+data-pacbio_standard

### ISSUE THREAD

**Issue by jelber2** [google/deepvariant#500]
Hi,

I was trying to train a PacBio HiFi model for bacteria (surprisingly the default DeepVariant 1.3.0 PacBio model seems to work pretty well), but I run into an error with the `model_train` binary such that this command works:

```bash
GCS_PRETRAINED_MODEL="gs://deepvariant/models/DeepVariant/1.3.0/DeepVariant-inception_v3-1.3.0+data-wgs_standard/model.ckpt"

singularity exec --nv ~/bin/deepvariant-1.3.0-gpu.simg \
/opt/deepvariant/bin/model_train \
--dataset_config_pbtxt="examples/training_set.dataset_config.pbtxt" \
--train_dir="training" \
--model_name="inception_v3" \
--number_of_steps=900 \
--save_interval_secs=300 \
--start_from_checkpoint="${GCS_PRETRAINED_MODEL}"
```

But, when I try the following

 ```bash
GCS_PRETRAINED_MODEL="gs://deepvariant/models/DeepVariant/1.3.0/DeepVariant-inception_v3-1.3.0+data-pacbio_standard/model.ckpt"

singularity exec --nv ~/bin/deepvariant-1.3.0-gpu.simg \
/opt/deepvariant/bin/model_train \
--dataset_config_pbtxt="examples/training_set.dataset_config.pbtxt" \
--train_dir="training" \
--model_name="inception_v3" \
--number_of_steps=900 \
--save_interval_secs=300 \
--start_from_checkpoint="${GCS_PRETRAINED_MODEL}"
```
I get the following error presumably because the `model_train` binary does make the correct tensor shape for the PacBio model's checkpoint?

```python
Warm-starting variables only in TRAINABLE_VARIABLES.
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_eh_1d4ep/runfiles/com_google_deepvariant/deepvariant/model_train.py", line 298, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/tmp/Bazel.runfiles_eh_1d4ep/runfiles/absl_py/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_eh_1d4ep/runfiles/absl_py/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_eh_1d4ep/runfiles/com_google_deepvariant/deepvariant/model_train.py", line 283, in main
    parse_and_run()
  File "/tmp/Bazel.runfiles_eh_1d4ep/runfiles/com_google_deepvariant/deepvariant/model_train.py", line 229, in parse_and_run
    return run(
  File "/tmp/Bazel.runfiles_eh_1d4ep/runfiles/com_google_deepvariant/deepvariant/model_train.py", line 191, in run
    estimator.train(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1206, in _train_model_default
    return self._train_with_estimator_spec(estimator_spec, worker_hooks,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1388, in _train_with_estimator_spec
    tf.compat.v1.train.warm_start(*self._warm_start_settings)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/training/warm_starting_util.py", line 532, in warm_start
    checkpoint_utils.init_from_checkpoint(ckpt_to_initialize_from, vocabless_vars)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/training/checkpoint_utils.py", line 311, in init_from_checkpoint
    distribution_strategy_context.get_replica_context().merge_call(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 3048, in merge_call
    return self._merge_call(merge_fn, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 3055, in _merge_call
    return merge_fn(self._strategy, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/autograph/impl/api.py", line 597, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/training/checkpoint_utils.py", line 306, in <lambda>
    init_from_checkpoint_fn = lambda _: _init_from_checkpoint(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/training/checkpoint_utils.py", line 347, in _init_from_checkpoint
    raise ValueError(
ValueError: Shape of variable InceptionV3/Conv2d_1a_3x3/weights:0 ((3, 3, 6, 32)) doesn't match with shape of tensor InceptionV3/Conv2d_1a_3x3/weights ([3, 3, 9, 32]) from checkpoint reader.
```

How does one specify the shape in `model_train`?

**Comment by jelber2** [comment]
My apologies, I guess I needed to edit my command for the make_examples

      /opt/deepvariant/bin/make_examples \
      --mode training \
      --ref reference.fasta \
      --reads 3-to-reference.bam \
      --examples examples/training_set.with_label.tfrecord.gz \
      --confident_regions reference.bed \
      --truth_variants 3-asm.paf.vcf.gz \
      --sort_by_haplotypes=false --parse_sam_aux_fields=false --add_hp_channel=true --alt_aligned_pileup=diff_channels

Such that I now included the `bottom line` of the above command (my BAMs do not need to be phased for this model for haploid organisms I guess?)
