### ISSUE TITLE
The same script runs successfully on Chr5 but not on the other 4 chromosomes

### ISSUE THREAD

**Issue by justdx** [google/deepvariant#548]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.4/docs/FAQ.md**:

**Describe the issue:**
The same script runs successfully on Chr5 but not on the other 4 chromosomes.

**Setup**
  - Operating system: Debian GNU/Linux 9
  - DeepVariant version: 1.4.0
  - Installation method (Docker, built from source, etc.):
  - Type of data: hybrid of Illumina and HiFi data, the reference is the assembly based on the hifi reads

**Steps to reproduce:**
  - Command: singularity run --bind ${PWD} \
/software/deepvariant/deepvariant.img \
/opt/deepvariant/bin/run_deepvariant \
--model_type HYBRID_PACBIO_ILLUMINA \
--ref ragtag.fasta \
--reads hifi_illu.bam \
--intermediate_results_dir ./tmp \
--output_vcf rep1.hifi-illu.Chr1.vcf.gz \
--num_shards 4 \
--regions Chr1_RagTag

  - Error trace:  Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/client/session.py", line 1380, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/client/session.py", line 1363, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/client/session.py", line 1456, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.DataLossError: inflate() failed with error -3: invalid literal/length code
     [[{{node IteratorGetNext}}]]

**Comment by akolesnikov** [comment]
This error is most likely due to the corrupted tf records file which is the output of call_variants step. In your set up the intermediate results are dumped into /tmp. Could it be that you ran multiple instances of deepvariant  simultaneously with the same output directory?
