### ISSUE TITLE
Dynamic cast failed

### ISSUE THREAD

**Issue by tahashmi** [google/deepvariant#559]
I am trying to run this PacBio use case and encountered following error: 
https://github.com/google/deepvariant/blob/r1.4/docs/deepvariant-pacbio-model-case-study.md

Any hint/info to solve this issue? 

```
INFO:    Using cached SIF image
I0828 10:16:33.630316 22957909862208 run_deepvariant.py:342] Re-using the directory for intermediate results in /scratch-local/tahmad.1459036/tmpcy60f694

***** Intermediate results will be written to /scratch-local/tahmad.1459036/tmpcy60f694 in docker. ****


***** Running the command:*****
time seq 0 71 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "reference/GRCh38_no_alt_analysis_set.fasta" --reads "input/HG003.GRCh38.chr20.pFDA_truthv2.bam" --examples "/scratch-local/tahmad.1459036/tmpcy60f694/make_examples.tfrecord@72.gz" --add_hp_channel --alt_aligned_pileup "diff_channels" --max_reads_per_partition "600" --min_mapping_quality "1" --parse_sam_aux_fields --partition_size "25000" --phase_reads --pileup_image_width "199" --norealign_reads --regions "chr20" --sort_by_haplotypes --track_ref_reads --vsc_min_fraction_indels "0.12" --task {}

2022-08-28 10:16:41.685530: W third_party/nucleus/io/sam_reader.cc:131] Unknown tag pb: in header line, ignoring: @HD   VN:1.9  SO:coordinate   pb:3.0.7
I0828 10:16:41.685937 22858289674048 genomics_reader.py:222] Reading input/HG003.GRCh38.chr20.pFDA_truthv2.bam with NativeSamReader
I0828 10:16:41.693562 22858289674048 make_examples_core.py:243] Task 0/72: Preparing inputs
2022-08-28 10:16:41.685378: W third_party/nucleus/io/sam_reader.cc:131] Unknown tag pb: in header line, ignoring: @HD   VN:1.9  SO:coordinate   pb:3.0.7
I0828 10:16:41.685891 23090607179584 genomics_reader.py:222] Reading input/HG003.GRCh38.chr20.pFDA_truthv2.bam with NativeSamReader
I0828 10:16:41.693572 23090607179584 make_examples_core.py:243] Task 51/72: Preparing inputs
2022-08-28 10:16:41.910178: W third_party/nucleus/io/sam_reader.cc:131] Unknown tag pb: in header line, ignoring: @HD   VN:1.9  SO:coordinate   pb:3.0.7
I0828 10:16:41.910383 22858289674048 genomics_reader.py:222] Reading input/HG003.GRCh38.chr20.pFDA_truthv2.bam with NativeSamReader
I0828 10:16:41.917916 22858289674048 make_examples_core.py:243] Task 0/72: Common contigs are ['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20', 'chr21', 'chr22', 'chrX', 'chrY', 'chrM']
I0828 10:16:41.927865 22858289674048 make_examples_core.py:243] Task 0/72: Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2022-08-28 10:16:41.928017: I third_party/nucleus/io/sam_reader.cc:736] Setting HTS_OPT_BLOCK_SIZE to 134217728
2022-08-28 10:16:41.910192: W third_party/nucleus/io/sam_reader.cc:131] Unknown tag pb: in header line, ignoring: @HD   VN:1.9  SO:coordinate   pb:3.0.7
I0828 10:16:41.910406 23090607179584 genomics_reader.py:222] Reading input/HG003.GRCh38.chr20.pFDA_truthv2.bam with NativeSamReader
I0828 10:16:41.918358 23090607179584 make_examples_core.py:243] Task 51/72: Common contigs are ['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20', 'chr21', 'chr22', 'chrX', 'chrY', 'chrM']
I0828 10:16:41.928208 23090607179584 make_examples_core.py:243] Task 51/72: Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2022-08-28 10:16:41.928362: I third_party/nucleus/io/sam_reader.cc:736] Setting HTS_OPT_BLOCK_SIZE to 134217728
2022-08-28 10:16:42.297998: W third_party/nucleus/io/sam_reader.cc:131] Unknown tag pb: in header line, ignoring: @HD   VN:1.9  SO:coordinate   pb:3.0.7
I0828 10:16:42.298424 22358796187456 genomics_reader.py:222] Reading input/HG003.GRCh38.chr20.pFDA_truthv2.bam with NativeSamReader
I0828 10:16:42.304855 22358796187456 make_examples_core.py:243] Task 9/72: Preparing inputs
2022-08-28 10:16:42.306635: W third_party/nucleus/io/sam_reader.cc:131] Unknown tag pb: in header line, ignoring: @HD   VN:1.9  SO:coordinate   pb:3.0.7
I0828 10:16:42.306837 22358796187456 genomics_reader.py:222] Reading input/HG003.GRCh38.chr20.pFDA_truthv2.bam with NativeSamReader
I0828 10:16:42.314611 22358796187456 make_examples_core.py:243] Task 9/72: Common contigs are ['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20', 'chr21', 'chr22', 'chrX', 'chrY', 'chrM']
I0828 10:16:42.324295 22358796187456 make_examples_core.py:243] Task 9/72: Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2022-08-28 10:16:42.324449: I third_party/nucleus/io/sam_reader.cc:736] Setting HTS_OPT_BLOCK_SIZE to 134217728
2022-08-28 10:16:42.229368: W third_party/nucleus/io/sam_reader.cc:131] Unknown tag pb: in header line, ignoring: @HD   VN:1.9  SO:coordinate   pb:3.0.7
I0828 10:16:42.229775 22823217350464 genomics_reader.py:222] Reading input/HG003.GRCh38.chr20.pFDA_truthv2.bam with NativeSamReader
I0828 10:16:42.236391 22823217350464 make_examples_core.py:243] Task 16/72: Preparing inputs
2022-08-28 10:16:42.257786: W third_party/nucleus/io/sam_reader.cc:131] Unknown tag pb: in header line, ignoring: @HD   VN:1.9  SO:coordinate   pb:3.0.7
I0828 10:16:42.257981 22823217350464 genomics_reader.py:222] Reading input/HG003.GRCh38.chr20.pFDA_truthv2.bam with NativeSamReader
I0828 10:16:42.265606 22823217350464 make_examples_core.py:243] Task 16/72: Common contigs are ['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20', 'chr21', 'chr22', 'chrX', 'chrY', 'chrM']
I0828 10:16:42.275274 22823217350464 make_examples_core.py:243] Task 16/72: Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2022-08-28 10:16:42.275424: I third_party/nucleus/io/sam_reader.cc:736] Setting HTS_OPT_BLOCK_SIZE to 134217728
2022-08-28 10:16:42.621521: W third_party/nucleus/io/sam_reader.cc:131] Unknown tag pb: in header line, ignoring: @HD   VN:1.9  SO:coordinate   pb:3.0.7
I0828 10:16:42.621896 22858289674048 genomics_reader.py:222] Reading input/HG003.GRCh38.chr20.pFDA_truthv2.bam with NativeSamReader
2022-08-28 10:16:42.702562: W third_party/nucleus/io/sam_reader.cc:131] Unknown tag pb: in header line, ignoring: @HD   VN:1.9  SO:coordinate   pb:3.0.7
I0828 10:16:42.702797 22858289674048 genomics_reader.py:222] Reading input/HG003.GRCh38.chr20.pFDA_truthv2.bam with NativeSamReader
I0828 10:16:42.727535 22858289674048 make_examples_core.py:243] Task 0/72: Writing examples to /scratch-local/tahmad.1459036/tmpcy60f694/make_examples.tfrecord-00000-of-00072.gz
I0828 10:16:42.727609 22858289674048 make_examples_core.py:243] Task 0/72: Overhead for preparing inputs: 1 seconds
2022-08-28 10:16:42.748975: W ./third_party/nucleus/util/proto_clif_converter.h:75] Failed to cast type N6google8protobuf14DynamicMessageE
Traceback (most recent call last):
  File "/scratch-local/tahmad.1459036/Bazel.runfiles_w_myh_2e/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 180, in <module>
    app.run(main)
  File "/scratch-local/tahmad.1459036/Bazel.runfiles_w_myh_2e/runfiles/absl_py/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/scratch-local/tahmad.1459036/Bazel.runfiles_w_myh_2e/runfiles/absl_py/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/scratch-local/tahmad.1459036/Bazel.runfiles_w_myh_2e/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 170, in main
    make_examples_core.make_examples_runner(options)
  File "/scratch-local/tahmad.1459036/Bazel.runfiles_w_myh_2e/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1795, in make_examples_runner
    runtimes) = region_processor.process(region)
  File "/scratch-local/tahmad.1459036/Bazel.runfiles_w_myh_2e/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1123, in process
    reads = self.region_reads(
  File "/scratch-local/tahmad.1459036/Bazel.runfiles_w_myh_2e/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1200, in region_reads
    reads.extend(sam_reader.query(region))
  File "/scratch-local/tahmad.1459036/Bazel.runfiles_w_myh_2e/runfiles/com_google_deepvariant/third_party/nucleus/io/clif_postproc.py", line 82, in __next__
    record, not_done = self._raw_next()
  File "/scratch-local/tahmad.1459036/Bazel.runfiles_w_myh_2e/runfiles/com_google_deepvariant/third_party/nucleus/io/clif_postproc.py", line 141, in _raw_next
    not_done = self._cc_iterable.PythonNext(record)
RuntimeError: PythonNext() argument read is not valid: Dynamic cast failed
2022-08-28 10:16:42.621554: W third_party/nucleus/io/sam_reader.cc:131] Unknown tag pb: in header line, ignoring: @HD   VN:1.9  SO:coordinate   pb:3.0.7
I0828 10:16:42.621905 23090607179584 genomics_reader.py:222] Reading input/HG003.GRCh38.chr20.pFDA_truthv2.bam with NativeSamReader
2022-08-28 10:16:42.705882: W third_party/nucleus/io/sam_reader.cc:131] Unknown tag pb: in header line, ignoring: @HD   VN:1.9  SO:coordinate   pb:3.0.7
I0828 10:16:42.706136 23090607179584 genomics_reader.py:222] Reading input/HG003.GRCh38.chr20.pFDA_truthv2.bam with NativeSamReader
I0828 10:16:42.727798 23090607179584 make_examples_core.py:243] Task 51/72: Writing examples to /scratch-local/tahmad.1459036/tmpcy60f694/make_examples.tfrecord-00051-of-00072.gz
I0828 10:16:42.727886 23090607179584 make_examples_core.py:243] Task 51/72: Overhead for preparing inputs: 1 seconds
2022-08-28 10:16:42.768980: W ./third_party/nucleus/util/proto_clif_converter.h:75] Failed to cast type N6google8protobuf14DynamicMessageE
Traceback (most recent call last):
  File "/scratch-local/tahmad.1459036/Bazel.runfiles_v_r0zvkm/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 180, in <module>
    app.run(main)
  File "/scratch-local/tahmad.1459036/Bazel.runfiles_v_r0zvkm/runfiles/absl_py/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/scratch-local/tahmad.1459036/Bazel.runfiles_v_r0zvkm/runfiles/absl_py/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/scratch-local/tahmad.1459036/Bazel.runfiles_v_r0zvkm/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 170, in main
    make_examples_core.make_examples_runner(options)
  File "/scratch-local/tahmad.1459036/Bazel.runfiles_v_r0zvkm/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1795, in make_examples_runner
    runtimes) = region_processor.process(region)
  File "/scratch-local/tahmad.1459036/Bazel.runfiles_v_r0zvkm/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1123, in process
    reads = self.region_reads(
  File "/scratch-local/tahmad.1459036/Bazel.runfiles_v_r0zvkm/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1200, in region_reads
    reads.extend(sam_reader.query(region))
  File "/scratch-local/tahmad.1459036/Bazel.runfiles_v_r0zvkm/runfiles/com_google_deepvariant/third_party/nucleus/io/clif_postproc.py", line 82, in __next__
    record, not_done = self._raw_next()
  File "/scratch-local/tahmad.1459036/Bazel.runfiles_v_r0zvkm/runfiles/com_google_deepvariant/third_party/nucleus/io/clif_postproc.py", line 141, in _raw_next
    not_done = self._cc_iterable.PythonNext(record)
RuntimeError: PythonNext() argument read is not valid: Dynamic cast failed
2022-08-28 10:16:42.783298: W third_party/nucleus/io/sam_reader.cc:131] Unknown tag pb: in header line, ignoring: @HD   VN:1.9  SO:coordinate   pb:3.0.7
I0828 10:16:42.783742 22429787215680 genomics_reader.py:222] Reading input/HG003.GRCh38.chr20.pFDA_truthv2.bam with NativeSamReader
I0828 10:16:42.790578 22429787215680 make_examples_core.py:243] Task 35/72: Preparing inputs
2022-08-28 10:16:42.806732: W third_party/nucleus/io/sam_reader.cc:131] Unknown tag pb: in header line, ignoring: @HD   VN:1.9  SO:coordinate   pb:3.0.7
I0828 10:16:42.806946 22429787215680 genomics_reader.py:222] Reading input/HG003.GRCh38.chr20.pFDA_truthv2.bam with NativeSamReader
I0828 10:16:42.814701 22429787215680 make_examples_core.py:243] Task 35/72: Common contigs are ['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20', 'chr21', 'chr22', 'chrX', 'chrY', 'chrM']
I0828 10:16:42.824596 22429787215680 make_examples_core.py:243] Task 35/72: Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2022-08-28 10:16:42.824762: I third_party/nucleus/io/sam_reader.cc:736] Setting HTS_OPT_BLOCK_SIZE to 134217728
2022-08-28 10:16:42.621537: W third_party/nucleus/io/sam_reader.cc:131] Unknown tag pb: in header line, ignoring: @HD   VN:1.9  SO:coordinate   pb:3.0.7
I0828 10:16:42.621887 22358796187456 genomics_reader.py:222] Reading input/HG003.GRCh38.chr20.pFDA_truthv2.bam with NativeSamReader
2022-08-28 10:16:42.702981: W third_party/nucleus/io/sam_reader.cc:131] Unknown tag pb: in header line, ignoring: @HD   VN:1.9  SO:coordinate   pb:3.0.7
```

**Comment by kishwarshafin** [comment]
@tahashmi,

It looks like [nucleus](https://github.com/google/nucleus) is having issues with the newer tensorflow version you installed. I'm not exactly sure why your installing tensorflow locally fixed the issue. Can you please see if you install nucleus locally, it fixes it:
```
pip install --user google-nucleus
```

**Comment by pichuan** [comment]
I'm closing this issue. Feel free to open another issue if you still have any questions. Thanks!
