### ISSUE TITLE
Could not open BAM

### ISSUE THREAD

**Issue by imdanique** [google/deepvariant#577]
Hi! 

I have a problem that docker can't find BAM file:

```bash
[E::hts_open_format] Failed to open file "/data/deepvariant/test_bam/DP8400014945BR_L01_541.picard_MD.bam" : No such file or directory
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_wjhib79c/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 180, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_wjhib79c/runfiles/absl_py/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_wjhib79c/runfiles/absl_py/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_wjhib79c/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 166, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/tmp/Bazel.runfiles_wjhib79c/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 128, in default_options
    samples_in_order, sample_role_to_train = one_sample_from_flags(
  File "/tmp/Bazel.runfiles_wjhib79c/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 85, in one_sample_from_flags
    sample_name = make_examples_core.assign_sample_name(
  File "/tmp/Bazel.runfiles_wjhib79c/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 134, in assign_sample_name
    with sam.SamReader(reads_filenames.split(',')[0]) as sam_reader:
  File "/tmp/Bazel.runfiles_wjhib79c/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 221, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_wjhib79c/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 260, in _native_reader
    return NativeSamReader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_wjhib79c/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 227, in __init__
    self._reader = sam_reader.SamReader.from_file(
ValueError: NOT_FOUND: Could not open /data/deepvariant/test_bam/DP8400014945BR_L01_541.picard_MD.bam
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /data/PublicData/hg38/GCA_000001405.15_GRCh38_no_alt_cleaned.fna --reads /data/deepvariant/test_bam/DP8400014945BR_L01_541.picard_MD.bam --examples /tmp/tmpq8fl_xv9/make_examples.tfrecord@1.gz --channels insert_size --gvcf /tmp/tmpq8fl_xv9/gvcf.tfrecord@1.gz --task 0

real	0m2.791s
user	0m5.497s
sys	0m4.089s

```

Here is my .sh file that i'm running:

```bash

 #!/bin/bash
  
BIN_VERSION="1.4.0"
docker run --gpus all \
        -v "${INPUT_DIR}":"/data/deepvariant/test_bam" \
        -v "${OUTPUT_DIR}":"/data/deepvariant/output" \
        -v "${REF}":"/data/PublicData/hg38" \
            google/deepvariant:"${BIN_VERSION}" \
            /opt/deepvariant/bin/run_deepvariant \
        --model_type=WGS \
        --ref=/data/PublicData/hg38/GCA_000001405.15_GRCh38_no_alt_cleaned.fna \
        --reads=/data/deepvariant/test_bam/DP8400014945BR_L01_541.picard_MD.bam \
        --output_vcf=/data/deepvariant/output/output.vcf.gz \
        --output_gvcf=/data/deepvariant/output/output.g.vcf.gz \
```

I suppose that's a problem with mounting a directory to docker, however I don't understand what's incorrect in my code. Could you help me please?

**Comment by akolesnikov** [comment]
$INPUT_DIR should exist on your local machine. It should contain all the expected input files. Binding your local directories to directories inside a container is done through -v option:
```
-v / --volume - Binds a volume. You can specify a path and a corresponding path inside your container. 
```

**Comment by imdanique** [comment]
@akolesnikov 
Thank you for the answer. All paths (both directories and fiels) that I included in my script do exist. Still, it shows me an error as file doesn't exist as I wrote in my first message above

**Comment by pichuan** [comment]
@imdanique 

If you run something like:

```
BIN_VERSION="1.4.0"
docker run --gpus all \
        -v "${INPUT_DIR}":"/data/deepvariant/test_bam" \
        -v "${OUTPUT_DIR}":"/data/deepvariant/output" \
        -v "${REF}":"/data/PublicData/hg38" \
            google/deepvariant:"${BIN_VERSION}" \
            ls /data/deepvariant/test_bam/DP8400014945BR_L01_541.picard_MD.bam
```

Can you see the file?

This will help us understand whether the docker filesystem can actually see the file.

Or, try:

```
BIN_VERSION="1.4.0"
docker run --gpus all \
        -v "${INPUT_DIR}":"/data/deepvariant/test_bam" \
        -v "${OUTPUT_DIR}":"/data/deepvariant/output" \
        -v "${REF}":"/data/PublicData/hg38" \
            google/deepvariant:"${BIN_VERSION}" \
            ls /data/deepvariant/test_bam/
```

**Comment by imdanique** [comment]
@pichuan 
"""bash ls: cannot access '/data/dkarabayev/deepvariant/test_bam/': No such file or directory"""

**Comment by imdanique** [comment]
@pichuan 
When I run ec, the output is empty. 
When I run
```bash
 ls  ${INPUT_DIR}
```
it shows a list of files of pwd, but not /data/deepvariant/test_bam/. If I run the script from /data/deepvariant directory, then it shows me files in /data/deepvariant, and if I run it from /data, then it shows me ls of /data

**Comment by pichuan** [comment]
Hi @imdanique ,
Thanks for the update.
Can try to get to a point where when you run the docker command, your ls can see the file? Because if the ls command can't list the file, that means deepvariant binary would have no chance to find the file.
Does that make sense?
To diagnose the problem, maybe simplifying the script or script to remove the use of variables could help too, in case they were not set correctly.

**Comment by pichuan** [comment]
Hi @imdanique ,
I'll be closing this issue now. Please feel free to reopen or open a new issue if you have other questions.

**Comment by DirtyPawss** [comment]
Hello, 
I have encountered the same problem as mentioned in this issue. 
And I have also tried the solutions provided above, but the deepvariant binary still cannot see the bam files.
The version I'm using is: google/deepvariant:"1.5.0".
Here is the command i run:
```
docker run \
  -v "/data2/share/home/liyi/TEs/dv/input":"/input" \
  -v "/data2/share/home/liyi/TEs/dv/output":"/output" \
  google/deepvariant:"1.5.0" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref=/data2/share/home/liyi/TEs/dv/input/C162-2_final.fasta \
  --reads=/data2/share/home/liyi/TEs/dv/input/C111_mapped.bam \
  --output_vcf=/data2/share/home/liyi/TEs/dv/output/C111.vcf.gz \
  --output_gvcf=/data2/share/home/liyi/TEs/dv/output/C111.g.vcf.gz \
  --intermediate_results_dir /data2/share/home/liyi/TEs/dv/output/intermediate_results_dir \
  --num_shards=5
```
The error output is: 
```
[E::hts_open_format] Failed to open file "/data2/share/home/liyi/TEs/dv/input/C111_mapped.bam" : No such file or directory
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_3_jead3w/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 196, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_3_jead3w/runfiles/absl_py/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_3_jead3w/runfiles/absl_py/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_3_jead3w/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 182, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/tmp/Bazel.runfiles_3_jead3w/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 133, in default_options
    samples_in_order, sample_role_to_train = one_sample_from_flags(
  File "/tmp/Bazel.runfiles_3_jead3w/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 88, in one_sample_from_flags
    sample_name = make_examples_core.assign_sample_name(
  File "/tmp/Bazel.runfiles_3_jead3w/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 147, in assign_sample_name
    with sam.SamReader(reads_filenames.split(',')[0]) as sam_reader:
  File "/tmp/Bazel.runfiles_3_jead3w/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 221, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_3_jead3w/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 260, in _native_reader
    return NativeSamReader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_3_jead3w/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 227, in __init__
    self._reader = sam_reader.SamReader.from_file(
ValueError: NOT_FOUND: Could not open /data2/share/home/liyi/TEs/dv/input/C111_mapped.bam
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /data2/share/home/liyi/TEs/dv/input/C162-2_final.fasta --reads /data2/share/home/liyi/TEs/dv/input/C111_mapped.bam --examples /data2/share/home/liyi/TEs/dv/output/intermediate_results_dir/make_examples.tfrecord@5.gz --channels insert_size --gvcf /data2/share/home/liyi/TEs/dv/output/intermediate_results_dir/gvcf.tfrecord@5.gz --task 0

real	0m3.521s
user	0m3.689s
sys	0m3.908s
```
Is there any other solutions, Could you please help?

**Comment by pgrosu** [comment]
Hi @LiYi0604,

Just change your script to the following, and it should run:

```
docker run \
  -v "/data2/share/home/liyi/TEs/dv/input":"/input" \
  -v "/data2/share/home/liyi/TEs/dv/output":"/output" \
  google/deepvariant:"1.5.0" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref=/input/C162-2_final.fasta \
  --reads=/input/C111_mapped.bam \
  --output_vcf=/output/C111.vcf.gz \
  --output_gvcf=/output/C111.g.vcf.gz \
  --intermediate_results_dir /output/intermediate_results_dir \
  --num_shards=5
```

Basically `"/data2/share/home/liyi/TEs/dv/input":"/input"` makes the folder available inside the docker container as `/input`, so you don't need the long name.

Hope it helps,
Paul

**Comment by LiYi0604** [comment]
@pgrosu 
Thanks for the answer.
I've tried this command, and it got the same error.
```
[E::hts_open_format] Failed to open file "/input/C111_mapped.bam" : No such file or directory
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_g1m5s08g/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 196, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_g1m5s08g/runfiles/absl_py/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_g1m5s08g/runfiles/absl_py/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_g1m5s08g/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 182, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/tmp/Bazel.runfiles_g1m5s08g/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 133, in default_options
    samples_in_order, sample_role_to_train = one_sample_from_flags(
  File "/tmp/Bazel.runfiles_g1m5s08g/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 88, in one_sample_from_flags
    sample_name = make_examples_core.assign_sample_name(
  File "/tmp/Bazel.runfiles_g1m5s08g/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 147, in assign_sample_name
    with sam.SamReader(reads_filenames.split(',')[0]) as sam_reader:
  File "/tmp/Bazel.runfiles_g1m5s08g/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 221, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_g1m5s08g/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 260, in _native_reader
    return NativeSamReader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_g1m5s08g/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 227, in __init__
    self._reader = sam_reader.SamReader.from_file(
ValueError: NOT_FOUND: Could not open /input/C111_mapped.bam
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /input/C162-2_final.fasta --reads /input/C111_mapped.bam --examples /output/intermediate_results_dir/make_examples.tfrecord@5.gz --channels insert_size --gvcf /output/intermediate_results_dir/gvcf.tfrecord@5.gz --task 1

real	0m3.507s
user	0m3.304s
sys	0m2.638s

```

**Comment by pgrosu** [comment]
Hi @LiYi0604,

Another user is having a similar issue as well (https://github.com/google/deepvariant/issues/184#issuecomment-1700285417).  Could you try this instead to see if you see the files:

```
docker run \
  --mount type=bind,source="/data2/share/home/liyi/TEs/dv/input",target="/input" \
  google/deepvariant:"1.5.0" ls -l /input
```

It's an interesting new behavior that shouldn't be happening.  What operating system are your running this on?

Thanks,
Paul

**Comment by LiYi0604** [comment]
Hi Paul,
Sorry for the late reply, the server has just completed rebooting.

I ran the code, and the output is:
```
lrwxrwxrwx 1 1010 1010 66 Aug 31 02:25 C111_mapped.bam -> /data2/share/home/liyi/TEs/Pan-genome/Giraffe/C111/C111_mapped.bam
lrwxrwxrwx 1 1010 1010 58 Aug 31 02:25 C162-2_final.fasta -> /data2/share/home/liyi/TEs/Genome/fasta/C162-2_final.fasta
```
Looks the docker knows where the file is.

And this is my Linux info and docker version:
```
Linux mgr 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Docker version 18.03.1-ce, build 9ee9f40
```
I'm new to Linux, hoping this can provide useful information.

Thanks, 
LiYi

**Comment by pgrosu** [comment]
Hi LiYi,

No worries, and this is very helpful!  So this is a good sign, but here's the issue.  The files in `/data2/share/home/liyi/TEs/dv/input` actually point to other directories that are not connected to Docker.  It is best to just refer to them directly.  For that I've updated your script to the following:

```
docker run \
  -v "/data2/share/home/liyi/TEs/Pan-genome/Giraffe/C111":"/input" \
  -v "/data2/share/home/liyi/TEs/dv/output":"/output" \
  -v "/data2/share/home/liyi/TEs/Genome/fasta":"/fasta" \
  google/deepvariant:"1.5.0" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref=/fasta/C162-2_final.fasta \
  --reads=/input/C111_mapped.bam \
  --output_vcf=/output/C111.vcf.gz \
  --output_gvcf=/output/C111.g.vcf.gz \
  --intermediate_results_dir /output/intermediate_results_dir \
  --num_shards=5

```

Let me know if this works for you.

Thanks,
Paul

**Comment by LiYi0604** [comment]
Hi Paul, 
Thank you for the answer, it works!
Although I still got some error about the format of BAM file, I can try if I can resolve it on my own.

Thanks again!
LiYi

**Comment by pgrosu** [comment]
Hi LiYi,

Awesome!  Please don't hesitate to reach out again if you have more questions.

You're welcome :)
Paul
