### ISSUE TITLE
Singularity GPU Quick Start TypeError: bases must be types

### ISSUE THREAD

**Issue by weilu1998** [google/deepvariant#580]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.4/docs/FAQ.md**:
Yes

**Describe the issue:**
I was following the quick start guide for running singularity on a gpu node. Initially, I encounter the dynamic cast failed error similar to #559 . After installing the google-nucleus package, I encountered this new error about protobuf package. I tried protobuf version 3.20.3 and 4.21.9, but the error message is the same. In order to run DeepVariant successfully, what additional packages (version) should I install besides cloning the singularity image?

**Setup**
  - Operating system: 
  - DeepVariant version: 1.4.0
  - Installation method: singularity
  - Type of data: quick start test
  
**Steps to reproduce:**
 
```
SINGULARITY_TMPDIR=/scratch/midway3/weilu1/tmp SINGULARITY_CACHEDIR=/scratch/midway3/weilu1/cache singularity run --nv -B /usr/lib/locale/:/usr/lib/locale/ \
  deepvariant_1.4.0-gpu.sif \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref="${INPUT_DIR}"/ucsc.hg19.chr20.unittest.fasta \
  --reads="${INPUT_DIR}"/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf="${OUTPUT_DIR}"/output.vcf.gz \
  --output_gvcf="${OUTPUT_DIR}"/output.g.vcf.gz \
  --intermediate_results_dir "${OUTPUT_DIR}/intermediate_results_dir" \
  --num_shards=1

INFO:    Converting SIF file to temporary sandbox...
WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (469) bind mounts
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 48, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/__init__.py", line 41, in <module>
    from tensorflow.python.eager import context
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/context.py", line 33, in <module>
    from tensorflow.core.framework import function_pb2
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/core/framework/function_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/home/weilu1/.local/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 40, in <module>
    from google.protobuf.internal import api_implementation
  File "/home/weilu1/.local/lib/python3.8/site-packages/google/protobuf/internal/api_implementation.py", line 104, in <module>
    from google.protobuf.pyext import _message
TypeError: bases must be types
INFO:    Cleaning up image...
```

**Comment by danielecook** [comment]
@weilu1998 you shouldn't have to install any additional software if you are using singularity.

Can you try running singularity using the `--cleanenv` flag?

**Comment by weilu1998** [comment]
Hi @danielecook ,

Thanks for the reply. I retried adding --cleanenv flag and get the same error. I also cleanup the tmp folder. Here is the command I tried.

```
SINGULARITY_TMPDIR=/scratch/midway3/weilu1/tmp SINGULARITY_CACHEDIR=/scratch/midway3/weilu1/tmp singularity run --cleanenv --nv -B /usr/lib/locale/:/usr/lib/locale/ \
  deepvariant_1.4.0-gpu.sif \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref="${INPUT_DIR}"/ucsc.hg19.chr20.unittest.fasta \
  --reads="${INPUT_DIR}"/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf="${OUTPUT_DIR}"/output.vcf.gz \
  --output_gvcf="${OUTPUT_DIR}"/output.g.vcf.gz \
  --intermediate_results_dir "${OUTPUT_DIR}/intermediate_results_dir" \
  --num_shards=1

```

**Comment by danielecook** [comment]
Does the message still appear to indicate that it is using libraries installed on your machine rather than those present in the container?

**Comment by weilu1998** [comment]
Yes, the error log is the same. I also added `unset PYTHONPATH` before the singularity command. How can I prevent it from 
using the local libraries? 

```
INFO:    Converting SIF file to temporary sandbox...
WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (469) bind mounts
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 48, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/__init__.py", line 41, in <module>
    from tensorflow.python.eager import context
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/context.py", line 33, in <module>
    from tensorflow.core.framework import function_pb2
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/core/framework/function_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/home/weilu1/.local/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 40, in <module>
    from google.protobuf.internal import api_implementation
  File "/home/weilu1/.local/lib/python3.8/site-packages/google/protobuf/internal/api_implementation.py", line 104, in <module>
    from google.protobuf.pyext import _message
TypeError: bases must be types
INFO:    Cleaning up image...
```

**Comment by danielecook** [comment]
I am guessing it could be related to the use of the `--nv` flag ([docs](https://docs.sylabs.io/guides/3.5/user-guide/gpu.html)), but I am not familiar with using GPUs with singularity containers.

This [guide](https://modinst.lu.lv/wp-content/uploads/2021/03/Singularity_seminars_Aleksandrs_Gutcaits.pdf) suggests unsetting the `LD_LIBRARY_PATH`.  Which version of singularity are you using?

**Comment by weilu1998** [comment]
Thanks for the reply! @danielecook I used singularity 3.7.1, adding the `LD_LIBRARY_PATH=""` doesn't change the output.

**Comment by weilu1998** [comment]
Adding a `--no-home` flag for singularity solved the issue!

**Comment by danielecook** [comment]
Excellent! Thank you for following up with the solution!
