### ISSUE TITLE
Running Issue DeepVariant

### ISSUE THREAD

**Issue by 543090lee** [google/deepvariant#585]
Hello,
I am running Deepvariant and facing an issue.

PS C:\Users\Seungmo Lee\Desktop\researchProj> docker run -v C:\Users\Seungmo` Lee\Desktop\researchProj:/input -v C:\Users\Seungmo` Lee\Desktop\researchProj:/output google/deepvariant /opt/deepvariant/bin/run_deepvariant --model_type=WGS --ref=/input/chr19_new.fa --reads=/input/A_J.chr19.bam --output_vcf=/output --output_gvcf=/output --num_shards=2 --dry_run=false
I1114 07:56:43.730724 140466373666624 run_deepvariant.py:342] Re-using the directory for intermediate results in /tmp/tmpr4ux434h

***** Intermediate results will be written to /tmp/tmpr4ux434h in docker. ****

***** Running the command:*****
time seq 0 1 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/chr19_new.fa" --reads "/input/A_J.chr19.bam" --examples "/tmp/tmpr4ux434h/make_examples.tfrecord@2.gz" --channels "insert_size" --gvcf "/tmp/tmpr4ux434h/gvcf.tfrecord@2.gz" --task {}

[E::idx_find_and_load] Could not retrieve index file for '/input/A_J.chr19.bam'
I1114 07:56:46.139676 140084824217408 genomics_reader.py:222] Reading /input/A_J.chr19.bam with NativeSamReader
I1114 07:56:46.142330 140084824217408 make_examples_core.py:243] Task 1/2: Preparing inputs
[E::fai_load3_core] Failed to open FASTA index /input/chr19_new.fa.fai: No such file or directory
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_2wmov4iu/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 180, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_2wmov4iu/runfiles/absl_py/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_2wmov4iu/runfiles/absl_py/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_2wmov4iu/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 170, in main
    make_examples_core.make_examples_runner(options)
  File "/tmp/Bazel.runfiles_2wmov4iu/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1746, in make_examples_runner
    regions = processing_regions_from_options(options)
  File "/tmp/Bazel.runfiles_2wmov4iu/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1653, in processing_regions_from_options
    ref_contigs = fasta.IndexedFastaReader(
  File "/tmp/Bazel.runfiles_2wmov4iu/runfiles/com_google_deepvariant/third_party/nucleus/io/fasta.py", line 105, in __init__
    self._reader = reference.IndexedFastaReader.from_file(
ValueError: NOT_FOUND: could not load fasta and/or fai for fasta /input/chr19_new.fa
[E::idx_find_and_load] Could not retrieve index file for '/input/A_J.chr19.bam'
I1114 07:56:46.139744 140275925796672 genomics_reader.py:222] Reading /input/A_J.chr19.bam with NativeSamReader
I1114 07:56:46.142346 140275925796672 make_examples_core.py:243] Task 0/2: Preparing inputs
[E::fai_load3_core] Failed to open FASTA index /input/chr19_new.fa.fai: No such file or directory
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_1n42qf4z/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 180, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_1n42qf4z/runfiles/absl_py/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_1n42qf4z/runfiles/absl_py/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_1n42qf4z/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 170, in main
    make_examples_core.make_examples_runner(options)
  File "/tmp/Bazel.runfiles_1n42qf4z/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1746, in make_examples_runner
    regions = processing_regions_from_options(options)
  File "/tmp/Bazel.runfiles_1n42qf4z/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1653, in processing_regions_from_options
    ref_contigs = fasta.IndexedFastaReader(
  File "/tmp/Bazel.runfiles_1n42qf4z/runfiles/com_google_deepvariant/third_party/nucleus/io/fasta.py", line 105, in __init__
    self._reader = reference.IndexedFastaReader.from_file(
ValueError: NOT_FOUND: could not load fasta and/or fai for fasta /input/chr19_new.fa
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /input/chr19_new.fa --reads /input/A_J.chr19.bam --examples /tmp/tmpr4ux434h/make_examples.tfrecord@2.gz --channels insert_size --gvcf /tmp/tmpr4ux434h/gvcf.tfrecord@2.gz --task 1

real    0m2.768s
user    0m2.534s
sys     0m0.541s

Thank you

**Comment by marchoeppner** [comment]
Not a deepvariant dev, but maybe Docker does not like your bind path (since it includes a blank in your name). At least it complains about not finding your inputs, which would suggest that the bind path is not working (assuming your files are otherwise where they should be). Maybe you can move the files to another location on your system and try again.

**Comment by pichuan** [comment]
Thank you @marchoeppner for helping here!

@543090lee it'll be great if you can check if you have the file chr19_new.fa under C:\Users\Seungmo Lee\Desktop\researchProj  , and to check wither Docker can see it (like @marchoeppner suggested)

My answer in this other issue might also be useful: https://github.com/google/deepvariant/issues/577#issuecomment-1285622624
