### ISSUE TITLE
deepvariant software installed using mamba does not run correctly ;lchmod error;No such file or directory: '/usr/bin/python3' error

### ISSUE THREAD

**Issue by Zero-Sun** [google/deepvariant#598]
Hi,
    I want to call variations on the Pacbio bam data to get gvcf files.
    But something went wrong with the program, and I spent two days wondering what went wrong. How do you solve this problem? 
    Please help!
    (No root permission;Centos7 x86;Only the user directory has read and write permission)
```
dv_make_examples.py --cores 3 --sample QJ --ref QJref.fa --reads F0F_sorted.merged.addg.uniq.rmdup.bam --logdir .  --examples EXAMPLES  --gvcf GVCF
```
```
Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence this citation notice: run 'parallel --citation'.


Computers / CPU cores / Max jobs to run
1:local / 48 / 3

Computer:jobs running/jobs completed/%of started jobs/Average seconds to complete
ETA: 0s Left: 3 AVG: 0.00s  local:3/0/100%/0.0s lchmod (file attributes) error: Function not implemented
lchmod (file attributes) error: Function not implemented
lchmod (file attributes) error: Function not implemented
lchmod (file attributes) error: Function not implemented
lchmod (file attributes) error: Function not implemented
lchmod (file attributes) error: Function not implemented
lchmod (file attributes) error: Function not implemented
lchmod (file attributes) error: Function not implemented
lchmod (file attributes) error: Function not implemented
lchmod (file attributes) error: Function not implemented
lchmod (file attributes) error: Function not implemented
lchmod (file attributes) error: Function not implemented
lchmod (file attributes) error: Function not implemented
lchmod (file attributes) error: Function not implemented
lchmod (file attributes) error: Function not implemented
lchmod (file attributes) error: Function not implemented
lchmod (file attributes) error: Function not implemented
lchmod (file attributes) error: Function not implemented
lchmod (file attributes) error: Function not implemented
lchmod (file attributes) error: Function not implemented
Traceback (most recent call last):
  File "/path/Mambaforge-4.14.0-1/envs/dpv/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/path/Mambaforge-4.14.0-1/envs/dpv/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/path/Mambaforge-4.14.0-1/envs/dpv/share/deepvariant-1.4.0-0/binaries/DeepVariant/1.4.0/DeepVariant-1.4.0/make_examples.zip/__main__.py", line 387, in <module>
  File "/path/Mambaforge-4.14.0-1/envs/dpv/share/deepvariant-1.4.0-0/binaries/DeepVariant/1.4.0/DeepVariant-1.4.0/make_examples.zip/__main__.py", line 360, in Main
  File "/path/Mambaforge-4.14.0-1/envs/dpv/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/path/Mambaforge-4.14.0-1/envs/dpv/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/path/Mambaforge-4.14.0-1/envs/dpv/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/python3': '/usr/bin/python3'
parallel: This job failed:
/path/Mambaforge-4.14.0-1/envs/dpv/bin/python /path/Mambaforge-4.14.0-1/envs/dpv/share/deepvariant-1.4.0-0/binaries/DeepVariant/1.4.0/DeepVariant-1.4.0/make_examples.zip --mode calling --ref QJref.fa --reads F0F_sorted.merged.addg.uniq.rmdup.bam --gvcf GVCF/QJ.gvcf.tfrecord@3.gz --sample_name QJ --examples EXAMPLES/QJ.tfrecord@3.gz --task 2
```

**Comment by pichuan** [comment]
Hi @Zero-Sun 
`dv_make_examples.py` isn't a file that our GitHub repo provided. Can you tell me a bit more about what's in that file and how did you install DeepVariant?

**Comment by Zero-Sun** [comment]
Sorry, I used mamba to install it. And then I get `dv_make_examples.py`,`dv_call_variants.py`,`dv_postprocess_variants.py`.
```
$ mamba search deepvariant
Name                       Version           Build  Channel
deepvariant              1.3.0  py36hf3e76ba_0  bioconda
deepvariant              1.4.0  py36hf3e76ba_0  bioconda
$ mamba install deepvariant
```
When I run `dv_make_examples.py`, this is the directory where my `python` executes `make_examples.zip`, the same directory as the file you provide at this site.
[https://console.cloud.google.com/storage/browser/deepvariant/binaries/DeepVariant/1.4.0/DeepVariant-1.4.0](url)
```
$cd /path/deepvariant-1.4.0-0/binaries/DeepVariant/1.4.0/DeepVariant-1.4.0/
$ls
call_variants_keras.zip  freeze_graph.zip   model_eval.zip                 postprocess_variants.zip   settings.sh
call_variants.zip        licenses.zip       model_train.zip                run-prereq.sh              show_examples.zip
deeptrio                 make_examples.zip  multisample_make_examples.zip  runtime_by_region_vis.zip  vcf_stats_report.zip
```

**Comment by pichuan** [comment]
I see. Given that this is from conda, I wonder if @chapmanb has some thoughts on this.

By the way, @Zero-Sun I'm seeing this:
```
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/python3': '/usr/bin/python3'
```
Do you expect to see that?

**Comment by Zero-Sun** [comment]
Thank you for your reply!
For the following code, I don't have permission to modify the path `/usr/bin/`, and I didn't find `/usr/bin/python3` from `subprocess.py`, so I didn't fix the error either.
As a study student, I am working hard to learn to solve these mistakes. It hasn't been resolved yet.
```
File "/path/Mambaforge-4.14.0-1/envs/dpv/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/python3': '/usr/bin/python3'
```

**Comment by pichuan** [comment]
1. Does your machine have `/usr/bin/python3`? If not, I'm not exactly sure how this would work.
2. Does your machine have Singularity? If so, you can consider that as an alternative. An example here https://github.com/google/deepvariant/blob/r1.4/docs/deepvariant-quick-start.md#notes-on-singularity

**Comment by Zero-Sun** [comment]
Thank you for your reply!
1、My machine doesn't have `/usr/bin/python3`.I don't have permission to change `/usr/bin/`.I tried to modify the source code, but I couldn't locate the code.
2、I tried to install Singularity. I use the parameter `--without -- seccomp --without -- conmon` because of the following error
`./mconfig --without-suid --without-seccomp --without-conmon --prefix=/path/singularity && make -C ./builddir &&make -C ./builddir install`
```
seccomp headers are required to build Singularity with seccomp support.
To disable seccomp support run mconfig using '--without-seccomp'.

Cannot build conmon for OCI support without libseccomp headers.
Use --without-conmon to disable build and use conmon on PATH if present.
```
Then I try to run it
```
singularity run -B /path/locale/:/path/locale/ \
>   docker://google/deepvariant:"1.4.0" \
>  /path/dpv_singu \
> --model_type=PACBIO \
> --ref=/path/ref_fasta/QJref.fa \
> --reads=/path/bam_files/F1N_sorted.merged.addg.uniq.rmdup.bam \
>  --output_vcf=/path/output.vcf.gz \
> --output_gvcf=/path/output.g.vcf.gz \
> --intermediate_results_dir /path/intermediate_results_dir
```
The error information is as follows
```
INFO:    Using cached SIF image
INFO:    Converting SIF file to temporary sandbox...
FATAL:   while handling /home/my_user_name/.singularity/cache/oci-tmp/sha256.83ce0d6bbe3695bcbaa348b73c48737bdbfaeaea2272b0105dd4bdfa7a804f18: while extracting image: root filesystem extraction failed: extract command failed: ERROR  : Failed to create user namespace: user namespace disabled
: exit status 1
```

**Comment by kishwarshafin** [comment]
@Zero-Sun ,

Can you please try the same command with `--no-home` parameter?

**Comment by pichuan** [comment]
Hi @Zero-Sun ,
Given that we haven't heard from you for 3 weeks, I'm closing this issue now.
Please let us know if you still encounter more issues.
