### ISSUE TITLE
NumPy dependency error despite matching versions

### ISSUE THREAD

**Issue by asherrar** [google/deepvariant#610]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.4/docs/FAQ.md**: Yes

**Describe the issue:**
Unable to run Singularity image despite prerequisites appearing satisfied

**Setup**
  - Operating system: CentOS 7 
  - DeepVariant version: 1.4.0 (google/deepvariant:latest)
  - Installation method (Docker, built from source, etc.): `singularity pull docker://google/deepvariant:latest` and attempted execution via `singularity run`
  - Type of data: N/A

**Steps to reproduce:**
  - Command: `singularity run -B /home/ -B /scratch/ deepvariant.sif`
  - Error trace:
```
Traceback (most recent call last):
  File "/home/asherrar/.local/lib/python3.8/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/home/asherrar/.local/lib/python3.8/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/asherrar/.local/lib/python3.8/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libflexiblas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 48, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/__init__.py", line 41, in <module>
    from tensorflow.python.eager import context
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/context.py", line 30, in <module>
    import numpy as np
  File "/home/asherrar/.local/lib/python3.8/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/home/asherrar/.local/lib/python3.8/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/usr/bin/python3"
  * The NumPy version is: "1.23.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libflexiblas.so.3: cannot open shared object file: No such file or directory
```

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start? Any attempt to execute via `singularity run` leads to an error

**Any additional context:**
As far as I can tell, my environment meets the requirements for both Python and NumPy - though at the same time when I `singularity shell` into the SIF file, its versioning seems semi-independent of my main environment (Python 3.8.10 regardless of my environment's version, but using the NumPy 1.23.0 provided by my computing cluster). I feel like I'm missing something really simple, but I've tried the NumPy troubleshooting page and can't seem to crack this error.

If it helps, I'm attempting this with `singularity` version 3.8.4, which is the newest version available to me in my computing cluster.

**Comment by pichuan** [comment]
Hi, sorry this is taking a while. I should have handled this last week but got too busy. I'll try to reply today or tomorrow.

**Comment by pichuan** [comment]
@asherrar Unfortunately, I'm unable to reproduce what you're seeing. I'm going to write down what I did. Maybe you can spot what differences we have:

Create a CentOS7 machine to test:

```
gcloud compute instances create "${USER}-centos7" \
--scopes "compute-rw,storage-full,cloud-platform" \
--image-family "centos-7" \
--image-project "centos-cloud" \
--machine-type "e2-standard-16" \
--zone "us-west1-b"

gcloud compute ssh pichuan-centos7 --zone "us-west1-b"
```

By default the machine has Python2
```
[pichuan@pichuan-centos7 ~]$ python --version 
Python 2.7.5
```

## Install Python 3.8.10
```
sudo yum update
sudo yum install gcc openssl-devel bzip2-devel libffi-devel -y
sudo yum install -y wget
sudo yum install -y python3
```

```
wget https://www.python.org/ftp/python/3.8.10/Python-3.8.10.tgz
tar xvfz Python-3.8.10.tgz
```

```
cd Python-3.8.10
./configure --enable-optimizations
```

```
sudo yum install -y make
sudo make altinstall
```

```
[pichuan@pichuan-centos7 Python-3.8.10]$ python3.8 --version
Python 3.8.10
```

## Install Singularity

```
sudo yum update -y && \
     sudo yum groupinstall -y 'Development Tools' && \
     sudo yum install -y \
     openssl-devel \
     libuuid-devel \
     libseccomp-devel \
     wget \
     squashfs-tools \
     cryptsetup
```


```
export VERSION=1.14.12 OS=linux ARCH=amd64
# Downloads the required Go package
wget https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz
# Extracts the archive
sudo tar -C /usr/local -xzvf go$VERSION.$OS-$ARCH.tar.gz
# Deletes the ``tar`` file
rm go$VERSION.$OS-$ARCH.tar.gz

export VERSION=3.8.4
wget https://github.com/hpcng/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz
tar -xzf singularity-${VERSION}.tar.gz
pushd singularity-3.8.4
export PATH=/usr/local/go/bin:$PATH

./mconfig
make -C builddir
sudo make -C builddir install
```

Check version:
```
[pichuan@pichuan-centos7 ~]$ singularity --version
singularity version 3.8.4
```

## Try running DeepVariant with Singularity

I followed Quick Start to get data.

```
singularity pull docker://google/deepvariant:1.4.0
# Run DeepVariant.
singularity run -B /usr/lib/locale/:/usr/lib/locale/ \
  docker://google/deepvariant:1.4.0 \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref="${INPUT_DIR}"/ucsc.hg19.chr20.unittest.fasta \
  --reads="${INPUT_DIR}"/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf="${OUTPUT_DIR}"/output.vcf.gz \
  --output_gvcf="${OUTPUT_DIR}"/output.g.vcf.gz \
  --intermediate_results_dir "${OUTPUT_DIR}/intermediate_results_dir" \
  --num_shards=1
```

This worked for me.

Check numpy version:

```
singularity run -B /usr/lib/locale/:/usr/lib/locale/ \
  docker://google/deepvariant:1.4.0 \
  python -c 'import numpy as np; print(np.version.version)'
```
Which shows:
```
1.19.2
```

It seems like my machine doesn't already have numpy, though:

```
[pichuan@pichuan-centos7 Python-3.8.10]$ pip3.8 show numpy
WARNING: Package(s) not found: numpy
```
doesn't show anything.

## Install numpy 1.23.0 to see it breaks things

I ran:
```
pip3.8 install numpy==1.23.0
```
(Because you mentioned your cluster has 1.23.0)

Now this shows:

```
[pichuan@pichuan-centos7 ~]$ pip3.8 show numpy
Name: numpy
Version: 1.23.0
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /home/pichuan/.local/lib/python3.8/site-packages
Requires: 
Required-by: 
```

Then I re-ran:

```
# Run DeepVariant.
singularity run -B /usr/lib/locale/:/usr/lib/locale/ \
  docker://google/deepvariant:1.4.0 \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref="${INPUT_DIR}"/ucsc.hg19.chr20.unittest.fasta \
  --reads="${INPUT_DIR}"/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf="${OUTPUT_DIR}"/output.vcf.gz \
  --output_gvcf="${OUTPUT_DIR}"/output.g.vcf.gz \
  --intermediate_results_dir "${OUTPUT_DIR}/intermediate_results_dir" \
  --num_shards=1
```

Which still seems to work fine for me.

And, this actually shows 1.23.0 as well:
```
singularity run -B /usr/lib/locale/:/usr/lib/locale/ \
  docker://google/deepvariant:1.4.0 \
  python -c 'import numpy as np; print(np.version.version)'
```

```
1.23.0
```

I also checked TensorFlow version:

```
singularity run -B /usr/lib/locale/:/usr/lib/locale/ \
  docker://google/deepvariant:1.4.0 \
  python -c 'import tensorflow; print(tensorflow.__version__)'
```
This shows:
```
2.7.0
```

@asherrar Let me know what you think I need to change to try to reproduce the error you saw. Thanks!

**Comment by pichuan** [comment]
Hi @asherrar , I haven't heard from you, so I'll close this issue for now.
Please feel free to reopen again.
