### ISSUE TITLE
ModuleNotFoundError: No module named 'chardet'

### ISSUE THREAD

**Issue by Famingzhao** [google/deepvariant#634]
- Command:#docker
BIN_VERSION="1.5.0"
reference=/home/data/ref_annotation_Geneset/11.variant_calling/deepvariant/reference
INPUT_DIR=/home/data/ref_annotation_Geneset/11.variant_calling/deepvariant/input
OUTPUT_DIR=/home/data/ref_annotation_Geneset/11.variant_calling/deepvariant/outdir
singularity run --nv -B /home/data/ref_annotation_Geneset/11.variant_calling/deepvariant/ \
  docker://google/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WES \
  --ref="${reference}"/GRCh38_no_alt_analysis_set.fasta \
  --reads="${INPUT_DIR}"/HG003.novaseq.wes_idt.100x.dedup.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf="${OUTPUT_DIR}"/output.vcf.gz \
  --output_gvcf="${OUTPUT_DIR}"/output.g.vcf.gz \
  --intermediate_results_dir "${OUTPUT_DIR}/intermediate_results_dir" \
  --num_shards=1
 
 - Error trace: INFO:    Using cached SIF image
WARNING: Could not find any nv files on this host!
2023-04-22 17:10:50.025707: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 48, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/__init__.py", line 51, in <module>
    from ._api.v2 import compat
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/compat/__init__.py", line 37, in <module>
    from . import v1
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/compat/v1/__init__.py", line 30, in <module>
    from . import compat
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py", line 38, in <module>
    from . import v2
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/compat/v1/compat/v2/__init__.py", line 28, in <module>
    from tensorflow._api.v2.compat.v2 import __internal__
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/compat/v2/__init__.py", line 33, in <module>
    from . import compat
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/compat/v2/compat/__init__.py", line 38, in <module>
    from . import v2
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/compat/v2/compat/v2/__init__.py", line 37, in <module>
    from tensorflow._api.v2.compat.v2 import distribute
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/compat/v2/distribute/__init__.py", line 182, in <module>
    from . import experimental
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/compat/v2/distribute/experimental/__init__.py", line 10, in <module>
    from . import rpc
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/compat/v2/distribute/experimental/rpc/__init__.py", line 8, in <module>
    from tensorflow.python.distribute.experimental.rpc.rpc_ops import Client
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/experimental/__init__.py", line 22, in <module>
    from tensorflow.python.distribute.failure_handling import failure_handling
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/failure_handling/failure_handling.py", line 34, in <module>
    from tensorflow.python.distribute.failure_handling import gce_util
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/failure_handling/gce_util.py", line 20, in <module>
    import requests
  File "/home/data/ssy43/.local/lib/python3.8/site-packages/requests/__init__.py", line 44, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

**Comment by Famingzhao** [comment]
I have installed chardet 3.0.4 by using 'pip install chardet==3.04'. 
But the error are still reported.

**Comment by Famingzhao** [comment]
I have now solved this error.
Firstly, input within shell:
> singularity shell deepvariant_1.5.0.sif
Then,
> pip install --upgrade pip
> pip install chardet==3.04

**Comment by CWYuan08** [comment]
@Famingzhao, thanks for sharing, I have encountered the same issue, I tried to use your solution, but I am not sure what this step is: singularity shell deepvariant_1.5.0.sif? 

Thank you!

**Comment by pgrosu** [comment]
@CWYuan08 Basically `singularity shell` drops you with a shell prompt within your running container.  The container will require that pip update.  Here is a [video link](https://www.youtube.com/watch?v=97VuBVnfcwg) describing this process.  Once inside the container just run the pip install and then run DeepVariant from there, to use the updated environment.
