### ISSUE TITLE
Fatal: python Bus Error

### ISSUE THREAD

**Issue by yangyxt** [google/deepvariant#646]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.5/docs/FAQ.md**:
Yes

**Describe the issue:**
Run into Fatal python Bus error repeatedly

**Setup**
  - Operating system: CentOS 7 
  - DeepVariant version: 1.4 (DeepTrio)
  - Installation method (Docker, built from source, etc.): singularity 
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)
Illumina NovaSeq data, reference genome hg19. 
**Steps to reproduce:**
  - Command:
  - `/opt/deepvariant/bin/deeptrio/make_examples --mode calling --ref /paedyl01/disk1/yangyxt/indexed_genome/ucsc.hg19.fasta --reads_parent1 /paedyl01/disk1/yangyxt/wesplus/50_samples_20220304/aligned_results/A210126.deduped.bam --reads /paedyl01/disk1/yangyxt/wesplus/50_samples_20220304/aligned_results/A210124.deduped.bam --examples /paedyl01/disk1/yangyxt/test_tmp/singularity_inter_aRMiURV3spzCOiBE1ojvo_fj2J05oPk1/make_examples.tfrecord@6.gz --sample_name A210124 --sample_name_parent1 A210126 --channels insert_size --gvcf /paedyl01/disk1/yangyxt/test_tmp/singularity_inter_aRMiURV3spzCOiBE1ojvo_fj2J05oPk1/gvcf.tfrecord@6.gz --normalize_reads --pileup_image_height_child 100 --pileup_image_height_parent 100 --regions /paedyl01/disk1/yangyxt/indexed_genome/hg19/ucsc.hg19.no_dad.bed --task 0`
  - Error trace: (if applicable)
`Fatal Python error: Bus error

Current thread 0x00002af3a27fa740 (most recent call first):
  File "/paedyl01/disk1/yangyxt/test_tmp/singularity_run_aRMiURV3spzCOiBE1ojvo_fj2J05oPk1/Bazel.runfiles_dtfjmfk6/runfiles/com_google_deepvariant/deepvariant/very_sensitive_caller.py", line 58 in <dictcomp>
  File "/paedyl01/disk1/yangyxt/test_tmp/singularity_run_aRMiURV3spzCOiBE1ojvo_fj2J05oPk1/Bazel.runfiles_dtfjmfk6/runfiles/com_google_deepvariant/deepvariant/very_sensitive_caller.py", line 57 in get_candidates
  File "/paedyl01/disk1/yangyxt/test_tmp/singularity_run_aRMiURV3spzCOiBE1ojvo_fj2J05oPk1/Bazel.runfiles_dtfjmfk6/runfiles/com_google_deepvariant/deepvariant/variant_caller.py", line 382 in calls_and_gvcfs
  File "/paedyl01/disk1/yangyxt/test_tmp/singularity_run_aRMiURV3spzCOiBE1ojvo_fj2J05oPk1/Bazel.runfiles_dtfjmfk6/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1379 in candidates_in_region
  File "/paedyl01/disk1/yangyxt/test_tmp/singularity_run_aRMiURV3spzCOiBE1ojvo_fj2J05oPk1/Bazel.runfiles_dtfjmfk6/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1145 in process
  File "/paedyl01/disk1/yangyxt/test_tmp/singularity_run_aRMiURV3spzCOiBE1ojvo_fj2J05oPk1/Bazel.runfiles_dtfjmfk6/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1795 in make_examples_runner
  File "/paedyl01/disk1/yangyxt/test_tmp/singularity_run_aRMiURV3spzCOiBE1ojvo_fj2J05oPk1/Bazel.runfiles_dtfjmfk6/runfiles/com_google_deepvariant/deeptrio/make_examples.py", line 302 in main
  File "/paedyl01/disk1/yangyxt/test_tmp/singularity_run_aRMiURV3spzCOiBE1ojvo_fj2J05oPk1/Bazel.runfiles_dtfjmfk6/runfiles/absl_py/absl/app.py", line 251 in _run_main
  File "/paedyl01/disk1/yangyxt/test_tmp/singularity_run_aRMiURV3spzCOiBE1ojvo_fj2J05oPk1/Bazel.runfiles_dtfjmfk6/runfiles/absl_py/absl/app.py", line 300 in run
  File "/paedyl01/disk1/yangyxt/test_tmp/singularity_run_aRMiURV3spzCOiBE1ojvo_fj2J05oPk1/Bazel.runfiles_dtfjmfk6/runfiles/com_google_deepvariant/deeptrio/make_examples.py", line 312 in <module>
parallel: This job failed:
/opt/deepvariant/bin/deeptrio/make_examples --mode calling --ref /paedyl01/disk1/yangyxt/indexed_genome/ucsc.hg19.fasta --reads_parent1 /paedyl01/disk1/yangyxt/wesplus/50_samples_20220304/aligned_results/A210126.deduped.bam --reads /paedyl01/disk1/yangyxt/wesplus/50_sampl

real    1154m27.406s
user    287m31.460s
sys     2m20.121s
I0509 05:42:42.322269 47221860157248 run_deeptrio.py:674] None

Traceback (most recent call last):
  File "/opt/deepvariant/bin/deeptrio/run_deeptrio.py", line 688, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/deeptrio/run_deeptrio.py", line 672, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 5 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/deeptrio/make_examples --mode calling --ref "/paedyl01/disk1/yangyxt/indexed_genome/ucsc.hg19.fasta" --reads_parent1 "/paedyl01/disk1/yangyxt/wesplus/50_samples_
Line 770: In function call_deeptrio_per_pair: Tue May  9 05:42:52 HKT 2023: Failed on running singularity DeepTrio. Quit with error
`

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

**Any additional context:**

**Comment by danielecook** [comment]
@yangyxt how much memory do you have available on this machine? Is it possible to increase the amount of memory?

**Comment by yangyxt** [comment]
@danielecook Thanks for the swift response. I ran this on an HPC cluster using the PBS scheduler. I allocated 200 GB for this job, and according to "qstat", this job only uses 20GB at maximum.  I'm preferred to believe that this issue is not due to the lack of sufficient memory for DeepVariant or DeepTrio. 

Here is a screenshot of the finished job status in the qstat table:
![image](https://github.com/google/deepvariant/assets/40780228/9b7fe09d-fb20-4f8a-9ff9-972e539aa6a1)

**Comment by pichuan** [comment]
Hi @yangyxt ,
In your log, I saw this line which is a bit strange:

```
Line 770: In function call_deeptrio_per_pair: Tue May 9 05:42:52 HKT 2023: Failed on running singularity DeepTrio. Quit with error
```

I tried to search for that function in our r1.4 codebase (which is the version you mentioned you're using):

```
git clone https://github.com/google/deepvariant.git
cd deepvariant/
git checkout r1.4
find .  -type f -exec grep -H call_deeptrio_per_pair {} \;
```

And I can't find that function in our codebase.

Can you confirm that you're running our version, or maybe you're running a modified version from somewhere else?

**Comment by yangyxt** [comment]
hi @pichuan , this log line is generated from my bash function wrapper running singularity version of DeepTrio. I confirm that I am using the official docker image (converted to SIF image with Singularity)

**Comment by pichuan** [comment]
Can you share the command of how you convert to SIF? Thanks.

**Comment by pichuan** [comment]
Actually I have a suggestion:
Can you directly run the failed command

`./opt/deepvariant/bin/deeptrio/make_examples --mode calling --ref /paedyl01/disk1/yangyxt/indexed_genome/ucsc.hg19.fasta --reads_parent1 /paedyl01/disk1/yangyxt/wesplus/50_samples_20220304/aligned_results/A210126.deduped.bam --reads /paedyl01/disk1/yangyxt/wesplus/50_samples_20220304/aligned_results/A210124.deduped.bam --examples /paedyl01/disk1/yangyxt/test_tmp/singularity_inter_aRMiURV3spzCOiBE1ojvo_fj2J05oPk1/make_examples.tfrecord@6.gz --sample_name A210124 --sample_name_parent1 A210126 --channels insert_size --gvcf /paedyl01/disk1/yangyxt/test_tmp/singularity_inter_aRMiURV3spzCOiBE1ojvo_fj2J05oPk1/gvcf.tfrecord@6.gz --normalize_reads --pileup_image_height_child 100 --pileup_image_height_parent 100 --regions /paedyl01/disk1/yangyxt/indexed_genome/hg19/ucsc.hg19.no_dad.bed --task 0`


Without using run_deeptrio.py.

I now remember that the way I wrote that script can make the underlying error unclear, and as a result hard to debug when an error occurs.

If you directly run the failed job, you should get more helpful error message.

Sorry for the inconvenience. I believe I improved that for run_deepvariant.py a while ago but haven't done the same for run_deeptrio.py.

**Comment by yangyxt** [comment]
Hello @pichuan I will try your suggestion and let you know the feedback. As to the SIF conversion its just simple command using singularity (version 3.7.2) pull docker://google/deepvariant:1.4 (Now I use 1.5).

**Comment by yangyxt** [comment]
Hi @pichuan, I tried your command and it returns with successful return code. I dont know what went wrong if I use run_deeptrio.

**Comment by pichuan** [comment]
Hi @yangyxt ,
I see...

For now, to help you continue your work, I suggest using run_deeptrio with the `--dry_run=true` flag to get the list of commands, and run the commands there individually for now.

Sorry for the inconvenience. The goal for having the one-step run_deeptrio.py script was to make things easier. But I need to do some improvements to make the error reporting better in the next release.

**Comment by pichuan** [comment]
I'll close this issue for now.

@yangyxt if you are able to find more detailed errors, feel free to update and reopen.

**Comment by eesiribloom** [comment]
@yangyxt did you work this out? I am having a similar issue with deepsomatic
