### ISSUE TITLE
Error in pbc_varicall

### ISSUE THREAD

**Issue by kiranpatil222** [google/deepvariant#659]
Hi i have deepvariant 1.5.0 version singularity SIF file,
I ran successfully from command line for PacBio data, but when i ran the same through NextFlow as below
#nextflow.config
```
singularity {
process.container = '/data/shared/clinical/LongRead/DeepVariant/deepvariant.simg'
cacheDir = "/data/shared/clinical/LongRead/cache/"
singularity.enabled = true
singularity.autoMounts = true
SINGULARITY_BINDPATH  = "/data"
}

conda
        {
                enabled = true
                cacheDir = "/data/shared/clinical/LongRead/Programs/"
        }
params
        {
        path="/data/shared/clinical/LongRead/"
        ref_genome="/data/shared/clinical/LongRead/Data/resources/Homo_sapiens_assembly38.fasta"
        pbhg38_tdx="/data/shared/clinical/LongRead/Data/resources/Homo_sapiens_assembly38.mmi"
        at=18
        st=6
        data_input="/data/shared/clinical/LongRead/Data/"
        }
```
#deepvariant.nf
```
process pbc_varicall {
        publishDir "/data/shared/clinical/LongRead/Data/resources/"
        container 'docker://google/deepvariant:1.5.0'

        input:
        path 'fa'
        output:
        file "*"
        path 'm84011_220902_175841_NF_sif.vcf.gz'

        script:
        """
        run_deepvariant  --model_type PACBIO --ref ${params.ref_genome} --reads ${params.data_input}/m84011_220902_175841_Aln.bam --output_vcf ${params.data_input}/Analysis/out_m84011_220902_175841_NF_sif.vcf.gz --num_shards 40
        """
}

workflow {
        fa=channel.fromPath("/data/shared/clinical/LongRead/Data/resources/Homo_sapiens_assembly38.fasta")
        pbc_varicall(fa)
}
```
after running for several hours i do not get any output, instead during run , i get msg as
`TaskHandler[id: 1; name: pbc_varicall (1); status: RUNNING; exit: -; error: -; workDir: `
this is during `make_examples` step

**Comment by kiranpatil222** [comment]
Hi @MariaNattestad ,

Thank you for the reply,
1) NextFlow pipeline is written by me. 3) I ran with Chr20, below is the log, 4) in NextFlow Input out we can give any name for the files as input/out.
```
Jun-08 12:02:05.261 [main] INFO  nextflow.cli.CmdRun - Launching `dv.nf` [spontaneous_wright] DSL2 - revision: fbe7d83e44
Jun-08 12:02:05.261 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Jun-08 12:02:05.261 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[]
Jun-08 12:02:05.268 [main] DEBUG nextflow.secret.LocalSecretsProvider - Secrets store: /home/kiran.patil/.nextflow/secrets/store.json
Jun-08 12:02:05.271 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@58472096] - activable => nextflow.secret.LocalSecretsProvider@58472096
Jun-08 12:02:05.320 [main] DEBUG nextflow.Session - Session UUID: 1e83b778-2b0d-4f02-9875-bf3b18b4a30a
Jun-08 12:02:05.320 [main] DEBUG nextflow.Session - Run name: spontaneous_wright
Jun-08 12:02:05.320 [main] DEBUG nextflow.Session - Executor pool size: 96
Jun-08 12:02:05.330 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=288; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Jun-08 12:02:05.348 [main] DEBUG nextflow.cli.CmdRun -
  Version: 22.10.7 build 5853
  Created: 18-02-2023 20:32 UTC (19-02-2023 02:02 IDT)
  System: Linux 5.4.0-146-generic
  Runtime: Groovy 3.0.13 on OpenJDK 64-Bit Server VM 14.0.2+12-Ubuntu-120.04
  Encoding: UTF-8 (UTF-8)
  Process: 683315@victor [127.0.1.1]
  CPUs: 96 - Mem: 503.5 GB (137.9 GB) - Swap: 108 GB (107.9 GB)
Jun-08 12:02:05.365 [main] DEBUG nextflow.Session - Work-dir: /data/shared/clinical/LongRead/Pipeline/work [ext2/ext3]
Jun-08 12:02:05.365 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /data/shared/clinical/LongRead/Pipeline/bin
Jun-08 12:02:05.372 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Jun-08 12:02:05.380 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Jun-08 12:02:05.398 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Jun-08 12:02:05.407 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 97; maxThreads: 1000
Jun-08 12:02:05.482 [main] DEBUG nextflow.Session - Session start
Jun-08 12:02:05.642 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Jun-08 12:02:05.728 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Jun-08 12:02:05.738 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=96; memory=503.5 GB; capacity=96; pollInterval=100ms; dumpInterval=5m
Jun-08 12:02:05.804 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: pbc_varicall
Jun-08 12:02:05.804 [main] DEBUG nextflow.Session - Igniting dataflow network (2)
Jun-08 12:02:05.809 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > pbc_varicall
Jun-08 12:02:05.810 [main] DEBUG nextflow.script.ScriptRunner - > Awaiting termination
Jun-08 12:02:05.810 [main] DEBUG nextflow.Session - Session await
Jun-08 12:02:05.895 [Actor Thread 5] DEBUG nextflow.container.SingularityCache - Singularity found local store for image=docker://google/deepvariant:1.5.0; path=/data/shared/clinical/LongRead/cache/google-deepvariant-1.5.0.img
Jun-08 12:02:06.011 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Jun-08 12:02:06.012 [Task submitter] INFO  nextflow.Session - [55/335c47] Submitted process > pbc_varicall (1)
Jun-08 12:07:05.943 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! executor local > tasks to be completed: 1 -- submitted tasks are shown below
~> TaskHandler[id: 1; name: pbc_varicall (1); status: RUNNING; exit: -; error: -; workDir: /data/shared/clinical/LongRead/Pipeline/work/55/335c478f0f7e93d6d5e06cd4d99711]
Jun-08 12:12:06.012 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! executor local > tasks to be completed: 1 -- submitted tasks are shown below
~> TaskHandler[id: 1; name: pbc_varicall (1); status: RUNNING; exit: -; error: -; workDir: /data/shared/clinical/LongRead/Pipeline/work/55/335c478f0f7e93d6d5e06cd4d99711]
Jun-08 12:17:06.076 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! executor local > tasks to be completed: 1 -- submitted tasks are shown below
~> TaskHandler[id: 1; name: pbc_varicall (1); status: RUNNING; exit: -; error: -; workDir: /data/shared/clinical/LongRead/Pipeline/work/55/335c478f0f7e93d6d5e06cd4d99711]
Jun-08 12:17:16.724 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: pbc_varicall (1); status: COMPLETED; exit: 1; error: -; workDir: /data/shared/clinical/LongRead/Pipeline/work/55/335c478f0f7e93d6d5e06cd4d99711]
Jun-08 12:17:16.741 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'pbc_varicall (1)'

Caused by:
  Process `pbc_varicall (1)` terminated with an error exit status (1)
Command executed:

  run_deepvariant  --model_type PACBIO --ref /data/shared/clinical/LongRead/Data/resources/Homo_sapiens_assembly38.fasta --reads /data/shared/clinical/LongRead/Data//m84011_220902_175841_Aln.bam --output_vcf /data/shared/clinical/LongRead/Data//Analysis/out_m84011_220902_175841_NFR_sif.vcf.gz --num_shards 40 --regions chr20

Command exit status:
  1

Command output:
  I0608 12:13:28.741300 139794368661312 call_variants.py:462] Processed 100001 examples in 196 batches [0.087 sec per 100]
  I0608 12:14:06.236101 139794368661312 call_variants.py:462] Processed 150001 examples in 293 batches [0.083 sec per 100]
  I0608 12:14:43.829042 139794368661312 call_variants.py:462] Processed 200001 examples in 391 batches [0.081 sec per 100]
  I0608 12:15:22.101066 139794368661312 call_variants.py:462] Processed 250001 examples in 489 batches [0.080 sec per 100]
  I0608 12:15:59.773940 139794368661312 call_variants.py:462] Processed 300001 examples in 586 batches [0.079 sec per 100]
  I0608 12:16:37.228438 139794368661312 call_variants.py:462] Processed 350001 examples in 684 batches [0.079 sec per 100]
  I0608 12:17:07.588583 139794368661312 call_variants.py:468] Processed 390233 examples in 763 batches [0.078 sec per 100]
  I0608 12:17:07.588791 139794368661312 call_variants.py:471] Done calling variants from a total of 390233 examples.

  real  5m9.540s
  user  294m6.601s
  sys   10m18.739s

  ***** Running the command:*****
  time /opt/deepvariant/bin/postprocess_variants --ref "/data/shared/clinical/LongRead/Data/resources/Homo_sapiens_assembly38.fasta" --infile "/tmp/tmpye305c9i/call_variants_output.tfrecord.gz" --outfile "/data/shared/clinical/LongRead/Data//Analysis/out_m84011_220902_175841_NFR_sif.vcf.gz"

  2023-06-08 12:17:08.837575: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
  I0608 12:17:10.554912 140524419180352 postprocess_variants.py:972] Using sample name from call_variants output. Sample name: HG002
  2023-06-08 12:17:10.560565: I deepvariant/postprocess_variants.cc:88] Read from: /tmp/tmpye305c9i/call_variants_output.tfrecord.gz
  2023-06-08 12:17:12.148564: I deepvariant/postprocess_variants.cc:103] Total #entries in single_site_calls = 390233
  I0608 12:17:15.074928 140524419180352 postprocess_variants.py:1037] CVO sorting took 0.07523852189381917 minutes
  I0608 12:17:15.075901 140524419180352 postprocess_variants.py:1040] Transforming call_variants_output to variants.
  I0608 12:17:15.089107 140524419180352 postprocess_variants.py:1061] Writing variants to VCF.
  I0608 12:17:15.089209 140524419180352 postprocess_variants.py:771] Writing output to VCF file: /data/shared/clinical/LongRead/Data//Analysis/out_m84011_220902_175841_NFR_sif.vcf.gz
  [E::hts_open_format] Failed to open file "/data/shared/clinical/LongRead/Data//Analysis/out_m84011_220902_175841_NFR_sif.vcf.gz" : No such file or directory
  Traceback (most recent call last):
    File "/tmp/Bazel.runfiles_21tufdoh/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1112, in <module>
      tf.compat.v1.app.run()
    File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/platform/app.py", line 36, in run
      _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
    File "/tmp/Bazel.runfiles_21tufdoh/runfiles/absl_py/absl/app.py", line 312, in run
      _run_main(main, args)
    File "/tmp/Bazel.runfiles_21tufdoh/runfiles/absl_py/absl/app.py", line 258, in _run_main
      sys.exit(main(argv))
    File "/tmp/Bazel.runfiles_21tufdoh/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1062, in main
      write_variants_to_vcf(
    File "/tmp/Bazel.runfiles_21tufdoh/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 772, in write_variants_to_vcf
      with vcf.VcfWriter(
    File "/tmp/Bazel.runfiles_21tufdoh/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_writer.py", line 174, in __init__
      self._writer = self._native_writer(output_path, **kwargs)
 return NativeVcfWriter(
    File "/tmp/Bazel.runfiles_21tufdoh/runfiles/com_google_deepvariant/third_party/nucleus/io/vcf.py", line 287, in __init__
      self._writer = vcf_writer.VcfWriter.to_file(output_path, header,
  ValueError: UNKNOWN: Could not open variants_path: /data/shared/clinical/LongRead/Data//Analysis/out_m84011_220902_175841_NFR_sif.vcf.gz

  real  0m7.906s
  user  0m8.421s
  sys   0m8.363s

Command error:
  I0608 12:13:28.741300 139794368661312 call_variants.py:462] Processed 100001 examples in 196 batches [0.087 sec per 100]
  I0608 12:14:06.236101 139794368661312 call_variants.py:462] Processed 150001 examples in 293 batches [0.083 sec per 100]
  I0608 12:14:43.829042 139794368661312 call_variants.py:462] Processed 200001 examples in 391 batches [0.081 sec per 100]
  I0608 12:15:22.101066 139794368661312 call_variants.py:462] Processed 250001 examples in 489 batches [0.080 sec per 100]
  I0608 12:15:59.773940 139794368661312 call_variants.py:462] Processed 300001 examples in 586 batches [0.079 sec per 100]
  I0608 12:16:37.228438 139794368661312 call_variants.py:462] Processed 350001 examples in 684 batches [0.079 sec per 100]
  I0608 12:17:07.588583 139794368661312 call_variants.py:468] Processed 390233 examples in 763 batches [0.078 sec per 100]
  I0608 12:17:07.588791 139794368661312 call_variants.py:471] Done calling variants from a total of 390233 examples.

  real  5m9.540s
  user  294m6.601s
  sys   10m18.739s

  ***** Running the command:*****
  time /opt/deepvariant/bin/postprocess_variants --ref "/data/shared/clinical/LongRead/Data/resources/Homo_sapiens_assembly38.fasta" --infile "/tmp/tmpye305c9i/call_variants_output.tfrecord.gz" --outfile "/data/shared/clinical/LongRead/Data//Analysis/out_m84011_220902_175841_NFR_sif.vcf.gz"

  2023-06-08 12:17:08.837575: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
 File "/tmp/Bazel.runfiles_21tufdoh/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 772, in write_variants_to_vcf
      with vcf.VcfWriter(
    File "/tmp/Bazel.runfiles_21tufdoh/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_writer.py", line 174, in __init__
      self._writer = self._native_writer(output_path, **kwargs)
    File "/tmp/Bazel.runfiles_21tufdoh/runfiles/com_google_deepvariant/third_party/nucleus/io/vcf.py", line 309, in _native_writer
      return NativeVcfWriter(
    File "/tmp/Bazel.runfiles_21tufdoh/runfiles/com_google_deepvariant/third_party/nucleus/io/vcf.py", line 287, in __init__
      self._writer = vcf_writer.VcfWriter.to_file(output_path, header,
  ValueError: UNKNOWN: Could not open variants_path: /data/shared/clinical/LongRead/Data//Analysis/out_m84011_220902_175841_NFR_sif.vcf.gz

  real  0m7.906s
  user  0m8.421s
  sys   0m8.363s

Work dir:
  /data/shared/clinical/LongRead/Pipeline/work/55/335c478f0f7e93d6d5e06cd4d99711

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
Jun-08 12:17:16.749 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Process `pbc_varicall (1)` terminated with an error exit status (1)
Jun-08 12:17:16.752 [main] DEBUG nextflow.Session - Session await > all processes finished
Jun-08 12:17:16.764 [main] DEBUG nextflow.Session - Session await > all barriers passed
Jun-08 12:17:16.776 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=1; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=15m 11s; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=1; peakCpus=1; peakMemory=0; ]
Jun-08 12:17:16.977 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Jun-08 12:17:16.991 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

**Comment by MariaNattestad** [comment]
Looks like the relevant error message is:
```
ValueError: UNKNOWN: Could not open variants_path: /data/shared/clinical/LongRead/Data//Analysis/out_m84011_220902_175841_NFR_sif.vcf.gz
```
On many systems, writing an output file is not possible if the directory is not present already, so can you make sure the directory exists first:

```
mkdir -p /data/shared/clinical/LongRead/Data//Analysis/
```

**Comment by pichuan** [comment]
I'll close this issue now. @kiranpatil222 feel free to reopen if you have more questions.
