### ISSUE TITLE
Error running bioconda installed version

### ISSUE THREAD

**Issue by mwhitesi** [google/deepvariant#664]
Installed DeepVariant 1.5.0 from bioconda using micromamba. Running make examples command produces the following error:
```
micromamba run --name dv /opt/conda/envs/dv/bin/python /opt/conda/envs/dv/share/deepvariant-1.5.0-0/binaries/DeepVariant/1.5.0/DeepVariant-1.5.0/make_examples.zip --mode calling --ref /data/dpipe/rundata/refdata/hg/hg19_no_chr6_hap.fasta --reads /data/dpipe/rundata/runs/run1/NA12878/NA12878.bam --sample_name NA12878 --examples /data/dpipe/rundata/runs/run1/dvout//NA12878.tfrecord@1.gz --task 0
Traceback (most recent call last):
  File "/opt/conda/envs/dv/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/dv/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/dv/share/deepvariant-1.5.0-0/binaries/DeepVariant/1.5.0/DeepVariant-1.5.0/make_examples.zip/__main__.py", line 392, in <module>
  File "/opt/conda/envs/dv/share/deepvariant-1.5.0-0/binaries/DeepVariant/1.5.0/DeepVariant-1.5.0/make_examples.zip/__main__.py", line 365, in Main
  File "/opt/conda/envs/dv/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/conda/envs/dv/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/opt/conda/envs/dv/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/python3': '/usr/bin/python3'
```

I noticed inside the bazel .zip files the python binary is hard-coded:
/share/deepvariant-1.5.0-0/binaries/DeepVariant/1.5.0/DeepVariant-1.5.0/make_examples.zip Line 60: `PYTHON_BINARY = '/usr/bin/python3'`

Is there any way to override this value to select a different python binary? The micromamba python binary is not in the standard location and there is also multiple python binaries in this system.

DeepVariant was installed using micromamba:

```
micromamba create -n dv && micromamba install -y -n dv -f /tmp/env_deepvariant.yaml
``` 
With environment file:
```
name: dv
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.6
  - deepvariant=1.5.0
```

Thanks

**Comment by mwhitesi** [comment]
The bash script does bypass the python3 error, but then other missing package errors appear:
```/opt/conda/envs/dv/bin/python /opt/conda/envs/dv/share/deepvariant-1.5.0-0/binaries/DeepVariant/1.5.0/DeepVariant-1.5.0/make_examples.zip --mode calling --ref /data/dpipe/rundata/refdata/hg/hg19_no_chr6_hap.fasta --reads /data/dpipe/rundata/runs/run1/NA12878/NA12878.bam --regions /data/dpipe/rundata/runs/run1/reference/CP.bed --sample_name NA12878 --examples /data/dpipe/rundata/runs/run1/dvout//NA12878.tfrecord@1.gz --task 0
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_qb8gn44e/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 38, in <module>
    from deepvariant import make_examples_core
  File "/tmp/Bazel.runfiles_qb8gn44e/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 41, in <module>
    from etils import epath
ModuleNotFoundError: No module named 'etils'
```

**Comment by danielecook** [comment]
Can you confirm that you had activated the Conda environment you used to install DeepVariant when you ran that command?

**Comment by mwhitesi** [comment]
Confirmed:
```
(dv) dpipe@4de3e1b4384c:/app/dpipe$ which python3
/opt/conda/envs/dv/bin/python3
(dv) dpipe@4de3e1b4384c:/app/dpipe$ python3 /opt/conda/envs/dv/share/deepvariant-1.5.0-0/binaries/DeepVariant/1.5.0/DeepVariant-1.5.0/make_examples.zip --mode calling --ref /data/dpipe/rundata/refdata/hg/hg19_no_chr6_hap.fasta --reads /data/dpipe/rundata/runs/run1/NA12878/NA12878.bam --regions /data/dpipe/rundata/runs/run1/reference/CP.bed --sample_name NA12878 --examples /data/dpipe/rundata/runs/run1/dvout//NA12878.tfrecord@1.gz --task 0
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_od9li1rj/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 38, in <module>
    from deepvariant import make_examples_core
  File "/tmp/Bazel.runfiles_od9li1rj/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 41, in <module>
    from etils import epath
ModuleNotFoundError: No module named 'etils'
(dv) dpipe@4de3e1b4384c:/app/dpipe$ micromamba list -n dv
List of packages in environment: "/opt/conda/envs/dv"

  Name                     Version       Build                   Channel    
──────────────────────────────────────────────────────────────────────────────
  _libgcc_mutex            0.1           conda_forge             conda-forge
  _openmp_mutex            4.5           2_gnu                   conda-forge
  _tflow_select            2.1.0         gpu                                
  absl-py                  0.15.0        pyhd8ed1ab_0            conda-forge
  aiohttp                  3.7.4.post0   py36h8f6f2f9_0          conda-forge
  altair                   4.2.0         pyhd8ed1ab_0            conda-forge
  astor                    0.8.1         pyh9f0ad1d_0            conda-forge
  async-timeout            3.0.1         py_1000                 conda-forge
  attrs                    22.2.0        pyh71513ae_0            conda-forge
  blinker                  1.5           pyhd8ed1ab_0            conda-forge
  boost                    1.75.0        py36h355b2fd_0          conda-forge
  boost-cpp                1.75.0        hc6e9bd1_0              conda-forge
  brotlipy                 0.7.0         py36h8f6f2f9_1001       conda-forge
  bzip2                    1.0.8         h7f98852_4              conda-forge
  c-ares                   1.19.1        hd590300_0              conda-forge
  ca-certificates          2023.5.7      hbcca054_0              conda-forge
  cached-property          1.5.2         hd8ed1ab_1              conda-forge
  cached_property          1.5.2         pyha770c72_1            conda-forge
  cachetools               5.0.0         pyhd8ed1ab_0            conda-forge
  certifi                  2021.5.30     py36h5fab9bb_0          conda-forge
  cffi                     1.14.6        py36hd8eec40_1          conda-forge
  chardet                  4.0.0         py36h5fab9bb_1          conda-forge
  charset-normalizer       2.1.1         pyhd8ed1ab_0            conda-forge
  click                    8.0.1         py36h5fab9bb_0          conda-forge
  contextlib2              21.6.0        pyhd8ed1ab_0            conda-forge
  crcmod                   1.7           py36h8f6f2f9_1006       conda-forge
  cryptography             35.0.0        py36hb60f036_0          conda-forge
  cudatoolkit              10.0.130      h8c5a6a4_11             conda-forge
  cudnn                    7.6.5.32      ha8d7eb6_1              conda-forge
  cupti                    10.0.130      0                                  
  curl                     7.87.0        h6312ad2_0              conda-forge
  deepvariant              1.5.0         py36hf3e76ba_0          bioconda   
  entrypoints              0.4           pyhd8ed1ab_0            conda-forge
  enum34                   1.1.10        py36h9f0ad1d_2          conda-forge
  gast                     0.2.2         py_0                    conda-forge
  google-auth              2.20.0        pyh1a96a4e_0            conda-forge
  google-auth-oauthlib     0.4.6         pyhd8ed1ab_0            conda-forge
  google-cloud-sdk         359.0.0       py36h5fab9bb_0          conda-forge
  google-pasta             0.2.0         pyh8c360ce_0            conda-forge
  grpcio                   1.38.1        py36h8e87921_0          conda-forge
  h5py                     3.1.0         nompi_py36hc1bc4f5_100  conda-forge
  hdf5                     1.10.6        nompi_h6a2412b_1114     conda-forge
  htslib                   1.17          h6bc39ce_1              bioconda   
  httplib2                 0.22.0        pyhd8ed1ab_0            conda-forge
  icu                      68.2          h9c3ff4c_0              conda-forge
  idna                     3.4           pyhd8ed1ab_0            conda-forge
  idna_ssl                 1.1.0         pyhd8ed1ab_1002         conda-forge
  importlib-metadata       4.8.1         py36h5fab9bb_0          conda-forge
  intervaltree             3.1.0         pyhd8ed1ab_1            conda-forge
  jinja2                   3.0.3         pyhd8ed1ab_0            conda-forge
  jsonschema               4.1.2         pyhd8ed1ab_0            conda-forge
  keras-applications       1.0.8         py_1                    conda-forge
  keras-preprocessing      1.1.2         pyhd8ed1ab_0            conda-forge
  keyutils                 1.6.1         h166bdaf_0              conda-forge
  krb5                     1.20.1        hf9c8cef_0              conda-forge
  ld_impl_linux-64         2.40          h41732ed_0              conda-forge
  libblas                  3.9.0         17_linux64_openblas     conda-forge
  libcblas                 3.9.0         17_linux64_openblas     conda-forge
  libcurl                  7.87.0        h6312ad2_0              conda-forge
  libdeflate               1.18          h0b41bf4_0              conda-forge
  libedit                  3.1.20191231  he28a2e2_2              conda-forge
  libev                    4.33          h516909a_1              conda-forge
  libffi                   3.4.2         h7f98852_5              conda-forge
  libgcc-ng                13.1.0        he5830b7_0              conda-forge
  libgfortran-ng           13.1.0        h69a702a_0              conda-forge
  libgfortran5             13.1.0        h15d22d2_0              conda-forge
  libgomp                  13.1.0        he5830b7_0              conda-forge
  liblapack                3.9.0         17_linux64_openblas     conda-forge
  libnghttp2               1.51.0        hdcd2b5c_0              conda-forge
  libnsl                   2.0.0         h7f98852_0              conda-forge
  libopenblas              0.3.23        pthreads_h80387f5_0     conda-forge
  libprotobuf              3.18.0        h780b84a_1              conda-forge
  libsqlite                3.42.0        h2797004_0              conda-forge
  libssh2                  1.10.0        haa6b8db_3              conda-forge
  libstdcxx-ng             13.1.0        hfd8a6a1_0              conda-forge
  libzlib                  1.2.13        hd590300_5              conda-forge
  lz4-c                    1.9.3         h9c3ff4c_1              conda-forge
  markdown                 3.4.3         pyhd8ed1ab_0            conda-forge
  markupsafe               2.0.1         py36h8f6f2f9_0          conda-forge
  mock                     5.0.2         pyhd8ed1ab_0            conda-forge
  multidict                5.2.0         py36h8f6f2f9_0          conda-forge
  ncurses                  6.4           hcb278e6_0              conda-forge
  numpy                    1.16.6        py36h2aa4a07_0          conda-forge
  oauth2client             4.1.3         py_0                    conda-forge
  oauthlib                 3.2.2         pyhd8ed1ab_0            conda-forge
  openjdk                  8.0.332       h166bdaf_0              conda-forge
  openssl                  1.1.1u        hd590300_0              conda-forge
  opt_einsum               3.3.0         pyhd8ed1ab_1            conda-forge
  pandas                   1.1.5         py36h284efc9_0          conda-forge
  parallel                 20230522      ha770c72_0              conda-forge
  perl                     5.32.1        2_h7f98852_perl5        conda-forge
  pip                      21.3.1        pyhd8ed1ab_0            conda-forge
  protobuf                 3.18.0        py36hc4f0c31_0          conda-forge
  psutil                   5.8.0         py36h8f6f2f9_1          conda-forge
  pyasn1                   0.4.8         py_0                    conda-forge
  pyasn1-modules           0.2.7         py_0                    conda-forge
  pycparser                2.21          pyhd8ed1ab_0            conda-forge
  pyjwt                    2.7.0         pyhd8ed1ab_0            conda-forge
  pyopenssl                22.0.0        pyhd8ed1ab_1            conda-forge
  pyparsing                3.0.9         pyhd8ed1ab_0            conda-forge
  pyrsistent               0.17.3        py36h8f6f2f9_2          conda-forge
  pysocks                  1.7.1         py36h5fab9bb_3          conda-forge
  python                   3.6.15        hb7a2778_0_cpython      conda-forge
  python-dateutil          2.8.2         pyhd8ed1ab_0            conda-forge
  python_abi               3.6           2_cp36m                 conda-forge
  pytz                     2023.3        pyhd8ed1ab_0            conda-forge
  pyu2f                    0.1.5         pyhd8ed1ab_0            conda-forge
  readline                 8.2           h8228510_1              conda-forge
  requests                 2.28.1        pyhd8ed1ab_0            conda-forge
  requests-oauthlib        1.3.1         pyhd8ed1ab_0            conda-forge
  rsa                      4.9           pyhd8ed1ab_0            conda-forge
  scipy                    1.5.3         py36h9e8f40b_0          conda-forge
  setuptools               58.0.4        py36h5fab9bb_2          conda-forge
  six                      1.16.0        pyh6c4a22f_0            conda-forge
  sortedcontainers         2.4.0         pyhd8ed1ab_0            conda-forge
  sqlite                   3.42.0        h2c6b66d_0              conda-forge
  tensorboard              2.8.0         pyhd8ed1ab_1            conda-forge
  tensorboard-data-server  0.6.0         py36hc39840e_0          conda-forge
  tensorboard-plugin-wit   1.8.1         pyhd8ed1ab_0            conda-forge
  tensorflow               2.0.0         gpu_py36h6b29c10_0                 
  tensorflow-base          2.0.0         gpu_py36h0ec5d1f_0                 
  tensorflow-estimator     2.0.0         pyh2649769_0                       
  tensorflow-gpu           2.0.0         h0d30ee6_0                         
  termcolor                1.1.0         pyhd8ed1ab_3            conda-forge
  tk                       8.6.12        h27826a3_0              conda-forge
  toolz                    0.12.0        pyhd8ed1ab_0            conda-forge
  typing-extensions        4.1.1         hd8ed1ab_0              conda-forge
  typing_extensions        4.1.1         pyha770c72_0            conda-forge
  unzip                    6.0           h7f98852_3              conda-forge
  urllib3                  1.26.15       pyhd8ed1ab_0            conda-forge
  werkzeug                 0.16.1        py_0                    conda-forge
  wheel                    0.37.1        pyhd8ed1ab_0            conda-forge
  wrapt                    1.13.1        py36h8f6f2f9_0          conda-forge
  xz                       5.2.6         h166bdaf_0              conda-forge
  yarl                     1.6.3         py36h8f6f2f9_2          conda-forge
  zipp                     3.6.0         pyhd8ed1ab_0            conda-forge
  zlib                     1.2.13        hd590300_5              conda-forge
  zstd                     1.4.9         ha95c52a_0              conda-forge
(dv) dpipe@4de3e1b4384c:/app/dpipe$ 
```

**Comment by danielecook** [comment]
Can you try adding "which python3" to that bash script and reporting what is output?

I wonder whether you need to initialize Conda in that script to get this working.

**Comment by mwhitesi** [comment]
`which python` indicates its pointing to the proper environment python
```
(dv) dpipe@3a2ea3796f25:/app/dpipe$ python3 /opt/conda/envs/dv/share/deepvariant-1.5.0-0/binaries/DeepVariant/1.5.0/DeepVariant-1.5.0/make_examples.zip --mode calling --ref /data/dpipe/rundata/refdata/hg/hg19_no_chr6_hap.fasta --reads /data/dpipe/rundata/runs/run1/NA12878/NA12878.bam --regions /data/dpipe/rundata/runs/run1/reference/CP.bed --sample_name NA12878 --examples /data/dpipe/rundata/runs/run1/dvout//NA12878.tfrecord@1.gz --task 0
/opt/conda/envs/dv/bin/python3
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_446zcm18/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 38, in <module>
    from deepvariant import make_examples_core
  File "/tmp/Bazel.runfiles_446zcm18/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 32, in <module>
    import dataclasses
ModuleNotFoundError: No module named 'dataclasses'
```
Its strange that these modules are not found. I see many of the deepvariant package dependencies installed in the environment but not `dataclasses` or `etils` etc.
```
(dv) dpipe@3a2ea3796f25:/app/dpipe$ python --version
Python 3.6.15
(dv) dpipe@3a2ea3796f25:/app/dpipe$ which python
/opt/conda/envs/dv/bin/python
(dv) dpipe@3a2ea3796f25:/app/dpipe$ python
Python 3.6.15 | packaged by conda-forge | (default, Dec  3 2021, 18:49:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dataclasses
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'dataclasses'
>>> import tensorflow
>>> quit()
(dv) dpipe@3a2ea3796f25:/app/dpipe$ pip freeze
absl-py @ file:///home/conda/feedstock_root/build_artifacts/absl-py_1634676905105/work
aiohttp @ file:///home/conda/feedstock_root/build_artifacts/aiohttp_1623682242746/work
altair @ file:///home/conda/feedstock_root/build_artifacts/altair_1640796027299/work
astor @ file:///home/conda/feedstock_root/build_artifacts/astor_1593610464257/work
async-timeout==3.0.1
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1671632566681/work
blinker @ file:///home/conda/feedstock_root/build_artifacts/blinker_1664823096650/work
brotlipy==0.7.0
cached-property @ file:///home/conda/feedstock_root/build_artifacts/cached_property_1615209429212/work
cachetools @ file:///home/conda/feedstock_root/build_artifacts/cachetools_1640686991047/work
certifi==2021.5.30
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1631636256886/work
chardet @ file:///home/conda/feedstock_root/build_artifacts/chardet_1610093477613/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1661170624537/work
click @ file:///home/conda/feedstock_root/build_artifacts/click_1621503698523/work
contextlib2 @ file:///home/conda/feedstock_root/build_artifacts/contextlib2_1624848568296/work
crcmod @ file:///home/conda/feedstock_root/build_artifacts/crcmod_1624134625038/work
cryptography @ file:///home/conda/feedstock_root/build_artifacts/cryptography_1634230300355/work
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1643888246732/work
gast==0.2.2
google-auth @ file:///home/conda/feedstock_root/build_artifacts/google-auth_1686724583094/work
google-auth-oauthlib @ file:///home/conda/feedstock_root/build_artifacts/google-auth-oauthlib_1630497468950/work
google-pasta==0.2.0
grpcio @ file:///home/conda/feedstock_root/build_artifacts/grpcio_1624380494797/work
h5py @ file:///home/conda/feedstock_root/build_artifacts/h5py_1604753633596/work
httplib2 @ file:///home/conda/feedstock_root/build_artifacts/httplib2_1679483503307/work
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1663625384323/work
idna-ssl @ file:///home/conda/feedstock_root/build_artifacts/idna_ssl_1636483491140/work
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1630267465156/work
intervaltree @ file:///home/conda/feedstock_root/build_artifacts/intervaltree_1683532206518/work
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1636510082894/work
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema_1634752161479/work
Keras-Applications==1.0.8
Keras-Preprocessing @ file:///home/conda/feedstock_root/build_artifacts/keras-preprocessing_1610713559828/work
Markdown @ file:///home/conda/feedstock_root/build_artifacts/markdown_1679584000376/work
MarkupSafe @ file:///home/conda/feedstock_root/build_artifacts/markupsafe_1621455668064/work
mock @ file:///home/conda/feedstock_root/build_artifacts/mock_1681654098624/work
multidict @ file:///home/conda/feedstock_root/build_artifacts/multidict_1633329770033/work
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1607958944856/work
oauth2client==4.1.3
oauthlib @ file:///home/conda/feedstock_root/build_artifacts/oauthlib_1666056362788/work
opt-einsum @ file:///home/conda/feedstock_root/build_artifacts/opt_einsum_1617859230218/work
pandas==1.1.5
protobuf==3.18.0
psutil @ file:///home/conda/feedstock_root/build_artifacts/psutil_1610127101219/work
pyasn1==0.4.8
pyasn1-modules==0.2.7
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
PyJWT @ file:///home/conda/feedstock_root/build_artifacts/pyjwt_1683676063469/work
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1663846997386/work
pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1652235407899/work
pyrsistent @ file:///home/conda/feedstock_root/build_artifacts/pyrsistent_1610146795286/work
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1610291458349/work
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1680088766131/work
pyu2f @ file:///home/conda/feedstock_root/build_artifacts/pyu2f_1604248910016/work
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1656534056640/work
requests-oauthlib @ file:///home/conda/feedstock_root/build_artifacts/requests-oauthlib_1643557462909/work
rsa @ file:///home/conda/feedstock_root/build_artifacts/rsa_1658328885051/work
scipy @ file:///home/conda/feedstock_root/build_artifacts/scipy_1604304777848/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
sortedcontainers @ file:///home/conda/feedstock_root/build_artifacts/sortedcontainers_1621217038088/work
tensorboard @ file:///home/conda/feedstock_root/build_artifacts/tensorboard_1644015949874/work/tensorboard-2.8.0-py3-none-any.whl
tensorboard-data-server @ file:///home/conda/feedstock_root/build_artifacts/tensorboard-data-server_1629677084688/work/tensorboard_data_server-0.6.0-py3-none-manylinux2010_x86_64.whl
tensorboard-plugin-wit @ file:///home/conda/feedstock_root/build_artifacts/tensorboard-plugin-wit_1641458951060/work/tensorboard_plugin_wit-1.8.1-py3-none-any.whl
tensorflow==2.0.0
tensorflow-estimator==2.0.0
termcolor @ file:///home/conda/feedstock_root/build_artifacts/termcolor_1657118200573/work
tf-slim @ git+https://github.com/google-research/tf-slim.git@f67a0b4412c9a15b08fe0ed6daa9c95656751a6d
toolz @ file:///home/conda/feedstock_root/build_artifacts/toolz_1657485559105/work
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1644850595256/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1678635778344/work
Werkzeug==0.16.1
wrapt @ file:///home/conda/feedstock_root/build_artifacts/wrapt_1633440474617/work
yarl @ file:///home/conda/feedstock_root/build_artifacts/yarl_1625232870338/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1633302054558/work
```

**Comment by danielecook** [comment]
One last thing you could try is to upgrade the version of python you are using.

While dataclasses were backported to 3.6, they were formally introduced in python 3.7. 

You could try to manually install those packages and/or try upgrading python?

I'm not sure what to try next, but I can ask around.

**Comment by pgrosu** [comment]
@mwhitesi To better understand what's possible, I had a few small questions to get a state of your running environment:

1) What operating system are you running on, and what version is it?  For Linux one of these should work from the command-line:

```
cat /etc/lsb-release
cat /etc/redhat-release
cat /etc/os-release
```

2) What CPU are you operating on?  If you are on Linux, you can type from your terminal: `cat /proc/cpuinfo`

3) Do you have root access, or is this a shared compute environment (cluster)?  I will try to remain in user-space.

4) Is micromamba the preferred approach, or would you be willing try other ones like miniconda if it becomes the case?

5) Do you have Docker and/or Singularity?  This will be an option if the above fail.

Again these are just preliminary to gauge for possibilities.

Thanks,
Paul

**Comment by pichuan** [comment]
H @mwhitesi ,
thanks for the question!

One thing I'll mention is that the version on bioconda isn't maintained by our team. But if you can provide more context, we can continue to try to see if we can help here. Let us know if you want to follow up in this thread. I'll keep this open for now.

**Comment by akolesnikov** [comment]
Closing due to inactivity.
