### ISSUE TITLE
Error running deepvariant from singularity in cluster

### ISSUE THREAD

**Issue by Zhanghaibo777** [google/deepvariant#679]
Dear all,

I was trying to run deepvariant from singularity in cluster, but I always meet same error, I don't know hou to fix it:

/share/app/singularity/3.8.1/bin/singularity exec --containall --bind /hwfssz1/ST_SUPERCELLS/P21Z10200N0125/tmp:/tmp --bind /usr/lib/locale/:/usr/lib/locale/ --bind $ccsbam:$ccsbam --bind $ccsbam.bai:$ccsbam.bai --bind $fasta:$fasta --bind $fasta.fai:$fasta.fai --bind /hwfssz5/ST_SUPERCELLS/P21Z10200N0125/zhanghaibo/translatome/HCT116/PacBio/analysis/deepvariant.v3/T202302180201:/output /hwfssz1/ST_SUPERCELLS/P21Z10200N0125/zhanghaibo/software/deepvariant/deepvariant_1.5.0.sif   /opt/deepvariant/bin/run_deepvariant   --model_type=PACBIO   --ref=$fasta   --reads=$ccsbam   --output_vcf=/output/T202302180201.deepvariant.vcf.gz   --output_gvcf=/output/T202302180201.deepvariant.g.vcf.gz   --num_shards=20   --intermediate_results_dir=/tmp

***** Running the command:*****
time /opt/deepvariant/bin/call_variants --outfile "/tmp/call_variants_output.tfrecord.gz" --examples "/tmp/make_examples.tfrecord@20.gz" --checkpoint "/opt/models/pacbio/model.ckpt"

2023-07-15 14:06:58.063861: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical oper
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0715 14:07:10.199614 47821886322496 call_variants.py:317] From /tmp/make_examples.tfrecord-00000-of-00020.gz.example_info.json: Shape of input examples: [100, 199, 9], Channels of input examples: [1, 2, 3, 4, 5, 6, 7, 9, 10].
I0715 14:07:10.205330 47821886322496 call_variants.py:317] From /opt/models/pacbio/model.ckpt.example_info.json: Shape of input examples: [100, 199, 9], Channels of input examples: [1, 2, 3, 4, 5, 6, 7, 9, 10].
2023-07-15 14:07:10.211204: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical oper
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-15 14:07:10.223654: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2023-07-15 14:07:10.226851: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:357] MLIR V1 optimization pass is not enabled
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpl_zjylv7
W0715 14:07:10.308488 47821886322496 estimator.py:1864] Using temporary folder as model directory: /tmp/tmpl_zjylv7
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpl_zjylv7', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': , '_keep_checkpoint_max': 10000
I0715 14:07:10.309390 47821886322496 estimator.py:202] Using config: {'_model_dir': '/tmp/tmpl_zjylv7', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_c
I0715 14:07:10.309847 47821886322496 call_variants.py:446] Writing calls to /tmp/call_variants_output.tfrecord.gz
INFO:tensorflow:Calling model_fn.
I0715 14:07:10.758818 47821886322496 estimator.py:1173] Calling model_fn.
/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
INFO:tensorflow:Done calling model_fn.
I0715 14:07:16.873909 47821886322496 estimator.py:1175] Done calling model_fn.
2023-07-15 14:07:17.753203: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
INFO:tensorflow:Graph was finalized.
I0715 14:07:18.197918 47821886322496 monitored_session.py:240] Graph was finalized.
INFO:tensorflow:Restoring parameters from /opt/models/pacbio/model.ckpt
I0715 14:07:18.198770 47821886322496 saver.py:1410] Restoring parameters from /opt/models/pacbio/model.ckpt
INFO:tensorflow:Running local_init_op.
I0715 14:07:20.793029 47821886322496 session_manager.py:526] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I0715 14:07:20.857252 47821886322496 session_manager.py:529] Done running local_init_op.
INFO:tensorflow:Reloading EMA...
I0715 14:07:21.417166 47821886322496 modeling.py:418] Reloading EMA...
INFO:tensorflow:Restoring parameters from /opt/models/pacbio/model.ckpt
I0715 14:07:21.417759 47821886322496 saver.py:1410] Restoring parameters from /opt/models/pacbio/model.ckpt
I0715 14:07:25.965068 47821886322496 call_variants.py:462] Processed 1 examples in 1 batches [1565.044 sec per 100]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/client/session.py", line 1378, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/client/session.py", line 1361, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/client/session.py", line 1454, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 484865306
         [[{{node IteratorGetNext}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_y5t4ngn_/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 513, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/platform/app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/tmp/Bazel.runfiles_y5t4ngn_/runfiles/absl_py/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_y5t4ngn_/runfiles/absl_py/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_y5t4ngn_/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 494, in main
    call_variants(
  File "/tmp/Bazel.runfiles_y5t4ngn_/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 453, in call_variants
    prediction = next(predictions)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 642, in predict
    preds_evaluated = mon_sess.run(predictions)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/training/monitored_session.py", line 778, in run
    return self._sess.run(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/training/monitored_session.py", line 1307, in run
    return self._sess.run(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/training/monitored_session.py", line 1397, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/training/monitored_session.py", line 1464, in run
    outputs = _WrappedSession.run(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/training/monitored_session.py", line 1228, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/client/session.py", line 968, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/client/session.py", line 1191, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/client/session.py", line 1371, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/client/session.py", line 1397, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.DataLossError: Graph execution error:

Detected at node 'IteratorGetNext' defined at (most recent call last):
    File "/tmp/Bazel.runfiles_y5t4ngn_/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 513, in <module>
      tf.compat.v1.app.run()
    File "/tmp/Bazel.runfiles_y5t4ngn_/runfiles/absl_py/absl/app.py", line 312, in run
      _run_main(main, args)
    File "/tmp/Bazel.runfiles_y5t4ngn_/runfiles/absl_py/absl/app.py", line 258, in _run_main
      sys.exit(main(argv))
    File "/tmp/Bazel.runfiles_y5t4ngn_/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 494, in main
      call_variants(
    File "/tmp/Bazel.runfiles_y5t4ngn_/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 453, in call_variants
      prediction = next(predictions)
    File "/usr/local/lib/python3.8/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 621, in predict
      features, input_hooks = self._get_features_from_input_fn(
    File "/usr/local/lib/python3.8/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1019, in _get_features_from_input_fn
      result, _, hooks = estimator_util.parse_input_fn_result(result)
    File "/usr/local/lib/python3.8/dist-packages/tensorflow_estimator/python/estimator/util.py", line 60, in parse_input_fn_result
      result = iterator.get_next()
Node: 'IteratorGetNext'
corrupted record at 484865306
         [[{{node IteratorGetNext}}]]

Original stack trace for 'IteratorGetNext':
  File "/tmp/Bazel.runfiles_y5t4ngn_/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 513, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/platform/app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/tmp/Bazel.runfiles_y5t4ngn_/runfiles/absl_py/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_y5t4ngn_/runfiles/absl_py/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_y5t4ngn_/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 494, in main
    call_variants(
  File "/tmp/Bazel.runfiles_y5t4ngn_/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 453, in call_variants
    prediction = next(predictions)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 621, in predict
    features, input_hooks = self._get_features_from_input_fn(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1019, in _get_features_from_input_fn
    result, _, hooks = estimator_util.parse_input_fn_result(result)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_estimator/python/estimator/util.py", line 60, in parse_input_fn_result
    result = iterator.get_next()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 445, in get_next
    flat_ret = gen_dataset_ops.iterator_get_next(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3037, in iterator_get_next
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/op_def_library.py", line 795, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 3798, in _create_op_internal
    ret = Operation(

Best Regards!
Bo

**Comment by pgrosu** [comment]
Hi Bo,

First remove the following two from your command-line:

```
--bind /hwfssz1/ST_SUPERCELLS/P21Z10200N0125/tmp:/tmp
--intermediate_results_dir=/tmp
```

The Singularity container already has its own `/tmp` folder, and if you want an intermediate results folder you would want it be a different (unused) path name.  You don't need the intermediate results folder to run DeepVariant.

If you want to use stuff from your home folder (or other auto-mounted ones), then you don't need `--containall` either.

Let me know if that fixes things, otherwise we can see what the next error you get and we progress like that.

Let me know if it helped.

Thanks,
Paul

**Comment by Zhanghaibo777** [comment]
Dear Paul:
    Thank you so much for the speedy reply.
    I tested the following two command-line operation schemes separately, and encountered some problems. I feel that the previous error report is not a problem with the (--containall; tmpDir) parameter.


## command-line plan A:
/share/app/singularity/3.8.1/bin/singularity exec \
--containall \
--bind /usr/lib/locale/:/usr/lib/locale/ \
--bind $ccsbam:$ccsbam \
--bind $ccsbam.bai:$ccsbam.bai \
--bind $fasta:$fasta \
--bind $fasta.fai:$fasta.fai \
--bind /hwfssz5/ST_SUPERCELLS/P21Z10200N0125/zhanghaibo/translatome/HCT116/PacBio/analysis/deepvariant.v3/T202302180201:/output \
/hwfssz1/ST_SUPERCELLS/P21Z10200N0125/zhanghaibo/software/deepvariant/deepvariant_1.5.0.sif /opt/deepvariant/bin/run_deepvariant \
--model_type=PACBIO --ref=$fasta --reads=$ccsbam --output_vcf=/output/T202302180201.deepvariant.vcf.gz --output_gvcf=/output/T202302180201.deepvariant.g.vcf.gz --num_shards=20

***** Intermediate results will be written to /tmp/tmp8_1neaqr in docker. ****


***** Running the command:*****
time seq 0 19 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/hwfssz1/ST_SUPERCELLS/P21Z10200N0125/zhanghaibo/Reference/PacBio/minimap2/Homo_sapiens_assembly38.fasta" --reads "/hwfssz5/ST_SUPERCELLS/P21Z10200N0125/zhanghaibo/translatome/HCT116/PacBio/analysis/deepvariant.v4/R202302180101/R202302180101.pbmm2.CCS.alignment.sort.bam" --examples "/tmp/tmp8_1neaqr/make_examples.tfrecord@20.gz" --add_hp_channel --alt_aligned_pileup "diff_channels" --gvcf "/tmp/tmp8_1neaqr/gvcf.tfrecord@20.gz" --max_reads_per_partition "600" --min_mapping_quality "1" --parse_sam_aux_fields --partition_size "25000" --phase_reads --pileup_image_width "199" --norealign_reads --sort_by_haplotypes --track_ref_reads --vsc_min_fraction_indels "0.12" --task {}

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/deepvariant/bin/make_examples.zip/__main__.py", line 392, in <module>
  File "/opt/deepvariant/bin/make_examples.zip/__main__.py", line 326, in Main
AssertionError: Cannot exec() '/tmp/Bazel.runfiles_nwff5xo0/runfiles/com_google_deepvariant/deepvariant/make_examples.py': file not found.
warning:  /tmp/Bazel.runfiles_4ji1hg9j/runfiles/com_google_protobuf/python/google/protobuf/pyext/_message.so is probably truncated
/tmp/Bazel.runfiles__5bs6aw8/runfiles/com_google_protobuf/python/google/protobuf/pyext/_message.so:  write error (disk full?).  Continue? (y/n/^C) 
warning:  /tmp/Bazel.runfiles__5bs6aw8/runfiles/com_google_protobuf/python/google/protobuf/pyext/_message.so is probably truncated
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/deepvariant/bin/make_examples.zip/__main__.py", line 392, in <module>
  File "/opt/deepvariant/bin/make_examples.zip/__main__.py", line 326, in Main
AssertionError: Cannot exec() '/tmp/Bazel.runfiles_i3h8s325/runfiles/com_google_deepvariant/deepvariant/make_examples.py': file not found.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/deepvariant/bin/make_examples.zip/__main__.py", line 392, in <module>
  File "/opt/deepvariant/bin/make_examples.zip/__main__.py", line 326, in Main
AssertionError: Cannot exec() '/tmp/Bazel.runfiles_8twzrz82/runfiles/com_google_deepvariant/deepvariant/make_examples.py': file not found.
parallel: Error: Output is incomplete. Cannot append to buffer file in /tmp. Is the disk full?
parallel: Error: Change $TMPDIR with --tmpdir or use --compress.
Warning: unable to close filehandle properly: No space left on device during global destruction.

real    0m2.302s
user    0m1.215s
sys     0m0.687s


## command-line plan B:
/share/app/singularity/3.8.1/bin/singularity exec \
--bind /usr/lib/locale/:/usr/lib/locale/ \
--bind $ccsbam:$ccsbam \
--bind $ccsbam.bai:$ccsbam.bai \
--bind $fasta:$fasta \
--bind $fasta.fai:$fasta.fai \
--bind /hwfssz5/ST_SUPERCELLS/P21Z10200N0125/zhanghaibo/translatome/HCT116/PacBio/analysis/deepvariant.v3/T202302180201:/output \
/hwfssz1/ST_SUPERCELLS/P21Z10200N0125/zhanghaibo/software/deepvariant/deepvariant_1.5.0.sif /opt/deepvariant/bin/run_deepvariant \
--model_type=PACBIO --ref=$fasta --reads=$ccsbam --output_vcf=/output/T202302180201.deepvariant.vcf.gz --output_gvcf=/output/T202302180201.deepvariant.g.vcf.gz --num_shards=20

***** Intermediate results will be written to /tmp/6178902.1.st_supermem.q/tmpezd79ese in docker. ****
***** Running the command:*****
time seq 0 19 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/hwfssz1/ST_SUPERCELLS/P21Z10200N0125/zhanghaibo/Reference/PacBio/minimap2/Homo_sapiens_assembly38.fasta" --reads "/hwfssz5/ST_SUPERCELLS/P21Z10200N0125/zhanghaibo/translatome/HCT116/PacBio/analysis/deepvariant.v4/T202302180201/T202302180201.pbmm2.CCS.alignment.sort.bam" --examples "/tmp/6178902.1.st_supermem.q/tmpezd79ese/make_examples.tfrecord@20.gz" --add_hp_channel --alt_aligned_pileup "diff_channels" --gvcf "/tmp/6178902.1.st_supermem.q/tmpezd79ese/gvcf.tfrecord@20.gz" --max_reads_per_partition "600" --min_mapping_quality "1" --parse_sam_aux_fields --partition_size "25000" --phase_reads --pileup_image_width "199" --norealign_reads --sort_by_haplotypes --track_ref_reads --vsc_min_fraction_indels "0.12" --task {}

perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Error in tempfile() using template /hwfssz1/ST_SUPERCELLS/P21Z10200N0125/zhanghaibo/temporary_internet_files/parXXXXX.par: Parent directory (/hwfssz1/ST_SUPERCELLS/P21Z10200N0125/zhanghaibo/temporary_internet_files/) does not exist at /usr/bin/parallel line 3889.

real    0m2.813s
user    0m0.258s
sys     0m0.406s

**Comment by pgrosu** [comment]
Hi Bo,

If you type the following command, what do you get for an output -- just trying to check that your container has a /tmp folder with proper permissions:

```
/share/app/singularity/3.8.1/bin/singularity exec --containall --bind /usr/lib/locale/:/usr/lib/locale/ /hwfssz1/ST_SUPERCELLS/P21Z10200N0125/zhanghaibo/software/deepvariant/deepvariant_1.5.0.sif ls -l /
```

By the way, when you `--bind` don't bind individual files, just bind the folder, and then just reference the bam or reference file from that folder, like in the following doc:

https://github.com/google/deepvariant/blob/r1.5/docs/deepvariant-quick-start.md#notes-on-singularity

Thanks,
Paul

**Comment by Zhanghaibo777** [comment]
Dear Paul:

Thank you for your reply! Although I don’t know why, I can suddenly run successfully using the same command line as before.😂

Best Regards!
Bo

**Comment by pgrosu** [comment]
Dear Bo,

That's really awesome to hear!  Yeah, sometimes how quickly distributed file systems become consistent under heavy workloads is something that has the rare possibility of happening.  Today you might have hit a sweet timeslot where the cluster was not being hit very hard, so more resources were available to match (or exceed) the requirements of your run.

Glad to hear it all worked out,
Paul

**Comment by kishwarshafin** [comment]
Thank you for your help @pgrosu . Good to know the issue has been resolved. I will close this now. @Zhanghaibo777 , please feel free to reopen if the issue persists.
