### ISSUE TITLE
question about deepTrio1.5 

### ISSUE THREAD

**Issue by crazysummerW** [google/deepvariant#718]
Hello, 
I have tested PacBio data on version 1.5 of the deepTrio image. I have performed pbmm2 and whatshap haplotag on the BAM file. However, I encountered an error message stating that the parameter "use_hp_information" is missing. What could be the reason for this?

`![image](https://github.com/google/deepvariant/assets/70870741/738c6c72-d6b5-486e-99e4-9a689a00deb5)`
![1697527223540](https://github.com/google/deepvariant/assets/70870741/bd8eca89-b44b-464d-acbd-5889f9e408a8)

Looking forward to your reply.
Thanks.

**Comment by crazysummerW** [comment]
My cmd:
 `/opt/deepvariant/bin/deeptrio/run_deeptrio \
  --model_type PACBIO \
  --ref hs37d5.fasta \
  --reads_child /input/HG002.phased.bam \
  --reads_parent1 /input/HG003.phased.bam \
  --reads_parent2 /input/HG004.phased.bam \
  --output_vcf_child /output/HG002.output.vcf.gz \
  --output_vcf_parent1 /output/HG003.output.vcf.gz \
  --output_vcf_parent2 /output/HG004.output.vcf.gz \
  --sample_name_child 'HG002' \
  --sample_name_parent1 'HG003' \
  --sample_name_parent2 'HG004' \
  --num_shards $(nproc) \
  --intermediate_results_dir /output/intermediate_results_dir \
  --output_gvcf_child /output/HG002.g.vcf.gz \
  --output_gvcf_parent1 /output/HG003.g.vcf.gz \
  --output_gvcf_parent2 /output/HG004.g.vcf.gz \
  --regions chr20 \
  --use_hp_information`

**Comment by pichuan** [comment]
@crazysummerW Make sure your're using `BIN_VERSION="1.4.0"` with the command above, which was what's in the documentation. In r1.5, we didn't update the DeepTrio PacBio version. So you'll need to use the 1.4.0 version.

That said, we're about to update to r1.6! And this time, DeepTrio PacBio will get an update as well. So, @crazysummerW instead of trying to get 1.4.0 to work, I recommend that you wait a little bit. The new version is coming out soon.

**Comment by crazysummerW** [comment]
@pichuan 
Thank you for your answer. I tested PacBio data on version 1.4 of the deepTrio image. But I received an error message after more than 100 minutes.
`parallel: This job failed:
/opt/deepvariant/bin/deeptrio/make_examples --mode calling --ref hs37d5_m.fasta --reads_parent1 HG003.haplotagged.bam --reads_parent2 HG004.haplotagged.bam --reads HG002.haplotagged.bam --examples intermediate_results_dir/make_examples.tfrecord@32.gz --sample_name HG002 --sample_name_parent1 HG003 --sample_name_parent2 HG004 --add_hp_channel --alt_aligned_pileup diff_channels --gvcf intermediate_results_dir/gvcf.tfrecord@32.gz --parse_sam_aux_fields --pileup_image_height_child 60 --pileup_image_height_parent 40 --pileup_image_width 199 --norealign_reads --sort_by_haplotypes --vsc_min_fraction_indels 0.12 --task 0

real    113m56.944s
user    112m32.542s
sys     0m37.407s
I1020 05:16:02.013775 140329939375936 run_deeptrio.py:674] None
Traceback (most recent call last):
  File "/opt/deepvariant/bin/deeptrio/run_deeptrio.py", line 688, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/deeptrio/run_deeptrio.py", line 672, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 31 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/deeptrio/make_examples --mode calling --ref "hs37d5_m.fasta" --reads_parent1 "HG003.haplotagged.bam" --reads_parent2 "HG004.haplotagged.bam" --reads "HG002.haplotagged.bam" --examples "intermediate_results_dir/make_examples.tfrecord@32.gz" --sample_name "HG002" --sample_name_parent1 "HG003" --sample_name_parent2 "HG004" --add_hp_channel --alt_aligned_pileup "diff_channels" --gvcf "intermediate_results_dir/gvcf.tfrecord@32.gz" --parse_sam_aux_fields --pileup_image_height_child "60" --pileup_image_height_parent "40" --pileup_image_width "199" --norealign_reads --sort_by_haplotypes --vsc_min_fraction_indels "0.12" --task {}' returned non-zero exit status 247.
Fri Oct 20 05:16:03 UTC 2023 end`

What went wrong?
