### ISSUE TITLE
make_examples.py script - regions parameter

### ISSUE THREAD

**Issue by itai889** [google/deepvariant#73]
in make_examples.py script when I pass to --regions parameter 'chr20' it produces error and if I use '20' it does produce for chr 20 only(it seems that the documentation is a bit ambiguous - in the description of "exclude_regions" it does pass only 20 to --regions flag). I used the file from the example.

The error I get from passing "chr20" is:
```
python input/bin/make_examples.zip --mode calling --ref "${REF}" --reads "
${BAM}" --regions "chr20" --examples hexample.tfrecord.gz

[W::hts_idx_load2] The index file is older than the data file: /home/user78/project_examples_sources/input/data/HG002_NIST_150bp_50x.bam.bai
2018-05-14 22:42:53.250882: W third_party/nucleus/io/sam_reader.cc:531] Unrecognized SAM header type, ignoring:
I0514 22:42:53.251095 140678655026944 genomics_reader.py:174] Reading /home/user78/project_examples_sources/input/data/HG002_NIST_150bp_50x.bam with NativeSamReader
I0514 22:42:53.259068 140678655026944 make_examples.py:1024] Preparing inputs
[W::hts_idx_load2] The index file is older than the data file: /home/user78/project_examples_sources/input/data/HG002_NIST_150bp_50x.bam.bai
2018-05-14 22:42:53.286098: W third_party/nucleus/io/sam_reader.cc:531] Unrecognized SAM header type, ignoring:
I0514 22:42:53.286269 140678655026944 genomics_reader.py:174] Reading /home/user78/project_examples_sources/input/data/HG002_NIST_150bp_50x.bam with NativeSamReader
I0514 22:42:53.306706 140678655026944 make_examples.py:946] Common contigs are [u'1', u'2', u'3', u'4', u'5', u'6', u'7', u'8', u'9', u'10', u'11', u'12', u'13', u'14', u'15', u'16', u'17', u'18', u'19', u'20', u'21', u'22', u'X', u'Y']
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_OAibdX/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1120, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_OAibdX/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1110, in main
    make_examples_runner(options)
  File "/tmp/Bazel.runfiles_OAibdX/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1025, in make_examples_runner
    regions = processing_regions_from_options(options)
  File "/tmp/Bazel.runfiles_OAibdX/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 953, in processing_regions_from_options
    options.exclude_calling_regions),
  File "/tmp/Bazel.runfiles_OAibdX/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 557, in build_calling_regions
    ranges.RangeSet.from_regions(regions_to_include, contig_dict))
  File "/tmp/Bazel.runfiles_OAibdX/runfiles/com_google_deepvariant/third_party/nucleus/util/ranges.py", line 121, in from_regions
    return cls(ranges=from_regions(regions, contig_map=contig_map))
  File "/tmp/Bazel.runfiles_OAibdX/runfiles/com_google_deepvariant/third_party/nucleus/util/ranges.py", line 85, in __init__
    for range_ in ranges:
  File "/tmp/Bazel.runfiles_OAibdX/runfiles/com_google_deepvariant/third_party/nucleus/util/ranges.py", line 421, in from_regions
    yield parse_literal(region, contig_map)
  File "/tmp/Bazel.runfiles_OAibdX/runfiles/com_google_deepvariant/third_party/nucleus/util/ranges.py", line 510, in parse_literal
    raise ValueError('Could not parse: ', region_literal)
ValueError: ('Could not parse: ', u'chr20')
```

**Comment by pichuan** [comment]
Hi,
as you can see in the message:
```
I0514 22:42:53.306706 140678655026944 make_examples.py:946] Common contigs are [u'1', u'2', u'3', u'4', u'5', u'6', u'7', u'8', u'9', u'10', u'11', u'12', u'13', u'14', u'15', u'16', u'17', u'18', u'19', u'20', u'21', u'22', u'X', u'Y']
```
This shows that in the input files you gave to make_examples use the convention *without* the prefix "chr". Therefore, in this case you should use `--regions "20"` in your argument.

It could be a bit confusing, but both conventions exist. For example, depending on which version of the reference you're using they can also be different.

Would it help if we add a bit more error message? 
Maybe in addition to "Could not parse", we can say something more verbose like:
`Could not parse chr20 : make sure if the regions you specify are in the contigs of your BAM and FASTA file. A common error is to use "chr" prefix on files that don't have it, or vice versa.`
Would that have helped?

**Comment by itai889** [comment]
A more verbose is nice to have. I should've checked the header of the BAM file with samtools to see the regions that are presented in the file from which I could make examples.

Thanks

**Comment by pichuan** [comment]
We've added a more verbose message. It will come out in later releases of Nucleus and DeepVariant. Thanks!
