### ISSUE TITLE
Errors on testing DeepTrio on PacBio samples

### ISSUE THREAD

**Issue by aheravi** [google/deepvariant#742]
Hi DeepVariant,
I am getting below errors on running DeepTrio on the provided PacBio samples using singularity:

```
***** Running the command:*****
time /opt/deepvariant/bin/postprocess_variants --ref "./reference/GRCh38_no_alt_analysis_set.fasta" --infile "./output/intermediate_results_dir/call_variants_output_child.tfrecord.gz" --outfile "./output/HG002.output.vcf.gz" --cpus 0 --nonvariant_site_tfrecord_path "./output/intermediate_results_dir/gvcf_child.tfrecord@128.gz" --gvcf_outfile "./output/HG002.g.vcf.gz"


***** Running the command:*****
time /opt/deepvariant/bin/postprocess_variants --ref "./reference/GRCh38_no_alt_analysis_set.fasta" --infile "./output/intermediate_results_dir/call_variants_output_parent1.tfrecord.gz" --outfile "./output/HG003.output.vcf.gz" --cpus 0 --nonvariant_site_tfrecord_path "./output/intermediate_results_dir/gvcf_parent1.tfrecord@128.gz" --gvcf_outfile "./output/HG003.g.vcf.gz"


***** Running the command:*****
time /opt/deepvariant/bin/postprocess_variants --ref "./reference/GRCh38_no_alt_analysis_set.fasta" --infile "./output/intermediate_results_dir/call_variants_output_parent2.tfrecord.gz" --outfile "./output/HG004.output.vcf.gz" --cpus 0 --nonvariant_site_tfrecord_path "./output/intermediate_results_dir/gvcf_parent2.tfrecord@128.gz" --gvcf_outfile "./output/HG004.g.vcf.gz"

Traceback (most recent call last):
  File "/var/tmp/Bazel.runfiles_m2211dcw/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1419, in <module>
    app.run(main)
  File "/var/tmp/Bazel.runfiles_m2211dcw/runfiles/absl_py/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/var/tmp/Bazel.runfiles_m2211dcw/runfiles/absl_py/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/var/tmp/Bazel.runfiles_m2211dcw/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1300, in main
    sample_name = get_sample_name()
  File "/var/tmp/Bazel.runfiles_m2211dcw/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1203, in get_sample_name
    _, record = get_cvo_paths_and_first_record()
  File "/var/tmp/Bazel.runfiles_m2211dcw/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1179, in get_cvo_paths_and_first_record
    raise ValueError(
ValueError: ('Found multiple file patterns in input filename space: ', './output/intermediate_results_dir/call_variants_output_parent1.tfrecord.gz')
Traceback (most recent call last):
  File "/var/tmp/Bazel.runfiles_35db5i5u/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1419, in <module>
    app.run(main)
  File "/var/tmp/Bazel.runfiles_35db5i5u/runfiles/absl_py/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/var/tmp/Bazel.runfiles_35db5i5u/runfiles/absl_py/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/var/tmp/Bazel.runfiles_35db5i5u/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1300, in main
    sample_name = get_sample_name()
  File "/var/tmp/Bazel.runfiles_35db5i5u/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1203, in get_sample_name
    _, record = get_cvo_paths_and_first_record()
  File "/var/tmp/Bazel.runfiles_35db5i5u/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1179, in get_cvo_paths_and_first_record
    raise ValueError(
ValueError: ('Found multiple file patterns in input filename space: ', './output/intermediate_results_dir/call_variants_output_child.tfrecord.gz')
Traceback (most recent call last):
  File "/var/tmp/Bazel.runfiles_qvjnuxsy/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1419, in <module>
    app.run(main)
  File "/var/tmp/Bazel.runfiles_qvjnuxsy/runfiles/absl_py/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/var/tmp/Bazel.runfiles_qvjnuxsy/runfiles/absl_py/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/var/tmp/Bazel.runfiles_qvjnuxsy/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1300, in main
    sample_name = get_sample_name()
  File "/var/tmp/Bazel.runfiles_qvjnuxsy/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1203, in get_sample_name
    _, record = get_cvo_paths_and_first_record()
  File "/var/tmp/Bazel.runfiles_qvjnuxsy/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1179, in get_cvo_paths_and_first_record
    raise ValueError(
ValueError: ('Found multiple file patterns in input filename space: ', './output/intermediate_results_dir/call_variants_output_parent2.tfrecord.gz')
```

Any thoughts?
Thanks.

**Comment by aheravi** [comment]
Hi @kishwarshafin ,
Here is the command I used:
```

**Comment by aheravi** [comment]
Thanks, @kishwarshafin.
Sounds working.
