### ISSUE TITLE
deepvariant error on gpu

### ISSUE THREAD

**Issue by gulkhan007** [google/deepvariant#754]
I am running deep variant example code using gpu but getting this error:

Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 49, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/context.py", line 28, in <module>
    from tensorflow.core.framework import function_pb2
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/core/framework/function_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/home/rmehmood/.local/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 51, in <module>
    from google.protobuf.pyext import _message
ImportError: cannot import name '_message' from 'google.protobuf.pyext' (/home/rmehmood/.local/lib/python3.8/site-packages/google/protobuf/pyext/__init__.py)

need kind help, many thanks.

**Comment by kishwarshafin** [comment]
@gulkhan007 ,

Can you please paste the full command and the logs here please?

**Comment by pichuan** [comment]
Hi @gulkhan007 ,
Given the inactivity, I'll close this issue for now. Please feel free to open with more information if you still need help.
