### ISSUE TITLE
Unrecognized SAM header type, ignoring:

### ISSUE THREAD

**Issue by aderzelle** [google/deepvariant#77]
Hello, I am trying to run DeepVariant but ...
here is my command
`time seq 0 $((N_SHARDS-1)) |parallel --eta --halt 2 --joblog "${LOGDIR}/log" --res "${LOGDIR}" python bin/make_examples.zip --mode calling --ref "${REF}" --reads "${BAM}" --sample_name FalconSet --examples "${OUTPUT_DIR}/examples.tfrecord@${N_SHARDS}.gz" --task {}`

And here is the output

```
When using programs that use GNU Parallel to process data for publication please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; and it won't cost you a cent.
Or you can get GNU Parallel without this requirement by paying 10000 EUR.

To silence this citation notice run 'parallel --bibtex' once or use '--no-notice'.


Computers / CPU cores / Max jobs to run
1:local / 48 / 40

Computer:jobs running/jobs completed/%of started jobs/Average seconds to complete
ETA: 0s Left: 40 AVG: 0.00s  local:40/0/100%/0.0s WARNING: Logging before flag parsing goes to stderr.
I0601 15:22:01.182291 140355759671040 make_examples.py:1024] Preparing inputs
2018-06-01 15:22:01.188982: W third_party/nucleus/io/sam_reader.cc:531] Unrecognized SAM header type, ignoring: 
I0601 15:22:01.189755 140355759671040 genomics_reader.py:174] Reading ../Falcon_Unzip/out.bam with NativeSamReader
I0601 15:22:01.543628 140355759671040 make_examples.py:946] Common contigs are [u'000000F', u'000001F', u'000002F', u'000003F', u'000004F', u'000005F', u'000006F', u'000007F', u'000009F', u'000010F', u'000011F', u'000012F', u'000013F', u'000014F', u'000015F', u'000016F', u'000017F', u'000018F', u'000019F', u'000020F', u'000021F', u'000022F', u'000023F', u'000024F', u'000025F', u'000026F', u'000027F', u'000028F', u'000029F', u'000030F', u'000031F', u'000032F', u'000033F', u'000034F', u'000035F', u'000036F', u'000037F', u'000038F', u'000039F', u'000040F', u'000041F', u'000042F', u'000043F', u'000045F', u'000046F', u'000047F', u'000048F', u'000049F', u'000050F', u'000051F', u'000052F', u'000053F', u'000054F', u'000055F', u'000056F', u'000057F', u'000058F', u'000059F', u'000060F', u'000061F', u'000062F', u'000063F', u'000064F', u'000065F', u'000066F', u'000067F', u'000068F', u'000069F', u'000070F', u'000071F', u'000072F', u'000073F', u'000074F', u'000075F', u'000076F', u'000077F', u'000078F', u'000079F', u'000080F', u'000081F', u'000082F', u'000083F', u'000084F', u'000085F', u'000086F', u'000087F', u'000088F', u'000089F', u'000090F', u'000091F', u'000092F', u'000093F', u'000094F', u'000095F', u'000096F', u'000097F', u'000098F', u'000099F', u'000100F', u'000101F', u'000102F', u'000103F', u'000104F', u'000105F', u'000106F', u'000107F', u'000108F', u'000109F', u'000110F', u'000111F', u'000112F', u'000113F', u'000114F', u'000115F', u'000116F', u'000117F', u'000118F', u'000119F', u'000120F', u'000121F', u'000122F', u'000123F', u'000124F', u'000125F', u'000126F', u'000127F', u'000128F', u'000129F', u'000130F', u'000131F', u'000132F', u'000133F', u'000134F', u'000135F', u'000136F', u'000137F', u'000138F', u'000139F', u'000140F', u'000141F', u'000142F', u'000143F', u'000144F', u'000145F', u'000146F', u'000147F', u'000148F', u'000149F', u'000150F', u'000151F', u'000152F', u'000153F', u'000154F', u'000155F', u'000156F', u'000157F', u'000158F', u'000159F', u'000160F', u'000161F', u'000162F', u'000163F', u'000164F', u'000165F', u'000166F', u'000167F', u'000168F', u'000169F', u'000170F', u'000171F', u'000172F', u'000173F', u'000174F', u'000175F', u'000176F', u'000177F', u'000178F', u'000179F', u'000180F', u'000181F', u'000182F', u'000183F', u'000184F', u'000185F', u'000186F', u'000187F', u'000188F', u'000189F', u'000190F', u'000191F', u'000192F', u'000193F', u'000194F', u'000195F', u'000196F', u'000197F', u'000198F', u'000199F', u'000200F', u'000201F', u'000202F', u'000203F', u'000204F', u'000205F', u'000206F', u'000207F', u'000208F', u'000209F', u'000210F', u'000211F', u'000212F', u'000213F', u'000214F', u'000215F', u'000216F', u'000217F', u'000218F', u'000219F', u'000220F', u'000221F', u'000222F', u'000223F', u'000224F', u'000225F', u'000226F', u'000227F', u'000228F', u'000229F', u'000230F', u'000231F', u'000232F', u'000233F', u'000234F', u'000235F', u'000236F', u'000237F', u'000238F', u'000239F', u'000240F', u'000241F', u'000242F', u'000243F', u'000244F', u'000245F', u'000246F', u'000247F', u'000248F', u'000250F', u'000251F', u'000252F', u'000254F', u'000255F', u'000256F', u'000257F', u'000258F', u'000259F', u'000260F', u'000262F', u'000263F', u'000265F', u'000266F', u'000267F', u'000268F', u'000270F', u'000271F', u'000272F', u'000273F']
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_1j54j0yh/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1120, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/tmp/Bazel.runfiles_1j54j0yh/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1110, in main
    make_examples_runner(options)
  File "/tmp/Bazel.runfiles_1j54j0yh/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1025, in make_examples_runner
    regions = processing_regions_from_options(options)
  File "/tmp/Bazel.runfiles_1j54j0yh/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 953, in processing_regions_from_options
    options.exclude_calling_regions),
  File "/tmp/Bazel.runfiles_1j54j0yh/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 549, in build_calling_regions
    regions = ranges.RangeSet.from_contigs(contigs)
  File "/tmp/Bazel.runfiles_1j54j0yh/runfiles/com_google_deepvariant/third_party/nucleus/util/ranges.py", line 126, in from_contigs
    return cls(make_range(contig.name, 0, contig.n_bases) for contig in contigs)
  File "/tmp/Bazel.runfiles_1j54j0yh/runfiles/com_google_deepvariant/third_party/nucleus/util/ranges.py", line 86, in __init__
    self._by_chr[range_.reference_name].addi(range_.start, range_.end, None)
  File "/usr/local/lib/python2.7/dist-packages/intervaltree/intervaltree.py", line 330, in addi
    return self.add(Interval(begin, end, data))
  File "/usr/local/lib/python2.7/dist-packages/intervaltree/intervaltree.py", line 313, in add
    " {0}".format(interval)
ValueError: IntervalTree: Null Interval objects not allowed in IntervalTree: Interval(0, 0)
parallel: This job failed:
python bin/make_examples.zip --mode calling --ref ../Falcon_Unzip/all_p_ctg.fa --reads ../Falcon_Unzip/out.bam --sample_name FalconSet --examples quickstart-output/examples.tfrecord@40.gz --task 1
seq 0 $((N_SHARDS-1))  0,00s user 0,00s system 0% cpu 0,003 total
parallel --eta --halt 2 --joblog "${LOGDIR}/log" --res "${LOGDIR}" python      2,40s user 0,92s system 109% cpu 3,034 total

```

Is there something wrong with the bam file? My reads were mapped using bwa mem 
`bwa mem -p -t 48 all_p_ctg.fa ../ARC_MA_sequencing/94_Fastq_files_GC047403/GC047403.170925_ARC_.fq.gz|samtools sort -@ 48 -m 5G -o out.bam -`

thanks for any help

**Comment by pichuan** [comment]
Your BAM file has contig names like:
'000000F', '000001F', '000002F'
Is that expected?

**Comment by aderzelle** [comment]
Hello,

yes it is, should I rename them?

**Comment by pichuan** [comment]
Hi,
looking at your log closely, specifically this:
```
  File "/tmp/Bazel.runfiles_1j54j0yh/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 549, in build_calling_regions
    regions = ranges.RangeSet.from_contigs(contigs)
```

and 
```
ValueError: IntervalTree: Null Interval objects not allowed in IntervalTree: Interval(0, 0)
```

It seems like you might have contigs in your reference files that are empty. Is that expected?

**Comment by aderzelle** [comment]
This is not expected. I am going to investigate and come back to you. 
Thanks for your help.

**Comment by pichuan** [comment]
If there's no update on this, I'm going to close this for now.
