### ISSUE TITLE
The model files model/model.ckpt* do not exist

### ISSUE THREAD

**Issue by MetteBoge** [google/deepvariant#777]
Hi I have an issue with running the DeepVariant v.1.4.0 and v.1.5.0 on RNA-seq data.
I tried to follow the example you have here on git, but it cannot find the model.ckpt. What am I doing wrong here?

```
BIN_VERSION="1.4.0"

docker run \
  -v "$(pwd):$(pwd)" \
  -w "$(pwd)" \
  google/deepvariant:"${BIN_VERSION}" \
  run_deepvariant \
    --model_type=WES \
    --customized_model=model/model.ckpt \
    --ref=reference/GRCh38.primary_assembly.genome.fa \
    --reads=data/VR0024SA.deduped.sortedByCoord.bam \
    --output_vcf=output_DeepVariant/VR0024SA.output.vcf.gz \
    --num_shards=100 \
    --make_examples_extra_args="split_skip_reads=true,channels=''" \
    --intermediate_results_dir output_DeepVariant/intermediate_results_dir
```

```I0228 18:37:53.652402 140377021216576 run_deepvariant.py:342] Re-using the directory for intermediate results in output_DeepVariant/intermediate_results_dir
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 490, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 464, in main
    commands_logfiles = create_all_commands_and_logfiles(intermediate_results_dir)
  File "/opt/deepvariant/bin/run_deepvariant.py", line 375, in create_all_commands_and_logfiles
    check_flags()
  File "/opt/deepvariant/bin/run_deepvariant.py", line 354, in check_flags
    raise RuntimeError('The model files {}* do not exist. Potentially '
RuntimeError: The model files model/model.ckpt* do not exist. Potentially relevant issue: https://github.com/google/deepvariant/blob/r1.4/docs/FAQ.md#why-cant-it-find-one-of-the-input-files-eg-could-not-open```

**Comment by danielecook** [comment]
@MetteBoge can you confirm that you have the following files under a model directory?

```
├── model
│   ├── model.ckpt.data-00000-of-00001
│   ├── model.ckpt.index
│   └── model.ckpt.meta
```

You will want to make sure the model files have been downloaded to the model directory:

```bash
curl https://storage.googleapis.com/deepvariant/models/DeepVariant/1.4.0/DeepVariant-inception_v3-1.4.0+data-rnaseq_standard/model.ckpt.data-00000-of-00001 > model/model.ckpt.data-00000-of-00001
curl https://storage.googleapis.com/deepvariant/models/DeepVariant/1.4.0/DeepVariant-inception_v3-1.4.0+data-rnaseq_standard/model.ckpt.example_info.json > model/model.ckpt.example_info.json
curl https://storage.googleapis.com/deepvariant/models/DeepVariant/1.4.0/DeepVariant-inception_v3-1.4.0+data-rnaseq_standard/model.ckpt.index > model/model.ckpt.index
curl https://storage.googleapis.com/deepvariant/models/DeepVariant/1.4.0/DeepVariant-inception_v3-1.4.0+data-rnaseq_standard/model.ckpt.meta > model/model.ckpt.meta
```

**Comment by MetteBoge** [comment]
Ah of course, thanks. They are in /opt/models/wes/ instead. It seems to be working now.

**Comment by danielecook** [comment]
@MetteBoge those are whole-exome model files. You'll want to make sure you are pointing to the RNA-seq model.
