### ISSUE TITLE
How to train deepvariant v1.6.1 on tpu?

### ISSUE THREAD

**Issue by gambalab** [google/deepvariant#841]
I managed to start training on a GPU, but it took too much time. Now, I am attempting to train DeepVariant on a TPU v3-8 VM. However, the most recent tutorial I found is for version 0.9, and I am unsure how to proceed with version 1.6.1.

The command I used is the following: 

```
docker run \
    -v ${HOME}:${HOME} \
   google/deepvariant:1.6.1 \
    train \
    --config=${HOME}/dv_config.py:base \
    --config.train_dataset_pbtxt="${SHUFFLE_DIR}/training_set.dataset_config.pbtxt" \
    --config.tune_dataset_pbtxt="${SHUFFLE_DIR}/validation_set.dataset_config.pbtxt" \
    --config.num_epochs=10 \
    --config.learning_rate=0.001 \
    --config.num_validation_examples=0 \
    --experiment_dir=${TRAINING_DIR} \
    --strategy=tpu \
    --config.batch_size=1024
```

However, I am not an expert with TPUs, and this is entirely new to me. Below is the error I encountered. Do you have any suggestions or can you direct me to an updated tutorial to follow?

```
/usr/local/lib/python3.8/dist-packages/tensorflow_addons/utils/tfa_eol_msg.py:23: UserWarning: 

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). 

For more information see: https://github.com/tensorflow/addons/issues/2807 

  warnings.warn(
I0627 21:18:43.707066 139683296487232 train.py:92] Running with debug=False
I0627 21:18:43.707488 139683296487232 train.py:100] Use TPU at local
I0627 21:18:43.707705 139683296487232 train.py:103] experiment_dir: /home/gambardella/training_chk
INFO:tensorflow:Deallocate tpu buffers before initializing tpu system.
I0627 21:18:43.707828 139683296487232 tpu_strategy_util.py:57] Deallocate tpu buffers before initializing tpu system.
INFO:tensorflow:Initializing the TPU system: local
I0627 21:18:43.846984 139683296487232 tpu_strategy_util.py:81] Initializing the TPU system: local
2024-06-27 21:18:43.848149: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-27 21:18:43.855816: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/tpu/tpu_strategy_util.py", line 110, in initialize_tpu_system
    output = _tpu_init_fn()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 134, in __call__
    return concrete_function._call_flat(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/polymorphic_function/monomorphic_function.py", line 1745, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/polymorphic_function/monomorphic_function.py", line 378, in call
    outputs = execute.execute(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'ConfigureDistributedTPU' used by {{node ConfigureDistributedTPU}} with these attrs: [compilation_failure_closes_chips=false, tpu_cancellation_closes_chips=2, tpu_embedding_config="", embedding_config="", enable_whole_mesh_compilations=false, is_global_init=false]
Registered devices: [CPU]
Registered kernels:
  <no registered kernels>

         [[ConfigureDistributedTPU]] [Op:__inference__tpu_init_fn_4]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_ol6r0lcv/runfiles/com_google_deepvariant/deepvariant/train.py", line 532, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_ol6r0lcv/runfiles/absl_py/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_ol6r0lcv/runfiles/absl_py/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_ol6r0lcv/runfiles/com_google_deepvariant/deepvariant/train.py", line 518, in main
    train(FLAGS.config)
  File "/tmp/Bazel.runfiles_ol6r0lcv/runfiles/com_google_deepvariant/deepvariant/train.py", line 109, in train
    tf.tpu.experimental.initialize_tpu_system(resolver)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/tpu/tpu_strategy_util.py", line 113, in initialize_tpu_system
    raise errors.NotFoundError(
tensorflow.python.framework.errors_impl.NotFoundError: TPUs not found in the cluster. Failed in initialization: No OpKernel was registered to support Op 'ConfigureDistributedTPU' used by {{node ConfigureDistributedTPU}} with these attrs: [compilation_failure_closes_chips=false, tpu_cancellation_closes_chips=2, tpu_embedding_config="", embedding_config="", enable_whole_mesh_compilations=false, is_global_init=false]
Registered devices: [CPU]
Registered kernels:
  <no registered kernels>

         [[ConfigureDistributedTPU]] [Op:__inference__tpu_init_fn_4]
```

**Comment by kishwarshafin** [comment]
hi @gambalab ,

Our current DeepVariant training code is only optimized to train on GPUs externally and will not work on TPUs. As you can see the TPU initialization is not achieved as the API is not present in the current code:
```bash
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'ConfigureDistributedTPU' used by {{node ConfigureDistributedTPU}} with these attrs: [compilation_failure_closes_chips=false, tpu_cancellation_closes_chips=2, tpu_embedding_config="", embedding_config="", enable_whole_mesh_compilations=false, is_global_init=false]
```
