### ISSUE TITLE
Memory issue while running deepvariant_1.6.0.sif with  ONT_R104 

### ISSUE THREAD

**Issue by DineshRavindraRaju** [google/deepvariant#854]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.6.1/docs/FAQ.md**:

**Describe the issue:**
Python encountered a MemoryError, no matter how much we increase the memory allocation the error exists

**Setup**
  - Operating system:
  - DeepVariant version: 1.6.0
  - Installation method (Docker, built from source, etc.): apptainer pull docker://google/deepvariant:"1.6.1"
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?) bam files, ONT

**Steps to reproduce:**
  - Command: 
apptainer exec --bind /scratch/XXXX/ONT_WGS/HH/FL9-1_deepvaraint /work/XXXX/ls6/deepvariant/deepvariant_1.6.0.sif /opt/deepvariant/bin/run_deepvariant  --model_type ONT_R104  --ref /work/XXXX/data/common/human/hg38bundle/Homo_sapiens_assembly38.fasta --reads  /scratch/XXXX/ONT_WGS/HH/FL9-1/FL9-1.chr10.bam --output_vcf /scratch/XXXX/ONT_WGS/HH/FL9-1_deepvaraint/FL9-1/chr10/FL9-1_chr10.output.vcf.gz  --output_gvcf  /scratch/XXXX/ONT_WGS/HH/FL9-1_deepvaraint/FL9-1/chr10/FL9-1_chr10.output.g.vcf.gz  --num_shards 64  --logging_dir /scratch/XXXX/ONT_WGS/HH/FL9-1_deepvaraint/FL9-1/chr10/  --intermediate_results_dir  /scratch/XXXX/ONT_WGS/HH/FL9-1_deepvaraint/FL9-1/chr10/intermediate_results

  - Error trace: (if applicable)
  
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "C.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "C.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_2p_bcqtz/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 38, in <module>
    from deepvariant import make_examples_core
  File "/tmp/Bazel.runfiles_2p_bcqtz/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 43, in <module>
    import numpy as np
  File "/usr/local/lib/python3.8/dist-packages/numpy/__init__.py", line 152, in <module>
    from . import random
  File "/usr/local/lib/python3.8/dist-packages/numpy/random/__init__.py", line 180, in <module>
    from . import _pickle
  File "/usr/local/lib/python3.8/dist-packages/numpy/random/_pickle.py", line 1, in <module>
    from .mtrand import RandomState
  File "mtrand.pyx", line 1, in init numpy.random.mtrand
ImportError: /usr/local/lib/python3.8/dist-packages/numpy/random/_bounded_integers.cpython-38-x86_64-linux-gnu.so: failed to map segment from shared object
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_rd22bn15/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 38, in <module>
    from deepvariant import make_examples_core
  File "/tmp/Bazel.runfiles_rd22bn15/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 43, in <module>
    import numpy as np
  File "/usr/local/lib/python3.8/dist-packages/numpy/__init__.py", line 141, in <module>
    from . import core
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/__init__.py", line 101, in <module>
    from . import _add_newdocs
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 939, in get_code
  File "<frozen importlib._bootstrap_external>", line 1038, in get_data
MemoryError
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles__l7njte_/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 38, in <module>
    from deepvariant import make_examples_core
  File "/tmp/Bazel.runfiles__l7njte_/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 43, in <module>
    import numpy as np
  File "/usr/local/lib/python3.8/dist-packages/numpy/__init__.py", line 144, in <module>
    from . import lib
  File "/usr/local/lib/python3.8/dist-packages/numpy/lib/__init__.py", line 34, in <module>
    from . import polynomial
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 939, in get_code
  File "<frozen importlib._bootstrap_external>", line 1038, in get_data
MemoryError
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_2dnpe5cn/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 38, in <module>
    from deepvariant import make_examples_core
  File "/tmp/Bazel.runfiles_2dnpe5cn/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 46, in <module>
    from deepvariant import allele_frequency
  File "/tmp/Bazel.runfiles_2dnpe5cn/runfiles/com_google_deepvariant/deepvariant/allele_frequency.py", line 36, in <module>
    from third_party.nucleus.io import vcf
  File "/tmp/Bazel.runfiles_2dnpe5cn/runfiles/com_google_deepvariant/third_party/nucleus/io/vcf.py", line 83, in <module>
    from third_party.nucleus.protos import variants_pb2
  File "/tmp/Bazel.runfiles_2dnpe5cn/runfiles/com_google_deepvariant/third_party/nucleus/protos/variants_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/__init__.py", line 37, in <module>
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 82, in <module>
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/version.py", line 191, in <module>
    class Version(_BaseVersion):
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/version.py", line 193, in Version
    _regex = re.compile(
  File "/usr/lib/python3.8/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 768, in compile
    code = _code(p, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 607, in _code
    _compile(code, p.data, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 156, in _compile
    _compile(code, av[2], flags)
  File "/usr/lib/python3.8/sre_compile.py", line 168, in _compile
    _compile(code, p, _combine_flags(flags, add_flags, del_flags))
  File "/usr/lib/python3.8/sre_compile.py", line 148, in _compile
    _compile(code, av[2], flags)
  File "/usr/lib/python3.8/sre_compile.py", line 120, in _compile
    charset, hascased = _optimize_charset(av, iscased, tolower, fixes)
  File "/usr/lib/python3.8/sre_compile.py", line 389, in _optimize_charset
    charmap = bytes(charmap) # should be hashable
MemoryError
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_3qjgcvn2/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 38, in <module>
    from deepvariant import make_examples_core
  File "/tmp/Bazel.runfiles_3qjgcvn2/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 43, in <module>
    import numpy as np
  File "/usr/local/lib/python3.8/dist-packages/numpy/__init__.py", line 151, in <module>
    from . import polynomial
  File "/usr/local/lib/python3.8/dist-packages/numpy/polynomial/__init__.py", line 120, in <module>
    from .hermite_e import HermiteE
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 939, in get_code
  File "<frozen importlib._bootstrap_external>", line 1038, in get_data
MemoryError
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_chdgmdtc/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 38, in <module>
    from deepvariant import make_examples_core
  File "/tmp/Bazel.runfiles_chdgmdtc/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 46, in <module>
    from deepvariant import allele_frequency
  File "/tmp/Bazel.runfiles_chdgmdtc/runfiles/com_google_deepvariant/deepvariant/allele_frequency.py", line 36, in <module>
    from third_party.nucleus.io import vcf
  File "/tmp/Bazel.runfiles_chdgmdtc/runfiles/com_google_deepvariant/third_party/nucleus/io/vcf.py", line 83, in <module>
    from third_party.nucleus.protos import variants_pb2
  File "/tmp/Bazel.runfiles_chdgmdtc/runfiles/com_google_deepvariant/third_party/nucleus/protos/variants_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/__init__.py", line 37, in <module>
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 82, in <module>
    __import__('pkg_resources.extern.packaging.version')
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/version.py", line 191, in <module>
    class Version(_BaseVersion):
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/version.py", line 193, in Version
    _regex = re.compile(
  File "/usr/lib/python3.8/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 768, in compile
    code = _code(p, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 607, in _code
    _compile(code, p.data, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 156, in _compile
    _compile(code, av[2], flags)
  File "/usr/lib/python3.8/sre_compile.py", line 168, in _compile
    _compile(code, p, _combine_flags(flags, add_flags, del_flags))
  File "/usr/lib/python3.8/sre_compile.py", line 148, in _compile
    _compile(code, av[2], flags)
  File "/usr/lib/python3.8/sre_compile.py", line 120, in _compile
    charset, hascased = _optimize_charset(av, iscased, tolower, fixes)
  File "/usr/lib/python3.8/sre_compile.py", line 389, in _optimize_charset
    charmap = bytes(charmap) # should be hashable
MemoryError
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_wycra2sl/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 38, in <module>
    from deepvariant import make_examples_core
  File "/tmp/Bazel.runfiles_wycra2sl/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 43, in <module>
    import numpy as np
  File "/usr/local/lib/python3.8/dist-packages/numpy/__init__.py", line 141, in <module>
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/__init__.py", line 57, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 939, in get_code
  File "<frozen importlib._bootstrap_external>", line 1037, in get_data
MemoryError
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /work/09505/s223885/data/common/human/hg38bundle/Homo_sapiens_assembly38.fasta --reads /scratch/09505/s223885/ONT_WGS/HH/FL9-1/FL9-1.chr10.bam --examples /scratch/09505/s223885/ONT_WGS/HH/FL9-1_deepvaraint/FL9-1/chr10/intermediate_results/make_examples.tfrecord@64.gz --add_hp_channel --alt_aligned_pileup diff_channels --gvcf /scratch/09505/s223885/ONT_WGS/HH/FL9-1_deepvaraint/FL9-1/chr10/intermediate_results/gvcf.tfrecord@64.gz --max_reads_per_partition 600 --min_mapping_quality 5 --parse_sam_aux_fields --partition_size 25000 --phase_reads --pileup_image_width 199 --norealign_reads --sort_by_haplotypes --track_ref_reads --vsc_min_fraction_indels 0.12 --vsc_min_fraction_snps 0.08 --task 22
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /work/09505/s223885/data/common/human/hg38bundle/Homo_sapiens_assembly38.fasta --reads /scratch/09505/s223885/ONT_WGS/HH/FL9-1/FL9-1.chr10.bam --examples /scratch/09505/s223885/ONT_WGS/HH/FL9-1_deepvaraint/FL9-1/chr10/intermediate_results/make_examples.tfrecord@64.gz --add_hp_channel --alt_aligned_pileup diff_channels --gvcf /scratch/09505/s223885/ONT_WGS/HH/FL9-1_deepvaraint/FL9-1/chr10/intermediate_results/gvcf.tfrecord@64.gz --max_reads_per_partition 600 --min_mapping_quality 5 --parse_sam_aux_fields --partition_size 25000 --phase_reads --pileup_image_width 199 --norealign_reads --sort_by_haplotypes --track_ref_reads --vsc_min_fraction_indels 0.12 --vsc_min_fraction_snps 0.08 --task 24
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /work/09505/s223885/data/common/human/hg38bundle/Homo_sapiens_assembly38.fasta --reads /scratch/09505/s223885/ONT_WGS/HH/FL9-1/FL9-1.chr10.bam --examples /scratch/09505/s223885/ONT_WGS/HH/FL9-1_deepvaraint/FL9-1/chr10/intermediate_results/make_examples.tfrecord@64.gz --add_hp_channel --alt_aligned_pileup diff_channels --gvcf /scratch/09505/s223885/ONT_WGS/HH/FL9-1_deepvaraint/FL9-1/chr10/intermediate_results/gvcf.tfrecord@64.gz --max_reads_per_partition 600 --min_mapping_quality 5 --parse_sam_aux_fields --partition_size 25000 --phase_reads --pileup_image_width 199 --norealign_reads --sort_by_haplotypes --track_ref_reads --vsc_min_fraction_indels 0.12 --vsc_min_fraction_snps 0.08 --task 39
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /work/09505/s223885/data/common/human/hg38bundle/Homo_sapiens_assembly38.fasta --reads /scratch/09505/s223885/ONT_WGS/HH/FL9-1/FL9-1.chr10.bam --examples /scratch/09505/s223885/ONT_WGS/HH/FL9-1_deepvaraint/FL9-1/chr10/intermediate_results/make_examples.tfrecord@64.gz --add_hp_channel --alt_aligned_pileup diff_channels --gvcf /scratch/09505/s223885/ONT_WGS/HH/FL9-1_deepvaraint/FL9-1/chr10/intermediate_results/gvcf.tfrecord@64.gz --max_reads_per_partition 600 --min_mapping_quality 5 --parse_sam_aux_fields --partition_size 25000 --phase_reads --pileup_image_width 199 --norealign_reads --sort_by_haplotypes --track_ref_reads --vsc_min_fraction_indels 0.12 --vsc_min_fraction_snps 0.08 --task 52
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /work/09505/s223885/data/common/human/hg38bundle/Homo_sapiens_assembly38.fasta --reads /scratch/09505/s223885/ONT_WGS/HH/FL9-1/FL9-1.chr10.bam --examples /scratch/09505/s223885/ONT_WGS/HH/FL9-1_deepvaraint/FL9-1/chr10/intermediate_results/make_examples.tfrecord@64.gz --add_hp_channel --alt_aligned_pileup diff_channels --gvcf /scratch/09505/s223885/ONT_WGS/HH/FL9-1_deepvaraint/FL9-1/chr10/intermediate_results/gvcf.tfrecord@64.gz --max_reads_per_partition 600 --min_mapping_quality 5 --parse_sam_aux_fields --partition_size 25000 --phase_reads --pileup_image_width 199 --norealign_reads --sort_by_haplotypes --track_ref_reads --vsc_min_fraction_indels 0.12 --vsc_min_fraction_snps 0.08 --task 57

real	0m4.925s
user	0m4.781s
sys	0m19.092s

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

**Any additional context:**
 Did not face this error in DeepVariant version: 1.5.0

**Comment by kishwarshafin** [comment]
@DineshRavindraRaju ,

It looks like it's not a memory issue rather it's a compilation issue. What operating system are you working on? Looks like it's throwing an error for typecasting `bytes`. Can you please run https://github.com/google/deepvariant/blob/r1.6.1/docs/deepvariant-quick-start.md to see if it runs to completion? You should be able to run it just by copy pasting the commands.

**Comment by DineshRavindraRaju** [comment]
@kishwarshafin ,

What operating system are you working on?
Linux in TACC cluster (ls6)

In the previous run, I was executing four separate runs on a single node, distributing them evenly across 32 threads.

I did run the test data, it did finish and have generated the output files. Have attached the log file
[Deepvarint.txt](https://github.com/user-attachments/files/16364399/Deepvarint.txt)

**Comment by kishwarshafin** [comment]
Is it possible for you to share the bam so I can take a closer look?

**Comment by DineshRavindraRaju** [comment]
@kishwarshafin ,

Sure, how do I share it ,bam file is around 125gb. Should I down sample it to 10,000k reads?

**Comment by kishwarshafin** [comment]
@DineshRavindraRaju , 

Would be great if I can get the entire file to see if memory usage is the issue. If you can put it temporarily to somewhere public until I download, that would be very helpful. Please send an email to shafin@google.com

**Comment by DineshRavindraRaju** [comment]
@kishwarshafin 

Sorry to inform you, but the researcher is not okay to share the BAM file due to confidentiality concerns.

Quick question: where can I download the complete datasets (aligned BAM files) for HG002 and HG003 datasets for R10 ONT chemistry used for benchmarking in the study "Local read haplotagging enables accurate long-read small variant calling"? Thank you!

**Comment by kishwarshafin** [comment]
@DineshRavindraRaju , no worries, the files are here:

```bash
gsutil ls gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.10x.bam
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.10x.bam.bai
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.15x.bam
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.15x.bam.bai
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.20x.bam
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.20x.bam.bai
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.25x.bam
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.25x.bam.bai
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.30x.bam
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.30x.bam.bai
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.35x.bam
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.35x.bam.bai
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.40x.bam
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.40x.bam.bai
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.45x.bam
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.45x.bam.bai
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.50x.bam
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.50x.bam.bai
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.55x.bam
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.55x.bam.bai
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.60x.bam
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.60x.bam.bai
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.65x.bam
gs://brain-genomics-public/publications/kolesnikov2023_dv_haplotagging/evaluation/ont_simplex/downsampled_bams/HG003_R1041_Guppy6_sup_2_GRCh38.pass.65x.bam.bai
```

**Comment by DineshRavindraRaju** [comment]
@kishwarshafin 

What happens if I run the command deepvaraint 1.5  --model_type ONT_R104 for ONT datasets HG002 (FLO-PRO002 and guppy-v2.3.5-dna_r9.4.1_450bps_flipflop.cfg)? will this be an issue? 

Dataset :  https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG004_NA24143_mother/UCSC_Ultralong_OxfordNanopore_Promethion/

**Comment by mylena-s** [comment]
Hello! I have the same issue, were you able to solve it?

**Comment by DineshRavindraRaju** [comment]
I was able to successfully run it using an older version, DeepVariant 1.5.
