### ISSUE TITLE
AssertionError: Some objects had attributes which were not restored:

### ISSUE THREAD

**Issue by xianyu0623** [google/deepvariant#857]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.6.1/docs/FAQ.md**:YES

**Describe the issue:**
When Running deep variant wes mode, there arised an assetion error when loading the weights of the model.

**Setup**
  - Operating system:Linux 
  - DeepVariant version:1.6.1
  - Installation method (Docker, built from source, etc.):Singularity
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)

**Steps to reproduce:**
  - Command:
 ```
DV="singularity run /autofs/bal34/xyu/softwares/deepvariant_1.6.1.sif \
  /opt/deepvariant/bin/run_deepvariant "
${DV} \
                                                --model_type=WES \
                                                --customized_model=/autofs/bal34/xyu/run_software/dv_illu/model/model.ckpt \
                                                --ref  ${REF_FILE_PATH} \
                                                --reads {1} \
                                                --output_vcf ${BASE_DIR}/{2}/output.vcf.gz \
                                                --num_shards 30 \
                                                --make_examples_extra_args="split_skip_reads=true,channels=''" \
                                                --intermediate_results_dir ${BASE_DIR}/{2}/intermediate_results_dir
```
  - Error trace: (if applicable)
```
WARNING:tensorflow:From /usr/local/lib/python3.8/dist-packages/tensorflow/python/checkpoint/checkpoint.py:1473: NameBasedSaverStatus.__init__ (from tensorflow.python.checkpoint.checkpoint) is deprecated and will be removed in a future version.
Instructions for updating:
Restoring a name-based tf.train.Saver checkpoint using the object-based restore API. This mode uses global names to match variables, and so is somewhat fragile. It also adds new restore ops to the graph each time it is called when graph building. Prefer re-encoding training checkpoints in the object-based format: run save() on the object-based saver (the same one this message is coming from) and use that checkpoint in the future.
W0731 11:52:32.961261 140355267913536 deprecation.py:350] From /usr/local/lib/python3.8/dist-packages/tensorflow/python/checkpoint/checkpoint.py:1473: NameBasedSaverStatus.__init__ (from tensorflow.python.checkpoint.checkpoint) is deprecated and will be removed in a future version.
Instructions for updating:
Restoring a name-based tf.train.Saver checkpoint using the object-based restore API. This mode uses global names to match variables, and so is somewhat fragile. It also adds new restore ops to the graph each time it is called when graph building. Prefer re-encoding training checkpoints in the object-based format: run save() on the object-based saver (the same one this message is coming from) and use that checkpoint in the future.
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_rw0m5gar/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 789, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_rw0m5gar/runfiles/absl_py/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_rw0m5gar/runfiles/absl_py/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_rw0m5gar/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 768, in main
    call_variants(
  File "/tmp/Bazel.runfiles_rw0m5gar/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 640, in call_variants
    model.load_weights(checkpoint_path).expect_partial()
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/checkpoint/checkpoint.py", line 1047, in assert_consumed
    raise AssertionError(
AssertionError: Some objects had attributes which were not restored: 
```
**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

**Any additional context:**

**Comment by kishwarshafin** [comment]
@xianyu0623 ,

Looks like the custom model file you are loading is not valid. Can you give a little more information on how you generated the custom model?

**Comment by xianyu0623** [comment]
@kishwarshafin Hi! Thanks for your reply. The custom model is downloaded from these links:
```
curl https://storage.googleapis.com/deepvariant/models/DeepVariant/1.4.0/DeepVariant-inception_v3-1.4.0+data-rnaseq_standard/model.ckpt.data-00000-of-00001 > model/model.ckpt.data-00000-of-00001
curl https://storage.googleapis.com/deepvariant/models/DeepVariant/1.4.0/DeepVariant-inception_v3-1.4.0+data-rnaseq_standard/model.ckpt.example_info.json > model/model.ckpt.example_info.json
curl https://storage.googleapis.com/deepvariant/models/DeepVariant/1.4.0/DeepVariant-inception_v3-1.4.0+data-rnaseq_standard/model.ckpt.index > model/model.ckpt.index
curl https://storage.googleapis.com/deepvariant/models/DeepVariant/1.4.0/DeepVariant-inception_v3-1.4.0+data-rnaseq_standard/model.ckpt.meta > model/model.ckpt.meta
```

**Comment by kishwarshafin** [comment]
@xianyu0623 ,

You are trying to run V1.6.0 with 1.4 models which is the issue. Please use the 1.4.0 docker to run it successfully. We have moved from slim to keras between these versions so the models are not compatible.

**Comment by xianyu0623** [comment]
@kishwarshafin Thanks a lot for your help! This works!
