### ISSUE TITLE
Fail to shuffle_tfrecords_beam.py to shuffling the tensorflow.Example

### ISSUE THREAD

**Issue by ssm0808** [google/deepvariant#91]
I would like to training a new model with two different dataset. There are about 8,500,00 training examples. But I used the python script shuffle_tfrecords_beam.py to shuffling these examples. I get the error that the code uses too mach memory. It is out of memory of my machine. My machine have 376G memory. Here is my command and the error log.
Command:
```javascript
EXAMPLES="/home/suanfa/Documents/shishiming/WGS_trained_model/BGISEQ-500_4_and_5_model/NA12878_BGISEQ_PE150_5.training.examples.tfrecord-?????-of-00038.gz"
echo "${EXAMPLES}"
OUTPUT_DIR=${EXAMPLES%/*} 
time python ./shuffle_tfrecords_beam.py 
   --input_pattern_list="${EXAMPLES}"
   --output_pattern_prefix="${OUTPUT_DIR}/training_set.with_label.shuffled" 
   --output_dataset_config_pbtxt="${OUTPUT_DIR}/training_set.dataset_config.pbtxt" 
   --output_dataset_name="HG001"
   --runner=BundleBasedDirectRunner
```
the error message:
```
/home/suanfa/Documents/shishiming/WGS_trained_model/BGISEQ-500_4_and_5_model/sample.training.examples.tfrecord-?????-of-00076.gz
/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/direct_runner.py:342: DeprecationWarning: options is deprecated since First stable release.. References to <pipeline>.options will not be supported
  pipeline.replace_all(_get_transform_overrides(pipeline.options))
INFO:root:Running pipeline with DirectRunner.
WARNING:root:Couldn't find python-snappy so the implementation of _TFRecordUtil._masked_crc32c is not as fast as it could be.
ERROR:root:Exception at bundle <apache_beam.runners.direct.bundle_factory._Bundle object at 0x7f86daaa07e8>, due to an exception.
 Traceback (most recent call last):
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.py", line 341, in call
    finish_state)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.py", line 381, in attempt_call
    result = evaluator.finish_bundle()
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/transform_evaluator.py", line 303, in finish_bundle
    bundles = _read_values_to_bundles(reader)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/transform_evaluator.py", line 293, in _read_values_to_bundles
    read_result = [GlobalWindows.windowed_value(e) for e in reader]
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/concat_source.py", line 83, in read
    range_tracker.sub_range_tracker(source_ix)):
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/tfrecordio.py", line 175, in read_records
    record = _TFRecordUtil.read_record(file_handle)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/tfrecordio.py", line 131, in read_record
    buf = file_handle.read(buf_length_expected)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/filesystem.py", line 240, in read
    self._fetch_to_internal_buffer(num_bytes)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/filesystem.py", line 197, in _fetch_to_internal_buffer
    decompressed = self._decompressor.decompress(buf)
MemoryError

ERROR:root:Exception at bundle <apache_beam.runners.direct.bundle_factory._Bundle object at 0x7f86daaa07e8>, due to an exception.
 Traceback (most recent call last):
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.py", line 341, in call
    finish_state)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.py", line 381, in attempt_call
    result = evaluator.finish_bundle()
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/transform_evaluator.py", line 303, in finish_bundle
    bundles = _read_values_to_bundles(reader)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/transform_evaluator.py", line 293, in _read_values_to_bundles
    read_result = [GlobalWindows.windowed_value(e) for e in reader]
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/concat_source.py", line 83, in read
    range_tracker.sub_range_tracker(source_ix)):
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/tfrecordio.py", line 175, in read_records
    record = _TFRecordUtil.read_record(file_handle)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/tfrecordio.py", line 131, in read_record
    buf = file_handle.read(buf_length_expected)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/filesystem.py", line 240, in read
    self._fetch_to_internal_buffer(num_bytes)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/filesystem.py", line 199, in _fetch_to_internal_buffer
    self._read_buffer.write(decompressed)
MemoryError: out of memory

ERROR:root:Exception at bundle <apache_beam.runners.direct.bundle_factory._Bundle object at 0x7f86daaa07e8>, due to an exception.
 Traceback (most recent call last):
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.py", line 341, in call
    finish_state)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.py", line 381, in attempt_call
    result = evaluator.finish_bundle()
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/transform_evaluator.py", line 303, in finish_bundle
    bundles = _read_values_to_bundles(reader)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/transform_evaluator.py", line 293, in _read_values_to_bundles
    read_result = [GlobalWindows.windowed_value(e) for e in reader]
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/concat_source.py", line 83, in read
    range_tracker.sub_range_tracker(source_ix)):
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/tfrecordio.py", line 175, in read_records
    record = _TFRecordUtil.read_record(file_handle)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/tfrecordio.py", line 131, in read_record
    buf = file_handle.read(buf_length_expected)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/filesystem.py", line 240, in read
    self._fetch_to_internal_buffer(num_bytes)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/filesystem.py", line 197, in _fetch_to_internal_buffer
    decompressed = self._decompressor.decompress(buf)
MemoryError

ERROR:root:Exception at bundle <apache_beam.runners.direct.bundle_factory._Bundle object at 0x7f86daaa07e8>, due to an exception.
 Traceback (most recent call last):
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.py", line 341, in call
    finish_state)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.py", line 381, in attempt_call
    result = evaluator.finish_bundle()
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/transform_evaluator.py", line 303, in finish_bundle
    bundles = _read_values_to_bundles(reader)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/transform_evaluator.py", line 293, in _read_values_to_bundles
    read_result = [GlobalWindows.windowed_value(e) for e in reader]
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/concat_source.py", line 83, in read
    range_tracker.sub_range_tracker(source_ix)):
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/tfrecordio.py", line 175, in read_records
    record = _TFRecordUtil.read_record(file_handle)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/tfrecordio.py", line 131, in read_record
    buf = file_handle.read(buf_length_expected)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/filesystem.py", line 240, in read
    self._fetch_to_internal_buffer(num_bytes)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/filesystem.py", line 199, in _fetch_to_internal_buffer
    self._read_buffer.write(decompressed)
MemoryError: out of memory

ERROR:root:Giving up after 4 attempts.
WARNING:root:A task failed with exception: out of memory
Traceback (most recent call last):
  File "./shuffle_tfrecords_beam.py", line 229, in <module>
    main()
  File "./shuffle_tfrecords_beam.py", line 224, in main
    known_args.output_dataset_config_pbtxt)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/pipeline.py", line 410, in __exit__
    self.run().wait_until_finish()
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/direct_runner.py", line 421, in wait_until_finish
    self._executor.await_completion()
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.py", line 398, in await_completion
    self._executor.await_completion()
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.py", line 444, in await_completion
    six.reraise(t, v, tb)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.py", line 341, in call
    finish_state)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.py", line 381, in attempt_call
    result = evaluator.finish_bundle()
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/transform_evaluator.py", line 303, in finish_bundle
    bundles = _read_values_to_bundles(reader)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/runners/direct/transform_evaluator.py", line 293, in _read_values_to_bundles
    read_result = [GlobalWindows.windowed_value(e) for e in reader]
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/concat_source.py", line 83, in read
    range_tracker.sub_range_tracker(source_ix)):
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/tfrecordio.py", line 175, in read_records
    record = _TFRecordUtil.read_record(file_handle)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/tfrecordio.py", line 131, in read_record
    buf = file_handle.read(buf_length_expected)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/filesystem.py", line 240, in read
    self._fetch_to_internal_buffer(num_bytes)
  File "/home/suanfa/virtualenv_beam/local/lib/python2.7/site-packages/apache_beam/io/filesystem.py", line 199, in _fetch_to_internal_buffer
    self._read_buffer.write(decompressed)
MemoryError: out of memory

real    471m5.950s
user    150m11.981s
sys     30m20.862s
```
What reason are the cause of the error?
Can I train a new model without using shuffle_tfrecords_beam.py? If yes, can you tell me how to do that? 
Thank you

**Comment by ssm0808** [comment]
Hi, pichuan!
Thanks for your help! I just change the name of tfrecord file to shuffle the training dataset. Is it OK to use this way to shuffle the training dataset? This way is introduced from "Improve DeepVariant for 
BGISEQ germline variant calling" file. The accuracy of trained model have raised compared with trained model without shuffling. But I'm not sure whether it is the highest accuracy performance. I don't know how to shuffle on Spark. Maybe I would try to shuffle on Spark in future.

**Comment by pgrosu** [comment]
@ssm0808 FYI on how to shuffle on Spark: http://people.apache.org/~pwendell/spark-nightly/spark-master-docs/latest/rdd-programming-guide.html#shuffle-operations

**Comment by GuillaumeHolley** [comment]
Just for the record, I wrote a script which shuffles the records locally using as little memory as possible: [TFrecordShuffler](https://github.com/GuillaumeHolley/TFrecordShuffler). It uses about as much RAM as the total size of the input (record) files on disk. Downside is obviously the time it takes which is much longer than with a distributed google cloud or spark system I imagine. As an example, shuffling ~30 million records totaling 125 GB of files took 46h (wall-clock and CPU) and 150 GB of RAM.
