### ISSUE TITLE
Building DeepVariant on CentOS 7

### ISSUE THREAD

**Issue by ssm0808** [google/deepvariant#95]
Hi;
I would like to build DeepVariant on CentOS 7. I have installed dependencies of the Centos version corresponding to run-prereq.sh. But I also cann't run copying binaries on my local machines which have installed CentOS 7. The wrror message indicate it cann't find some dependent package in environment.
the error message:
```
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_w1ath6/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 41, in <module>
    from deepvariant import pileup_image
  File "/tmp/Bazel.runfiles_w1ath6/runfiles/com_google_deepvariant/deepvariant/pileup_image.py", line 42, in <module>
    from third_party.nucleus.util import ranges
  File "/tmp/Bazel.runfiles_w1ath6/runfiles/com_google_deepvariant/third_party/nucleus/util/ranges.py", line 42, in <module>
    from third_party.nucleus.io import bed
  File "/tmp/Bazel.runfiles_w1ath6/runfiles/com_google_deepvariant/third_party/nucleus/io/bed.py", line 79, in <module>
    from third_party.nucleus.io.python import bed_reader
ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory
```
I know we can use docker to run DeepVariant on CentOS 7. But There are some reason why I cann't use docker to run DeepVariant. Did you try to build DeepVariant for CentOS 7. Or, you know who have build DeepVariant with some way on CentOS 7. If you know, can give me some advice？
Thanks a lot,
Simon.

**Comment by pgrosu** [comment]
Hi Simon,

You'll need the bz2 libs installed.  Either yum bzip2-libs and/or libbz2, as they are required.

@ramcn Which do you have installed on your system?

~p

**Comment by pichuan** [comment]
@ssm0808 Hi, I've tried building on CentOS a while ago, but didn't succeed.  At the time I was trying to build on CentOS 6 (in this issue: https://github.com/google/deepvariant/issues/29)
If you made more progress, please let us know.

**Comment by gunjanbaid** [comment]
Closing this issue as there has been no activity for a while. For anyone referencing this discussion, [here is a link](https://github.com/google/deepvariant/issues/137#issuecomment-452921108) to detailed instructions on how to install DeepVariant for CentOS7.
